---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2018/10/10 10:53
---
DungeonExpEndPanel = DungeonExpEndPanel or class("DungeonExpEndPanel", BasePanel)
local this = DungeonExpEndPanel

function DungeonExpEndPanel:ctor()
    self.abName = "dungeon";
    self.image_ab = "dungeon_image";
    self.assetName = "DungeonExpEndPanel"
    self.layer = "UI"

    self.model = DungeonModel.GetInstance()
    self.events = {};
    self.schedules = {};
end

function DungeonExpEndPanel:dctor()
    GlobalEvent:RemoveTabListener(self.events);
    if self.event_id_1 then
        self.model:RemoveListener(self.event_id_1)
        self.event_id_1 = nil
    end
    self:StopAllSchedules()
    self.model = nil;
    if self.enditem then
        self.enditem:destroy();
    end
end

function DungeonExpEndPanel:Open(data)
    self.data = data;
    print2(Table2String(self.data));
    WindowPanel.Open(self)
end

function DungeonExpEndPanel:LoadCallBack()
    self.nodes = {
        "win/passTime", "win/awardCon", "win/starCon/star2", "lose/equip_2",
        "win/starCon", "lose", "lose/mount", "lose/equip_1", "win", "win/starCon/star1",
        "win/starCon/star3",  "win/winLabels/challenge_label",  "win/winLabels",
        "win/killnum",
        "win/level_change",

        "win/jingyan","win/jingyanlogo","win/huodejingyan",
        "lose/jingyan_defeat","lose/jingyanlogo_defeat","lose/huodejingyan_defeat",

        --"win/prop", "win/prop/stars", "win/prop/stars/star_1", "win/prop/stars/star_2", "win/prop/stars/star_3",
        --"win/prop/txt", "win/prop/txt/text_1", "win/prop/txt/text_2", "win/prop/txt/text_3",
        --"sureBtn", "autoCloseText", "closeBtn",
    }
    self:GetChildren(self.nodes)
    local orderIndex = LayerManager:GetInstance():GetLayerOrderByName(self.layer)
    self:SetOrderIndex(orderIndex + 5)

    SetLocalPosition(self.transform, 0, 0, 0)
    self:Init();

    self:AddEvent();

    if AutoFightManager:GetInstance():GetAutoFightState() then
        GlobalEvent:Brocast(FightEvent.AutoFight)
    end
end

--{
--	["stat"]=
--	{
--		["count"]=
--		{
--			[1002029]=260,
--			[1002027]=234,
--			[1002028]=267
--		},
--		["star"]=3,
--		["dur"]=280,
--		["exp"]=262263676592,
--		["rise"]=0,
--		["stype"]=301,
--		["isClear"]=true,
--		["id"]=30101
--	},
--	["id"]=30101,
--	["count"]=
--	{
--		[1002029]=260,
--		[1002027]=234,
--		[1002028]=267
--	},
--	["stype"]=301,
--	["clear"]=true,
--	["reward"]=
--	{
--
--	}
--}
function DungeonExpEndPanel:Init()
    --print2(Table2String(self.data));
    self.enditem = DungeonEndItem(self.transform, self.data);

    self.passTime = GetText(self.passTime);
    self.challenge_label = GetText(self.challenge_label);
    self.jingyan = GetText(self.jingyan);
    self.huodejingyan = GetText(self.huodejingyan);
    self.jingyanlogo = GetImage(self.jingyanlogo);
    self.level_change = GetText(self.level_change);

    self.jingyan_defeat = GetText(self.jingyan_defeat);
    self.huodejingyan_defeat = GetText(self.huodejingyan_defeat);
    self.jingyanlogo_defeat = GetImage(self.jingyanlogo_defeat);

    self.killnum = GetText(self.killnum);

    if self.data then
        local killnum = 0;
        if self.data["count"] then
            for k, v in pairs(self.data["count"]) do
                killnum = killnum + v;
            end
        end
        self.killnum.text = killnum .. "X";
        -- 成功界面
        if self.data.isClear == true then
            self.win.gameObject:SetActive(true);
            self.lose.gameObject:SetActive(false);

            if self.data.stype == enum.SCENE_STYPE.SCENE_STYPE_DUNGE_EXP then
                self.passTime.text = tostring(self.data.dur) .. "sec";
                self.challenge_label.text = "EXP Bonus<color=#43F673>" .. (self.data.rise / 100) .. "%</color>";
                self.jingyan.text = tostring(GetShowNumber(self.data.exp));
                self.level_change.text = self.data.oldlv .. "Level→" .. self.data.newlv .. "Level";
                --elseif self.data.stype == enum.SCENE_STYPE.SCENE_STYPE_DUNGE_MAGICTOWER then
                --    self.passTime.gameObject:SetActive(false);
                --    self.winLabels.gameObject:SetActive(false);
                --    -- 还有没有打完的要继续
                --    if Config.db_dunge_magic[self.data.floor + 1] then
                --        SetVisible(self.sureBtn, true)
                --    end
            end
            -- 失败界面
        else
            --SetGameObjectActive(self.zhandoujiangli.gameObject, false);
            --SetLocalPositionXY(self.jingyan.transform, 372, 113);
            --SetLocalPositionXY(self.jingyanlogo.transform, 237, 115);
            --SetLocalPositionXY(self.huodejingyan.transform, 170, 112);

            self.win.gameObject:SetActive(false);
            self.lose.gameObject:SetActive(true);
            if self.data.stype == enum.SCENE_STYPE.SCENE_STYPE_DUNGE_EXP then
                self.jingyan_defeat.text = tostring(GetShowNumber(self.data.exp));

                --elseif self.data.stype == enum.SCENE_STYPE.SCENE_STYPE_DUNGE_MAGICTOWER then
                --    self.passTime.gameObject:SetActive(false);
                --    self.winLabels.gameObject:SetActive(false);
            end
        end
    end
    local time = 5;
    local dungeTab = Config.db_dunge[SceneManager:GetInstance():GetSceneId()];
    if dungeTab then
        time = dungeTab.exit_cd;
    end
    time = time or 5;
    self.enditem:StartAutoClose(time);
end

local closeTime = 5;
function DungeonExpEndPanel:AddEvent()
    local function callBack1 (data)
        SceneControler:GetInstance():RequestSceneLeave();
        self:Close();
    end
    self.enditem:SetAutoCloseCallBack(callBack1);

    local function call_back()
        self:Close()
    end
    self.events[#self.events + 1] = GlobalEvent:AddListener(DungeonEvent.LEAVE_DUNGEON_SCENE, call_back)

    self.event_id_1 = self.model:AddListener(DungeonEvent.ResEnterDungeonInfo, call_back)

    local call_back = function()
        SceneControler:GetInstance():RequestSceneLeave();
        self:Close();
    end

    self.enditem:SetCloseCallBack(call_back);

    local call_back1 = function(target, x, y)
        GlobalEvent.BrocastEvent(MountEvent.OPEN_MOUNT_PANEL);
    end
    AddClickEvent(self.mount.gameObject, call_back1);

    local call_back2 = function(target, x, y)
        Notify.ShowText("Tap [Craft Gear]")--GlobalEvent.BrocastEvent(MountEvent.OPEN_MOUNT_PANEL);
    end
    AddClickEvent(self.equip_1.gameObject, call_back2);

    local call_back3 = function(target, x, y)
        Notify.ShowText("Tap [Forge]")--GlobalEvent.BrocastEvent(MountEvent.OPEN_MOUNT_PANEL);
    end
    AddClickEvent(self.equip_2.gameObject, call_back3);
end

function DungeonExpEndPanel:StopAllSchedules()
    for i = 1, #self.schedules, 1 do
        GlobalSchedule:Stop(self.schedules[i]);
    end
    self.schedules = {};
end