---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2018/10/11 15:01
---
ExpBtnItem = ExpBtnItem or class("ExpBtnItem", Node)
local ExpBtnItem = ExpBtnItem

ExpBtnItem.itemids = {
	[1] = 10015,
	[2] = 10016,
	[3] = 10017,
}



function ExpBtnItem:ctor(_obj, pos)
	self.pos = pos;
	self.showBg = pos ~= 3;
	self.transform = _obj.transform
	self.gameObject = self.transform.gameObject;
	self.transform_find = self.transform.Find;
	
	self:InitUI();
	self.events = {}
	
	self:AddEvent();
end

function ExpBtnItem:InitUI()
	self.is_loaded = true;
	self.nodes = {
		"btn/label", "bg/Text", "bg", "btn", "cureff", "cureff/eff_text",
	}
	self:GetChildren(self.nodes)
	
	self.btn = GetButton(self.btn);
	self.Text = GetText(self.Text);
	self.bg = GetImage(self.bg);
	
	self.eff_text = GetText(self.eff_text);
	self.eff_text.text = nil;
	SetGameObjectActive(self.cureff , false);
	
	self:HideBgText();
	
	self.effect = UIEffect(self.transform, 10201, false, "Bottom");
	
	if self.pos == 2 then
		local main_role_data = RoleInfoModel:GetInstance():GetMainRoleData()
		if main_role_data:IsAddExp1Buff() then
			self.showBg = false;
			self:HideBgText();
		end
	elseif self.pos == 1 then
		
	end
end

function ExpBtnItem:SetEffText(str)
	self.eff_text.text = tostring(str);
    if not string.isNilOrEmpty(str) then
        SetGameObjectActive(self.cureff , true);

        self.bg.gameObject:SetActive(false);
        cc.ActionManager:GetInstance():removeAllActionsFromTarget(self.bg.transform);
    else
        SetGameObjectActive(self.cureff , false);
    end

end

function ExpBtnItem:HideBgText()
	if not self.showBg then
		self.Text.gameObject:SetActive(false);
		self.bg.gameObject:SetActive(false);
		
		--SetGameObjectActive(self.cureff , true);
	end
end

function ExpBtnItem:AddEvent()
	local call_back = function(target, bool)
		self.showBg = false;
		if self.pos == 1 then
			if not DungeonModel:GetInstance().dungeonInfo then
				return ;
			end
			
			if tonumber(DungeonModel:GetInstance().dungeonInfo.gold_inspire or 0) > 0 or tonumber(DungeonModel:GetInstance().dungeonInfo.coin_inspire or 0) > 0 then

			else
				self:HideBgText();
			end
			
		elseif self.pos == 2 then
			
		end
		
		if self.pos == 3 then
			Dialog.ShowTwo("Tip", "Are you sure you want to leave?\n(Leave now will still cost your attempts)", "Confirm", handler(self, self.SendExitDungeon), nil, "Cancel", nil, nil)
		elseif self.pos == 2 then
			lua_panelMgr:GetPanelOrCreate(ExpEffPanel):Open();
		else
			lua_panelMgr:GetPanelOrCreate(GuwuPanel):Open();
		end
		self:RemoveEffect();
	end
	AddClickEvent(self.btn.gameObject, call_back);
	if self.pos ~= 3 then
		local localPos = self.bg.transform.localPosition;
		
		local moveAction = cc.MoveTo(0.5, localPos.x, localPos.y - 3, localPos.z)
		local moveAction1 = cc.MoveTo(0.5, localPos.x, localPos.y + 3, localPos.z)
		local action = cc.Sequence(moveAction, moveAction1)
		local action2 = cc.RepeatForever(action)
		cc.ActionManager:GetInstance():addAction(action2, self.bg.transform);
	end
	
	
	--AddValueChange(self.tog.gameObject , call_back)
end

function ExpBtnItem:SendExitDungeon()
	DungeonCtrl:GetInstance():RequestLeaveDungeon();
end

function ExpBtnItem:dctor()
	GlobalEvent:RemoveTabListener(self.events);
	self:RemoveEffect();
end

function ExpBtnItem:RemoveEffect()
	if self.effect then
		self.effect:destroy();
	end
	self.effect = nil;
end
