---
--- Generated by ling(https://github.com/EmmyLua)
--- Created by ling.
--- DateTime: 18/11/19 17:34
---
SweepResultPanel = SweepResultPanel or class("SweepResultPanel", BaseRewardPanel)
local this = SweepResultPanel

function SweepResultPanel:ctor(parent_node)
    self.abName = "dungeon";
    self.image_ab = "dungeon_image";
    self.assetName = "SweepResultPanel"
    self.layer = "UI"

    self.use_background = true
 --   self.panel_type = 4;
    self.model = DungeonModel.GetInstance()
    self.events = {};
    self.schedules = {};

    self.btn_list = {
        {btn_res = "common:btn_blue_2",btn_name = "Cancel",call_back = handler(self, self.HandleCancel)},

        {btn_res = "common:btn_yellow_2",btn_name = "Try again", call_back = handler(self, self.HandleSure)},
    }

    self.separate_frame_schedule_id = nil
end

function SweepResultPanel:dctor()
    self.model = nil;
    GlobalEvent:RemoveTabListener(self.events);
    self:StopAllSchedules()

    destroyTab(self.items);
end

function SweepResultPanel:Open(data)
    self.data = data;
    --print2(Table2String(data));
   -- WindowPanel.Open(self)
    SweepResultPanel.super.Open(self)
end

function SweepResultPanel:LoadCallBack()
    self.nodes = {
        "cost_value", "sure_btn", "gain_value", "gain_label" , "can_btn", "gold_exp_icon","awards/ScrollView/Viewport/award_con",--"awards/award_con",
        "awards/ScrollView",
    }
    self:GetChildren(self.nodes)

    SetLocalPosition(self.transform, 0, 0, 0)
    --设置标题
 --   self:SetTileTextImage("dungeon_image", "asdasdasd");
    self:InitUI();

    self:AddEvent();
end

function SweepResultPanel:InitUI()
    self.cost_value = GetText(self.cost_value);
    self.gain_value = GetText(self.gain_value);
    self.gold_exp_icon = GetImage(self.gold_exp_icon);
    self.scroll = GetScrollRect(self.ScrollView)

    self:SetValue();

    lua_resMgr:SetImageTexture(self, self.gold_exp_icon, "system_image", "drop_icon_1", false, nil, false);
end

function SweepResultPanel:RefreshData(data)
    self.data = data;
    --print2(Table2String(data));
    self:SetValue();
end

function SweepResultPanel:SetValue()
    self.cost_value.text = "1";
    self.gain_value.text = "1";
    if self.data then
        local tab = Config.db_dunge[self.data.id];
        if tab then
            local sweep = String2Table(tab.sweep_cost);
            if sweep and #sweep > 1 then
                local num = BagModel:GetInstance():GetItemNumByItemID(sweep[1]);
                self.cost_value.text = num .. "/" .. sweep[2];
            end
        end
    else
        self.cost_value.text = "1";
    end

    -- destroyTab(self.items);
    -- self.items = {};

    self.items = self.items or {}
    local totalNum = 0;
    local index = 0
    local tab = {}
    if self.data and self.data.reward then
        if self.data.id == 30102 then
            SetLocalPositionX(self.gain_label.transform , 0);
            SetGameObjectActive(self.gold_exp_icon , false);
            SetGameObjectActive(self.gain_value , false);
        end

        for d, v in pairs(self.data.reward) do
            local t = {}
            t.color = Config.db_item[d].color
            t.id = d
            t.num = v
            t.stype = Config.db_item[d].stype
            table.insert(tab, t)
        end

		local function call_back(a, b)
			if a.color == b.color then
				return a.stype > b.stype
			else
				return a.color > b.color
			end		
		end
        table.sort(tab, call_back)

        local count = 0

        --分帧实例化
        for i=1,#tab do
            if tab[i].id == 90010005 or tab[i].id == 90010002 then
            count = count + 1
            totalNum = totalNum + tab[i].num;
        end
 
        local len = #tab - count
        if len < 11 then
            SetLocalPositionY(self.ScrollView.transform, -80)
            self.scroll.enabled = false
        elseif len > 10 and len < 21 then
            SetLocalPositionY(self.ScrollView.transform, -40)
            self.scroll.enabled = false
        else
            self.scroll.enabled = true
            SetLocalPositionY(self.ScrollView.transform, 0)
        end
     end
 
        local rt = GetRectTransform(self.award_con.gameObject);
        rt.sizeDelta = Vector2(0, rt.sizeDelta.y);
        self.gain_value.text = tostring(GetShowNumber(totalNum));
 
        self:SeparateFrameInstantia(tab)
    end




    
end

--分帧实例化
function SweepResultPanel:SeparateFrameInstantia(tab)
    local num = #tab
    if num <= 0 then
		return
	end
    local index = 0
    local function op_call_back(cur_frame_count,cur_all_count)
        
        if tab[cur_all_count].id == 90010005 then

        elseif tab[cur_all_count].id == 90010002 then

        else
            --实例化圣痕
            index = index + 1
            local item = self.items[index]
            if not item then
                item = AwardItem(self.award_con.transform);
                self.items[index] = item;
            end
            SetVisible(item, true)
            item:SetData(tab[cur_all_count].id, 0);
            item:SetNumText(tostring(tab[cur_all_count].num));

            SetVisible(item, true)
            item:SetData(tab[cur_all_count].id, 0);
            item:SetNumText(tostring(tab[cur_all_count].num));
            
            if item.transform then
                item.transform.localScale = Vector3(2, 2, 2);
                local scaleAction = cc.ScaleTo(0.2, 0.5, 0.5, 0.5);
                local scaleAction2 = cc.ScaleTo(0.1, 1, 1, 1);

                if index > 1 then
                    local delayAction = cc.DelayTime(0.1 * index);
                    item.gameObject:SetActive(false);
                    local end_call = function()
                        item.gameObject:SetActive(true);
                    end
                    local finAction = cc.CallFunc(end_call);
                    local scaleAction1 = cc.Sequence(delayAction, finAction, scaleAction, scaleAction2);--finAction,
                    cc.ActionManager:GetInstance():addAction(scaleAction1, item.transform);
                else
                    local scaleAction3 = cc.Sequence(scaleAction, scaleAction2);
                    cc.ActionManager:GetInstance():addAction(scaleAction3, item.transform);
                end
            else
                item:AddLoadCallBack(function()
                    item.transform.localScale = Vector3(2, 2, 2);
                    local scaleAction = cc.ScaleTo(0.2, 0.5, 0.5, 0.5);
                    local scaleAction2 = cc.ScaleTo(0.1, 1, 1, 1);

                    if index > 1 then
                        local delayAction = cc.DelayTime(0.1 * index);
                        item.gameObject:SetActive(false);
                        local end_call = function()
                            item.gameObject:SetActive(true);
                        end
                        local finAction = cc.CallFunc(end_call);
                        local scaleAction1 = cc.Sequence(delayAction, finAction, scaleAction, scaleAction2);--finAction,
                        cc.ActionManager:GetInstance():addAction(scaleAction1, item.transform);
                    else
                        local scaleAction3 = cc.Sequence(scaleAction, scaleAction2);
                        cc.ActionManager:GetInstance():addAction(scaleAction3, item.transform);
                    end
                end);
            end
        end
	end
	local function all_frame_op_complete()
		self:SeparateFrameInstantiaComplete(index)
	end
	--一帧实例化一个 保证不卡
	self.separate_frame_schedule_id =  SeparateFrameUtil.SeparateFrameOperate(op_call_back,nil,1,num,nil,all_frame_op_complete)
end

function SweepResultPanel:SeparateFrameInstantiaComplete(index)
    self.separate_frame_schedule_id = nil
    for i = index + 1, #self.items do
        local item = self.items[i]
        item:SetVisible(false)
    end
end

function SweepResultPanel:AddEvent()
    AddClickEvent(self.sure_btn.gameObject, handler(self, self.HandleSure));
    AddClickEvent(self.can_btn.gameObject, handler(self, self.HandleCancel));
end
--再扫一次
function SweepResultPanel:HandleSure(target, x, y)
    if self.data then
        DungeonCtrl:GetInstance():RequestSweep(self.data.stype, self.data.floor);
    else
        Notify.ShowText("Unable to find the dungeon");
    end
end
--取消
function SweepResultPanel:HandleCancel(target, x, y)
    self:Close();
end

function SweepResultPanel:StopAllSchedules()
    for i = 1, #self.schedules, 1 do
        GlobalSchedule:Stop(self.schedules[i]);
    end
    self.schedules = {};
end
SweepResultPanel.TempAdvanceData = {
    ["reward"]=
    {
        [50000]=30,
        [90010002]=114744839430,
        [55000]=42
    },
    ["stype"]=308,
    ["floor"]=0,
    ["id"]=30401
}