---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2018/10/10 10:53
---
WorldBossPanel = WorldBossPanel or class("WorldBossPanel", BaseItem)
local this = WorldBossPanel

WorldBossPanel.DungeTaskID = 1109006;

function WorldBossPanel:ctor(parent_node, dungeonPanel, sel_idx)
    self.abName = "dungeon";
    self.image_ab = "dungeon_image";
    self.assetName = "WorldBossPanel"
    self.layer = "Bottom"

    self.parentPanel = dungeonPanel;
    self.model = DungeonModel.GetInstance()
    self.events = {};
    self.schedules = {};
    self.selectedBossid = sel_idx
    self.togBoss = {}
    self.togItems = {} 
    self.items = {}
    WorldBossPanel.super.Load(self);
    --DungeonCtrl:GetInstance().WorldBossPanel = self;
end

function WorldBossPanel:dctor()
    self.model = nil;

    if self.map_bg then
        self.map_bg.transform:SetParent(self.transform);
    end

    GlobalEvent:RemoveTabListener(self.events);
    self.selectedItemIndex = 1;
    self:StopAllSchedules()

    destroyTab(self.items);
    self.items = {};

    self.parentPanel = nil;
    self.selectedBossid = nil

    if self.qianwangBtn_reddot then
        self.qianwangBtn_reddot:destroy();
    end
    self.qianwangBtn_reddot = nil;

    self.togItems = nil

    self.togBoss = nil
end


function WorldBossPanel:Open(data)
    self.data = data;
    WindowPanel.Open(self)
end

function WorldBossPanel:LoadCallBack()
    self.nodes = {
        "bg_layer/shuoming",
        "pilaoText", "qianwangBtn", "ScrollView/Viewport/Content",
        "bossitem_0","boss_tog_1","togLayer","bg_layer/droptip",
    }
    self:GetChildren(self.nodes)

    SetLocalPosition(self.transform, 0, 0, 0)

    self:InitUI();

    self:AddEvent();

    --请求boss列表
    DungeonCtrl:GetInstance():RequestBossList(enum.BOSS_TYPE.BOSS_TYPE_WORLD);

    self.parentPanel:DropCallBack();
end

function WorldBossPanel:InitUI()
    self.qianwangBtn = GetButton(self.qianwangBtn);

    self.boss_tog_1 = GetToggle(self.boss_tog_1)

    self.pilaoText = GetText(self.pilaoText);
    --self.pilaoText.color = Color(59 / 255, 0x2e/255, 12 / 255, 1);
    --玩法说明
    self.shuoming = GetButton(self.shuoming);

    --self.care = GetToggle(self.care);

    self.items = {};
    self.selectedItemIndex = self.selectedBossid or 1;
    table.sort(self.model.worldBossTab, SeqCompareFun);

    for i=1, #self.model.worldBossTab do
        local bossTab = self.model.worldBossTab[i]
        local lv = RoleInfoModel:GetInstance():GetMainRoleLevel()
        if lv >= bossTab.show_lv then
            local floor = bossTab.floor
            self.togBoss[floor] = self.togBoss[floor] or {}
            table.insert(self.togBoss[floor], bossTab)
            if bossTab.lock_lv then
                local lockLv = String2Table(bossTab.lock_lv);
                if #lockLv > 0 then
                    if lv >= tonumber(lockLv[1]) and lv <= tonumber(lockLv[2]) and self.selectedBossid == nil then
                        self.selectedItemIndex = i;
                        self.currentFloor = floor
                    elseif bossTab.id == self.selectedBossid then
                        self.selectedItemIndex = i;
                        self.currentFloor = floor
                    end
                end
            end
        end
    end
    self.currentFloor = self.currentFloor or 0

    destroyTab(self.togItems);
    self.togItems = {};
    local floors = table.keys(self.togBoss)
    self.boss_tog_1.gameObject:SetActive(true)
    table.sort(floors)
    for i = 1, #floors do
        local floor = floors[i]
        local tog = newObject(self.boss_tog_1);
        tog.gameObject.name = "boss_tog_" .. floor;
        local labelObj = GetChild(tog, "Label");
        if labelObj then
            local labelText = GetText(labelObj);
            if floor == 0 then
                labelText.text = "Bonus Stage"
            else
                labelText.text = string.format("F%s", DungeonModel.NumToChinese[floor]);
            end
            SetColor(labelText, 255, 255, 255)
        end
        tog.isOn = false;
        tog.transform:SetParent(self.togLayer.transform);
        SetLocalPosition(tog.transform, 0, 0, 0);
        SetLocalScale(tog.transform, 1, 1, 1);
        self.togItems[#self.togItems+1] = tog;
    end

    self.boss_tog_1.gameObject:SetActive(false)
    self:ShowFloorBosses()
    --lua_resMgr:SetImageTexture(self, self.winlose, self.image_ab, "dungeon_result2_win", true);
end

function WorldBossPanel:ShowFloorBosses()
    local bosses = self.togBoss[self.currentFloor] or {}
    destroyTab(self.items)
    self.items = {}
    self.bossitem_0.gameObject:SetActive(true)
    self.selectedItemIndex = 1
    for i=1, #bosses do
        local bossTab = bosses[i]

        if bossTab.lock_lv then
            local lockLv = String2Table(bossTab.lock_lv);
            if #lockLv > 0 then
                local lv = RoleInfoModel:GetInstance():GetMainRoleLevel();
                if lv >= tonumber(lockLv[1]) and lv <= tonumber(lockLv[2]) and self.selectedBossid == nil then
                    self.selectedItemIndex = i;
                    --self.currentFloor = floor
                elseif bossTab.id == self.selectedBossid then
                    self.selectedItemIndex = i;
                    --self.currentFloor = floor
                end
            end
        end

        local item = DungeonScrollItem(newObject(self.bossitem_0), bossTab);
        item.gameObject.name = "world_boss_" .. i;
        self.items[i] = item;
        item:ShowCare(false);
        item:ShowPeace(bossTab.peace == 1);
        AddClickEvent(item.gameObject, handler(self, self.HandleSelectItem))
        --item:SetJie();
        item.transform:SetParent(self.Content.transform);
        SetLocalScale(item.transform, 1, 1, 1);
        SetLocalPosition(item.transform, 0, 0, 0);
        self:RefreshDungeonScrollItem(item);
    end

    local rt = self.Content:GetComponent("RectTransform");
    rt.sizeDelta = Vector2(rt.sizeDelta.x, #self.model.worldBossTab * 103.2);
    --SetLocalPosition(self.Content.transform, 0, -self.selectedItemIndex * 103.2);
    rt.anchoredPosition = Vector2(0, (self.selectedItemIndex - 1) * 90.2);
    self.bossitem_0.gameObject:SetActive(false);

    local ditem = self.items[self.selectedItemIndex];
    --ditem:SetSelected(true);
    self.parentPanel:InitDrops(ditem);
    self.parentPanel:InitModelView(ditem);

    self.qianwangBtn_reddot = RedDot(self.qianwangBtn.transform, nil, RedDot.RedDotType.Nor)
    self.qianwangBtn_reddot:SetPosition(68, 22);
    self:CheckReddot();

    if self.currentFloor and self.currentFloor ~= 0 and self.togItems[self.currentFloor] then
        self:HandleTogClick(self.togItems[self.currentFloor+1].gameObject)
        self.togItems[self.currentFloor+1].isOn = true;
        self:SetToggleColor(self.togItems[self.currentFloor+1])
    else
        self.togItems[1].isOn = true;
        self:HandleTogClick();
        self:SetToggleColor(self.togItems[1])
    end
	self:HandleSelectItem(self.items[self.selectedItemIndex].gameObject)
    if self.currentFloor == 0 then
        self.pilaoText.text = "No fatigue cost"
        SetVisible(self.droptip, true)
    else
        self.pilaoText.text = self.pilao_text or ""
        SetVisible(self.droptip, false)
    end
end

function WorldBossPanel:AddEvent()

    --self.schedules[#self.schedules + 1] = GlobalSchedule:Start(callBack1, 1, -1);
    --[[for i = 1, #self.items, 1 do
        AddClickEvent(self.items[i].gameObject, handler(self, self.HandleSelectItem));
    end--]]

    local call_back = function()
        if not AutoFightManager:GetInstance():GetAutoFightState() then
            GlobalEvent:Brocast(FightEvent.AutoFight)
        end
    end

    local main_role = SceneManager:GetInstance():GetMainRole()
    local main_pos = main_role:GetPosition();

    local qianwang_callback = function(target, x, y)
        local taskid = WorldBossPanel.DungeTaskID;
        if Config.db_game["dunge_worldboss"] then
            local vt = String2Table(Config.db_game["dunge_worldboss"].val);
            if vt then
                taskid = vt[1];
            end
        end

        local task = TaskModel:GetInstance():GetTask(taskid);
        if task then
            local goals = task.goals;
            local cur_goal = goals[1];
            if cur_goal then
                DungeonCtrl:GetInstance():RequestEnterDungeon(cur_goal[2], nil, cur_goal[4]);
            else
                Notify.ShowText("Unable to find the dungeon");
            end
            return
        end

        local item = self.items[self.selectedItemIndex];
        if item then
            if item.data then
                local function ok_func()
                    local sceneid = item.data.scene;
                    local coord = String2Table(item.data.coord);
                    if sceneid and coord then
                        if SceneManager:GetInstance():GetSceneId() == sceneid then
                            OperationManager:GetInstance():TryMoveToPosition(nil, main_pos, { x = coord[1], y = coord[2] }, call_back);
                            local panel = lua_panelMgr:GetPanel(DungeonPanel);
                            if panel then
                                panel:Close();
                            end
                        else
                            DungeonCtrl:GetInstance():RequestEnterWorldBoss(sceneid, coord[1], coord[2]);
                            DungeonModel:GetInstance().SelectedDungeonID = item.data.id;
                        end
                    end
                end
                local boss_type = item.data.type
                local boss_drop_limit = String2Table(Config.db_game["boss_drop_limit"].val)[1]
                if table.containValue(boss_drop_limit, boss_type) then
                    local level = RoleInfoModel:GetInstance():GetRoleValue("level")
                    local creep = Config.db_creep[item.data.id]
                    if level-creep.level >= item.data.drop_lv then
                        Dialog.ShowTwo("Tip","\nYour level is X higher than the boss and no loot will be available after defeating it.\nProceed?\nDaily fatigue left:"..self.curTired,"Confirm",ok_func,nil,"Cancel",nil,nil,"Don't notice me again today",false,nil,-10010)
                        return
                    end
                end
                local power = RoleInfoModel:GetInstance():GetMainRoleData().power
                if power < item.data.power  then
                    local str = string.format("\n\nThat boss has higher CP<color=#eb0000>(%s)</color> and challenging it might be difficult.Proceed anyway?\n   My CP：%s",item.data.power,power)
                    Dialog.ShowTwo("Tip",str,"Confirm",ok_func,nil,"Cancel",nil,nil,"Don't notice me again today",false,nil,-10011)
                    return
                end
                ok_func()
            end
        end
    end
    AddClickEvent(self.qianwangBtn.gameObject, qianwang_callback)

    local shuomingTip = function(target, x, y)
        if self.currentFloor == 0 then
            ShowHelpTip(HelpConfig.Dungeon.worldBoss2 , true)
        else
            ShowHelpTip(HelpConfig.Dungeon.worldBoss , true);
        end
    end
    AddClickEvent(self.shuoming.gameObject, shuomingTip)

    self.events[#self.events + 1] = GlobalEvent.AddEventListener(DungeonEvent.WORLD_BOSS_LIST, handler(self, self.HaneleBossList));

    AddEventListenerInTab(DungeonEvent.UpdateReddot, handler(self, self.CheckReddot), self.events);

    for k, v in pairs(self.togItems) do
        AddValueChange(v.gameObject, handler(self, self.HandleTogClick));
    end

    --self.events[#self.events + 1] = GlobalEvent.AddEventListener(DungeonEvent.WORLD_BOSS_CARE, handler(self, self.HaneleBossCare));
end

function WorldBossPanel:HandleTogClick(target, bool)
    if bool then
        for i = 1, #self.togItems do
            local labelObj = GetChild(self.togItems[i], "Label")
            if labelObj then
                local LabelText = GetText(labelObj)
                SetColor(LabelText, 255, 255, 255)
            end
            if self.togItems[i].gameObject == target then
                self.currentFloor = i-1;
                self:ShowFloorBosses();
                SetColor(LabelText, 133, 132, 176)
            end
        end
    end
end

function WorldBossPanel:SetToggleColor(target)
    if target then
        local labelObj = GetChild(target, "Label")
        if labelObj then
            local LabelText = GetText(labelObj)
            SetColor(LabelText, 133, 132, 176)
        end
    end
end

--function WorldBossPanel:HaneleBossCare(data)
--    if self.items then
--        for i = 1, #self.items, 1 do
--            local bossTab = self.items[i].data;
--            if bossTab.id == data.id then
--                self.items[i]:SetIsCare(data.op == 1);
--                self.items[i]:ShowCare(false);
--            end
--        end
--    end
--end

function WorldBossPanel:HaneleBossList(data)
    if self.items then
        for i = 1, #self.items, 1 do
            self:RefreshDungeonScrollItem(self.items[i]);
        end
        self.parentPanel:RefreshProp(self.items[self.selectedItemIndex]);
    end

    --BOSS 疲劳: 1/3
    --if data.tired then
    --    local tired = 10;
    --    if Config.db_game["boss_tired"] then
    --        local val = String2Table(Config.db_game["boss_tired"].val);
    --        tired = tonumber(val[1]);
    --    end
    --    self.pilao_text = "首领疲劳: " .. (SafetoNumber(tired) - SafetoNumber(data.tired)) .. "/" .. tired
    --    self.curTired = SafetoNumber(tired) - SafetoNumber(data.tired)
    --    if self.currentFloor > 0 then
    --        self.pilaoText.text = self.pilao_text;
    --    else
    --        self.pilaoText.text = "不减少疲劳值"
    --    end
    --end
    local main_role_data = RoleInfoModel:GetInstance():GetMainRoleData()
    if main_role_data then
        local buffer = main_role_data:GetBuffByID(enum.BUFF_ID.BUFF_ID_WORLD_BOSS_KILL_TIRED)
        local value = (buffer and buffer.value or 0)
        local tired = 10;
        if Config.db_game["boss_tired"] then
            local val = String2Table(Config.db_game["boss_tired"].val);
            tired = tonumber(val[1]);
        end
        self.curTired = SafetoNumber(tired) - SafetoNumber(value)
        self.pilao_text = "Boss fatigue: " .. self.curTired .. "/" .. tired;
        if self.currentFloor > 0 then
            self.pilaoText.text =self.pilao_text
        else
            self.pilaoText.text = "No fatigue will be cost"
        end
    end


--  等收到协议  才设置 默认item
    self:HandleSelectItem(self.items[self.selectedItemIndex].gameObject);
end

function WorldBossPanel:RefreshDungeonScrollItem(item)
    local bossTab = item.data;

    local bossinfo = DungeonModel:GetInstance():GetDungeonBossInfo(enum.BOSS_TYPE.BOSS_TYPE_WORLD, bossTab.id);
    if bossinfo then
        local time = bossinfo.born;--1541494877
        item:StartSechudle(time);
        item:SetIsCare(bossinfo.care);
        self.parentPanel:SetIsCare(bossinfo.care);
        --local monsterTab = Config.db_creep[bossTab.id];
        --self.valueTab[1].text = tostring(monsterTab.att);
        --self.valueTab[2].text = tostring(monsterTab.hpmax);
        --self.valueTab[3].text = tostring(monsterTab.def);
        --self.valueTab[4].text = tostring(monsterTab.hit);
        --self.valueTab[5].text = tostring(monsterTab.miss);
    end
end

function WorldBossPanel:HandleSelectItem(target, x, y)
    local item = nil;
    for i = 1, #self.items, 1 do
        if self.items[i].gameObject == target then
            item = self.items[i];
            self.selectedItemIndex = i;
        end
        self.items[i]:SetSelected(false);
    end
    item:SetSelected(true);
    self.parentPanel:RefreshProp(item);
    --self.robotSetValue = true;
    --self.care.isOn = toBool(item.care);
    --self.robotSetValue = false;
    local tab = DungeonModel:GetInstance():GetDungeonBossInfo(enum.BOSS_TYPE.BOSS_TYPE_WORLD, item.data.id);
    if tab then
        self.parentPanel:SetIsCare(tab.care)
    end

    self.parentPanel:InitDrops(item);

    self.parentPanel:SetBG(item);

    self.parentPanel:InitModelView(item);
end

function WorldBossPanel:Handle()

end

function WorldBossPanel:StopAllSchedules()
    for i = 1, #self.schedules, 1 do
        GlobalSchedule:Stop(self.schedules[i]);
    end
    self.schedules = {};
end

function WorldBossPanel:GetSelectedID()
    if self.items and self.items[self.selectedItemIndex] and self.items[self.selectedItemIndex].data then
        return self.items[self.selectedItemIndex].data.id;
    end
    return 0;
end

function WorldBossPanel:GetSelectedBossType()
    return enum.BOSS_TYPE.BOSS_TYPE_WORLD;
end

function WorldBossPanel:CheckReddot()
    local tab = DungeonModel:GetInstance().red_dot_list;

    if tab[enum.SCENE_STYPE.SCENE_STYPE_BOSS_WORLD] and self.qianwangBtn_reddot then
        self.qianwangBtn_reddot:SetRedDotParam(true);
    else
        self.qianwangBtn_reddot:SetRedDotParam(false);
    end
end