module(...)
--dialogueani editor build
DATA={
	[1]={
		cmdList={
			[1]={
				args={
					[1]={[1]=[[飞龙哥]],},
					[2]={[1]=1150,},
					[3]={[1]=15.5,[2]=8.4,},
					[4]={[1]=-144,},
					[5]={[1]=1,},
					[6]={[1]=0,},
				},
				cmdType=[[player]],
				func=[[AddPlayer]],
				name=[[生成人物]],
			},
			[2]={
				args={
					[1]={[1]=[[邓酒爷]],},
					[2]={[1]=1151,},
					[3]={[1]=13.8,[2]=8.5,},
					[4]={[1]=106,},
					[5]={[1]=2,},
					[6]={[1]=0,},
				},
				cmdType=[[player]],
				func=[[AddPlayer]],
				name=[[生成人物]],
			},
			[3]={
				args={
					[1]={[1]=[[小弟阿飞]],},
					[2]={[1]=1005,},
					[3]={[1]=14,[2]=7.5,},
					[4]={[1]=54,},
					[5]={[1]=3,},
					[6]={[1]=0,},
				},
				cmdType=[[player]],
				func=[[AddPlayer]],
				name=[[生成人物]],
			},
			[4]={
				args={
					[1]={[1]=[[小弟铁蛋]],},
					[2]={[1]=1007,},
					[3]={[1]=14.8,[2]=7,},
					[4]={[1]=12,},
					[5]={[1]=4,},
					[6]={[1]=0,},
				},
				cmdType=[[player]],
				func=[[AddPlayer]],
				name=[[生成人物]],
			},
		},
		delay=1,
		idx=1,
		startTime=0,
		type=[[player]],
	},
	[2]={
		cmdList={
			[1]={
				args={
					[1]={[1]=1,[2]=[[飞龙哥]],},
					[2]={[1]=[[传说中闹鬼的月见岛也就是吓吓小孩！]],},
				},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=3,
		idx=2,
		startTime=1,
		type=[[player]],
	},
	[3]={
		cmdList={
			[1]={
				args={
					[1]={[1]=2,[2]=[[邓酒爷]],},
					[2]={[1]=[[还是老大厉害！识破这些唬人的伎俩！]],},
				},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[2]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[wuyu3]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
		},
		delay=3,
		idx=3,
		startTime=4,
		type=[[player]],
	},
	[4]={
		cmdList={
			[1]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=[[就是！老大厉害！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[2]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=[[老大霸气！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=3,
		idx=4,
		startTime=7,
		type=[[player]],
	},
	[5]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[show]],},},
				cmdType=[[player]],
				func=[[PlayerDoAction]],
				name=[[人物动作]],
			},
			[2]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[走！进里面看看！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=4,
		idx=5,
		startTime=10,
		type=[[player]],
	},
	[6]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=21.4,[2]=11.8,},[3]={[1]=48,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[2]={
				args={[1]={[1]=2,[2]=[[邓酒爷]],},[2]={[1]=20.6,[2]=10.7,},[3]={[1]=48,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[3]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=19.6,[2]=11.3,},[3]={[1]=48,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[4]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=21.6,[2]=10.3,},[3]={[1]=14.5,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
		},
		delay=3,
		idx=6,
		startTime=14,
		type=[[player]],
	},
	[7]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[zhenjing]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
			[2]={
				args={[1]={[1]=2,[2]=[[邓酒爷]],},[2]={[1]=[[zhenjing]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
			[3]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=[[zhenjing]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
			[4]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=[[zhenjing]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
		},
		delay=3,
		idx=7,
		startTime=17,
		type=[[player]],
	},
	[8]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[还有别人敢来探险？]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[2]={
				args={[1]={[1]=2,[2]=[[邓酒爷]],},[2]={[1]=[[weiqu]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
			[3]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=[[weiqu]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
			[4]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=[[weiqu]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
		},
		delay=3,
		idx=8,
		startTime=20,
		type=[[player]],
	},
	[9]={
		cmdList={
			[1]={
				args={
					[1]={[1]=2,[2]=[[邓酒爷]],},
					[2]={[1]=[[不是啊老大，你看对方好像没有脚……]],},
				},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[2]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=[[那那那，那是什么？]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[3]={
				args={
					[1]={[1]=4,[2]=[[小弟铁蛋]],},
					[2]={[1]=[[不像妖妖妖，妖族啊……]],},
				},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[4]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=22.5,[2]=12.5,},[3]={[1]=24.6,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
		},
		delay=3,
		idx=9,
		startTime=23,
		type=[[player]],
	},
	[10]={
		cmdList={
			[1]={
				args={[1]={[1]=2,[2]=[[邓酒爷]],},[2]={[1]=16,[2]=6.9,},[3]={[1]=-165,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[2]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=16,[2]=6.9,},[3]={[1]=-165,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[3]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=16,[2]=6.9,},[3]={[1]=-165,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[4]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[你是哪条道上的？]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[5]={
				args={[1]={[1]=2,[2]=[[邓酒爷]],},[2]={[1]=[[有鬼啊！！！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[6]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=[[撞鬼啦！！！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
			[7]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[idleWar]],},},
				cmdType=[[player]],
				func=[[PlayerDoAction]],
				name=[[人物动作]],
			},
			[8]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=[[鬼鬼鬼！！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=3,
		idx=10,
		startTime=26,
		type=[[player]],
	},
	[11]={
		cmdList={
			[1]={
				args={[1]={[1]=2,[2]=[[邓酒爷]],},[2]={[1]=0,},},
				cmdType=[[player]],
				func=[[SetPlayerActive]],
				name=[[设置人物是否可见]],
			},
			[2]={
				args={[1]={[1]=3,[2]=[[小弟阿飞]],},[2]={[1]=0,},},
				cmdType=[[player]],
				func=[[SetPlayerActive]],
				name=[[设置人物是否可见]],
			},
			[3]={
				args={[1]={[1]=4,[2]=[[小弟铁蛋]],},[2]={[1]=0,},},
				cmdType=[[player]],
				func=[[SetPlayerActive]],
				name=[[设置人物是否可见]],
			},
			[4]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[不不不，不对劲……]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=3,
		idx=11,
		startTime=29,
		type=[[player]],
	},
	[12]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=-147,},},
				cmdType=[[player]],
				func=[[SetPlayerFaceTo]],
				name=[[设置人物朝向]],
			},
			[2]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[zhenjing]],},[3]={[1]=1,},},
				cmdType=[[player]],
				func=[[PlayerShowSocialEmoji]],
				name=[[社交表情]],
			},
		},
		delay=3,
		idx=12,
		startTime=32,
		type=[[player]],
	},
	[13]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[人人人，人呢！？]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=2,
		idx=13,
		startTime=35,
		type=[[player]],
	},
	[14]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=16,[2]=6.9,},[3]={[1]=-165,},},
				cmdType=[[player]],
				func=[[PlayerRunto]],
				name=[[人物移动]],
			},
			[2]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=[[有鬼啊啊啊啊啊啊！]],},},
				cmdType=[[player]],
				func=[[PlayerSay]],
				name=[[剧场冒泡说话]],
			},
		},
		delay=3,
		idx=14,
		startTime=37,
		type=[[player]],
	},
	[15]={
		cmdList={
			[1]={
				args={[1]={[1]=1,[2]=[[飞龙哥]],},[2]={[1]=0,},},
				cmdType=[[player]],
				func=[[SetPlayerActive]],
				name=[[设置人物是否可见]],
			},
		},
		delay=1,
		idx=15,
		startTime=40,
		type=[[player]],
	},
}

CONFIG={
	isLoop=1,
	isStroy=0,
	isTrigger=1,
	loopTime=60,
	mapInfo=[[]],
	minTriggerLevel=5,
	name=[[剧场动画名_10120]],
}
