---魔法卡卡片UI
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 18/12/04 16:18
---
MagicCard = MagicCard or class("MagicCard", BaseItem)
local this = MagicCard
--类似的卡片数据
--[20010] = {id = 20010, star = 0, max_star = 3, cost = [[]], slot = 2, attr_type = [[21]], base = [[{{21,10}}]], rare = [[]], gate = 1, score = 1000, gain = [[{90010012,100}]]},
--slot == 1普通属性,2是核心卡
--融合卡有2个基础属性,红色卡有极品属性
function MagicCard:ctor(parent_node, data)
    self.abName = "magiccard";
    self.image_ab = "magiccard_image";
    self.assetName = "card"
    self.layer = "UI"
    self.model = CardModel.GetInstance()
    self.schedules = {};
    self.events = {};
    self.data = data;
    self.cardData = nil;

    self.showcardname = true;
    self.showcardlevel = false;
    MagicCard.super.Load(self);
end

function MagicCard:dctor()
    GlobalEvent:RemoveTabListener(self.events);
    if self.schedule then
        GlobalSchedule:Stop(self.schedule);
    end
    self.cardData = nil;
    self.data = nil;
    self.model = nil;

    if self.red_dot then
        self.red_dot:destroy()
        self.red_dot = nil
    end

    self.starItems = nil;
end

function MagicCard:LoadCallBack()
    self.nodes = {
        "icon", "level", "ball", "ball2", "cname", "stars", "bg", "stars/star_1", "stars/star_4", "stars/star_5", "stars/star_6", "stars/star_2", "stars/star_3",
        "own_prop", "max_star_img", "cardlocktxt",
    }
    self:GetChildren(self.nodes);

    SetLocalPosition(self.transform, 0, 0, 0);
    --SetLocalScale(self.transform, 1, 1, 1);

    self:SetCardSacle(self.scale);

    self:InitUI();
    self:AddEvents();

end

function MagicCard:InitUI()
    self.starItems = {};
    for i = 1, 6, 1 do
        self.starItems[i] = GetImage(self["star_" .. i]);
        SetGameObjectActive(self.starItems[i], false);
    end

    self.cname = GetText(self.cname);
    self.level = GetText(self.level);
    self.icon = GetImage(self.icon);

    self.ball = GetImage(self.ball);
    self.ball2 = GetImage(self.ball2);

    self.bg = GetImage(self.bg);

    self.own_prop = GetImage(self.own_prop);
    self.max_star_img = GetImage(self.max_star_img);

    SetGameObjectActive(self.own_prop, false);
    SetGameObjectActive(self.own_prop, false);

    self.cardlocktxt = GetText(self.cardlocktxt);
    SetGameObjectActive(self.cardlocktxt);
    self:ShowStars(self.showstar);

    if self.data then
        self:InitData();
    end

    self:ShowCardName(self.showcardname);
    self:ShowCardLV(self.showcardlevel);

    self:SetCardLv(self.cardLevel);

    self:ShowOwn(self.showown);
    self:ShowMaxStarImg(self.showmaxstarimg);

    if self.cardlocktext then
        self:SetCardLock(self.cardlocktext);
    end


    self.red_dot = RedDot(self.transform, nil, RedDot.RedDotType.Nor);
    self.red_dot:SetPosition(98, 106);
    self.red_dot:SetScale(1.5);

    if self.is_udpate_reddot ~= nil then
        self:SetRedDotParam(self.is_udpate_reddot)
        self.is_udpate_reddot = nil
    end
end

function MagicCard:SetRedDotParam(bool)
    bool = toBool(bool);
    if self.is_loaded then
        self.red_dot:SetRedDotParam(bool)
    else
        self.is_udpate_reddot = bool
    end
end

function MagicCard:InitData()
    if self.data.name then
        self.cname.text = self.data.name;
    end
    self:SetCardCoreType(self.data.slot == 2);

    self:SetMaxStar(self.data.max_star);
    self:SetStarNum(self.data.star);

    local itemConfig = Config.db_item[self.data.id];
    if itemConfig then
        self:SetBgColor(itemConfig);
    end

    self:SetIcon();
end

function MagicCard:UpdateData(data)
    self.data = data;
    if data and self.is_loaded then
        self:InitData();
    end
end

function MagicCard:SetIcon()
    if self.data then
        local itemConfig = Config.db_item[self.data.id];
        if itemConfig then
            --local call_back = function()
                SetLocalScale(self.icon.transform, 1.5, 1.5, 1.5);
            --end
            lua_resMgr:SetImageTexture(self, self.icon, "iconasset/icon_magic_card", itemConfig.icon, false);
        end
    end
end

function MagicCard:SetBgColor(itemConfig)
    lua_resMgr:SetImageTexture(self, self.bg, self.image_ab, "card" .. itemConfig.color, true);
end

function MagicCard:SetCardLv(num)
    if not num then
        return ;
    end
    --print2(debug.traceback() .. num);
    self.cardLevel = tonumber(num);
    if self.cardLevel ~= 0 then
        self:ShowCardLV(true);
    else
        self:ShowCardLV(false);
    end
    if self.level then
        self.level.text = "LV." .. tostring(num);
    end

end

function MagicCard:ShowCardName(bool)
    bool = toBool(bool);
    self.showcardname = bool;
    SetGameObjectActive(self.cname, bool);
end

function MagicCard:SetCardLock(level)
    if self.cardlocktxt then
        SetGameObjectActive(self.cardlocktxt, true);
        self.cardlocktxt.text = tonumber(level) .. "Unlock at Stage X";
    else
        self.cardlocktext = level;
    end
end

function MagicCard:ShowCardLV(bool)
    bool = toBool(bool);
    self.showcardlevel = bool;
    SetGameObjectActive(self.level, bool);
end


--@ling autofun
function MagicCard:SetCardCoreType(bool)
    bool = toBool(bool);
    SetGameObjectActive(self.ball, bool);
    SetGameObjectActive(self.ball2, not bool);
end

function MagicCard:AddEvents()

end

function MagicCard:SetStarNum(num)
    for i = 1, num, 1 do
        SetGameObjectActive(self.starItems[i], true);
        SetAlpha(self.starItems[i], 1);
    end
end

function MagicCard:ShowStars(bool)
    bool = toBool(bool);
    self.showstar = bool;
    if self.starItems then
        for i = 1, 6, 1 do
            SetGameObjectActive(self.starItems[i], bool);
        end
    end
end

function MagicCard:SetCardSacle(num)
    num = num or 1;
    if self.transform then
        SetLocalScale(self.transform, num, num, num);
    else
        self.scale = num;
    end
end

function MagicCard:SetMaxStar(num)
    for i = 1, 6, 1 do
        if i <= num then
            SetGameObjectActive(self.starItems[i], true);
            SetAlpha(self.starItems[i], 0.5);
        else
            SetGameObjectActive(self.starItems[i], false);
        end
    end
end

function MagicCard:ShowOwn(bool)
    bool = toBool(bool);
    self.showown = bool;
    if self.own_prop then
        SetGameObjectActive(self.own_prop, bool);
    end
end
--比上面的优先级高
function MagicCard:ShowMaxStarImg(bool)
    bool = toBool(bool);
    self.showmaxstarimg = bool;
    if self.max_star_img then
        SetGameObjectActive(self.max_star_img, bool);
    end
end


