import(".netpack.init")
import(".netcommand.init")
import(".netsend.init")
import(".netprotocolext.init")
import(".protocols")
import(".Protocol")
netconn = import(".netconnect").new()
import(".netfunc")
import(".netdef")
