local t = {
		{
			name="ArenaPlayerListLayer",
			ui ="ArenaPlayerListLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaRewardItem",
			ui ="ArenaRewardItem.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaRewardListLayer",
			ui ="ArenaRewardListLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaHomeLayer",
			ui ="ArenaHomeLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaPlayerPage1Layer",
			ui ="ArenaPlayerPage1Layer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaPlayerPage2Layer",
			ui ="ArenaPlayerPage2Layer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaResultLayer",
			ui ="ArenaResultLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="OtherArmyVSLayer",
			ui ="OtherArmyVSLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaZhanbao",
			ui ="ArenaZhanbao.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaZhanbaoCell1",
			ui ="ArenaZhanbaoCell1.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaZhanbaoCell2",
			ui ="ArenaZhanbaoCell2.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
		{
			name="ArenaZhanbaoCell3",
			ui ="ArenaZhanbaoCell3.lua",
			x=0,
			y=0,
			speed=0,
			layer="arena",
			canLoad=true,
			logic="",
		},
}
return t
