-- this file is generated by program!
-- don't change it manaully.
-- source file: adventure_data.xls

Config = Config or {} 
Config.AdventureData = Config.AdventureData or {}
Config.AdventureData.data_map_key_depth = 1
Config.AdventureData.data_map_length = 4
Config.AdventureData.data_map_lan = "en"
Config.AdventureData.data_map = {
	[1] = {id=1,res_id=1},
	[2] = {id=2,res_id=1},
	[3] = {id=3,res_id=1},
	[4] = {id=4,res_id=2},
}
