-- this file is generated by program!
-- don't change it manaully.
-- source file: arena_elite_data.xls

Config = Config or {} 
Config.ArenaEliteData = Config.ArenaEliteData or {}
Config.ArenaEliteData.data_elite_last_level_key_depth = 1
Config.ArenaEliteData.data_elite_last_level_length = 22
Config.ArenaEliteData.data_elite_last_level_lan = "en"
Config.ArenaEliteData.data_elite_last_level = {
	[0] = 22,
	[2] = 1,
	[3] = 2,
	[4] = 3,
	[5] = 4,
	[6] = 5,
	[7] = 6,
	[8] = 7,
	[9] = 8,
	[10] = 9,
	[11] = 10,
	[12] = 11,
	[13] = 12,
	[14] = 13,
	[15] = 14,
	[16] = 15,
	[17] = 16,
	[18] = 17,
	[19] = 18,
	[20] = 19,
	[21] = 20,
	[22] = 21,
}
