-- this file is generated by program!
-- don't change it manaully.
-- source file: arena_cluster_data.xls

Config = Config or {} 
Config.ArenaClusterData = Config.ArenaClusterData or {}
Config.ArenaClusterData.data_rank_award_key_depth = 1
Config.ArenaClusterData.data_rank_award_length = 11
Config.ArenaClusterData.data_rank_award_lan = "en"
Config.ArenaClusterData.data_rank_award = {
	[1] = {items={{30,12000},{10450,2400},{51101,1}},max=1,min=1},
	[2] = {items={{30,10000},{10450,2000},{51102,1}},max=2,min=2},
	[3] = {items={{30,8500},{10450,1700},{51103,1}},max=3,min=3},
	[5] = {items={{30,7000},{10450,1400}},max=5,min=4},
	[10] = {items={{30,6000},{10450,1200}},max=10,min=6},
	[20] = {items={{30,5000},{10450,1000}},max=20,min=11},
	[50] = {items={{30,4500},{10450,900}},max=50,min=21},
	[100] = {items={{30,4000},{10450,800}},max=100,min=51},
	[200] = {items={{30,3500},{10450,700}},max=200,min=101},
	[300] = {items={{30,3000},{10450,600}},max=300,min=201},
	[99999] = {items={{30,2500},{10450,500}},max=99999,min=301},
}
