-- this file is generated by program!
-- don't change it manaully.
-- source file: arena_elite_war_order_data.xls

Config = Config or {} 
Config.ArenaEliteWarOrderData = Config.ArenaEliteWarOrderData or {}
Config.ArenaEliteWarOrderData.data_constant_key_depth = 1
Config.ArenaEliteWarOrderData.data_constant_length = 2
Config.ArenaEliteWarOrderData.data_constant_lan = "en"
Config.ArenaEliteWarOrderData.data_constant = {
	["rule_desc"] = {label="rule_desc",val=1,desc="Event rules:\n1. Participate in the tier match and get the designated wins to get super-value rewards\n2. Pay to buy the advanced card to unlock the advanced rewards and get the title of [Wang Zhezhi] limited time\n3. After the event, the game will be won The progress will be cleared, please complete the task in time to receive the corresponding reward!"},
	["warn_desc"] = {label="warn_desc",val=1,desc="The event will end after %s\nAfter the event ends, the winning progress will be cleared. \nPlease complete the task in time to avoid missing the reward!"},
}
