-- this file is generated by program!
-- don't change it manaully.
-- source file: attr_data.xls

Config = Config or {} 
Config.AttrData = Config.AttrData or {}
Config.AttrData.data_id_to_name_key_depth = 1
Config.AttrData.data_id_to_name_length = 29
Config.AttrData.data_id_to_name_lan = "en"
Config.AttrData.data_id_to_name = {
	[101] = "ATK",
	[102] = "P.DEF",
	[103] = "SP.DEF",
	[104] = "HP",
	[105] = "HP",
	[106] = "SPD",
	[107] = "DEF",
	[111] = "HIT",
	[112] = "Dodge",
	[113] = "CRT",
	[114] = "C.DMG",
	[115] = "CC",
	[116] = "Anti-CC",
	[117] = "Anti-CR",
	[118] = "ATK",
	[119] = "DEF",
	[120] = "HP",
	[121] = "DB",
	[122] = "No DMG",
	[123] = "Heal Output",
	[124] = "Healed",
	[125] = "P.DMG",
	[126] = "SP.DMG",
	[127] = "P.RES",
	[128] = "SP.RES",
	[129] = "SPD",
	[130] = "P.DEF",
	[131] = "SP.DEF",
	[132] = "toughness",
}
