-- this file is generated by program!
-- don't change it manaully.
-- source file: break_egg_data.xls

Config = Config or {} 
Config.BreakEggData = Config.BreakEggData or {}
Config.BreakEggData.data_const_key_depth = 1
Config.BreakEggData.data_const_length = 15
Config.BreakEggData.data_const_lan = "en"
Config.BreakEggData.data_const = {
	["add_lucky"] = {val=1,desc="Smash the egg to add lucky value"},
	["best_egg_max"] = {val=1,desc="Maximum number of premium eggs"},
	["egg_num"] = {val=6,desc="Number of golden eggs"},
	["free_time"] = {val=1,desc="Free refreshes"},
	["give_exp"] = {val=5000,desc="Free XP with a single purchase"},
	["gold_once"] = {val=200,desc="A single smashing egg consumes diamonds"},
	["holiday_rule"] = {val=1,desc="<div fontcolor=#fca000>How to play:</div><div fontcolor=#e7d499>\n1. During the event, consume</div><div fontcolor=#00ff00>Little Golden Hammer</div><div fontcolor=# e7d499>Smash the golden egg to get the props rewards in the golden egg</div><div fontcolor=#e7d499>\n2. Every time you refresh the golden egg, there is a probability that it can be brushed out</div><div fontcolor=#00ff00 >Superior Egg</div><div fontcolor=#e7d499>, smash it out</div><div fontcolor=#00ff00>Extreme Egg</div><div fontcolor=#e7d499> Definitely get the best reward</div>< div fontcolor=#e7d499>\n3. After smashing all the eggs, it will automatically refresh for free</div><div fontcolor=#e7d499>\n4. You will get lucky values when you smash the golden eggs. The higher the lucky value, the higher the lucky value will be refreshed</div>< div fontcolor=#00ff00>The best egg</div><div fontcolor=#e7d499>The higher the probability</div><div fontcolor=#e7d499>\n5. After the lucky value is full, the next refresh will be out</div> ><div fontcolor=#00ff00>Superior Egg</div><div fontcolor=#e7d499>, the lucky value is cleared to zero after the Super Egg is brushed. </div><div fontcolor=#e7d499>\n6. Probability of winning the best egg</div><div fontcolor=#e7d499>\n5-star random fragments*25:</div><div fontcolor=#15ee5c>15% </div><div fontcolor=#e7d499>\nHunting Ball*1:</div><div fontcolor=#15ee5c>15%</div><div fontcolor=#e7d499>\nStar Card*500 :</div><div fontcolor=#15ee5c>35%</div><div fontcolor=#e7d499>\nAdvanced Elf Ball*2:</div><div fontcolor=#15ee5c>35%</div> <div fontcolor=#e7d499>\n7. Normal egg winning probability</div><div fontcolor=#e7d499>\nStar Card*150:</div><div fontcolor=#15ee5c>10%</div ><div fontcolor=#e7d499>\nGem Essence*100:</div><div fontcolor=#15ee5c>10%</div><div fontcolor=#e7d499>\nOther props:</div><div fontcolor=#15ee5c>80%</div>"},
	["item_bid"] = {val=37004,desc="Little Golden Hammer"},
	["item_price"] = {val=200,desc="Single small golden hammer price"},
	["lev_limit"] = {val=10,desc="Open level"},
	["lucky_max"] = {val=8,desc="Lucky value upper limit"},
	["lucky_min"] = {val=0,desc="The lower limit of the lucky value required for the appearance of the best egg"},
	["open_lev"] = {val=10,desc="Open level"},
	["record_len"] = {val=30,desc="Total server records"},
	["refresh_gold"] = {val=50,desc="Refresh the required diamonds"},
}
