-- this file is generated by program!
-- don't change it manaully.
-- source file: dailyplay_data.xls

Config = Config or {} 
Config.DailyplayData = Config.DailyplayData or {}
Config.DailyplayData.data_exerciseactivity_key_depth = 1
Config.DailyplayData.data_exerciseactivity_length = 4
Config.DailyplayData.data_exerciseactivity_lan = "en"
Config.DailyplayData.data_exerciseactivity = {
	[1] = {id=1,activate={{"lev",15}},goto_id=2,is_open=1,pic_name="txt_cn_activity_item_12",val={{1,22,29904,72001}},desc="Participate to get a lot of useful items",lock_desc="Adventurer 15 levels open",name="Eevee\'s Treasure"},
	[2] = {id=2,activate={{"lev",25}},goto_id=1,is_open=1,pic_name="txt_cn_activity_item_11",val={{22,1,10403,10450}},desc="Participate to get a lot of Pokémon XP",lock_desc="Adventurer 25 levels open",name="Endless Trial"},
	[3] = {id=3,activate={{"lev",30}},goto_id=3,is_open=1,pic_name="txt_cn_activity_item_14",val={{29905,29904,1,25}},desc="Participate to get battle points and gold coins",lock_desc="Adventurer starts at level 30",name="Plane Battle"},
	[4] = {id=4,activate={{"lev",35}},goto_id=4,is_open=1,pic_name="txt_cn_activity_item_13",val={{50701,50702,50703}},desc="Participate to get the title of mighty power",lock_desc="Adventurer level 35 opens",name="Galaxy Temple"},
}
