-- this file is generated by program!
-- don't change it manaully.
-- source file: day_goals_data.xls

Config = Config or {} 
Config.DayGoalsData = Config.DayGoalsData or {}
Config.DayGoalsData.data_all_target_key_depth = 3
Config.DayGoalsData.data_all_target_length = 3
Config.DayGoalsData.data_all_target_lan = "en"
Config.DayGoalsData.data_all_target = {
	[1] = {
		[1] = {
			[1] = {award={{3,1000}},goal=20,id=1,period=1},
		},
		[2] = {
			[1] = {award={{10403,5}},goal=50,id=2,period=1},
		},
		[3] = {
			[1] = {award={{37002,5}},goal=70,id=3,period=1},
		},
		[4] = {
			[1] = {award={{3,5000}},goal=100,id=4,period=1},
		},
	},
	[4] = {
		[103] = {
			[1] = {award={{3,1000}},goal=20,id=103,period=4},
		},
		[203] = {
			[1] = {award={{10403,5}},goal=50,id=203,period=4},
		},
		[303] = {
			[1] = {award={{37002,5}},goal=70,id=303,period=4},
		},
		[403] = {
			[1] = {award={{3,5000}},goal=100,id=403,period=4},
		},
	},
	[7] = {
		[107] = {
			[1] = {award={{3,1000}},goal=20,id=107,period=7},
		},
		[207] = {
			[1] = {award={{10403,5}},goal=50,id=207,period=7},
		},
		[307] = {
			[1] = {award={{37002,5}},goal=70,id=307,period=7},
		},
		[407] = {
			[1] = {award={{3,5000}},goal=100,id=407,period=7},
		},
	},
}
