-- this file is generated by program!
-- don't change it manaully.
-- source file: day_goals_new_data.xls

Config = Config or {} 
Config.DayGoalsNewData = Config.DayGoalsNewData or {}
Config.DayGoalsNewData.data_make_lev_list_key_depth = 2
Config.DayGoalsNewData.data_make_lev_list_length = 10
Config.DayGoalsNewData.data_make_lev_list_lan = "en"
Config.DayGoalsNewData.data_make_lev_list = {
	[2] = {
		[1] = {exp=0,lev=1,period=2,reward={{10403,2},{37001,8}},title_name="Reach level 1 in Adventure Diary"},
		[2] = {exp=70,lev=2,period=2,reward={{10403,3},{37001,8}},title_name="Reach level 2 in Adventure Diary"},
		[3] = {exp=140,lev=3,period=2,reward={{38080,1},{37001,8}},title_name="Reach level 3 in Adventure Diary"},
		[4] = {exp=200,lev=4,period=2,reward={{38081,1},{37001,8}},title_name="Reach level 4 in the Adventure Diary"},
		[5] = {exp=270,lev=5,period=2,reward={{37002,1},{37001,8}},title_name="Reach level 5 in the Adventure Diary"},
		[6] = {exp=330,lev=6,period=2,reward={{3,2000},{37001,8}},title_name="Reach level 6 in the Adventure Diary"},
		[7] = {exp=390,lev=7,period=2,reward={{14001,1},{37001,8}},title_name="Reach level 7 in the Adventure Diary"},
		[8] = {exp=450,lev=8,period=2,reward={{24908,50},{37001,8}},title_name="Reach level 8 in Adventure Diary"},
	},
	[3] = {
		[1] = {exp=50,lev=1,period=3,reward={{10403,2},{10450,300}},title_name="Unlock the ordinary magic box (50 hope marks)"},
		[2] = {exp=100,lev=2,period=3,reward={{10403,3},{10450,300}},title_name="Unlock the lucky magic box (100 hope marks)"},
		[3] = {exp=150,lev=3,period=3,reward={{37002,1},{10450,300}},title_name="Unlock the advanced magic box (150 hope marks)"},
		[4] = {exp=200,lev=4,period=3,reward={{38091,1},{10450,300}},title_name="Unlock the Super Magic Box (200 hope marks)"},
		[5] = {exp=250,lev=5,period=3,reward={{3,2000},{10450,300}},title_name="Unlock the luxurious magic box (250 hope marks)"},
		[6] = {exp=300,lev=6,period=3,reward={{14001,1},{10450,300}},title_name="Unlock the noble magic box (300 hope marks)"},
		[7] = {exp=350,lev=7,period=3,reward={{26902,50},{10450,300}},title_name="Unlock the Supreme Magic Box (350 hope marks)"},
	},
	[5] = {
		[1] = {exp=0,lev=1,period=5,reward={{10403,2},{72001,15}},title_name="Reach level 1 in Adventure Diary"},
		[2] = {exp=70,lev=2,period=5,reward={{10403,3},{72001,15}},title_name="Reach level 2 in Adventure Diary"},
		[3] = {exp=140,lev=3,period=5,reward={{38081,1},{72001,15}},title_name="Reach level 3 in Adventure Diary"},
		[4] = {exp=200,lev=4,period=5,reward={{38091,1},{72001,15}},title_name="Reach level 4 in the Adventure Diary"},
		[5] = {exp=270,lev=5,period=5,reward={{37002,1},{72001,15}},title_name="Reach level 5 in the Adventure Diary"},
		[6] = {exp=330,lev=6,period=5,reward={{3,2000},{72001,15}},title_name="Reach level 6 in the Adventure Diary"},
		[7] = {exp=390,lev=7,period=5,reward={{14001,1},{72001,15}},title_name="Reach level 7 in the Adventure Diary"},
		[8] = {exp=450,lev=8,period=5,reward={{24903,50},{72001,15}},title_name="Reach level 8 in Adventure Diary"},
	},
	[6] = {
		[1] = {exp=50,lev=1,period=6,reward={{10403,2},{10450,300}},title_name="Unlock the ordinary magic box (50 hope marks)"},
		[2] = {exp=100,lev=2,period=6,reward={{10403,3},{10450,300}},title_name="Unlock the lucky magic box (100 hope marks)"},
		[3] = {exp=150,lev=3,period=6,reward={{37002,1},{10450,300}},title_name="Unlock the advanced magic box (150 hope marks)"},
		[4] = {exp=200,lev=4,period=6,reward={{38091,1},{10450,300}},title_name="Unlock the Super Magic Box (200 hope marks)"},
		[5] = {exp=250,lev=5,period=6,reward={{3,2000},{10450,300}},title_name="Unlock the luxury magic box (250 hope marks)"},
		[6] = {exp=300,lev=6,period=6,reward={{14001,1},{10450,300}},title_name="Unlock the noble magic box (300 hope marks)"},
		[7] = {exp=350,lev=7,period=6,reward={{25902,50},{10450,300}},title_name="Unlock the Supreme Magic Box (350 hope marks)"},
	},
	[8] = {
		[1] = {exp=0,lev=1,period=8,reward={{10403,2},{37001,8}},title_name="Reach level 1 in Adventure Diary"},
		[2] = {exp=70,lev=2,period=8,reward={{10403,3},{37001,8}},title_name="Reach level 2 in Adventure Diary"},
		[3] = {exp=140,lev=3,period=8,reward={{38080,1},{37001,8}},title_name="Reach level 3 in Adventure Diary"},
		[4] = {exp=200,lev=4,period=8,reward={{38081,1},{37001,8}},title_name="Reach level 4 in the Adventure Diary"},
		[5] = {exp=270,lev=5,period=8,reward={{37002,1},{37001,8}},title_name="Reach level 5 in the Adventure Diary"},
		[6] = {exp=330,lev=6,period=8,reward={{3,2000},{37001,8}},title_name="Reach level 6 in the Adventure Diary"},
		[7] = {exp=390,lev=7,period=8,reward={{14001,1},{37001,8}},title_name="Reach level 7 in the Adventure Diary"},
		[8] = {exp=450,lev=8,period=8,reward={{26905,50},{37001,8}},title_name="Reach level 8 in Adventure Diary"},
	},
	[9] = {
		[1] = {exp=50,lev=1,period=9,reward={{10403,2},{10450,300}},title_name="Unlock the ordinary magic box (50 hope marks)"},
		[2] = {exp=100,lev=2,period=9,reward={{10403,3},{10450,300}},title_name="Unlock the lucky magic box (100 hope marks)"},
		[3] = {exp=150,lev=3,period=9,reward={{37002,1},{10450,300}},title_name="Unlock the advanced magic box (150 hope marks)"},
		[4] = {exp=200,lev=4,period=9,reward={{38091,1},{10450,300}},title_name="Unlock the Super Magic Box (200 hope marks)"},
		[5] = {exp=250,lev=5,period=9,reward={{3,2000},{10450,300}},title_name="Unlock the luxury magic box (250 hope marks)"},
		[6] = {exp=300,lev=6,period=9,reward={{14001,1},{10450,300}},title_name="Unlock the noble magic box (300 hope marks)"},
		[7] = {exp=350,lev=7,period=9,reward={{24905,50},{10450,300}},title_name="Unlock the Supreme Magic Box (350 hope marks)"},
	},
	[10] = {
		[1] = {exp=0,lev=1,period=10,reward={{10403,2},{72001,15}},title_name="Reach level 1 in Adventure Diary"},
		[2] = {exp=70,lev=2,period=10,reward={{10403,3},{72001,15}},title_name="Reach level 2 in Adventure Diary"},
		[3] = {exp=140,lev=3,period=10,reward={{38081,1},{72001,15}},title_name="Reach level 3 in Adventure Diary"},
		[4] = {exp=200,lev=4,period=10,reward={{38091,1},{72001,15}},title_name="Reach level 4 in the Adventure Diary"},
		[5] = {exp=270,lev=5,period=10,reward={{37002,1},{72001,15}},title_name="Reach level 5 in the Adventure Diary"},
		[6] = {exp=330,lev=6,period=10,reward={{3,2000},{72001,15}},title_name="Reach level 6 in the Adventure Diary"},
		[7] = {exp=390,lev=7,period=10,reward={{14001,1},{72001,15}},title_name="Reach level 7 in the Adventure Diary"},
		[8] = {exp=450,lev=8,period=10,reward={{25905,50},{72001,15}},title_name="Reach level 8 in Adventure Diary"},
	},
	[11] = {
		[1] = {exp=50,lev=1,period=11,reward={{10403,2},{10450,300}},title_name="Unlock the ordinary magic box (50 hope marks)"},
		[2] = {exp=100,lev=2,period=11,reward={{10403,3},{10450,300}},title_name="Unlock the lucky magic box (100 hope marks)"},
		[3] = {exp=150,lev=3,period=11,reward={{37002,1},{10450,300}},title_name="Unlock the advanced magic box (150 hope marks)"},
		[4] = {exp=200,lev=4,period=11,reward={{38091,1},{10450,300}},title_name="Unlock the Super Magic Box (200 hope marks)"},
		[5] = {exp=250,lev=5,period=11,reward={{3,2000},{10450,300}},title_name="Unlock the luxury magic box (250 hope marks)"},
		[6] = {exp=300,lev=6,period=11,reward={{14001,1},{10450,300}},title_name="Unlock the noble magic box (300 hope marks)"},
		[7] = {exp=350,lev=7,period=11,reward={{26904,50},{10450,300}},title_name="Unlock the Supreme Magic Box (350 hope marks)"},
	},
	[12] = {
		[1] = {exp=0,lev=1,period=12,reward={{10403,2},{72001,15}},title_name="Reach level 1 in Adventure Diary"},
		[2] = {exp=70,lev=2,period=12,reward={{10403,3},{72001,15}},title_name="Reach level 2 in Adventure Diary"},
		[3] = {exp=140,lev=3,period=12,reward={{38081,1},{72001,15}},title_name="Reach level 3 in Adventure Diary"},
		[4] = {exp=200,lev=4,period=12,reward={{38091,1},{72001,15}},title_name="Reach level 4 in the Adventure Diary"},
		[5] = {exp=270,lev=5,period=12,reward={{37002,1},{72001,15}},title_name="Reach level 5 in the Adventure Diary"},
		[6] = {exp=330,lev=6,period=12,reward={{3,2000},{72001,15}},title_name="Reach level 6 in the Adventure Diary"},
		[7] = {exp=390,lev=7,period=12,reward={{14001,1},{72001,15}},title_name="Reach level 7 in the Adventure Diary"},
		[8] = {exp=450,lev=8,period=12,reward={{24907,50},{72001,15}},title_name="Reach level 8 in Adventure Diary"},
	},
	[13] = {
		[1] = {exp=50,lev=1,period=13,reward={{10403,2},{10450,300}},title_name="Unlock the ordinary magic box (50 hope marks)"},
		[2] = {exp=100,lev=2,period=13,reward={{10403,3},{10450,300}},title_name="Unlock the lucky magic box (100 hope marks)"},
		[3] = {exp=150,lev=3,period=13,reward={{37002,1},{10450,300}},title_name="Unlock the advanced magic box (150 hope marks)"},
		[4] = {exp=200,lev=4,period=13,reward={{38091,1},{10450,300}},title_name="Unlock the Super Magic Box (200 hope marks)"},
		[5] = {exp=250,lev=5,period=13,reward={{3,2000},{10450,300}},title_name="Unlock the luxurious magic box (250 hope marks)"},
		[6] = {exp=300,lev=6,period=13,reward={{14001,1},{10450,300}},title_name="Unlock the noble magic box (300 hope marks)"},
		[7] = {exp=350,lev=7,period=13,reward={{24908,50},{10450,300}},title_name="Unlock the Supreme Magic Box (350 hope marks)"},
	},
}
