-- this file is generated by program!
-- don't change it manaully.
-- source file: dial_data.xls

Config = Config or {} 
Config.DialData = Config.DialData or {}
Config.DialData.data_get_limit_open_key_depth = 1
Config.DialData.data_get_limit_open_length = 4
Config.DialData.data_get_limit_open_lan = "en"
Config.DialData.data_get_limit_open = {
	[1] = {add_item={{18,10}},add_lucky=10,count=1,expend_gold={},expend_item={{37001,1}},limit_open={{"lev",10}},rand_id=2,type=1,type2=1},
	[2] = {add_item={{18,150}},add_lucky=150,count=15,expend_gold={},expend_item={{37001,12}},limit_open={{"lev",10},{"vip_lev",2}},rand_id=2,type=1,type2=2},
	[3] = {add_item={{18,10}},add_lucky=10,count=1,expend_gold={},expend_item={{37002,1}},limit_open={{"lev",30}},rand_id=4,type=2,type2=1},
	[4] = {add_item={{18,100}},add_lucky=100,count=10,expend_gold={},expend_item={{37002,10}},limit_open={{"lev",30}},rand_id=4,type=2,type2=2},
}
