-- this file is generated by program!
-- don't change it manaully.
-- source file: endless_data.xls

Config = Config or {} 
Config.EndlessData = Config.EndlessData or {}
Config.EndlessData.data_new_type_key_depth = 1
Config.EndlessData.data_new_type_length = 4
Config.EndlessData.data_new_type_lan = "en"
Config.EndlessData.data_new_type = {
	[1] = {id=1,type=1,bids={},day=3,icon="1",describe="Water, the world\'s most soft, can ride the world\'s most solid. \nAdventurous, come and accept the trial of the water element!",title="Trial of Water System"},
	[2] = {id=2,type=2,bids={},day=3,icon="2",describe="The fire master kills, heralds destruction, and can burn everything into nothingness. \nAdventurous, come and accept the trial of the fire element!",title="Fire Trial"},
	[3] = {id=3,type=3,bids={},day=3,icon="3",describe="Grass symbolizes vitality, and smart grass brings vitality to the adventure continent. \nAdventurous, come and accept the test of the element of grass!",title="Trial of Grass"},
	[4] = {id=4,type=4,bids={},day=3,icon="4",describe="Day and night change, day is light, night is dark, light and dark are intertwined, and there is no end to reincarnation. \nAdventurous, come and accept the trial of reincarnation!",title="Trial of Light and Darkness"},
}
