-- this file is generated by program!
-- don't change it manaully.
-- source file: exchange_data.xls

Config = Config or {} 
Config.ExchangeData = Config.ExchangeData or {}
Config.ExchangeData.data_shop_exchage_pet_key_depth = 1
Config.ExchangeData.data_shop_exchage_pet_length = 18
Config.ExchangeData.data_shop_exchage_pet_lan = "en"
Config.ExchangeData.data_shop_exchage_pet = {
	[1] = {id=42101,item_bid=100101,item_desc="Suitable for short trips",item_name="Compressed biscuits",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=200,limit_week=0,order=1,pay_type="home_coin",price=200,type=42},
	[2] = {id=42102,item_bid=100102,item_desc="Suitable for short trips",item_name="Rice ball",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=600,limit_week=0,order=2,pay_type="home_coin",price=280,type=42},
	[3] = {id=42103,item_bid=100103,item_desc="Suitable for mid-range travel",item_name="cake",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=1000,limit_week=0,order=3,pay_type="home_coin",price=360,type=42},
	[4] = {id=42104,item_bid=100104,item_desc="Suitable for mid-range travel",item_name="French bread",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=1400,limit_week=0,order=4,pay_type="home_coin",price=480,type=42},
	[5] = {id=42105,item_bid=100105,item_desc="Suitable for long-distance travel",item_name="sandwich",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=1800,limit_week=0,order=5,pay_type="home_coin",price=600,type=42},
	[6] = {id=42106,item_bid=100106,item_desc="Suitable for long-distance travel",item_name="Hamburger",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=2300,limit_week=0,order=6,pay_type="home_coin",price=680,type=42},
	[7] = {id=42107,item_bid=100107,item_desc="Suitable for travel in ultra-distance areas",item_name="Pizza",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=2900,limit_week=0,order=7,pay_type="home_coin",price=760,type=42},
	[8] = {id=42108,item_bid=100108,item_desc="Suitable for travel in ultra-distance areas",item_name="Luxury sushi set",item_num=1,item_type=1,limit_day=0,limit_month=0,limit_soft=3500,limit_week=0,order=8,pay_type="home_coin",price=880,type=42},
	[9] = {id=42201,item_bid=100201,item_desc="Pokémon fragment probability +5%",item_name="Small gift box",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=9,pay_type="home_coin",price=80,type=42},
	[10] = {id=42202,item_bid=100202,item_desc="Gem Essence Probability +5%",item_name="Glass bottle",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=10,pay_type="home_coin",price=80,type=42},
	[11] = {id=42203,item_bid=100203,item_desc="Diary probability +2%",item_name="Brush",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=11,pay_type="home_coin",price=80,type=42},
	[12] = {id=42204,item_bid=100204,item_desc="Postcard probability +2%",item_name="Fool machine",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=12,pay_type="home_coin",price=80,type=42},
	[13] = {id=42205,item_bid=100205,item_desc="Probability of gold coins and Gems +5%",item_name="Handheld detector",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=13,pay_type="home_coin",price=80,type=42},
	[14] = {id=42241,item_bid=100241,item_desc="Pokémon fragment probability +10%",item_name="Treasure chest",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=14,pay_type="home_coin",price=160,type=42},
	[15] = {id=42242,item_bid=100242,item_desc="Gem Essence Probability +10%",item_name="Crystal bottle",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=15,pay_type="home_coin",price=160,type=42},
	[16] = {id=42243,item_bid=100243,item_desc="Diary probability +5%",item_name="Valuable fountain pen",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=16,pay_type="home_coin",price=160,type=42},
	[17] = {id=42244,item_bid=100244,item_desc="Postcard probability +5%",item_name="Smart camera",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=17,pay_type="home_coin",price=160,type=42},
	[18] = {id=42245,item_bid=100245,item_desc="Gold coin Gems probability +10%",item_name="Precision detector",item_num=1,item_type=2,limit_day=2,limit_month=0,limit_soft=0,limit_week=0,order=18,pay_type="home_coin",price=160,type=42},
}
