-- this file is generated by program!
-- don't change it manaully.
-- source file: exchange_data.xls

Config = Config or {} 
Config.ExchangeData = Config.ExchangeData or {}
Config.ExchangeData.data_shop_exchage_herosoul_key_depth = 1
Config.ExchangeData.data_shop_exchage_herosoul_length = 19
Config.ExchangeData.data_shop_exchage_herosoul_lan = "en"
Config.ExchangeData.data_shop_exchage_herosoul = {
	[1] = {bind=1,discount=0,icon=0,id=53001,is_partner=0,item_bid=24901,item_name="Articuno Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=1,pay_type=10005,price=30,role_lev={},type=53},
	[2] = {bind=1,discount=0,icon=0,id=53002,is_partner=0,item_bid=25903,item_name="Groudon Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=2,pay_type=10005,price=30,role_lev={},type=53},
	[3] = {bind=1,discount=0,icon=0,id=53003,is_partner=0,item_bid=26901,item_name="Shaymin Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=3,pay_type=10005,price=30,role_lev={},type=53},
	[4] = {bind=1,discount=0,icon=0,id=53004,is_partner=0,item_bid=24902,item_name="Froakie Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=4,pay_type=10005,price=20,role_lev={},type=53},
	[5] = {bind=1,discount=0,icon=0,id=53005,is_partner=0,item_bid=24905,item_name="Sandile Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=5,pay_type=10005,price=20,role_lev={},type=53},
	[6] = {bind=1,discount=0,icon=0,id=53006,is_partner=0,item_bid=24906,item_name="Dialga Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=6,pay_type=10005,price=20,role_lev={},type=53},
	[7] = {bind=1,discount=0,icon=0,id=53007,is_partner=0,item_bid=24907,item_name="Mudkip Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=7,pay_type=10005,price=20,role_lev={},type=53},
	[8] = {bind=1,discount=0,icon=0,id=53008,is_partner=0,item_bid=24908,item_name="Totodile Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=8,pay_type=10005,price=20,role_lev={},type=53},
	[9] = {bind=1,discount=0,icon=0,id=53009,is_partner=0,item_bid=25900,item_name="Charmander Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=9,pay_type=10005,price=20,role_lev={},type=53},
	[10] = {bind=1,discount=0,icon=0,id=53010,is_partner=0,item_bid=25901,item_name="Cyndaquil Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=10,pay_type=10005,price=20,role_lev={},type=53},
	[11] = {bind=1,discount=0,icon=0,id=53011,is_partner=0,item_bid=25902,item_name="Tepig Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=11,pay_type=10005,price=20,role_lev={},type=53},
	[12] = {bind=1,discount=0,icon=0,id=53012,is_partner=0,item_bid=25904,item_name="Torchic Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=12,pay_type=10005,price=20,role_lev={},type=53},
	[13] = {bind=1,discount=0,icon=0,id=53013,is_partner=0,item_bid=25905,item_name="Magby Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=13,pay_type=10005,price=20,role_lev={},type=53},
	[14] = {bind=1,discount=0,icon=0,id=53014,is_partner=0,item_bid=26900,item_name="Bulbasaur Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=14,pay_type=10005,price=20,role_lev={},type=53},
	[15] = {bind=1,discount=0,icon=0,id=53015,is_partner=0,item_bid=26902,item_name="Chikorita Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=15,pay_type=10005,price=20,role_lev={},type=53},
	[16] = {bind=1,discount=0,icon=0,id=53016,is_partner=0,item_bid=26903,item_name="Snivy Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=16,pay_type=10005,price=20,role_lev={},type=53},
	[17] = {bind=1,discount=0,icon=0,id=53017,is_partner=0,item_bid=26904,item_name="Rowlet Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=17,pay_type=10005,price=20,role_lev={},type=53},
	[18] = {bind=1,discount=0,icon=0,id=53018,is_partner=0,item_bid=26905,item_name="Treecko Shards",item_num=50,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=1,limit_rank=0,limit_week=0,order=18,pay_type=10005,price=20,role_lev={},type=53},
	[19] = {bind=1,discount=0,icon=0,id=53019,is_partner=0,item_bid=10403,item_name="Premium Poke Ball",item_num=10,label=0,lev={1,999},limit_count=0,limit_day=0,limit_month=0,limit_rank=0,limit_week=0,order=19,pay_type=10005,price=15,role_lev={},type=53},
}
