-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_dun_data.xls

Config = Config or {} 
Config.GuildDunData = Config.GuildDunData or {}
Config.GuildDunData.data_buff_data_key_depth = 1
Config.GuildDunData.data_buff_data_length = 10
Config.GuildDunData.data_buff_data_lan = "en"
Config.GuildDunData.data_buff_data = {
	[1] = {add_attr={{"atk_per",20}},buff_lev=1,desc="All Guild members\' attack power +2%"},
	[2] = {add_attr={{"atk_per",40}},buff_lev=2,desc="All Guild members\' attack power +4%"},
	[3] = {add_attr={{"atk_per",60}},buff_lev=3,desc="All Guild members\' attack power +6%"},
	[4] = {add_attr={{"atk_per",80}},buff_lev=4,desc="All Guild members\' attack power +8%"},
	[5] = {add_attr={{"atk_per",100}},buff_lev=5,desc="All Guild members\' attack power +10%"},
	[6] = {add_attr={{"atk_per",120}},buff_lev=6,desc="All Guild members\' attack power +12%"},
	[7] = {add_attr={{"atk_per",140}},buff_lev=7,desc="All Guild members\' attack power +14%"},
	[8] = {add_attr={{"atk_per",160}},buff_lev=8,desc="Attack power of all Guild members +16%"},
	[9] = {add_attr={{"atk_per",180}},buff_lev=9,desc="All Guild members\' attack power +18%"},
	[10] = {add_attr={{"atk_per",200}},buff_lev=10,desc="All Guild members\' attack power +20%"},
}
