-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_data.xls

Config = Config or {} 
Config.GuildData = Config.GuildData or {}
Config.GuildData.data_guild_red_bag_key_depth = 1
Config.GuildData.data_guild_red_bag_length = 3
Config.GuildData.data_guild_red_bag_lan = "en"
Config.GuildData.data_guild_red_bag = {
	[1] = {assets="coin",charge_id=501,id=1,limit=30,loss_assets={},loss_item={{10800,1}},num=10,price=12,res_name="redbag_4",reward={{3,120},{10,550}},type=2,val=600000,desc="nothing",msg="nothing",name="nothing"},
	[2] = {assets="gold",charge_id=502,id=2,limit=20,loss_assets={},loss_item={{10801,1}},num=10,price=50,res_name="redbag_10",reward={{3,500},{10,650},{10403,4}},type=2,val=500,desc="nothing",msg="nothing",name="nothing"},
	[3] = {assets="gold",charge_id=503,id=3,limit=10,loss_assets={},loss_item={},num=15,price=648,res_name="redbag_5",reward={{3,6480},{10,10000},{14001,12}},type=2,val=6480,desc="nothing",msg="nothing",name="nothing"},
}
