-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_quest_data.xls

Config = Config or {} 
Config.GuildQuestData = Config.GuildQuestData or {}
Config.GuildQuestData.data_task_data_key_depth = 1
Config.GuildQuestData.data_task_data_length = 8
Config.GuildQuestData.data_task_data_lan = "en"
Config.GuildQuestData.data_task_data = {
	[1] = {exp=10,id=101,progress={{target=0,param={},target_val=3,cli_label="evt_guild_skill"}},show_jump="evt_league_skill",type=1,desc="Upgrade Guild\nskills",name="Upgrade Guild skills"},
	[2] = {exp=5,id=102,progress={{target=0,param={},target_val=3,cli_label="evt_guild_dun_fight"}},show_jump="evt_league_dungeon",type=1,desc="Challenge Guild\ncopy",name="Challenge Guild copy"},
	[3] = {exp=5,id=107,progress={{target=0,param={5},target_val=2,cli_label="evt_exchange"}},show_jump="evt_league_shop",type=1,desc="Union store\nconsumption",name="Union store consumption"},
	[4] = {exp=5,id=108,progress={{target=1,param={},target_val=1,cli_label="evt_guild_donate"}},show_jump="evt_league_donate",type=1,desc="Gold coin\ndonation",name="Gold coin donation"},
	[5] = {exp=10,id=109,progress={{target=2,param={},target_val=1,cli_label="evt_guild_donate"}},show_jump="evt_league_donate",type=1,desc="Gems donation",name="Gems donation"},
	[6] = {exp=20,id=110,progress={{target=3,param={},target_val=1,cli_label="evt_guild_donate"}},show_jump="evt_league_donate",type=1,desc="Supreme Gems\nDonation",name="Supreme Gems Donation"},
	[8] = {exp=10,id=112,progress={{target=0,param={},target_val=1,cli_label="evt_guild_war"}},show_jump="evt_league_war",type=1,desc="Participate in 1\nGuild war",name="Participate in 1 Guild war"},
	[9] = {exp=50,id=201,progress={{target=0,param={},target_val=1,cli_label="evt_guild_dun_buff"}},show_jump="evt_league_dungeon",type=2,desc="Guild dungeon\nbonus",name="Guild dungeon bonus"},
}
