-- this file is generated by program!
-- don't change it manaully.
-- source file: holiday_nian_data.xls

Config = Config or {} 
Config.HolidayNianData = Config.HolidayNianData or {}
Config.HolidayNianData.data_rank_reward_key_depth = 1
Config.HolidayNianData.data_rank_reward_length = 8
Config.HolidayNianData.data_rank_reward_lan = "en"
Config.HolidayNianData.data_rank_reward = {
	[1] = {rank_high=1,rank_low=1,reward={{10408,10},{60003,1}}},
	[2] = {rank_high=2,rank_low=2,reward={{10408,8},{60003,1}}},
	[3] = {rank_high=3,rank_low=3,reward={{10408,6},{60003,1}}},
	[4] = {rank_high=4,rank_low=10,reward={{10408,5},{60003,1}}},
	[5] = {rank_high=11,rank_low=20,reward={{10408,4},{60003,1}}},
	[6] = {rank_high=21,rank_low=50,reward={{10408,3}}},
	[7] = {rank_high=51,rank_low=100,reward={{10408,2}}},
	[8] = {rank_high=101,rank_low=200,reward={{10408,1}}},
}
