-- this file is generated by program!
-- don't change it manaully.
-- source file: holiday_valentine_boss_data.xls

Config = Config or {} 
Config.HolidayValentineBossData = Config.HolidayValentineBossData or {}
Config.HolidayValentineBossData.data_constant_key_depth = 1
Config.HolidayValentineBossData.data_constant_length = 2
Config.HolidayValentineBossData.data_constant_lan = "en"
Config.HolidayValentineBossData.data_constant = {
	["holiday_valentine_boss_buy_loss1"] = {val={{3,200}},desc="Purchase the assets needed for the first time"},
	["holiday_valentine_boss_buy_loss2"] = {val={{3,200}},desc="Purchase the assets required for the second time"},
}
