-- this file is generated by program!
-- don't change it manaully.
-- source file: holiday_nian_data.xls

Config = Config or {} 
Config.HolidayNianData = Config.HolidayNianData or {}
Config.HolidayNianData.data_redbag_progress_key_depth = 1
Config.HolidayNianData.data_redbag_progress_length = 3
Config.HolidayNianData.data_redbag_progress_lan = "en"
Config.HolidayNianData.data_redbag_progress = {
	[1] = 450,
	[2] = 1350,
	[3] = 1800,
}
