-- this file is generated by program!
-- don't change it manaully.
-- source file: home_data.xls

Config = Config or {} 
Config.HomeData = Config.HomeData or {}
Config.HomeData.data_figure_key_depth = 1
Config.HomeData.data_figure_length = 7
Config.HomeData.data_figure_lan = "en"
Config.HomeData.data_figure = {
	[1] = {ico_id="figureicon_3",id=1,is_first=1,look_id="gameplay/crossmine/q_xiaoxia",look_run="run_loop",look_standby="standby_loop",loss={{3,300}},open_soft=1000,name="Ash Ketchum",tips=""},
	[2] = {ico_id="figureicon_1",id=2,is_first=1,look_id="gameplay/crossmine/q_xiaozhi",look_run="run_loop",look_standby="standby_loop",loss={{3,300}},open_soft=1000,name="Misty",tips=""},
	[3] = {ico_id="figureicon_2",id=3,is_first=0,look_id="gameplay/crossmine/q_bailu",look_run="run_loop",look_standby="standby_loop",loss={{3,500}},open_soft=1500,name="Bianca",tips=""},
	[4] = {ico_id="figureicon_4",id=4,is_first=0,look_id="gameplay/crossmine/q_xiu",look_run="run_loop",look_standby="standby_loop",loss={{3,500}},open_soft=2000,name="Hugh",tips=""},
	[5] = {ico_id="figureicon_5",id=5,is_first=0,look_id="gameplay/crossmine/q_douzi",look_run="run_loop",look_standby="standby_loop",loss={{3,500}},open_soft=2500,name="Hilda",tips=""},
	[6] = {ico_id="figureicon_6",id=6,is_first=0,look_id="gameplay/crossmine/q_sansejin",look_run="run_loop",look_standby="standby_loop",loss={{3,500}},open_soft=3000,name="Alexa",tips=""},
	[7] = {ico_id="figureicon_7",id=7,is_first=0,look_id="gameplay/crossmine/q_dujuan",look_run="run_loop",look_standby="standby_loop",loss={},open_soft=0,name="Roxanne",tips="New Year event unlocked"},
}
