-- this file is generated by program!
-- don't change it manaully.
-- source file: misc_data.xls

Config = Config or {} 
Config.MiscData = Config.MiscData or {}
Config.MiscData.data_cycle_gift_info_key_depth = 2
Config.MiscData.data_cycle_gift_info_length = 2
Config.MiscData.data_cycle_gift_info_lan = "en"
Config.MiscData.data_cycle_gift_info = {
	[1] = {
		[401] = {charge_id=401,gift_name="Weekly purchase limit",gift_type=1,limit_count=3,sort_id=1,val=4.99},
		[402] = {charge_id=402,gift_name="Weekly purchase limit",gift_type=1,limit_count=3,sort_id=2,val=9.99},
		[403] = {charge_id=403,gift_name="Weekly purchase limit",gift_type=1,limit_count=3,sort_id=3,val=19.99},
		[404] = {charge_id=404,gift_name="Weekly purchase limit",gift_type=1,limit_count=3,sort_id=4,val=49.99},
		[405] = {charge_id=405,gift_name="Weekly purchase limit",gift_type=1,limit_count=3,sort_id=5,val=69.99},
		[406] = {charge_id=406,gift_name="Weekly purchase limit",gift_type=1,limit_count=1,sort_id=6,val=99.99},
		[407] = {charge_id=407,gift_name="Weekly purchase limit",gift_type=1,limit_count=1,sort_id=7,val=99.99},
	},
	[2] = {
		[411] = {charge_id=411,gift_name="Monthly limit",gift_type=2,limit_count=1,sort_id=1,val=4.99},
		[412] = {charge_id=412,gift_name="Monthly limit",gift_type=2,limit_count=1,sort_id=2,val=9.99},
		[413] = {charge_id=413,gift_name="Monthly limit",gift_type=2,limit_count=2,sort_id=3,val=19.99},
		[414] = {charge_id=414,gift_name="Monthly limit",gift_type=2,limit_count=3,sort_id=4,val=49.99},
		[415] = {charge_id=415,gift_name="Monthly limit",gift_type=2,limit_count=3,sort_id=5,val=69.99},
		[416] = {charge_id=416,gift_name="Monthly limit",gift_type=2,limit_count=3,sort_id=6,val=99.99},
		[417] = {charge_id=417,gift_name="Monthly limit",gift_type=2,limit_count=3,sort_id=7,val=99.99},
	},
}
