-- this file is generated by program!
-- don't change it manaully.
-- source file: partner_holy_eqm_data.xls

Config = Config or {} 
Config.PartnerHolyEqmData = Config.PartnerHolyEqmData or {}
Config.PartnerHolyEqmData.data_suit_info_key_depth = 2
Config.PartnerHolyEqmData.data_suit_info_length = 140
Config.PartnerHolyEqmData.data_suit_info_lan = "en"
Config.PartnerHolyEqmData.data_suit_info = {
	[101] = {
		[1] = {all_skill_desc={{0},{0}},id=101,name="Courage 1-star set",num=4,skill_id={{"def_per",30}}},
		[2] = {all_skill_desc={{0}},id=101,name="Courage 1-star set",num=2,skill_id={{"def_per",30}}},
	},
	[102] = {
		[1] = {all_skill_desc={{0},{0}},id=102,name="Courage 2-star set",num=4,skill_id={{"def_per",40}}},
		[2] = {all_skill_desc={{0}},id=102,name="Courage 2-star set",num=2,skill_id={{"def_per",30}}},
	},
	[103] = {
		[1] = {all_skill_desc={{0},{0}},id=103,name="Courage 3-star set",num=4,skill_id={{"def_per",50}}},
		[2] = {all_skill_desc={{0}},id=103,name="Courage 3-star set",num=2,skill_id={{"def_per",30}}},
	},
	[104] = {
		[1] = {all_skill_desc={{0},{0}},id=104,name="Courage 4-star set",num=4,skill_id={{"def_per",60}}},
		[2] = {all_skill_desc={{0}},id=104,name="Courage 4-star set",num=2,skill_id={{"def_per",30}}},
	},
	[105] = {
		[1] = {all_skill_desc={{0},{0}},id=105,name="Courage 5-star set",num=4,skill_id={{"def_per",70}}},
		[2] = {all_skill_desc={{0}},id=105,name="Courage 5-star set",num=2,skill_id={{"def_per",30}}},
	},
	[106] = {
		[1] = {all_skill_desc={{0},{0}},id=106,name="Courage 6-star set",num=4,skill_id={{"def_per",80}}},
		[2] = {all_skill_desc={{0}},id=106,name="Courage 6-star set",num=2,skill_id={{"def_per",30}}},
	},
	[107] = {
		[1] = {all_skill_desc={{0},{0}},id=107,name="Courage 7-star set",num=4,skill_id={{"def_per",90}}},
		[2] = {all_skill_desc={{0}},id=107,name="Courage 7-star set",num=2,skill_id={{"def_per",30}}},
	},
	[108] = {
		[1] = {all_skill_desc={{0},{0}},id=108,name="Courage 8-star set",num=4,skill_id={{"def_per",100}}},
		[2] = {all_skill_desc={{0}},id=108,name="Courage 8-star set",num=2,skill_id={{"def_per",30}}},
	},
	[109] = {
		[1] = {all_skill_desc={{0},{0}},id=109,name="Courage 9-star set",num=4,skill_id={{"def_per",110}}},
		[2] = {all_skill_desc={{0}},id=109,name="Courage 9-star set",num=2,skill_id={{"def_per",30}}},
	},
	[110] = {
		[1] = {all_skill_desc={{0},{0}},id=110,name="Courage 10-star set",num=4,skill_id={{"def_per",120}}},
		[2] = {all_skill_desc={{0}},id=110,name="Courage 10-star set",num=2,skill_id={{"def_per",30}}},
	},
	[201] = {
		[1] = {all_skill_desc={{0},{0}},id=201,name="Furious 1-star set",num=4,skill_id={{"crit_rate",30}}},
		[2] = {all_skill_desc={{0}},id=201,name="Furious 1-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[202] = {
		[1] = {all_skill_desc={{0},{0}},id=202,name="Furious 2-star set",num=4,skill_id={{"crit_rate",40}}},
		[2] = {all_skill_desc={{0}},id=202,name="Furious 2-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[203] = {
		[1] = {all_skill_desc={{0},{0}},id=203,name="Furious 3-star set",num=4,skill_id={{"crit_rate",50}}},
		[2] = {all_skill_desc={{0}},id=203,name="Furious 3-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[204] = {
		[1] = {all_skill_desc={{0},{0}},id=204,name="Furious 4-star set",num=4,skill_id={{"crit_rate",60}}},
		[2] = {all_skill_desc={{0}},id=204,name="Furious 4-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[205] = {
		[1] = {all_skill_desc={{0},{0}},id=205,name="Furious 5-star set",num=4,skill_id={{"crit_rate",70}}},
		[2] = {all_skill_desc={{0}},id=205,name="Furious 5-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[206] = {
		[1] = {all_skill_desc={{0},{0}},id=206,name="Furious 6-star set",num=4,skill_id={{"crit_rate",80}}},
		[2] = {all_skill_desc={{0}},id=206,name="Furious 6-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[207] = {
		[1] = {all_skill_desc={{0},{0}},id=207,name="Furious 7-star set",num=4,skill_id={{"crit_rate",90}}},
		[2] = {all_skill_desc={{0}},id=207,name="Furious 7-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[208] = {
		[1] = {all_skill_desc={{0},{0}},id=208,name="Furious 8-star set",num=4,skill_id={{"crit_rate",100}}},
		[2] = {all_skill_desc={{0}},id=208,name="Furious 8-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[209] = {
		[1] = {all_skill_desc={{0},{0}},id=209,name="Furious 9-star set",num=4,skill_id={{"crit_rate",110}}},
		[2] = {all_skill_desc={{0}},id=209,name="Furious 9-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[210] = {
		[1] = {all_skill_desc={{0},{0}},id=210,name="Furious 10-star set",num=4,skill_id={{"crit_rate",120}}},
		[2] = {all_skill_desc={{0}},id=210,name="Furious 10-star set",num=2,skill_id={{"crit_rate",30}}},
	},
	[301] = {
		[1] = {all_skill_desc={{0},{0}},id=301,name="Fighting spirit 1-star set",num=4,skill_id={{"atk_per",30}}},
		[2] = {all_skill_desc={{0}},id=301,name="Fighting spirit 1-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[302] = {
		[1] = {all_skill_desc={{0},{0}},id=302,name="Fighting spirit 2-star set",num=4,skill_id={{"atk_per",40}}},
		[2] = {all_skill_desc={{0}},id=302,name="Fighting spirit 2-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[303] = {
		[1] = {all_skill_desc={{0},{0}},id=303,name="Fighting spirit 3-star set",num=4,skill_id={{"atk_per",50}}},
		[2] = {all_skill_desc={{0}},id=303,name="Fighting spirit 3-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[304] = {
		[1] = {all_skill_desc={{0},{0}},id=304,name="Fighting spirit 4-star set",num=4,skill_id={{"atk_per",60}}},
		[2] = {all_skill_desc={{0}},id=304,name="Fighting spirit 4-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[305] = {
		[1] = {all_skill_desc={{0},{0}},id=305,name="Fighting spirit 5-star set",num=4,skill_id={{"atk_per",70}}},
		[2] = {all_skill_desc={{0}},id=305,name="Fighting spirit 5-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[306] = {
		[1] = {all_skill_desc={{0},{0}},id=306,name="Fighting spirit 6-star set",num=4,skill_id={{"atk_per",80}}},
		[2] = {all_skill_desc={{0}},id=306,name="Fighting spirit 6-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[307] = {
		[1] = {all_skill_desc={{0},{0}},id=307,name="Fighting spirit 7-star set",num=4,skill_id={{"atk_per",90}}},
		[2] = {all_skill_desc={{0}},id=307,name="Fighting spirit 7-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[308] = {
		[1] = {all_skill_desc={{0},{0}},id=308,name="Fighting spirit 8-star set",num=4,skill_id={{"atk_per",100}}},
		[2] = {all_skill_desc={{0}},id=308,name="Fighting spirit 8-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[309] = {
		[1] = {all_skill_desc={{0},{0}},id=309,name="Fighting spirit 9-star set",num=4,skill_id={{"atk_per",110}}},
		[2] = {all_skill_desc={{0}},id=309,name="Fighting spirit 9-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[310] = {
		[1] = {all_skill_desc={{0},{0}},id=310,name="Fighting spirit 10-star set",num=4,skill_id={{"atk_per",120}}},
		[2] = {all_skill_desc={{0}},id=310,name="Fighting spirit 10-star set",num=2,skill_id={{"atk_per",30}}},
	},
	[401] = {
		[1] = {all_skill_desc={{0},{0}},id=401,name="Gaze 1-star set",num=4,skill_id={{"cure",50}}},
		[2] = {all_skill_desc={{0}},id=401,name="Gaze 1-star set",num=2,skill_id={{"cure",50}}},
	},
	[402] = {
		[1] = {all_skill_desc={{0},{0}},id=402,name="Gaze 2-star set",num=4,skill_id={{"cure",60}}},
		[2] = {all_skill_desc={{0}},id=402,name="Gaze 2-star set",num=2,skill_id={{"cure",50}}},
	},
	[403] = {
		[1] = {all_skill_desc={{0},{0}},id=403,name="Gaze 3-star set",num=4,skill_id={{"cure",70}}},
		[2] = {all_skill_desc={{0}},id=403,name="Gaze 3-star set",num=2,skill_id={{"cure",50}}},
	},
	[404] = {
		[1] = {all_skill_desc={{0},{0}},id=404,name="Gaze 4-star set",num=4,skill_id={{"cure",80}}},
		[2] = {all_skill_desc={{0}},id=404,name="Gaze 4-star set",num=2,skill_id={{"cure",50}}},
	},
	[405] = {
		[1] = {all_skill_desc={{0},{0}},id=405,name="Gaze 5-star set",num=4,skill_id={{"cure",90}}},
		[2] = {all_skill_desc={{0}},id=405,name="Gaze 5-star set",num=2,skill_id={{"cure",50}}},
	},
	[406] = {
		[1] = {all_skill_desc={{0},{0}},id=406,name="Gaze 6-star set",num=4,skill_id={{"cure",100}}},
		[2] = {all_skill_desc={{0}},id=406,name="Gaze 6-star set",num=2,skill_id={{"cure",50}}},
	},
	[407] = {
		[1] = {all_skill_desc={{0},{0}},id=407,name="Gaze 7-star set",num=4,skill_id={{"cure",110}}},
		[2] = {all_skill_desc={{0}},id=407,name="Gaze 7-star set",num=2,skill_id={{"cure",50}}},
	},
	[408] = {
		[1] = {all_skill_desc={{0},{0}},id=408,name="Gaze 8-star set",num=4,skill_id={{"cure",120}}},
		[2] = {all_skill_desc={{0}},id=408,name="Gaze 8-star set",num=2,skill_id={{"cure",50}}},
	},
	[409] = {
		[1] = {all_skill_desc={{0},{0}},id=409,name="Gaze 9-star set",num=4,skill_id={{"cure",130}}},
		[2] = {all_skill_desc={{0}},id=409,name="Gaze 9-star set",num=2,skill_id={{"cure",50}}},
	},
	[410] = {
		[1] = {all_skill_desc={{0},{0}},id=410,name="Gaze 10-star set",num=4,skill_id={{"cure",140}}},
		[2] = {all_skill_desc={{0}},id=410,name="Gaze 10-star set",num=2,skill_id={{"cure",50}}},
	},
	[501] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+7%"}},id=501,name="Puncture 1-star set",num=4,skill_id={763001}},
		[2] = {all_skill_desc={{0}},id=501,name="Puncture 1-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[502] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+9%"}},id=502,name="Puncture 2-star set",num=4,skill_id={763002}},
		[2] = {all_skill_desc={{0}},id=502,name="Puncture 2-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[503] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+11%"}},id=503,name="Puncture 3-star set",num=4,skill_id={763003}},
		[2] = {all_skill_desc={{0}},id=503,name="Puncture 3-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[504] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+13%"}},id=504,name="Puncture 4-star set",num=4,skill_id={763004}},
		[2] = {all_skill_desc={{0}},id=504,name="Puncture 4-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[505] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+15%"}},id=505,name="Puncture 5-star set",num=4,skill_id={763005}},
		[2] = {all_skill_desc={{0}},id=505,name="Puncture 5-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[506] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+17%"}},id=506,name="Puncture 6-star set",num=4,skill_id={763006}},
		[2] = {all_skill_desc={{0}},id=506,name="Puncture 6-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[507] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+19%"}},id=507,name="Puncture 7-star set",num=4,skill_id={763007}},
		[2] = {all_skill_desc={{0}},id=507,name="Puncture 7-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[508] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+21%"}},id=508,name="Puncture 8-star set",num=4,skill_id={763008}},
		[2] = {all_skill_desc={{0}},id=508,name="Puncture 8-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[509] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+23%"}},id=509,name="Puncture 9-star set",num=4,skill_id={763009}},
		[2] = {all_skill_desc={{0}},id=509,name="Puncture 9-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[510] = {
		[1] = {all_skill_desc={{0},{1,"DMG to DEF+25%"}},id=510,name="Puncture 10-star set",num=4,skill_id={763010}},
		[2] = {all_skill_desc={{0}},id=510,name="Puncture 10-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[601] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+7%"}},id=601,name="Insect 1-star set",num=4,skill_id={761001}},
		[2] = {all_skill_desc={{0}},id=601,name="Insect 1-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[602] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+9%"}},id=602,name="Insect 2-star set",num=4,skill_id={761002}},
		[2] = {all_skill_desc={{0}},id=602,name="Insect 2-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[603] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+11%"}},id=603,name="Insect 3-star set",num=4,skill_id={761003}},
		[2] = {all_skill_desc={{0}},id=603,name="Insect 3-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[604] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+13%"}},id=604,name="Insect 4-star set",num=4,skill_id={761004}},
		[2] = {all_skill_desc={{0}},id=604,name="Insect 4-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[605] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+15%"}},id=605,name="Insect 5-star set",num=4,skill_id={761005}},
		[2] = {all_skill_desc={{0}},id=605,name="Insect 5-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[606] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+17%"}},id=606,name="Insect 6-star set",num=4,skill_id={761006}},
		[2] = {all_skill_desc={{0}},id=606,name="Insect 6-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[607] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+19%"}},id=607,name="Insect 7-star set",num=4,skill_id={761007}},
		[2] = {all_skill_desc={{0}},id=607,name="Insect 7-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[608] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+21%"}},id=608,name="Insect 8-star set",num=4,skill_id={761008}},
		[2] = {all_skill_desc={{0}},id=608,name="Insect 8-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[609] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+23%"}},id=609,name="Insect 9-star set",num=4,skill_id={761009}},
		[2] = {all_skill_desc={{0}},id=609,name="Insect 9-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[610] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SP.ATK+25%"}},id=610,name="Insect 10-star set",num=4,skill_id={761010}},
		[2] = {all_skill_desc={{0}},id=610,name="Insect 10-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[701] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+7%"}},id=701,name="Lightning 1-star set",num=4,skill_id={762001}},
		[2] = {all_skill_desc={{0}},id=701,name="Lightning 1-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[702] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+9%"}},id=702,name="Lightning 2-star set",num=4,skill_id={762002}},
		[2] = {all_skill_desc={{0}},id=702,name="Lightning 2-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[703] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+11%"}},id=703,name="Lightning 3-star set",num=4,skill_id={762003}},
		[2] = {all_skill_desc={{0}},id=703,name="Lightning 3-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[704] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+13%"}},id=704,name="Lightning 4-star set",num=4,skill_id={762004}},
		[2] = {all_skill_desc={{0}},id=704,name="Lightning 4-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[705] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+15%"}},id=705,name="Lightning 5-star set",num=4,skill_id={762005}},
		[2] = {all_skill_desc={{0}},id=705,name="Lightning 5-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[706] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+17%"}},id=706,name="Lightning 6-star set",num=4,skill_id={762006}},
		[2] = {all_skill_desc={{0}},id=706,name="Lightning 6-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[707] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+19%"}},id=707,name="Lightning 7-star set",num=4,skill_id={762007}},
		[2] = {all_skill_desc={{0}},id=707,name="Lightning 7-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[708] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+21%"}},id=708,name="Lightning 8-star set",num=4,skill_id={762008}},
		[2] = {all_skill_desc={{0}},id=708,name="Lightning 8-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[709] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+23%"}},id=709,name="Lightning 9-star set",num=4,skill_id={762009}},
		[2] = {all_skill_desc={{0}},id=709,name="Lightning 9-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[710] = {
		[1] = {all_skill_desc={{0},{1,"DMG to P.ATK+25%"}},id=710,name="Lightning 10-star set",num=4,skill_id={762010}},
		[2] = {all_skill_desc={{0}},id=710,name="Lightning 10-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[801] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+7%"}},id=801,name="Mountains  1-star set",num=4,skill_id={764001}},
		[2] = {all_skill_desc={{0}},id=801,name="Mountains  1-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[802] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+9%"}},id=802,name="Mountains  2-star set",num=4,skill_id={764002}},
		[2] = {all_skill_desc={{0}},id=802,name="Mountains  2-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[803] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+11%"}},id=803,name="Mountains  3-star set",num=4,skill_id={764003}},
		[2] = {all_skill_desc={{0}},id=803,name="Mountains  3-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[804] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+13%"}},id=804,name="Mountains  4-star set",num=4,skill_id={764004}},
		[2] = {all_skill_desc={{0}},id=804,name="Mountains  4-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[805] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+15%"}},id=805,name="Mountains  5-star set",num=4,skill_id={764005}},
		[2] = {all_skill_desc={{0}},id=805,name="Mountains  5-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[806] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+17%"}},id=806,name="Mountains  6-star set",num=4,skill_id={764006}},
		[2] = {all_skill_desc={{0}},id=806,name="Mountains  6-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[807] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+19%"}},id=807,name="Mountains  7-star set",num=4,skill_id={764007}},
		[2] = {all_skill_desc={{0}},id=807,name="Mountains  7-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[808] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+21%"}},id=808,name="Mountains  8-star set",num=4,skill_id={764008}},
		[2] = {all_skill_desc={{0}},id=808,name="Mountains  8-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[809] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+23%"}},id=809,name="Mountains  9-star set",num=4,skill_id={764009}},
		[2] = {all_skill_desc={{0}},id=809,name="Mountains  9-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[810] = {
		[1] = {all_skill_desc={{0},{1,"DMG to SUP+25%"}},id=810,name="Mountains  10-star set",num=4,skill_id={764010}},
		[2] = {all_skill_desc={{0}},id=810,name="Mountains  10-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[901] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=901,name="Anti-Armor 1-star set",num=4,skill_id={771001}},
		[2] = {all_skill_desc={{0}},id=901,name="Anti-Armor 1-star set",num=2,skill_id={{"def_per",50}}},
	},
	[902] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=902,name="Anti-Armor 2-star set",num=4,skill_id={771002}},
		[2] = {all_skill_desc={{0}},id=902,name="Anti-Armor 2-star set",num=2,skill_id={{"def_per",50}}},
	},
	[903] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=903,name="Anti-Armor 3-star set",num=4,skill_id={771003}},
		[2] = {all_skill_desc={{0}},id=903,name="Anti-Armor 3-star set",num=2,skill_id={{"def_per",50}}},
	},
	[904] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=904,name="Anti-Armor 4-star set",num=4,skill_id={771004}},
		[2] = {all_skill_desc={{0}},id=904,name="Anti-Armor 4-star set",num=2,skill_id={{"def_per",50}}},
	},
	[905] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=905,name="Anti-Armor 5-star set",num=4,skill_id={771005}},
		[2] = {all_skill_desc={{0}},id=905,name="Anti-Armor 5-star set",num=2,skill_id={{"def_per",50}}},
	},
	[906] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=906,name="Anti-Armor 6-star set",num=4,skill_id={771006}},
		[2] = {all_skill_desc={{0}},id=906,name="Anti-Armor 6-star set",num=2,skill_id={{"def_per",50}}},
	},
	[907] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=907,name="Anti-Armor 7-star set",num=4,skill_id={771007}},
		[2] = {all_skill_desc={{0}},id=907,name="Anti-Armor 7-star set",num=2,skill_id={{"def_per",50}}},
	},
	[908] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=908,name="Anti-Armor 8-star set",num=4,skill_id={771008}},
		[2] = {all_skill_desc={{0}},id=908,name="Anti-Armor 8-star set",num=2,skill_id={{"def_per",50}}},
	},
	[909] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=909,name="Anti-Armor 9-star set",num=4,skill_id={771009}},
		[2] = {all_skill_desc={{0}},id=909,name="Anti-Armor 9-star set",num=2,skill_id={{"def_per",50}}},
	},
	[910] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anti-armor]"}},id=910,name="Anti-Armor 10-star set",num=4,skill_id={771010}},
		[2] = {all_skill_desc={{0}},id=910,name="Anti-Armor 10-star set",num=2,skill_id={{"def_per",50}}},
	},
	[1001] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1001,name="Anger 1-star set",num=4,skill_id={772001}},
		[2] = {all_skill_desc={{0}},id=1001,name="Anger 1-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1002] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1002,name="Anger 2-star set",num=4,skill_id={772002}},
		[2] = {all_skill_desc={{0}},id=1002,name="Anger 2-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1003] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1003,name="Anger 3-star set",num=4,skill_id={772003}},
		[2] = {all_skill_desc={{0}},id=1003,name="Anger 3-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1004] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1004,name="Anger 4-star set",num=4,skill_id={772004}},
		[2] = {all_skill_desc={{0}},id=1004,name="Anger 4-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1005] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1005,name="Anger 5-star set",num=4,skill_id={772005}},
		[2] = {all_skill_desc={{0}},id=1005,name="Anger 5-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1006] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1006,name="Anger 6-star set",num=4,skill_id={772006}},
		[2] = {all_skill_desc={{0}},id=1006,name="Anger 6-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1007] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1007,name="Anger 7-star set",num=4,skill_id={772007}},
		[2] = {all_skill_desc={{0}},id=1007,name="Anger 7-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1008] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1008,name="Anger 8-star set",num=4,skill_id={772008}},
		[2] = {all_skill_desc={{0}},id=1008,name="Anger 8-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1009] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1009,name="Anger 9-star set",num=4,skill_id={772009}},
		[2] = {all_skill_desc={{0}},id=1009,name="Anger 9-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1010] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Anger]"}},id=1010,name="Anger 10-star set",num=4,skill_id={772010}},
		[2] = {all_skill_desc={{0}},id=1010,name="Anger 10-star set",num=2,skill_id={{"atk_per",50}}},
	},
	[1101] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1101,name="Dragon\'s might 1-star set",num=4,skill_id={773001}},
		[2] = {all_skill_desc={{0}},id=1101,name="Dragon\'s might 1-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1102] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1102,name="Dragon\'s might 2-star set",num=4,skill_id={773002}},
		[2] = {all_skill_desc={{0}},id=1102,name="Dragon\'s might 2-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1103] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1103,name="Dragon\'s might 3-star set",num=4,skill_id={773003}},
		[2] = {all_skill_desc={{0}},id=1103,name="Dragon\'s might 3-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1104] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1104,name="Dragon\'s might 4-star set",num=4,skill_id={773004}},
		[2] = {all_skill_desc={{0}},id=1104,name="Dragon\'s might 4-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1105] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1105,name="Dragon\'s might 5-star set",num=4,skill_id={773005}},
		[2] = {all_skill_desc={{0}},id=1105,name="Dragon\'s might 5-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1106] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1106,name="Dragon\'s might 6-star set",num=4,skill_id={773006}},
		[2] = {all_skill_desc={{0}},id=1106,name="Dragon\'s might 6-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1107] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1107,name="Dragon\'s might 7-star set",num=4,skill_id={773007}},
		[2] = {all_skill_desc={{0}},id=1107,name="Dragon\'s might 7-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1108] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1108,name="Dragon\'s might 8-star set",num=4,skill_id={773008}},
		[2] = {all_skill_desc={{0}},id=1108,name="Dragon\'s might 8-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1109] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1109,name="Dragon\'s might 9-star set",num=4,skill_id={773009}},
		[2] = {all_skill_desc={{0}},id=1109,name="Dragon\'s might 9-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1110] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Dragon might]"}},id=1110,name="Dragon\'s might 10-star set",num=4,skill_id={773010}},
		[2] = {all_skill_desc={{0}},id=1110,name="Dragon\'s might 10-star set",num=2,skill_id={{"crit_rate",50}}},
	},
	[1201] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1201,name="Angel 1-star set",num=4,skill_id={774001}},
		[2] = {all_skill_desc={{0}},id=1201,name="Angel 1-star set",num=2,skill_id={{"cure",70}}},
	},
	[1202] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1202,name="Angel 2-star set",num=4,skill_id={774002}},
		[2] = {all_skill_desc={{0}},id=1202,name="Angel 2-star set",num=2,skill_id={{"cure",70}}},
	},
	[1203] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1203,name="Angel 3-star set",num=4,skill_id={774003}},
		[2] = {all_skill_desc={{0}},id=1203,name="Angel 3-star set",num=2,skill_id={{"cure",70}}},
	},
	[1204] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1204,name="Angel 4-star set",num=4,skill_id={774004}},
		[2] = {all_skill_desc={{0}},id=1204,name="Angel 4-star set",num=2,skill_id={{"cure",70}}},
	},
	[1205] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1205,name="Angel 5-star set",num=4,skill_id={774005}},
		[2] = {all_skill_desc={{0}},id=1205,name="Angel 5-star set",num=2,skill_id={{"cure",70}}},
	},
	[1206] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1206,name="Angel 6-star set",num=4,skill_id={774006}},
		[2] = {all_skill_desc={{0}},id=1206,name="Angel 6-star set",num=2,skill_id={{"cure",70}}},
	},
	[1207] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1207,name="Angel 7-star set",num=4,skill_id={774007}},
		[2] = {all_skill_desc={{0}},id=1207,name="Angel 7-star set",num=2,skill_id={{"cure",70}}},
	},
	[1208] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1208,name="Angel 8-star set",num=4,skill_id={774008}},
		[2] = {all_skill_desc={{0}},id=1208,name="Angel 8-star set",num=2,skill_id={{"cure",70}}},
	},
	[1209] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1209,name="Angel 9-star set",num=4,skill_id={774009}},
		[2] = {all_skill_desc={{0}},id=1209,name="Angel 9-star set",num=2,skill_id={{"cure",70}}},
	},
	[1210] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Angel]"}},id=1210,name="Angel 10-star set",num=4,skill_id={774010}},
		[2] = {all_skill_desc={{0}},id=1210,name="Angel 10-star set",num=2,skill_id={{"cure",70}}},
	},
	[1301] = {
		[1] = {all_skill_desc={{0},{0}},id=1301,name="Speed 1-star set",num=4,skill_id={{"speed_per",30}}},
		[2] = {all_skill_desc={{0}},id=1301,name="Speed 1-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1302] = {
		[1] = {all_skill_desc={{0},{0}},id=1302,name="Speed 2-star set",num=4,skill_id={{"speed_per",40}}},
		[2] = {all_skill_desc={{0}},id=1302,name="Speed 2-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1303] = {
		[1] = {all_skill_desc={{0},{0}},id=1303,name="Speed 3-star set",num=4,skill_id={{"speed_per",50}}},
		[2] = {all_skill_desc={{0}},id=1303,name="Speed 3-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1304] = {
		[1] = {all_skill_desc={{0},{0}},id=1304,name="Speed 4-star set",num=4,skill_id={{"speed_per",60}}},
		[2] = {all_skill_desc={{0}},id=1304,name="Speed 4-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1305] = {
		[1] = {all_skill_desc={{0},{0}},id=1305,name="Speed 5-star set",num=4,skill_id={{"speed_per",70}}},
		[2] = {all_skill_desc={{0}},id=1305,name="Speed 5-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1306] = {
		[1] = {all_skill_desc={{0},{0}},id=1306,name="Speed 6-star set",num=4,skill_id={{"speed_per",80}}},
		[2] = {all_skill_desc={{0}},id=1306,name="Speed 6-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1307] = {
		[1] = {all_skill_desc={{0},{0}},id=1307,name="Speed 7-star set",num=4,skill_id={{"speed_per",90}}},
		[2] = {all_skill_desc={{0}},id=1307,name="Speed 7-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1308] = {
		[1] = {all_skill_desc={{0},{0}},id=1308,name="Speed 8-star set",num=4,skill_id={{"speed_per",100}}},
		[2] = {all_skill_desc={{0}},id=1308,name="Speed 8-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1309] = {
		[1] = {all_skill_desc={{0},{0}},id=1309,name="Speed 9-star set",num=4,skill_id={{"speed_per",110}}},
		[2] = {all_skill_desc={{0}},id=1309,name="Speed 9-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1310] = {
		[1] = {all_skill_desc={{0},{0}},id=1310,name="Speed 10-star set",num=4,skill_id={{"speed_per",120}}},
		[2] = {all_skill_desc={{0}},id=1310,name="Speed 10-star set",num=2,skill_id={{"speed_per",30}}},
	},
	[1401] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1401,name="Natural 1-star set",num=4,skill_id={775001}},
		[2] = {all_skill_desc={{0}},id=1401,name="Natural 1-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1402] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1402,name="Natural 2-star set",num=4,skill_id={775002}},
		[2] = {all_skill_desc={{0}},id=1402,name="Natural 2-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1403] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1403,name="Natural 3-star set",num=4,skill_id={775003}},
		[2] = {all_skill_desc={{0}},id=1403,name="Natural 3-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1404] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1404,name="Natural 4-star set",num=4,skill_id={775004}},
		[2] = {all_skill_desc={{0}},id=1404,name="Natural 4-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1405] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1405,name="Natural 5-star set",num=4,skill_id={775005}},
		[2] = {all_skill_desc={{0}},id=1405,name="Natural 5-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1406] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1406,name="Natural 6-star set",num=4,skill_id={775006}},
		[2] = {all_skill_desc={{0}},id=1406,name="Natural 6-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1407] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1407,name="Natural 7-star set",num=4,skill_id={775007}},
		[2] = {all_skill_desc={{0}},id=1407,name="Natural 7-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1408] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1408,name="Natural 8-star set",num=4,skill_id={775008}},
		[2] = {all_skill_desc={{0}},id=1408,name="Natural 8-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1409] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1409,name="Natural 9-star set",num=4,skill_id={775009}},
		[2] = {all_skill_desc={{0}},id=1409,name="Natural 9-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
	[1410] = {
		[1] = {all_skill_desc={{0},{2,"SKL[Natural]"}},id=1410,name="Natural 10-star set",num=4,skill_id={775010}},
		[2] = {all_skill_desc={{0}},id=1410,name="Natural 10-star set",num=2,skill_id={{"dodge_magic",50}}},
	},
}
