-- this file is generated by program!
-- don't change it manaully.
-- source file: partner_data.xls

Config = Config or {} 
Config.PartnerData = Config.PartnerData or {}
Config.PartnerData.data_partner_buy_key_depth = 1
Config.PartnerData.data_partner_buy_length = 10
Config.PartnerData.data_partner_buy_lan = "en"
Config.PartnerData.data_partner_buy = {
	[1] = {add_num=5,count=1,expend={{3,100}}},
	[2] = {add_num=5,count=2,expend={{3,150}}},
	[3] = {add_num=5,count=3,expend={{3,200}}},
	[4] = {add_num=5,count=4,expend={{3,250}}},
	[5] = {add_num=5,count=5,expend={{3,300}}},
	[6] = {add_num=5,count=6,expend={{3,300}}},
	[7] = {add_num=5,count=7,expend={{3,300}}},
	[8] = {add_num=5,count=8,expend={{3,300}}},
	[9] = {add_num=5,count=9,expend={{3,300}}},
	[10] = {add_num=5,count=10,expend={{3,300}}},
}
