-- this file is generated by program!
-- don't change it manaully.
-- source file: primus_data.xls

Config = Config or {} 
Config.PrimusData = Config.PrimusData or {}
Config.PrimusData.data_upgrade_key_depth = 1
Config.PrimusData.data_upgrade_length = 6
Config.PrimusData.data_upgrade_lan = "en"
Config.PrimusData.data_upgrade = {
	[1] = {arena_rank=10,honor_id=90801,look_id=340502,name="Top of pantheon",pos=1},
	[2] = {arena_rank=20,honor_id=90802,look_id=320508,name="Titan God shines",pos=2},
	[3] = {arena_rank=20,honor_id=90802,look_id=330506,name="Titan God shines",pos=3},
	[4] = {arena_rank=50,honor_id=90803,look_id=310501,name="Vast starlight",pos=4},
	[5] = {arena_rank=50,honor_id=90803,look_id=310501,name="Vast starlight",pos=5},
	[6] = {arena_rank=50,honor_id=90803,look_id=310501,name="Vast starlight",pos=6},
}
