-- this file is generated by program!
-- don't change it manaully.
-- source file: privilege_data.xls

Config = Config or {} 
Config.PrivilegeData = Config.PrivilegeData or {}
Config.PrivilegeData.data_privilege_data_ypsdk_key_depth = 1
Config.PrivilegeData.data_privilege_data_ypsdk_length = 6
Config.PrivilegeData.data_privilege_data_ypsdk_lan = "en"
Config.PrivilegeData.data_privilege_data_ypsdk = {
	[101] = {charge_id=304,desc="A must-buy gift pack for capturing powerful Pokémon! Super value discount, limited to once a week!",icon_id="10",id=101,limit_day=7,limit_lev=0,limit_type=1,loss=30,name="Hunting ball",pay_type=1,sort_id=1,title_type=1},
	[102] = {charge_id=305,desc="Collect resource privileges! Free fast battles three times a day, and then send summon benefits!",icon_id="10",id=102,limit_day=30,limit_lev=0,limit_type=1,loss=68,name="Quick combat",pay_type=1,sort_id=3,title_type=1},
	[103] = {charge_id=0,desc="Bounty adventure high-level privileges, the first bounty refresh every day will be a purple mission!",icon_id="11",id=103,limit_day=0,limit_lev=0,limit_type=0,loss=980,name="Bounty Premium",pay_type=2,sort_id=5,title_type=2},
	[104] = {charge_id=0,desc="Bounty adventure luxury privileges, the third time every day the bounty refresh will give an orange mission!",icon_id="11",id=104,limit_day=0,limit_lev=0,limit_type=0,loss=1980,name="Bounty luxury",pay_type=2,sort_id=6,title_type=2},
	[105] = {charge_id=307,desc="Privileges of the Temple of Elements! Two additional free times a day, six purchase times!",icon_id="12",id=105,limit_day=30,limit_lev=90,limit_type=1,loss=30,name="Temple of Elements",pay_type=1,sort_id=4,title_type=3},
	[106] = {charge_id=310,desc="Make machine privilege! Exclusive maker, and then send the best rare CD and machine props!",icon_id="12",id=106,limit_day=7,limit_lev=80,limit_type=1,loss=30,name="Make Machine",pay_type=1,sort_id=2,title_type=0},
}
