-- this file is generated by program!
-- don't change it manaully.
-- source file: resonate_data.xls

Config = Config or {} 
Config.ResonateData = Config.ResonateData or {}
Config.ResonateData.data_cell_cost_key_depth = 1
Config.ResonateData.data_cell_cost_length = 29
Config.ResonateData.data_cell_cost_lan = "en"
Config.ResonateData.data_cell_cost = {
	[1] = {count=1,loss1={{10480,200}},loss2={{3,500}}},
	[2] = {count=2,loss1={{10480,300}},loss2={{3,600}}},
	[3] = {count=3,loss1={{10480,400}},loss2={{3,700}}},
	[4] = {count=4,loss1={{10480,500}},loss2={{3,800}}},
	[5] = {count=5,loss1={{10480,600}},loss2={{3,900}}},
	[6] = {count=6,loss1={{10480,700}},loss2={{3,1000}}},
	[7] = {count=7,loss1={{10480,800}},loss2={{3,1100}}},
	[8] = {count=8,loss1={{10480,900}},loss2={{3,1200}}},
	[9] = {count=9,loss1={{10480,1000}},loss2={{3,1300}}},
	[10] = {count=10,loss1={{10480,1200}},loss2={{3,1400}}},
	[11] = {count=11,loss1={{10480,1400}},loss2={{3,1500}}},
	[12] = {count=12,loss1={{10480,1600}},loss2={{3,1600}}},
	[13] = {count=13,loss1={{10480,1800}},loss2={{3,1700}}},
	[14] = {count=14,loss1={{10480,2000}},loss2={{3,1800}}},
	[15] = {count=15,loss1={{10480,2200}},loss2={{3,1900}}},
	[16] = {count=16,loss1={{10480,2400}},loss2={{3,2000}}},
	[17] = {count=17,loss1={{10480,2600}},loss2={{3,2100}}},
	[18] = {count=18,loss1={{10480,2800}},loss2={{3,2200}}},
	[19] = {count=19,loss1={{10480,3000}},loss2={{3,2300}}},
	[20] = {count=20,loss1={{10480,3200}},loss2={{3,2400}}},
	[21] = {count=21,loss1={{10480,3400}},loss2={{3,2500}}},
	[22] = {count=22,loss1={{10480,3600}},loss2={{3,2600}}},
	[23] = {count=23,loss1={{10480,3800}},loss2={{3,2700}}},
	[24] = {count=24,loss1={{10480,4000}},loss2={{3,2800}}},
	[25] = {count=25,loss1={{10480,4200}},loss2={{3,2900}}},
	[26] = {count=26,loss1={{10480,4400}},loss2={{3,3000}}},
	[27] = {count=27,loss1={{10480,4600}},loss2={{3,3100}}},
	[28] = {count=28,loss1={{10480,4800}},loss2={{3,3200}}},
	[29] = {count=29,loss1={{10480,5000}},loss2={{3,3300}}},
}
