-- this file is generated by program!
-- don't change it manaully.
-- source file: shipping_data.xls

Config = Config or {} 
Config.ShippingData = Config.ShippingData or {}
Config.ShippingData.data_const_key_depth = 1
Config.ShippingData.data_const_length = 9
Config.ShippingData.data_const_lan = "en"
Config.ShippingData.data_const = {
	["discount"] = {desc="Information discount",key="discount",val=900},
	["first_refresh"] = {desc="Must be out for the first refresh",key="first_refresh",val={10905,10701,11001}},
	["guild_lev"] = {desc="Level 12 starts bounty adventure",key="guild_lev",val=12},
	["max_quest"] = {desc="Maximum number of orders",key="max_quest",val=6},
	["refresh_bless"] = {desc="Refresh guarantee times",key="refresh_bless",val=0},
	["refresh_cost"] = {desc="Item refresh cost",key="refresh_cost",val={{10002,1}}},
	["refresh_free_count"] = {desc="Free refreshes",key="refresh_free_count",val=2},
	["refresh_highvip"] = {desc="Premium Bounty Adventure Refresh Privileges",key="refresh_highvip",val={104}},
	["refresh_vip"] = {desc="Junior Bounty Adventure Refresh Privileges",key="refresh_vip",val={103}},
}
