-- this file is generated by program!
-- don't change it manaully.
-- source file: shipping_data.xls

Config = Config or {} 
Config.ShippingData = Config.ShippingData or {}
Config.ShippingData.data_condition_key_depth = 1
Config.ShippingData.data_condition_length = 15
Config.ShippingData.data_condition_lan = "en"
Config.ShippingData.data_condition = {
	[100] = {conition={{"partner_star",1,1}},desc="There is 1 partner with 1 star or above",id=100},
	[101] = {conition={{"partner_star",2,1}},desc="There is 1 partner with 2 stars or above",id=101},
	[102] = {conition={{"partner_star",3,1}},desc="There is 1 partner with 3 stars or above",id=102},
	[103] = {conition={{"partner_star",4,1}},desc="There is 1 partner with 4 stars or above",id=103},
	[104] = {conition={{"partner_star",5,1}},desc="There is 1 partner with 5 stars or above",id=104},
	[105] = {conition={{"partner_star",6,1}},desc="There is 1 partner with 6 stars or above",id=105},
	[106] = {conition={{"partner_star",7,1}},desc="There is 1 partner with 7 stars or above",id=106},
	[107] = {conition={{"partner_star",8,1}},desc="There is 1 partner with 8 stars or above",id=107},
	[108] = {conition={{"partner_star",9,1}},desc="There is 1 partner with 9 stars or above",id=108},
	[109] = {conition={{"partner_star",10,1}},desc="There is 1 partner with 10 stars or above",id=109},
	[200] = {conition={{"partner_camp_type",1,1}},desc="There is a partner in the water camp",id=200},
	[201] = {conition={{"partner_camp_type",2,1}},desc="There is a partner in the fire camp",id=201},
	[202] = {conition={{"partner_camp_type",3,1}},desc="There is 1 partner in the grass faction",id=202},
	[203] = {conition={{"partner_camp_type",4,1}},desc="There is a partner in the light camp",id=203},
	[204] = {conition={{"partner_camp_type",5,1}},desc="There is a partner in the dark camp",id=204},
}
