-- this file is generated by program!
-- don't change it manaully.
-- source file: sprite_data.xls

Config = Config or {} 
Config.SpriteData = Config.SpriteData or {}
Config.SpriteData.data_const_key_depth = 1
Config.SpriteData.data_const_length = 18
Config.SpriteData.data_const_lan = "en"
Config.SpriteData.data_const = {
	["ancient_desc"] = {desc="1. Each machine carries a <div fontcolor=#32CD32>exclusive skill</div>, and the integration of machines can increase the skill level. \n2. The player can attach the machine to the rotom and take advantage of the attributes of the rotom. \n3. The machine attached to the rotom will be used as special combat units to cooperate in battle. \n4. After the rotom level up, more locations for the machine to attach to can be unlocked. \n5. The machine of the same name can only attach <div fontcolor=#32CD32>one</div> to the rotom. \n6. The position of the machine determines the <div fontcolor=#32CD32>casting order</div> of its skills in battle. \n7. The machine can be obtained through <div fontcolor=#32CD32>machine maker</div>. The machine can be obtained through <div fontcolor=#32CD32> blank CD manufacturing</div>. The machine are placed in the maker, and a machine randomly made after waiting for a period of time. \n8. Through <div fontcolor=#32CD32> hang-up bonus, champion store, activities, supplement</div> and other channels, you can get a corresponding number of CD. \n9. In addition to normal manufacturing, the <div fontcolor=#32CD32> decompose</div> of extra machine can also be transformed into steel part needed for the level up of rotom.",val=1},
	["ancient_story"] = {desc="Rotom Phone is a kind of mobile phone with powerful functions such as Pokemon illustrated book. In it, Pokemon lotom can enter various electrical appliances. \n It also has many very practical functions. For example, after installing the Rotom Phone on the bicycle, the bicycle will not only run fast on the land, but also move on the water. \n Rotom Phone can not only query the properties and ecology of Pokemon, but also view the Pokemon you have accepted. \n Because of its powerful recording and simulation functions, after embedding the technical machine, lotom can obtain the skills recorded by the Machine and use it in combat. \n The technical machine is embedded in the lotom phone, so lotom can use this technical to fight with Pokemon.",val=1},
	["awake_gain"] = {desc="",val=10042},
	["daily_free_gift"] = {desc="Privilege daily gift items",val={{10601,2}}},
	["egg_buy_limit"] = {desc="Number of Egg Purchases/Daily",val=1},
	["egg_buy_price"] = {desc="Egg egg purchase price (itemid_ Gems price)",val={10603,{{3,2000000}}}},
	["end_time"] = {desc="At the end of the incubation, the light effect starts playing for n milliseconds, and then a pop-up window is requested.",val=1300},
	["free_programmes"] = {desc="Free quantity of machine management plan",val=2},
	["hatch_desc"] = {desc="Lv.<div fontcolor=#32CD32>0</div>; <div fontcolor=#32CD32>11</div> a little less manufacturing in seconds; <div fontcolor=#32CD32>0</div> Gems; VIP< div fontcolor=#32CD32>0</div>\nLv.<div fontcolor=#32CD32>1</div>; <div fontcolor=#32CD32>10</div> a little less incubation in seconds; <div fontcolor=# 32CD32>100</div> Gems; VIP<div fontcolor=#32CD32>0</div>\nLv.<div fontcolor=#32CD32>2</div>; <div fontcolor=#32CD32>9</div >Second less incubation point; <div fontcolor=#32CD32>200</div> Gems; VIP<div fontcolor=#32CD32>1</div>\nLv.<div fontcolor=#32CD32>3</div> ;<div fontcolor=#32CD32>8</div> one second less manufacturing point; <div fontcolor=#32CD32>500</div> Gems; VIP<div fontcolor=#32CD32>3</div>\nLv. <div fontcolor=#32CD32>4</div>; <div fontcolor=#32CD32>7</div> one second less manufacturing point; <div fontcolor=#32CD32>800</div> Gems; VIP<div fontcolor is required =#32CD32>4</div>\nLv.<div fontcolor=#32CD32>5</div>; <div fontcolor=#32CD32>6</div> one second less manufacturing point; <div fontcolor=#32CD32> 1200</div> Gems; VIP<div fontcolor=#32CD32>5</div>\nLv.<div fontcolor=#32CD32>6</div>; <div fontcolor=#32CD32>5</div> seconds Reduce the manufacturing point; <div fontcolor=#32CD32>1600</div> Gems; need vip<div fontcolor=#32CD32 >6</div>",val=1},
	["hatch_rate"] = {desc="Incubation efficiency",val=5},
	["programme_add_cost"] = {desc="machine management open plan price",val={3,300}},
	["prop_buy_limit"] = {desc="Speed up item purchases/day",val=2},
	["prop_buy_price"] = {desc="Speed up item purchase price (itemid_Gems price)",val={10701,{{3,100}}}},
	["reborn_exhibition"] = {desc="Elf rebirth gets a preview",val={{39067,1},{10040,1}}},
	["reborn_tips"] = {desc="1. During this period, you can only choose <div fontcolor=#32CD32>TM-04</div> and <div fontcolor=#32CD32>TM-07</div>. Level 1 ice rock behemoth\n2. Rebirth will retain <div fontcolor=#32CD32>1</div> Level 1 sprite body\n3. Rebirth returns the spirit of the sprite and all arcanes that are equivalent to the amount of body required for sprite cultivation. Dust\n4. The spirit of the spirit can choose to redeem any existing orange spirit except the rebirth spirit of this period\n5. The end of this period of activity: <div fontcolor=#32CD32> January 16, 2020 0:00</ div>",val=1},
	["sprite_max_star_show"] = {desc="The picture book shows the maximum star rating",val=5},
	["sprite_unlocked_lv"] = {desc="The machine system will be opened at level 45",val=45},
	["total_programmes"] = {desc="Total number of machine management solutions",val=10},
}
