-- this file is generated by program!
-- don't change it manaully.
-- source file: week_act_data.xls

Config = Config or {} 
Config.WeekActData = Config.WeekActData or {}
Config.WeekActData.data_lock_info_key_depth = 2
Config.WeekActData.data_lock_info_length = 3
Config.WeekActData.data_lock_info_lan = "en"
Config.WeekActData.data_lock_info = {
	[2] = {
		[1] = {bid=2,floor=1,unlock_num=0},
		[2] = {bid=2,floor=2,unlock_num=50},
		[3] = {bid=2,floor=3,unlock_num=100},
		[4] = {bid=2,floor=4,unlock_num=190},
		[5] = {bid=2,floor=5,unlock_num=340},
	},
	[1] = {
		[1] = {bid=1,floor=1,unlock_num=0},
		[2] = {bid=1,floor=2,unlock_num=70},
		[3] = {bid=1,floor=3,unlock_num=130},
		[4] = {bid=1,floor=4,unlock_num=240},
		[5] = {bid=1,floor=5,unlock_num=400},
	},
	[3] = {
		[1] = {bid=3,floor=1,unlock_num=0},
		[2] = {bid=3,floor=2,unlock_num=80},
		[3] = {bid=3,floor=3,unlock_num=150},
		[4] = {bid=3,floor=4,unlock_num=250},
		[5] = {bid=3,floor=5,unlock_num=450},
	},
}
