---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 19/01/04 20:25
---
BeastScrollItem = BeastScrollItem or class("BeastScrollItem", Node)
local this = BeastScrollItem

function BeastScrollItem:ctor(obj, tab)
    self.transform = obj.transform
    self.gameObject = self.transform.gameObject;
    self.data = tab;
    self.image_ab = "beast_image";
    self.transform_find = self.transform.Find;
    self.events = {};
    self:Init();
    self:AddEvents();
end

function BeastScrollItem:Init()
    self.is_loaded = true;
    self.nodes = {
        "selected", "base_score", "item_name", "normal", "assist", --"icon",
        "frame", "frame/icon",
    }
    self:GetChildren(self.nodes);

    self:InitUI();
end

function BeastScrollItem:dctor()
    GlobalEvent:RemoveTabListener(self.events);
    if self.schedule then
        GlobalSchedule:Stop(self.schedule);
    end

    if self.awardItem then
        self.awardItem:destroy();
    end
    self.awardItem = nil;
    if self.reddot then
        self.reddot:destroy();
    end
    self.reddot = nil;
end

function BeastScrollItem:InitUI()
    self.selected = GetImage(self.selected);
    self.base_score = GetText(self.base_score);
    self.item_name = GetText(self.item_name);
    self.normal = GetImage(self.normal);
    self.assist = GetImage(self.assist);
    self:SetIsSelected(false);
    self.icon_1 = GetImage(self.icon);
    self.frame = GetImage(self.frame);
    SetGameObjectActive(self.assist, false);

    if self.data then
        if self.data.name then
            self.item_name.text = tostring(self.data.name);
        else
            local itemConfig = Config.db_item[self.data.id];
            local equipConfig = Config.db_beast_equip[self.data.id];
            local colorStr = "666666";
            if itemConfig.color > 1 then
                colorStr = ColorUtil.GetColor(itemConfig.color)
            end
            self.item_name.text = "<color=#" .. colorStr .. ">" .. tostring(itemConfig.name) .. "</color>";--BeastModel.FONTCOLOR[itemConfig.color]

            local param = {}
            local operate_param = {}
            param["cfg"] = Config.db_beast_equip[self.data.id]
            param["p_item"] = self.data;
            param["can_click"] = true
            --param["out_call_back"] = callback
            param["operate_param"] = operate_param

            if self.awardItem then
                self.awardItem:destroy();
            end
            self.awardItem = GoodsIconSettorTwo(self.icon.transform);
            self.awardItem:SetIcon(param)
        end
    end

    self.reddot = RedDot(self.transform, nil, RedDot.RedDotType.Nor)
    self.reddot:SetPosition(-46, 28);
    --self.reddot:SetRedDotParam(true);
end

function BeastScrollItem:Refresh()
    if self.data then
        if self.data.name then
            self.item_name.text = tostring(self.data.name);
        else
            local itemConfig = Config.db_item[self.data.id];
            local equipConfig = Config.db_beast_equip[self.data.id];
            local colorStr = "666666";
            if itemConfig.color > 1 then
                colorStr = ColorUtil.GetColor(itemConfig.color)
            end
            self.item_name.text = "<color=#" .. colorStr .. ">" .. tostring(itemConfig.name) .. "</color>";--BeastModel.FONTCOLOR[itemConfig.color]

            local param = {}
            local operate_param = {}
            param["cfg"] = Config.db_beast_equip[self.data.id]
            param["p_item"] = self.data;
            param["can_click"] = true
            param["operate_param"] = operate_param

            if self.awardItem then
                self.awardItem:destroy();
            end
            self.awardItem = nil;
            self.awardItem = GoodsIconSettorTwo(self.icon.transform);
            self.awardItem:SetIcon(param);
        end
    end
end

function BeastScrollItem:SetIcon(iconid)
    --if self.icon then
    lua_resMgr:SetImageTexture(self, self.icon_1, self.image_ab, "beast_icon_" .. iconid, false);
    --else
    --    self.iconid = iconid;
    --end

end
function BeastScrollItem:SetColor(color)
    if self.frame then
        lua_resMgr:SetImageTexture(self, self.frame, "common_image", "com_icon_bg_" .. color, false);
    end
end

function BeastScrollItem:SetScoreText(str)
    self.base_score.text = str;
    if string.isNilOrEmpty(str) then
        SetLocalPositionXY(self.item_name.transform, 60, 0);
    end
end

function BeastScrollItem:AddEvents()

end

function BeastScrollItem:SetIsSelected(bool)
    bool = toBool(bool);
    if self.selected then
        SetGameObjectActive(self.selected, bool);
    end
end

function BeastScrollItem:SetIsAssist(bool)
    bool = toBool(bool);
    if self.assist then
        SetGameObjectActive(self.assist, bool);
    end
end
function BeastScrollItem:SetGray(bool)
    bool = toBool(bool);
    if bool then
        if self.data.name then
            self.item_name.text = "<color=#" .. ColorUtil.GetColor(ColorUtil.ColorType.GrayWhite) .. ">" .. tostring(self.data.name) .. "</color>";
        else
            local itemConfig = Config.db_item[self.data.id];
            self.item_name.text = "<color=#" .. ColorUtil.GetColor(ColorUtil.ColorType.GrayWhite) .. ">" .. tostring(itemConfig.name) .. "</color>";
        end
    else
        if self.data.name then
            self.item_name.text = tostring(self.data.name);
        else
            local itemConfig = Config.db_item[self.data.id];
            self.item_name.text = tostring(itemConfig.name);
        end
    end

    if self.awardItem then
        self.awardItem:SetIconGray(bool);
    else
        if bool then
            ShaderManager:GetInstance():SetImageGray(self.icon_1);
            ShaderManager:GetInstance():SetImageGray(self.frame);
        else
            ShaderManager:GetInstance():SetImageNormal(self.icon_1);
            ShaderManager:GetInstance():SetImageNormal(self.frame);
        end
    end
end

function BeastScrollItem:ShowReddot(bool)
    bool = toBool(bool);
    self.reddot:SetRedDotParam(bool);
end



----直接用GetChild实现算了吧
--BeastSkillItem = BeastSkillItem or class("BeastSkillItem", Node)
--local this = BeastSkillItem
--
--function BeastSkillItem:ctor(obj)
--    self.transform = obj.transform
--    self.gameObject = self.transform.gameObject;
--    self.image_ab = "beast_image";
--    self.transform_find = self.transform.Find;
--    self.events = {};
--    self:Init();
--    self:AddEvents();
--end
--
--function BeastSkillItem:dctor()
--    GlobalEvent:RemoveTabListener(self.events);
--    if self.schedule then
--        GlobalSchedule:Stop(self.schedule);
--    end
--end
--
--function BeastSkillItem:Init()
--    self.is_loaded = true;
--    self.nodes = {
--        "skill_level","skill_icon",
--    }
--    self:GetChildren(self.nodes);
--
--    self:InitUI();
--end
--
--function BeastSkillItem:InitUI()
--
--end
--
--function BeastSkillItem:AddEvents()
--
--end