---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2018/10/9 17:38
---
BeastEvent = {
    BAG_EVENT = "BeastEvent.BagEvent", --收到神兽背包协议
    BEAST_LIST = "BeastEvent.BeastList", --装在身上的神兽列表
    DELETE_ITEM = "BeastEvent.ItemDelete", --删除神兽背包的神兽
    ADD_ITEM = "BeastEvent.AddItem", --增加神兽背包一张神兽
    BEAST_UP_STAR = "BeastEvent.BeastUpStar", --神兽升星事件
    BEAST_DECOMPOSE = "BeastEvent.BeastDecompose", --神兽分解事件
    ADD_MAX_SUMMON = "BeastEvent.AddMaxSummon", --增加最大出战
    BEAST_EQIUP_UNLOAD = "BeastEvent.BeastEquipUnload", --神兽卸下
    BEAST_EQUIP_LOADED = "BeastEvent.BeastEquipLoad", --神兽穿装备
    BEAST_OPEN = "BeastEvent.BeastOpen", --神兽合成
    BEAST_STRENGTH = "BeastEvent.BeastStrength",--神兽强化
    BEAST_SUMMON = "BeastEvent.BeastSummon",--神兽出战
    BEAST_UNSUMMON = "BeastEvent.BeastUnSummon",--神兽出战
    UpdateRedDot = "BeastEvent.UpdateRedDot",--异兽红点
}