function main(itemId)
	if not SHOW_GUIDE then
		return 
	end

	x, y, mapid = getPlayerLocation()

	if itemId == 1 then
		actor = createRole("矿工小号", "hero", 10, 88, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("鹤嘴锄可以在用来比奇国王许可的地图挖矿，11级就能使用。")
		actor:showEquip(12)

		actor.dir = DIR.left

		for i = 1, 5, 1 do
			actor:playAct(ACTS.HEAVYHIT)
			delay(1)
		end

		actor:say("大部分时候你在武器商店就能购买到鹤嘴锄。")

		actor.dir = DIR.right

		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)

		for i = 1, 5, 1 do
			actor:playAct(ACTS.HEAVYHIT)
			delay(1)
		end

		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 2 then
		actor = createRole("矿工小号", "hero", 11, 88, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("鹤嘴锄可以在用来比奇国王许可的地图挖矿，11级就能使用。")
		actor:showEquip(12)

		actor.dir = DIR.left

		for i = 1, 5, 1 do
			actor:playAct(ACTS.HEAVYHIT)
			delay(1)
		end

		actor:say("大部分时候你在武器商店就能购买到鹤嘴锄。")

		actor.dir = DIR.right

		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)

		for i = 1, 5, 1 do
			actor:playAct(ACTS.HEAVYHIT)
			delay(1)
		end

		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 3 then
		actor = createRole("轻盔小号", "hero", 10, 55, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("轻型盔甲11级就能穿戴，可以帮助你顺利渡过前期。防御3-3魔御1-2，比布衣好多了。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("偷偷告诉你，击败骷髅洞穴、矿区的怪物是很容易爆出轻型盔甲的。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 4 then
		actor = createRole("轻盔小号", "hero", 11, 55, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("轻型盔甲11级就能穿戴，可以帮助你顺利渡过前期。防御3-3魔御1-2，比布衣好多了。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("偷偷告诉你，击败骷髅洞穴、矿区的怪物是很容易爆出轻型盔甲的。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 5 then
		actor = createRole("新手战士", "hero", 10, 57, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("15级拿上八荒，才算成为战士了。攻击4-12能够让你面对骷髅时毫无惧色。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("15级拿上八荒，才算成为战士了。攻击4-12能够让你面对骷髅时毫无惧色。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 6 then
		actor = createRole("新手战士", "hero", 11, 57, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("15级拿上八荒，才算成为战士了。攻击4-12能够让你面对骷髅时毫无惧色。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("15级拿上八荒，才算成为战士了。攻击4-12能够让你面对骷髅时毫无惧色。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 7 then
		actor = createRole("新手道士", "hero", 10, 68, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("半月是获得道术的第一把武器，15级可以使用，攻击5-10道术1-1。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("半月是获得道术的第一把武器，15级可以使用，攻击5-10道术1-1。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(2, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 8 then
		actor = createRole("新手道士", "hero", 11, 68, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("半月是获得道术的第一把武器，15级可以使用，攻击5-10道术1-1。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("半月是获得道术的第一把武器，15级可以使用，攻击5-10道术1-1。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(2, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 9 then
		actor = createRole("新手法师", "hero", 10, 34, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("海魂魔法1-2，是法师前期的得力武器，15级可以使用。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("海魂魔法1-2，是法师前期的得力武器，15级可以使用。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(8, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 10 then
		actor = createRole("新手法师", "hero", 11, 34, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("海魂魔法1-2，是法师前期的得力武器，15级可以使用。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("海魂魔法1-2，是法师前期的得力武器，15级可以使用。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(8, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 11 then
		actor = createRole("新手战士", "hero", 199, 57, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("16级可以穿中型盔甲了，防御3-5魔御1-2，能够帮你抵御更多的伤害。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("16级可以穿中型盔甲了，防御3-5魔御1-2，能够帮你抵御更多的伤害。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 12 then
		actor = createRole("新手战士", "hero", 200, 57, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("16级可以穿中型盔甲了，防御3-5魔御1-2，能够帮你抵御更多的伤害。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("16级可以穿中型盔甲了，防御3-5魔御1-2，能够帮你抵御更多的伤害。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 13 then
		actor = createRole("新手战士", "hero", 199, 37, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("凌风是一把如风般迅捷的武器，穿戴需求等级19，攻击6-12。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凌风是一把如风般迅捷的武器，穿戴需求等级19，攻击6-12。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 14 then
		actor = createRole("新手战士", "hero", 200, 37, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("凌风是一把如风般迅捷的武器，穿戴需求等级19，攻击6-12。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凌风是一把如风般迅捷的武器，穿戴需求等级19，攻击6-12。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 15 then
		actor = createRole("新手战士", "hero", 199, 39, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("长刀所向，无往不利。斩马刀攻击5-15，穿戴需要等级20。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("长刀所向，无往不利。斩马刀攻击5-15，穿戴需要等级20。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 16 then
		actor = createRole("新手战士", "hero", 200, 39, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("长刀所向，无往不利。斩马刀攻击5-15，穿戴需要等级20。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("长刀所向，无往不利。斩马刀攻击5-15，穿戴需要等级20。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 17 then
		actor = createRole("进阶战士", "hero", 25, 35, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("修罗，这把武器和它名字一样危险。攻击力0-20，需要等级22。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("修罗，这把武器和它名字一样危险。攻击力0-20，需要等级22。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 18 then
		actor = createRole("进阶战士", "hero", 22, 35, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("修罗，这把武器和它名字一样危险。攻击力0-20，需要等级22。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("修罗，这把武器和它名字一样危险。攻击力0-20，需要等级22。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 19 then
		actor = createRole("进阶道士", "hero", 27, 83, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("降魔，名字本身就代表了道士的责任。穿戴需要等级20，攻击6-11道术1-2。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("降魔，名字本身就代表了道士的责任。穿戴需要等级20，攻击6-11道术1-2。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(14, actor, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 20 then
		actor = createRole("进阶道士", "hero", 24, 83, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("降魔，名字本身就代表了道士的责任。穿戴需要等级20，攻击6-11道术1-2。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("降魔，名字本身就代表了道士的责任。穿戴需要等级20，攻击6-11道术1-2。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(14, actor, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 21 then
		actor = createRole("进阶法师", "hero", 26, 82, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("偃月能够增加1-3的魔法，穿戴需要等级20，好好使用它。 ")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("偃月能够增加1-3的魔法，穿戴需要等级20，好好使用它。 ")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(9, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 22 then
		actor = createRole("进阶法师", "hero", 23, 82, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("偃月能够增加1-3的魔法，穿戴需要等级20，好好使用它。 ")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("偃月能够增加1-3的魔法，穿戴需要等级20，好好使用它。 ")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(9, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 23 then
		actor = createRole("进阶战士", "hero", 25, 35, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上重盔甲，成为真正的战士。重盔甲防御4-7魔御2-3。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上重盔甲，成为真正的战士。重盔甲防御4-7魔御2-3。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 24 then
		actor = createRole("进阶战士", "hero", 22, 35, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上重盔甲，成为真正的战士。重盔甲防御4-7魔御2-3。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上重盔甲，成为真正的战士。重盔甲防御4-7魔御2-3。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 25 then
		actor = createRole("进阶道士", "hero", 27, 83, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上灵魂战衣，成为真正的道士。灵魂战衣防御3-6魔御3-3道术0-2。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上灵魂战衣，成为真正的道士。灵魂战衣防御3-6魔御3-3道术0-2。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(14, actor, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 26 then
		actor = createRole("进阶道士", "hero", 24, 83, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上灵魂战衣，成为真正的道士。灵魂战衣防御3-6魔御3-3道术0-2。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上灵魂战衣，成为真正的道士。灵魂战衣防御3-6魔御3-3道术0-2。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(14, actor, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 27 then
		actor = createRole("进阶法师", "hero", 26, 82, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上魔法长袍，成为真正的法师。魔法长袍防御3-5魔御3-4魔法0-2。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上魔法长袍，成为真正的法师。魔法长袍防御3-5魔御3-4魔法0-2。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(9, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 28 then
		actor = createRole("进阶法师", "hero", 23, 82, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上魔法长袍，成为真正的法师。魔法长袍防御3-5魔御3-4魔法0-2。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上魔法长袍，成为真正的法师。魔法长袍防御3-5魔御3-4魔法0-2。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(9, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 29 then
		actor = createRole("进阶战士", "hero", 25, 35, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上重盔甲，拿起修罗，成为真正的战士。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上重盔甲，拿起修罗，成为真正的战士。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 30 then
		actor = createRole("进阶战士", "hero", 22, 35, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("22级能够穿上重盔甲，拿起修罗，成为真正的战士。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("22级能够穿上重盔甲，拿起修罗，成为真正的战士。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(7, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 31 then
		actor = createRole("进阶战士", "hero", 25, 14, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("凝霜攻击10-13，有着稳定的发挥，穿戴需要等级25。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凝霜攻击10-13，有着稳定的发挥，穿戴需要等级25。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(12, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 32 then
		actor = createRole("进阶战士", "hero", 22, 14, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("凝霜攻击10-13，有着稳定的发挥，穿戴需要等级25。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凝霜攻击10-13，有着稳定的发挥，穿戴需要等级25。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(12, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 33 then
		actor = createRole("战士", "hero", 25, 36, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("炼狱攻击0-25，穿戴需要等级26。这把巨大的战斧，是战士进阶的标志。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("炼狱攻击0-25，穿戴需要等级26。这把巨大的战斧，是战士进阶的标志。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(12, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 34 then
		actor = createRole("战士", "hero", 22, 36, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("炼狱攻击0-25，穿戴需要等级26。这把巨大的战斧，是战士进阶的标志。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("炼狱攻击0-25，穿戴需要等级26。这把巨大的战斧，是战士进阶的标志。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(12, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 35 then
		actor = createRole("道士", "hero", 27, 33, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("银蛇攻击7-14道术1-3准确+1，穿戴需要等级26。这是道士进阶的标志。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("银蛇攻击7-14道术1-3准确+1，穿戴需要等级26。这是道士进阶的标志。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(15, actor, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 36 then
		actor = createRole("道士", "hero", 24, 33, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("银蛇攻击7-14道术1-3准确+1，穿戴需要等级26。这是道士进阶的标志。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("银蛇攻击7-14道术1-3准确+1，穿戴需要等级26。这是道士进阶的标志。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(15, actor, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 37 then
		actor = createRole("法师", "hero", 26, 56, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("魔杖能提供2-5的魔法，穿戴需要等级26。是法师进阶的标志。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("魔杖能提供2-5的魔法，穿戴需要等级26。是法师进阶的标志。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(22, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 38 then
		actor = createRole("法师", "hero", 23, 56, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("魔杖能提供2-5的魔法，穿戴需要等级26。是法师进阶的标志。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("魔杖能提供2-5的魔法，穿戴需要等级26。是法师进阶的标志。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(22, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 39 then
		actor = createRole("战士", "hero", 25, 32, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("这把武器刀型如月，奇利无比。故名：井中月。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("这把武器刀型如月，奇利无比。故名：井中月。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 40 then
		actor = createRole("战士", "hero", 22, 32, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("这把武器刀型如月，奇利无比。故名：井中月。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("这把武器刀型如月，奇利无比。故名：井中月。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 41 then
		actor = createRole("道士", "hero", 27, 165, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("看似平凡的造型，却蕴含了无限的灵气，这就是无极棍。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("看似平凡的造型，却蕴含了无限的灵气，这就是无极棍。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(16, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 42 then
		actor = createRole("道士", "hero", 24, 165, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("看似平凡的造型，却蕴含了无限的灵气，这就是无极棍。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("看似平凡的造型，却蕴含了无限的灵气，这就是无极棍。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(16, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 43 then
		actor = createRole("法师", "hero", 26, 166, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("血饮有着很高的准确，然而它如此受法师欢迎，似乎还有别的原因。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("血饮有着很高的准确，然而它如此受法师欢迎，似乎还有别的原因。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(24, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 44 then
		actor = createRole("法师", "hero", 23, 166, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("血饮有着很高的准确，然而它如此受法师欢迎，似乎还有别的原因。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("血饮有着很高的准确，然而它如此受法师欢迎，似乎还有别的原因。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(24, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 45 then
		actor = createRole("战士", "hero", 246, 167, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("战神盔甲防御5-9魔御3-5，穿戴需要攻击力46，而且，你的负重要足够。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("战神盔甲防御5-9魔御3-5，穿戴需要攻击力46，而且，你的负重要足够。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 46 then
		actor = createRole("战士", "hero", 247, 167, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("战神盔甲防御5-9魔御3-5，穿戴需要攻击力46，而且，你的负重要足够。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("战神盔甲防御5-9魔御3-5，穿戴需要攻击力46，而且，你的负重要足够。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 47 then
		actor = createRole("道士", "hero", 245, 165, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("幽灵战衣防御4-7魔御3-4道术1-4穿戴需要道术27，而且，你的负重要足够。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("幽灵战衣防御4-7魔御3-4道术1-4穿戴需要道术27，而且，你的负重要足够。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 48 then
		actor = createRole("道士", "hero", 244, 165, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("幽灵战衣防御4-7魔御3-4道术1-4穿戴需要道术27，而且，你的负重要足够。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("幽灵战衣防御4-7魔御3-4道术1-4穿戴需要道术27，而且，你的负重要足够。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 49 then
		actor = createRole("法师", "hero", 243, 166, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("恶魔长袍防御4-7 魔御3-4 魔法1-4穿戴需要魔法28，而且，你的负重要足够。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("恶魔长袍防御4-7 魔御3-4 魔法1-4穿戴需要魔法28，而且，你的负重要足够。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(24, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 50 then
		actor = createRole("法师", "hero", 242, 166, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("恶魔长袍防御4-7 魔御3-4 魔法1-4穿戴需要魔法28，而且，你的负重要足够。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("恶魔长袍防御4-7 魔御3-4 魔法1-4穿戴需要魔法28，而且，你的负重要足够。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(24, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 51 then
		actor = createRole("高级战士", "hero", 246, 167, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("裁决世间不平事，挥断尘世不了情。裁决之杖，攻击0-30，是战士身份的象征。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("裁决世间不平事，挥断尘世不了情。裁决之杖，攻击0-30，是战士身份的象征。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 52 then
		actor = createRole("高级战士", "hero", 247, 167, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("裁决世间不平事，挥断尘世不了情。裁决之杖，攻击0-30，是战士身份的象征。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("裁决世间不平事，挥断尘世不了情。裁决之杖，攻击0-30，是战士身份的象征。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 53 then
		actor = createRole("高级战士", "hero", 246, 207, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("掌握住自己的命运，才能主宰他人的命运，你可要拿好了。攻击12-16，还算不错的属性。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("掌握住自己的命运，才能主宰他人的命运，你可要拿好了。攻击12-16，还算不错的属性。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 54 then
		actor = createRole("高级战士", "hero", 247, 207, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("掌握住自己的命运，才能主宰他人的命运，你可要拿好了。攻击12-16，还算不错的属性。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("掌握住自己的命运，才能主宰他人的命运，你可要拿好了。攻击12-16，还算不错的属性。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 55 then
		actor = createRole("高级道士", "hero", 245, 209, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("很少有人知道龙纹剑的来历,但很多人都听说过它的威名。这是道士身份的象征。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("很少有人知道龙纹剑的来历,但很多人都听说过它的威名。这是道士身份的象征。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 56 then
		actor = createRole("高级道士", "hero", 244, 209, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("很少有人知道龙纹剑的来历,但很多人都听说过它的威名。这是道士身份的象征。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("很少有人知道龙纹剑的来历,但很多人都听说过它的威名。这是道士身份的象征。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 57 then
		actor = createRole("高级法师", "hero", 243, 221, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("骨玉权杖既有骨的质感，又有玉的灵气，这是法师身份的象征。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("骨玉权杖既有骨的质感，又有玉的灵气，这是法师身份的象征。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(33, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 58 then
		actor = createRole("高级法师", "hero", 242, 221, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("骨玉权杖既有骨的质感，又有玉的灵气，这是法师身份的象征。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("骨玉权杖既有骨的质感，又有玉的灵气，这是法师身份的象征。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(33, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 59 then
		actor = createRole("高级战士", "hero", 328, 208, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("武林至尊，宝刀屠龙，号令天下，莫敢不从。这把武器是所有战士梦寐以求之物。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("武林至尊，宝刀屠龙，号令天下，莫敢不从。这把武器是所有战士梦寐以求之物。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(43, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 60 then
		actor = createRole("高级战士", "hero", 331, 208, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("武林至尊，宝刀屠龙，号令天下，莫敢不从。这把武器是所有战士梦寐以求之物。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("武林至尊，宝刀屠龙，号令天下，莫敢不从。这把武器是所有战士梦寐以求之物。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(43, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 61 then
		actor = createRole("高级道士", "hero", 330, 326, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("逍遥扇是天尊留下的遗物，玛法大陆能有几人有资格拿起它。这把武器是所有道士梦寐以求之物。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("逍遥扇是天尊留下的遗物，玛法大陆能有几人有资格拿起它。这把武器是所有道士梦寐以求之物。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 62 then
		actor = createRole("高级道士", "hero", 333, 326, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("逍遥扇是天尊留下的遗物，玛法大陆能有几人有资格拿起它。这把武器是所有道士梦寐以求之物。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("逍遥扇是天尊留下的遗物，玛法大陆能有几人有资格拿起它。这把武器是所有道士梦寐以求之物。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 63 then
		actor = createRole("高级法师", "hero", 329, 210, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("嗜魂法杖能够吸取万物之魂，唯有至高的魔力才能够驾驭它。这把武器是所有法师梦寐以求之物。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("嗜魂法杖能够吸取万物之魂，唯有至高的魔力才能够驾驭它。这把武器是所有法师梦寐以求之物。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 64 then
		actor = createRole("高级法师", "hero", 332, 210, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("嗜魂法杖能够吸取万物之魂，唯有至高的魔力才能够驾驭它。这把武器是所有法师梦寐以求之物。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("嗜魂法杖能够吸取万物之魂，唯有至高的魔力才能够驾驭它。这把武器是所有法师梦寐以求之物。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 65 then
		actor = createRole("高级战士", "hero", 328, 208, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("天魔神甲是男战士专属的40级战衣，威风八面，谁不想穿上它呢？")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("天魔神甲是男战士专属的40级战衣，威风八面，谁不想穿上它呢？")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 66 then
		actor = createRole("高级战士", "hero", 331, 208, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("圣战宝甲是女战士专属的40级战衣，威风八面，谁不想穿上它呢？")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("圣战宝甲是女战士专属的40级战衣，威风八面，谁不想穿上它呢？")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 67 then
		actor = createRole("高级道士", "hero", 330, 326, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("天尊道袍是男道士专属的40级战衣，风度翩翩，谁不想穿上它呢？")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("天尊道袍是男道士专属的40级战衣，风度翩翩，谁不想穿上它呢？")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 68 then
		actor = createRole("高级道士", "hero", 333, 326, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("天师长袍是女道士专属的40级战衣，风度翩翩，谁不想穿上它呢？")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("天师长袍是女道士专属的40级战衣，风度翩翩，谁不想穿上它呢？")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 69 then
		actor = createRole("高级法师", "hero", 329, 210, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("法神披风是男法师专属的40级战衣，优雅华丽，谁不想穿上它呢？")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("法神披风是男法师专属的40级战衣，优雅华丽，谁不想穿上它呢？")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(33, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 70 then
		actor = createRole("高级法师", "hero", 332, 210, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("霓裳羽衣是女法师专属的40级战衣，优雅华丽，谁不想穿上它呢？")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("霓裳羽衣是女法师专属的40级战衣，优雅华丽，谁不想穿上它呢？")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(33, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 71 then
		actor = createRole("威武圣战", "hero", 328, 325, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("怒斩攻击12-26准确+3，有了这把武器，无论什么样的敌人都无处躲藏。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("怒斩攻击12-26准确+3，有了这把武器，无论什么样的敌人都无处躲藏。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 72 then
		actor = createRole("威武圣战", "hero", 331, 325, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("怒斩攻击12-26准确+3，有了这把武器，无论什么样的敌人都无处躲藏。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("怒斩攻击12-26准确+3，有了这把武器，无论什么样的敌人都无处躲藏。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(26, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 73 then
		actor = createRole("飘逸法神", "hero", 329, 324, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("据说这把武器是上古巨龙的牙齿，还残留着龙的力量。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("据说这把武器是上古巨龙的牙齿，还残留着龙的力量。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(33, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 74 then
		actor = createRole("飘逸法神", "hero", 332, 324, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("据说这把武器是上古巨龙的牙齿，还残留着龙的力量。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("据说这把武器是上古巨龙的牙齿，还残留着龙的力量。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(33, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 75 then
		actor = createRole("威武圣战", "hero", 352, 208, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("穿上雷霆战甲，会感受到一股雷霆之力鼓动着你勇往直前，这也是顶尖战士的责任。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("穿上雷霆战甲，会感受到一股雷霆之力鼓动着你勇往直前，这也是顶尖战士的责任。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(58, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 76 then
		actor = createRole("威武圣战", "hero", 353, 208, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("穿上雷霆战甲，会感受到一股雷霆之力鼓动着你勇往直前，这也是顶尖战士的责任。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("穿上雷霆战甲，会感受到一股雷霆之力鼓动着你勇往直前，这也是顶尖战士的责任。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(58, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 77 then
		actor = createRole("逍遥天尊", "hero", 404, 326, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("穿上光芒道袍，你走到哪都能照亮黑暗的阴霾，这也是顶级道士的荣耀。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("穿上光芒道袍，你走到哪都能照亮黑暗的阴霾，这也是顶级道士的荣耀。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 78 then
		actor = createRole("逍遥天尊", "hero", 405, 326, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("穿上光芒道袍，你走到哪都能照亮黑暗的阴霾，这也是顶级道士的荣耀。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("穿上光芒道袍，你走到哪都能照亮黑暗的阴霾，这也是顶级道士的荣耀。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 79 then
		actor = createRole("飘逸法神", "hero", 402, 210, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("穿上烈焰魔衣，无穷无尽的烈焰就会灼烧你一生，这也是顶级法师的宿命。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("穿上烈焰魔衣，无穷无尽的烈焰就会灼烧你一生，这也是顶级法师的宿命。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 80 then
		actor = createRole("飘逸法神", "hero", 403, 210, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("穿上烈焰魔衣，无穷无尽的烈焰就会灼烧你一生，这也是顶级法师的宿命。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("穿上烈焰魔衣，无穷无尽的烈焰就会灼烧你一生，这也是顶级法师的宿命。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 81 then
		actor = createRole("威武圣战", "hero", 350, 347, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("开天是玛法三大神兵之一，能够拿起它的必定是最伟大的战士，胸怀天地，志存玛法。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("开天是玛法三大神兵之一，能够拿起它的必定是最伟大的战士，胸怀天地，志存玛法。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(58, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 82 then
		actor = createRole("威武圣战", "hero", 351, 347, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("开天是玛法三大神兵之一，能够拿起它的必定是最伟大的战士，胸怀天地，志存玛法。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("开天是玛法三大神兵之一，能够拿起它的必定是最伟大的战士，胸怀天地，志存玛法。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(58, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 83 then
		actor = createRole("逍遥天尊", "hero", 350, 349, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("玄天是玛法三大神兵之一，能够拿起它的必定是最伟大的道士，胸怀天地，志存玛法。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("玄天是玛法三大神兵之一，能够拿起它的必定是最伟大的道士，胸怀天地，志存玛法。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 84 then
		actor = createRole("逍遥天尊", "hero", 351, 349, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("玄天是玛法三大神兵之一，能够拿起它的必定是最伟大的道士，胸怀天地，志存玛法。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("玄天是玛法三大神兵之一，能够拿起它的必定是最伟大的道士，胸怀天地，志存玛法。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 85 then
		actor = createRole("飘逸法神", "hero", 350, 348, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("镇天是玛法三大神兵之一，能够拿起它的必定是最伟大的法师，胸怀天地，志存玛法。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("镇天是玛法三大神兵之一，能够拿起它的必定是最伟大的法师，胸怀天地，志存玛法。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 86 then
		actor = createRole("飘逸法神", "hero", 351, 348, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("镇天是玛法三大神兵之一，能够拿起它的必定是最伟大的法师，胸怀天地，志存玛法。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("镇天是玛法三大神兵之一，能够拿起它的必定是最伟大的法师，胸怀天地，志存玛法。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 87 then
		actor = createRole("威武圣战", "hero", 350, 347, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("凤天魔甲融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凤天魔甲融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(58, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 88 then
		actor = createRole("威武圣战", "hero", 351, 347, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("凰天魔衣融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凰天魔衣融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(58, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 89 then
		actor = createRole("飘逸法神", "hero", 350, 348, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("凤天魔甲融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凤天魔甲融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 90 then
		actor = createRole("飘逸法神", "hero", 351, 348, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("凰天魔衣融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凰天魔衣融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(59, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 91 then
		actor = createRole("逍遥天尊", "hero", 350, 349, 0, 0, off2p(-2, 1), nil, 12)

		actor:say("凤天魔甲融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凤天魔甲融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	elseif itemId == 92 then
		actor = createRole("逍遥天尊", "hero", 351, 349, 1, 1, off2p(-2, 1), nil, 12)

		actor:say("凰天魔衣融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		actor:showEquip(12)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(1, 0), DIR.right)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, -1), DIR.up)
		actor:say("凰天魔衣融合了凤凰之力，最厉害的勇士也需经历浴火涅槃重生才有资格穿起它。")
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(-1, 0), DIR.left)
		delay(1)
		actor:playAct(ACTS.BIGHIT)
		delay(1)
		actor:playAct(ACT_WALK, pos(0, 1), DIR.bottom)
		delay(1.5)
		actor:magic(29, nil, nil, DIR.bottom)
		delay(1.5)
		actor:playAct(ACTS.SPACEMOVE_SHOW)
	end

	return 
end

return 
