EquipNotes = {}

EquipNotes.OPEN_EQUIPMAINPANEL = "OPEN_EQUIPMAINPANEL";
EquipNotes.CLOSE_EQUIPMAINPANELL = "CLOSE_EQUIPMAINPANELL";

EquipNotes.MES_CLOSE_EQUIPMAINPANELL = "MES_CLOSE_EQUIPMAINPANELL";

EquipNotes.OPEN_GEMCOMPOSEPANEL = "OPEN_GEMCOMPOSEPANEL";
EquipNotes.CLOSE_GEMCOMPOSEPANEL = "CLOSE_GEMCOMPOSEPANEL";



EquipNotes.classify_1="classify_1";
EquipNotes.classify_2="classify_2";
--EquipNotes.classify_3="classify_3";
EquipNotes.classify_4="classify_4";
EquipNotes.classify_5="classify_5";
EquipNotes.classify_6="classify_6";-- 装备套装

EquipNotes.MESSAGE_EQUIP_ZY_SUCCESS = "MESSAGE_EQUIP_ZY_SUCCESS";

EquipNotes.MESSAGE_EQUIP_SELECT = "MESSAGE_EQUIP_SELECT";
EquipNotes.MESSAGE_EQUIPREFINERESULT="MESSAGE_EQUIPREFINERESULT";
EquipNotes.MESSAGE_EQUIPSTRONGRESULT="MESSAGE_EQUIPSTRONGRESULT";
EquipNotes.MESSAGE_EQUIPNEWSTRONGRESULT="MESSAGE_EQUIPNEWSTRONGRESULT";


EquipNotes.MESSAGE_GEM_SELECT = "MESSAGE_GEM_SELECT";               --宝石列表-选择宝石
EquipNotes.MESSAGE_GEM_COMP_CLS = "MESSAGE_GEM_COMP_CLS";           --宝石合成-选择分类
EquipNotes.MESSAGE_GEM_COMP_ITEM = "MESSAGE_GEM_COMP_ITEM";         --宝石合成-选择宝石

EquipNotes.MESSAGE_GEM_SLOT_CHG = "MESSAGE_GEM_SLOT_CHG";           --宝石镶嵌发生变化
EquipNotes.MESSAGE_GEM_CHG = "MESSAGE_GEM_CHG";                     --宝石数量发生变化

EquipNotes.OPEN_EQUIPNEWSTRONGSUITONEPANEL = "OPEN_EQUIPNEWSTRONGSUITONEPANEL";
EquipNotes.CLOSE_EQUIPNEWSTRONGSUITONEPANEL = "CLOSE_EQUIPNEWSTRONGSUITONEPANEL";
EquipNotes.OPEN_EQUIPNEWSTRONGSUITPANEL = "OPEN_EQUIPNEWSTRONGSUITPANEL";
EquipNotes.CLOSE_EQUIPNEWSTRONGSUITPANEL = "CLOSE_EQUIPNEWSTRONGSUITPANEL";


EquipNotes.OPEN_EQUIPSQSUITPANEL = "OPEN_EQUIPSQSUITPANEL";

EquipNotes.CLOSE_EQUIPSQSUITPANEL = "CLOSE_EQUIPSQSUITPANEL";

EquipNotes.MESSAGE_UPLEFTEQSDATA = "MESSAGE_UPLEFTEQSDATA";

EquipNotes.MESSAGE_ADDEQINBAGPRODUCTITEM = "MESSAGE_ADDEQINBAGPRODUCTITEM";
EquipNotes.MESSAGE_PRODUCTITEMCLICKHANDLER = "MESSAGE_PRODUCTITEMCLICKHANDLER";

EquipNotes.MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_1_CHANGE = "MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_1_CHANGE";
EquipNotes.MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_2_CHANGE = "MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_2_CHANGE";
EquipNotes.MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_3_CHANGE = "MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_3_CHANGE";
EquipNotes.MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_4_CHANGE = "MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_4_CHANGE";
EquipNotes.MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_5_CHANGE = "MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_5_CHANGE";
EquipNotes.MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_6_CHANGE = "MESSAGE_CHECK_NPOINT_FOR_CLASSIFY_6_CHANGE";


EquipNotes.MESSAGE_EQUIPDRESSTIPPANELCONTROLL_SHOW = "MESSAGE_EQUIPDRESSTIPPANELCONTROLL_SHOW";
EquipNotes.MESSAGE_EQUIPDRESSTIPPANELCONTROLL_HIDE = "MESSAGE_EQUIPDRESSTIPPANELCONTROLL_HIDE";
EquipNotes.MESSAGE_EQUIPDRESSTIPPANELCONTROLL_UPDATA = "MESSAGE_EQUIPDRESSTIPPANELCONTROLL_UPDATA";
