
GuideNotes = { }

GuideNotes.OPEN_GUIDEMASKPANEL = "OPEN_GUIDEMASKPANEL"
GuideNotes.CLOSE_GUIDEMASKPANEL = "CLOSE_GUIDEMASKPANEL"
GuideNotes.UPDATE_GUIDEMASKPANEL = "UPDATE_GUIDEMASKPANEL"

GuideNotes.CLOSE_GUIDE = "CLOSE_GUIDE";
GuideNotes.OPEN_GUIDE_CLICK = "OPEN_GUIDE_CLICK";
GuideNotes.CLOSE_GUIDE_CLICK = "CLOSE_GUIDE_CLICK";

GuideNotes.OPEN_GUIDE_SELECT_ROLE = "OPEN_GUIDE_SELECT_ROLE";
GuideNotes.CLOSE_GUIDE_SELECT_ROLE = "CLOSE_GUIDE_SELECT_ROLE";
