ProductTipNotes = {}

ProductTipNotes.SHOW_BY_PRODUCT="SHOW_BY_PRODUCT";

ProductTipNotes.SHOW_EQUIPTIPPANEL="SHOW_EQUIPTIPPANEL";
ProductTipNotes.CLOSE_EQUIPTIPPANEL="CLOSE_EQUIPTIPPANEL";

ProductTipNotes.SHOW_SAMPLEPRODUCTTIPPANEL="SHOW_SAMPLEPRODUCTTIPPANEL";
ProductTipNotes.CLOSE_SAMPLEPRODUCTTIPPANEL="CLOSE_SAMPLEPRODUCTTIPPANEL";

ProductTipNotes.SHOW_PRODUCTUSEPANEL="SHOW_PRODUCTUSEPANEL";
ProductTipNotes.CLOSE_PRODUCTUSEPANELL="CLOSE_PRODUCTUSEPANELL";

ProductTipNotes.SHOW_PRODUCTSELLPANEL="SHOW_PRODUCTSELLPANEL";
ProductTipNotes.CLOSE_PRODUCTSELLPANELL="CLOSE_PRODUCTSELLPANELL";


ProductTipNotes.SHOW_EQUIPCOMPARISONTIPPANEL="SHOW_EQUIPCOMPARISONTIPPANEL";
ProductTipNotes.CLOSE_EQUIPCOMPARISONTIPPANEL="CLOSE_EQUIPCOMPARISONTIPPANEL";


ProductTipNotes.FUN_USEPRODUCT="useProduct";
ProductTipNotes.FUN_DRESSEQ="dressEq";
ProductTipNotes.FUN_UNDRESSEQ="undressEq";
ProductTipNotes.FUN_SELLPRUDUCT="sellPruduct";