return {
	id=2269,
	name=Lang.Item.n2269,
	desc=Lang.Item.i2269,
	--在线奖励(90分钟)
	--使用后获得以下所有奖励：\n{color;FF00c0ff;材料扫荡令x5}\n{color;FF00c0ff;高级经验珠x1}
	color=0xde00ff,
	type=102,
	icon=1686,
	shape=0,
	dura=0,
	useDurDrop=0,
	dup=199,
	dealType=0,
	dealPrice=10,
	time=0,
	suitId=0,
	colGroup=0,
	cdTime=0,
	dropBroadcast=0,
	batchStatus=11,
	sellBuyType=0,
	contri=0,
	showQuality=3,
	showQualityBg=3,
	staitcAttrs={
	},
	seal={},
	conds={
		{cond=1,value=1},
	},
	flags={
		recordLog=true,
		showLootTips=true,
		canMoveAttr=true,
		denyReclaim=true,
		isCanOnekeyUse=true,
	},
}