return {
{
	entityid = 1211,
	name = Lang.EntityName.m1211,
	modelid = 17,
	icon = 0,
	level = 40,
	entityType = 1,
	race = 0,
	camp = 0,
	monsterType = 1,
	aiConfigId = 2,
	exp = 0,
	innerExp = 0,
	nMaxHp = 1183,
	nMaxMp = 10,
	nPhysicalAttackMin = 98,
	nPhysicalAttackMax = 163,
	nMagicAttackMin = 98,
	nMagicAttackMax = 163,
	nWizardAttackMin = 98,
	nWizardAttackMax = 163,
	nHysicalDefenceMin = 4,
	nHysicalDefenceMax = 8,
	nMagicDefenceMin = 4,
	nMagicDefenceMax = 8,
	nHitrate = 17,
	nDogerate = 4,
	fMagicHitRate = 0,
	fMagicDogerate = 0,
	fToxicDogerate = 0,
	fToxicRenew = 0,
	fHpRenew = 0,
	fMpRenew = 0,
	nHpRenewAdd = 0,
	nLuck = 0,
	nCurse = 0,
	nNearAttackRate = 10000,
	nNearAttackType = 1,
	attackLevel = 100,
	attackInterval = 1500,
	nAttackSpeed = 1000,
	nMoveOneSlotTime = 1400,
	reSelTargetRate = 100,
	maxDropHp = 0,
	attackMusicId = 213,
	dieMusicId = 221,
	targetMusicId = 0,
	damageMusicId = 1,
	attackMusicRate = 50,
	dieMusicRate = 100,
	targetMusicTate = 30,
	damageMusicRate = 50,
	weaponid = 0,
	swingid = 0,
	hatsid = 0,
	flags = {
		CanDropCoinGround = true,
		AttackSeeKill = true,
	},
	monstercolor = {
 		0,169,169,169,
	},
	priorTarget = {
	},
	drops = {
	},
},
}