return {
{
	entityid = 29,
	name = Lang.EntityName.m29,
	modelid = 13,
	icon = 0,
	level = 26,
	entityType = 1,
	race = 0,
	camp = 0,
	monsterType = 1,
	aiConfigId = 1,
	exp = 220,
	innerExp = 22,
	nMaxHp = 453,
	nMaxMp = 10,
	nPhysicalAttackMin = 44,
	nPhysicalAttackMax = 73,
	nMagicAttackMin = 44,
	nMagicAttackMax = 73,
	nWizardAttackMin = 44,
	nWizardAttackMax = 73,
	nHysicalDefenceMin = 0,
	nHysicalDefenceMax = 0,
	nMagicDefenceMin = 0,
	nMagicDefenceMax = 0,
	nHitrate = 15,
	nDogerate = 3,
	fMagicHitRate = 0,
	fMagicDogerate = 0,
	fToxicDogerate = 0,
	fToxicRenew = 0,
	fHpRenew = 0,
	fMpRenew = 0,
	nHpRenewAdd = 0,
	nLuck = 0,
	nCurse = 0,
	nNearAttackRate = 10000,
	nNearAttackType = 1,
	attackLevel = 100,
	attackInterval = 1500,
	nAttackSpeed = 1000,
	nMoveOneSlotTime = 1400,
	reSelTargetRate = 100,
	maxDropHp = 0,
	attackMusicId = 210,
	dieMusicId = 221,
	targetMusicId = 0,
	damageMusicId = 1,
	attackMusicRate = 50,
	dieMusicRate = 100,
	targetMusicTate = 30,
	damageMusicRate = 50,
	weaponid = 0,
	swingid = 0,
	hatsid = 0,
	flags = {
		CanDropCoinGround = true,
		AttackSeeKill = true,
	},
	monstercolor = {
 		0,169,169,169,
	},
	priorTarget = {
	},
	drops = {
{type=3,id=0,count=1419,propability=100,group=0},
{type=3,id=0,count=39,propability=25,group=0},
	},
},
}