return {
{
	entityid = 465,
	name = Lang.EntityName.m465,
	modelid = 123,
	icon = 0,
	level = 1,
	entityType = 4,
	race = 0,
	camp = 0,
	monsterType = 1,
	aiConfigId = 1,
	exp = 0,
	innerExp = 0,
	nMaxHp = 100000,
	nMaxMp = 10,
	nPhysicalAttackMin = 600,
	nPhysicalAttackMax = 1000,
	nMagicAttackMin = 600,
	nMagicAttackMax = 1000,
	nWizardAttackMin = 600,
	nWizardAttackMax = 1000,
	nHysicalDefenceMin = 200,
	nHysicalDefenceMax = 500,
	nMagicDefenceMin = 200,
	nMagicDefenceMax = 500,
	nHitrate = 34,
	nDogerate = 5,
	fMagicHitRate = 0,
	fMagicDogerate = 0,
	fToxicDogerate = 0,
	fToxicRenew = 0,
	fHpRenew = 0,
	fMpRenew = 0,
	nHpRenewAdd = 0,
	nLuck = 0,
	nCurse = 0,
	nNearAttackRate = 10000,
	nNearAttackType = 1,
	attackLevel = 100,
	attackInterval = 800,
	nAttackSpeed = 600,
	nMoveOneSlotTime = 500,
	reSelTargetRate = 100,
	maxDropHp = 0,
	attackMusicId = 205,
	dieMusicId = 221,
	targetMusicId = 0,
	damageMusicId = 1,
	attackMusicRate = 50,
	dieMusicRate = 100,
	targetMusicTate = 30,
	damageMusicRate = 50,
	weaponid = 0,
	swingid = 0,
	hatsid = 0,
	flags = {
		CanAttackMonster = true,
		CanDropCoinGround = true,
		DenyAddNumber = true,
	},
	monstercolor = {
 		0,169,169,169,
	},
	priorTarget = {
	},
	drops = {
	},
},
}