return {
{
	entityid = 647,
	name = Lang.EntityName.m647,
	modelid = 100,
	icon = 0,
	level = 80,
	entityType = 1,
	race = 4,
	camp = 1,
	monsterType = 5,
	aiConfigId = 62,
	exp = 0,
	innerExp = 0,
	nMaxHp = 30640,
	nMaxMp = 10,
	nPhysicalAttackMin = 606,
	nPhysicalAttackMax = 1010,
	nMagicAttackMin = 606,
	nMagicAttackMax = 1010,
	nWizardAttackMin = 606,
	nWizardAttackMax = 1010,
	nHysicalDefenceMin = 21,
	nHysicalDefenceMax = 42,
	nMagicDefenceMin = 11,
	nMagicDefenceMax = 21,
	nHitrate = 25,
	nDogerate = 6,
	fMagicHitRate = 0,
	fMagicDogerate = 0,
	fToxicDogerate = 0,
	fToxicRenew = 0,
	fHpRenew = 0,
	fMpRenew = 0,
	nHpRenewAdd = 0,
	nLuck = 0,
	nCurse = 0,
	nNearAttackRate = 10000,
	nNearAttackType = 1,
	attackLevel = 100,
	attackInterval = 700,
	nAttackSpeed = 700,
	nMoveOneSlotTime = 700,
	reSelTargetRate = 100,
	maxDropHp = 0,
	attackMusicId = 216,
	dieMusicId = 221,
	targetMusicId = 0,
	damageMusicId = 1,
	attackMusicRate = 50,
	dieMusicRate = 100,
	targetMusicTate = 30,
	damageMusicRate = 50,
	weaponid = 140,
	swingid = 1,
	hatsid = 0,
	flags = {
		DenyAttackActor = true,
		DenyAttackedByActor = true,
		CanAttackMonster = true,
		CanDropCoinGround = true,
		CanAlwaysEnter = true,
		DenyAddNumber = true,
		noReturnHome = true,
	},
	monstercolor = {
 		0,250,250,250,
	},
	priorTarget = {
	},
	drops = {
	},
},
}