return {
{
	entityid = 674,
	name = Lang.EntityName.m674,
	modelid = 171,
	icon = 0,
	level = 110,
	entityType = 1,
	race = 4,
	camp = 1,
	monsterType = 5,
	aiConfigId = 64,
	exp = 0,
	innerExp = 0,
	nMaxHp = 90320,
	nMaxMp = 10,
	nPhysicalAttackMin = 1553,
	nPhysicalAttackMax = 2588,
	nMagicAttackMin = 1553,
	nMagicAttackMax = 2588,
	nWizardAttackMin = 1553,
	nWizardAttackMax = 2588,
	nHysicalDefenceMin = 74,
	nHysicalDefenceMax = 148,
	nMagicDefenceMin = 37,
	nMagicDefenceMax = 74,
	nHitrate = 31,
	nDogerate = 7,
	fMagicHitRate = 0,
	fMagicDogerate = 0,
	fToxicDogerate = 0,
	fToxicRenew = 0,
	fHpRenew = 0,
	fMpRenew = 0,
	nHpRenewAdd = 0,
	nLuck = 0,
	nCurse = 0,
	nNearAttackRate = 10000,
	nNearAttackType = 1,
	attackLevel = 100,
	attackInterval = 700,
	nAttackSpeed = 700,
	nMoveOneSlotTime = 700,
	reSelTargetRate = 100,
	maxDropHp = 0,
	attackMusicId = 216,
	dieMusicId = 221,
	targetMusicId = 0,
	damageMusicId = 1,
	attackMusicRate = 50,
	dieMusicRate = 100,
	targetMusicTate = 30,
	damageMusicRate = 50,
	weaponid = 180,
	swingid = 3,
	hatsid = 0,
	flags = {
		DenyAttackActor = true,
		DenyAttackedByActor = true,
		CanAttackMonster = true,
		CanDropCoinGround = true,
		CanAlwaysEnter = true,
		DenyAddNumber = true,
		noReturnHome = true,
	},
	monstercolor = {
 		0,250,250,250,
	},
	priorTarget = {
	},
	drops = {
	},
},
}