-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local macro_pb = require("macro_pb")
module('xxz_msg_pb')

local pb_table = {}


XXZ_MSG = protobuf.Descriptor();
pb_table.XXZ_MSG_MSGID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_UIN_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_ACCOUNT_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_SESSION_KEY_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_FEED_BACK_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_TIME_STAMP_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_PLATFORM_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_RESULT_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_TYPE_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_SRC_ID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_DEVICE_ID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_BUFFER_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_WORLD_ID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_GM_CMD_ID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_SRC_UIN_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_SRC_MSGID_FIELD = protobuf.FieldDescriptor();
pb_table.XXZ_MSG_SRC_WORLDID_FIELD = protobuf.FieldDescriptor();

pb_table.XXZ_MSG_MSGID_FIELD.name = "msgid"
pb_table.XXZ_MSG_MSGID_FIELD.full_name = ".protocol.xxz_Msg.msgid"
pb_table.XXZ_MSG_MSGID_FIELD.number = 1
pb_table.XXZ_MSG_MSGID_FIELD.index = 0
pb_table.XXZ_MSG_MSGID_FIELD.label = 2
pb_table.XXZ_MSG_MSGID_FIELD.has_default_value = false
pb_table.XXZ_MSG_MSGID_FIELD.default_value = 0
pb_table.XXZ_MSG_MSGID_FIELD.type = 5
pb_table.XXZ_MSG_MSGID_FIELD.cpp_type = 1

pb_table.XXZ_MSG_UIN_FIELD.name = "uin"
pb_table.XXZ_MSG_UIN_FIELD.full_name = ".protocol.xxz_Msg.uin"
pb_table.XXZ_MSG_UIN_FIELD.number = 2
pb_table.XXZ_MSG_UIN_FIELD.index = 1
pb_table.XXZ_MSG_UIN_FIELD.label = 1
pb_table.XXZ_MSG_UIN_FIELD.has_default_value = false
pb_table.XXZ_MSG_UIN_FIELD.default_value = 0
pb_table.XXZ_MSG_UIN_FIELD.type = 5
pb_table.XXZ_MSG_UIN_FIELD.cpp_type = 1

pb_table.XXZ_MSG_ACCOUNT_FIELD.name = "account"
pb_table.XXZ_MSG_ACCOUNT_FIELD.full_name = ".protocol.xxz_Msg.account"
pb_table.XXZ_MSG_ACCOUNT_FIELD.number = 3
pb_table.XXZ_MSG_ACCOUNT_FIELD.index = 2
pb_table.XXZ_MSG_ACCOUNT_FIELD.label = 1
pb_table.XXZ_MSG_ACCOUNT_FIELD.has_default_value = false
pb_table.XXZ_MSG_ACCOUNT_FIELD.default_value = ""
pb_table.XXZ_MSG_ACCOUNT_FIELD.type = 9
pb_table.XXZ_MSG_ACCOUNT_FIELD.cpp_type = 9

pb_table.XXZ_MSG_SESSION_KEY_FIELD.name = "session_key"
pb_table.XXZ_MSG_SESSION_KEY_FIELD.full_name = ".protocol.xxz_Msg.session_key"
pb_table.XXZ_MSG_SESSION_KEY_FIELD.number = 4
pb_table.XXZ_MSG_SESSION_KEY_FIELD.index = 3
pb_table.XXZ_MSG_SESSION_KEY_FIELD.label = 1
pb_table.XXZ_MSG_SESSION_KEY_FIELD.has_default_value = false
pb_table.XXZ_MSG_SESSION_KEY_FIELD.default_value = ""
pb_table.XXZ_MSG_SESSION_KEY_FIELD.type = 9
pb_table.XXZ_MSG_SESSION_KEY_FIELD.cpp_type = 9

pb_table.XXZ_MSG_FEED_BACK_FIELD.name = "feed_back"
pb_table.XXZ_MSG_FEED_BACK_FIELD.full_name = ".protocol.xxz_Msg.feed_back"
pb_table.XXZ_MSG_FEED_BACK_FIELD.number = 5
pb_table.XXZ_MSG_FEED_BACK_FIELD.index = 4
pb_table.XXZ_MSG_FEED_BACK_FIELD.label = 1
pb_table.XXZ_MSG_FEED_BACK_FIELD.has_default_value = false
pb_table.XXZ_MSG_FEED_BACK_FIELD.default_value = 0
pb_table.XXZ_MSG_FEED_BACK_FIELD.type = 5
pb_table.XXZ_MSG_FEED_BACK_FIELD.cpp_type = 1

pb_table.XXZ_MSG_TIME_STAMP_FIELD.name = "time_stamp"
pb_table.XXZ_MSG_TIME_STAMP_FIELD.full_name = ".protocol.xxz_Msg.time_stamp"
pb_table.XXZ_MSG_TIME_STAMP_FIELD.number = 6
pb_table.XXZ_MSG_TIME_STAMP_FIELD.index = 5
pb_table.XXZ_MSG_TIME_STAMP_FIELD.label = 1
pb_table.XXZ_MSG_TIME_STAMP_FIELD.has_default_value = false
pb_table.XXZ_MSG_TIME_STAMP_FIELD.default_value = 0
pb_table.XXZ_MSG_TIME_STAMP_FIELD.type = 3
pb_table.XXZ_MSG_TIME_STAMP_FIELD.cpp_type = 2

pb_table.XXZ_MSG_PLATFORM_FIELD.name = "platform"
pb_table.XXZ_MSG_PLATFORM_FIELD.full_name = ".protocol.xxz_Msg.platform"
pb_table.XXZ_MSG_PLATFORM_FIELD.number = 7
pb_table.XXZ_MSG_PLATFORM_FIELD.index = 6
pb_table.XXZ_MSG_PLATFORM_FIELD.label = 1
pb_table.XXZ_MSG_PLATFORM_FIELD.has_default_value = false
pb_table.XXZ_MSG_PLATFORM_FIELD.default_value = nil
pb_table.XXZ_MSG_PLATFORM_FIELD.enum_type = macro_pb.LOGINPLATFORM
pb_table.XXZ_MSG_PLATFORM_FIELD.type = 14
pb_table.XXZ_MSG_PLATFORM_FIELD.cpp_type = 8

pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.name = "client_debug_info"
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.full_name = ".protocol.xxz_Msg.client_debug_info"
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.number = 8
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.index = 7
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.label = 1
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.has_default_value = false
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.default_value = ""
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.type = 9
pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD.cpp_type = 9

pb_table.XXZ_MSG_RESULT_FIELD.name = "result"
pb_table.XXZ_MSG_RESULT_FIELD.full_name = ".protocol.xxz_Msg.result"
pb_table.XXZ_MSG_RESULT_FIELD.number = 9
pb_table.XXZ_MSG_RESULT_FIELD.index = 8
pb_table.XXZ_MSG_RESULT_FIELD.label = 1
pb_table.XXZ_MSG_RESULT_FIELD.has_default_value = false
pb_table.XXZ_MSG_RESULT_FIELD.default_value = 0
pb_table.XXZ_MSG_RESULT_FIELD.type = 5
pb_table.XXZ_MSG_RESULT_FIELD.cpp_type = 1

pb_table.XXZ_MSG_TYPE_FIELD.name = "type"
pb_table.XXZ_MSG_TYPE_FIELD.full_name = ".protocol.xxz_Msg.type"
pb_table.XXZ_MSG_TYPE_FIELD.number = 10
pb_table.XXZ_MSG_TYPE_FIELD.index = 9
pb_table.XXZ_MSG_TYPE_FIELD.label = 1
pb_table.XXZ_MSG_TYPE_FIELD.has_default_value = false
pb_table.XXZ_MSG_TYPE_FIELD.default_value = 0
pb_table.XXZ_MSG_TYPE_FIELD.type = 5
pb_table.XXZ_MSG_TYPE_FIELD.cpp_type = 1

pb_table.XXZ_MSG_SRC_ID_FIELD.name = "src_id"
pb_table.XXZ_MSG_SRC_ID_FIELD.full_name = ".protocol.xxz_Msg.src_id"
pb_table.XXZ_MSG_SRC_ID_FIELD.number = 11
pb_table.XXZ_MSG_SRC_ID_FIELD.index = 10
pb_table.XXZ_MSG_SRC_ID_FIELD.label = 1
pb_table.XXZ_MSG_SRC_ID_FIELD.has_default_value = false
pb_table.XXZ_MSG_SRC_ID_FIELD.default_value = 0
pb_table.XXZ_MSG_SRC_ID_FIELD.type = 5
pb_table.XXZ_MSG_SRC_ID_FIELD.cpp_type = 1

pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.name = "account_id"
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.full_name = ".protocol.xxz_Msg.account_id"
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.number = 12
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.index = 11
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.label = 1
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.has_default_value = false
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.default_value = 0
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.type = 5
pb_table.XXZ_MSG_ACCOUNT_ID_FIELD.cpp_type = 1

pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.name = "game_name_type"
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.full_name = ".protocol.xxz_Msg.game_name_type"
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.number = 16
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.index = 12
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.label = 1
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.has_default_value = false
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.default_value = 0
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.type = 13
pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD.cpp_type = 3

pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.name = "session_token"
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.full_name = ".protocol.xxz_Msg.session_token"
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.number = 14
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.index = 13
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.label = 1
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.has_default_value = false
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.default_value = 0
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.type = 13
pb_table.XXZ_MSG_SESSION_TOKEN_FIELD.cpp_type = 3

pb_table.XXZ_MSG_DEVICE_ID_FIELD.name = "device_id"
pb_table.XXZ_MSG_DEVICE_ID_FIELD.full_name = ".protocol.xxz_Msg.device_id"
pb_table.XXZ_MSG_DEVICE_ID_FIELD.number = 17
pb_table.XXZ_MSG_DEVICE_ID_FIELD.index = 14
pb_table.XXZ_MSG_DEVICE_ID_FIELD.label = 1
pb_table.XXZ_MSG_DEVICE_ID_FIELD.has_default_value = false
pb_table.XXZ_MSG_DEVICE_ID_FIELD.default_value = ""
pb_table.XXZ_MSG_DEVICE_ID_FIELD.type = 9
pb_table.XXZ_MSG_DEVICE_ID_FIELD.cpp_type = 9

pb_table.XXZ_MSG_BUFFER_FIELD.name = "buffer"
pb_table.XXZ_MSG_BUFFER_FIELD.full_name = ".protocol.xxz_Msg.buffer"
pb_table.XXZ_MSG_BUFFER_FIELD.number = 20
pb_table.XXZ_MSG_BUFFER_FIELD.index = 15
pb_table.XXZ_MSG_BUFFER_FIELD.label = 1
pb_table.XXZ_MSG_BUFFER_FIELD.has_default_value = false
pb_table.XXZ_MSG_BUFFER_FIELD.default_value = ""
pb_table.XXZ_MSG_BUFFER_FIELD.type = 12
pb_table.XXZ_MSG_BUFFER_FIELD.cpp_type = 9

pb_table.XXZ_MSG_WORLD_ID_FIELD.name = "world_id"
pb_table.XXZ_MSG_WORLD_ID_FIELD.full_name = ".protocol.xxz_Msg.world_id"
pb_table.XXZ_MSG_WORLD_ID_FIELD.number = 13
pb_table.XXZ_MSG_WORLD_ID_FIELD.index = 16
pb_table.XXZ_MSG_WORLD_ID_FIELD.label = 1
pb_table.XXZ_MSG_WORLD_ID_FIELD.has_default_value = false
pb_table.XXZ_MSG_WORLD_ID_FIELD.default_value = 0
pb_table.XXZ_MSG_WORLD_ID_FIELD.type = 13
pb_table.XXZ_MSG_WORLD_ID_FIELD.cpp_type = 3

pb_table.XXZ_MSG_GM_CMD_ID_FIELD.name = "gm_cmd_id"
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.full_name = ".protocol.xxz_Msg.gm_cmd_id"
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.number = 15
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.index = 17
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.label = 1
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.has_default_value = false
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.default_value = 0
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.type = 13
pb_table.XXZ_MSG_GM_CMD_ID_FIELD.cpp_type = 3

pb_table.XXZ_MSG_SRC_UIN_FIELD.name = "src_uin"
pb_table.XXZ_MSG_SRC_UIN_FIELD.full_name = ".protocol.xxz_Msg.src_uin"
pb_table.XXZ_MSG_SRC_UIN_FIELD.number = 21
pb_table.XXZ_MSG_SRC_UIN_FIELD.index = 18
pb_table.XXZ_MSG_SRC_UIN_FIELD.label = 1
pb_table.XXZ_MSG_SRC_UIN_FIELD.has_default_value = false
pb_table.XXZ_MSG_SRC_UIN_FIELD.default_value = 0
pb_table.XXZ_MSG_SRC_UIN_FIELD.type = 13
pb_table.XXZ_MSG_SRC_UIN_FIELD.cpp_type = 3

pb_table.XXZ_MSG_SRC_MSGID_FIELD.name = "src_msgid"
pb_table.XXZ_MSG_SRC_MSGID_FIELD.full_name = ".protocol.xxz_Msg.src_msgid"
pb_table.XXZ_MSG_SRC_MSGID_FIELD.number = 22
pb_table.XXZ_MSG_SRC_MSGID_FIELD.index = 19
pb_table.XXZ_MSG_SRC_MSGID_FIELD.label = 1
pb_table.XXZ_MSG_SRC_MSGID_FIELD.has_default_value = false
pb_table.XXZ_MSG_SRC_MSGID_FIELD.default_value = 0
pb_table.XXZ_MSG_SRC_MSGID_FIELD.type = 13
pb_table.XXZ_MSG_SRC_MSGID_FIELD.cpp_type = 3

pb_table.XXZ_MSG_SRC_WORLDID_FIELD.name = "src_worldid"
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.full_name = ".protocol.xxz_Msg.src_worldid"
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.number = 23
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.index = 20
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.label = 1
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.has_default_value = false
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.default_value = 0
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.type = 13
pb_table.XXZ_MSG_SRC_WORLDID_FIELD.cpp_type = 3

XXZ_MSG.name = "xxz_Msg"
XXZ_MSG.full_name = ".protocol.xxz_Msg"
XXZ_MSG.nested_types = {}
XXZ_MSG.enum_types = {}
XXZ_MSG.fields = {pb_table.XXZ_MSG_MSGID_FIELD, pb_table.XXZ_MSG_UIN_FIELD, pb_table.XXZ_MSG_ACCOUNT_FIELD, pb_table.XXZ_MSG_SESSION_KEY_FIELD, pb_table.XXZ_MSG_FEED_BACK_FIELD, pb_table.XXZ_MSG_TIME_STAMP_FIELD, pb_table.XXZ_MSG_PLATFORM_FIELD, pb_table.XXZ_MSG_CLIENT_DEBUG_INFO_FIELD, pb_table.XXZ_MSG_RESULT_FIELD, pb_table.XXZ_MSG_TYPE_FIELD, pb_table.XXZ_MSG_SRC_ID_FIELD, pb_table.XXZ_MSG_ACCOUNT_ID_FIELD, pb_table.XXZ_MSG_GAME_NAME_TYPE_FIELD, pb_table.XXZ_MSG_SESSION_TOKEN_FIELD, pb_table.XXZ_MSG_DEVICE_ID_FIELD, pb_table.XXZ_MSG_BUFFER_FIELD, pb_table.XXZ_MSG_WORLD_ID_FIELD, pb_table.XXZ_MSG_GM_CMD_ID_FIELD, pb_table.XXZ_MSG_SRC_UIN_FIELD, pb_table.XXZ_MSG_SRC_MSGID_FIELD, pb_table.XXZ_MSG_SRC_WORLDID_FIELD}
XXZ_MSG.is_extendable = false
XXZ_MSG.extensions = {}

xxz_Msg = protobuf.Message(XXZ_MSG)

