-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "tolua.protobuf/protobuf"
require("proto/pb_comm_pb")
local pb_comm_pb = pb_comm_pb
module('pb_1003_rank_pb')


M_RANK_LIST_TOS = protobuf.Descriptor();
M_RANK_LIST_TOS_ID_FIELD = protobuf.FieldDescriptor();
M_RANK_LIST_TOS_PAGE_FIELD = protobuf.FieldDescriptor();
M_RANK_LIST_TOC = protobuf.Descriptor();
M_RANK_LIST_TOC_ID_FIELD = protobuf.FieldDescriptor();
M_RANK_LIST_TOC_TOTAL_FIELD = protobuf.FieldDescriptor();
M_RANK_LIST_TOC_PAGE_FIELD = protobuf.FieldDescriptor();
M_RANK_LIST_TOC_LIST_FIELD = protobuf.FieldDescriptor();
M_RANK_LIST_TOC_MINE_FIELD = protobuf.FieldDescriptor();

M_RANK_LIST_TOS_ID_FIELD.name = "id"
M_RANK_LIST_TOS_ID_FIELD.full_name = ".m_rank_list_tos.id"
M_RANK_LIST_TOS_ID_FIELD.number = 1
M_RANK_LIST_TOS_ID_FIELD.index = 0
M_RANK_LIST_TOS_ID_FIELD.label = 2
M_RANK_LIST_TOS_ID_FIELD.has_default_value = false
M_RANK_LIST_TOS_ID_FIELD.default_value = 0
M_RANK_LIST_TOS_ID_FIELD.type = 5
M_RANK_LIST_TOS_ID_FIELD.cpp_type = 1

M_RANK_LIST_TOS_PAGE_FIELD.name = "page"
M_RANK_LIST_TOS_PAGE_FIELD.full_name = ".m_rank_list_tos.page"
M_RANK_LIST_TOS_PAGE_FIELD.number = 2
M_RANK_LIST_TOS_PAGE_FIELD.index = 1
M_RANK_LIST_TOS_PAGE_FIELD.label = 2
M_RANK_LIST_TOS_PAGE_FIELD.has_default_value = false
M_RANK_LIST_TOS_PAGE_FIELD.default_value = 0
M_RANK_LIST_TOS_PAGE_FIELD.type = 5
M_RANK_LIST_TOS_PAGE_FIELD.cpp_type = 1

M_RANK_LIST_TOS.name = "m_rank_list_tos"
M_RANK_LIST_TOS.full_name = ".m_rank_list_tos"
M_RANK_LIST_TOS.nested_types = {}
M_RANK_LIST_TOS.enum_types = {}
M_RANK_LIST_TOS.fields = {M_RANK_LIST_TOS_ID_FIELD, M_RANK_LIST_TOS_PAGE_FIELD}
M_RANK_LIST_TOS.is_extendable = false
M_RANK_LIST_TOS.extensions = {}
M_RANK_LIST_TOC_ID_FIELD.name = "id"
M_RANK_LIST_TOC_ID_FIELD.full_name = ".m_rank_list_toc.id"
M_RANK_LIST_TOC_ID_FIELD.number = 1
M_RANK_LIST_TOC_ID_FIELD.index = 0
M_RANK_LIST_TOC_ID_FIELD.label = 2
M_RANK_LIST_TOC_ID_FIELD.has_default_value = false
M_RANK_LIST_TOC_ID_FIELD.default_value = 0
M_RANK_LIST_TOC_ID_FIELD.type = 5
M_RANK_LIST_TOC_ID_FIELD.cpp_type = 1

M_RANK_LIST_TOC_TOTAL_FIELD.name = "total"
M_RANK_LIST_TOC_TOTAL_FIELD.full_name = ".m_rank_list_toc.total"
M_RANK_LIST_TOC_TOTAL_FIELD.number = 2
M_RANK_LIST_TOC_TOTAL_FIELD.index = 1
M_RANK_LIST_TOC_TOTAL_FIELD.label = 2
M_RANK_LIST_TOC_TOTAL_FIELD.has_default_value = false
M_RANK_LIST_TOC_TOTAL_FIELD.default_value = 0
M_RANK_LIST_TOC_TOTAL_FIELD.type = 5
M_RANK_LIST_TOC_TOTAL_FIELD.cpp_type = 1

M_RANK_LIST_TOC_PAGE_FIELD.name = "page"
M_RANK_LIST_TOC_PAGE_FIELD.full_name = ".m_rank_list_toc.page"
M_RANK_LIST_TOC_PAGE_FIELD.number = 3
M_RANK_LIST_TOC_PAGE_FIELD.index = 2
M_RANK_LIST_TOC_PAGE_FIELD.label = 2
M_RANK_LIST_TOC_PAGE_FIELD.has_default_value = false
M_RANK_LIST_TOC_PAGE_FIELD.default_value = 0
M_RANK_LIST_TOC_PAGE_FIELD.type = 5
M_RANK_LIST_TOC_PAGE_FIELD.cpp_type = 1

M_RANK_LIST_TOC_LIST_FIELD.name = "list"
M_RANK_LIST_TOC_LIST_FIELD.full_name = ".m_rank_list_toc.list"
M_RANK_LIST_TOC_LIST_FIELD.number = 4
M_RANK_LIST_TOC_LIST_FIELD.index = 3
M_RANK_LIST_TOC_LIST_FIELD.label = 3
M_RANK_LIST_TOC_LIST_FIELD.has_default_value = false
M_RANK_LIST_TOC_LIST_FIELD.default_value = {}
M_RANK_LIST_TOC_LIST_FIELD.message_type = pb_comm_pb.P_RANKING
M_RANK_LIST_TOC_LIST_FIELD.type = 11
M_RANK_LIST_TOC_LIST_FIELD.cpp_type = 10

M_RANK_LIST_TOC_MINE_FIELD.name = "mine"
M_RANK_LIST_TOC_MINE_FIELD.full_name = ".m_rank_list_toc.mine"
M_RANK_LIST_TOC_MINE_FIELD.number = 5
M_RANK_LIST_TOC_MINE_FIELD.index = 4
M_RANK_LIST_TOC_MINE_FIELD.label = 2
M_RANK_LIST_TOC_MINE_FIELD.has_default_value = false
M_RANK_LIST_TOC_MINE_FIELD.default_value = nil
M_RANK_LIST_TOC_MINE_FIELD.message_type = pb_comm_pb.P_RANKING
M_RANK_LIST_TOC_MINE_FIELD.type = 11
M_RANK_LIST_TOC_MINE_FIELD.cpp_type = 10

M_RANK_LIST_TOC.name = "m_rank_list_toc"
M_RANK_LIST_TOC.full_name = ".m_rank_list_toc"
M_RANK_LIST_TOC.nested_types = {}
M_RANK_LIST_TOC.enum_types = {}
M_RANK_LIST_TOC.fields = {M_RANK_LIST_TOC_ID_FIELD, M_RANK_LIST_TOC_TOTAL_FIELD, M_RANK_LIST_TOC_PAGE_FIELD, M_RANK_LIST_TOC_LIST_FIELD, M_RANK_LIST_TOC_MINE_FIELD}
M_RANK_LIST_TOC.is_extendable = false
M_RANK_LIST_TOC.extensions = {}

m_rank_list_toc = protobuf.Message(M_RANK_LIST_TOC)
m_rank_list_tos = protobuf.Message(M_RANK_LIST_TOS)

