StrConfig:Add(
{
	['role1'] = '等级不足%s',
	['role2'] = '经验不足',
	['role3'] = '将所有的潜能点分配在此属性上',
	['role4'] = '分配1点潜能点',
	['role5'] = '取消1点刚才分配的潜能点',
	['role6'] = '取消所有刚才分配在此属性的潜能点',
	['role7'] = '保存分配的潜能点，保存后不可变更',
	['role8'] = '按系统推荐方式分配所有潜能点',
	['role9'] = '手动分配所有的潜能点',
	['role10'] = '每次升级时自动按系统推荐方式分配潜能点',
	['role11'] = '',
	['role12'] = '经验不足，无法升级',
	['role13'] = '分配成功',
	['role14'] = '当前经验不足以升级',
	['role15'] = '玩家下线或者不在同一条线，无法查看信息',
	['role16'] = '该玩家没有激活灵兽',
	['role17'] = "<font color='%s' size='16'>%s</font><font color='#29cc00'>(%s重)</font><br/><p><img height='3'/></p><p><img width='200' height='2' align='baseline' vspace='5' src='%s'/></br></p><font color='#d1c0a5' size='14'>技能效果:</font><br/><font color='#ff8f43' size='14'>%s</font>",
	['role18'] = [[当前经验：%s/%s

当前经验已满，可将当前经验用于升级或者提升境界。
]],
	['role19'] = '升  级',
	['role20'] = '提升境界',
	['role21'] = '您已到达等级上限',

	-- 属性tips
	['role101'] = "<font color='#dcdcdc'>生命为0时，角色将死亡，死亡后可选择原点复活或回城复活</font>",
	['role102'] = "<font color='#dcdcdc'>内力可用于技能消耗，当内力不足时，无法释放技能</font>",
	['role103'] = "<font color='#dcdcdc'>攻击力数值大小影响您在打怪或PK时造成的伤害大小</font>",
	['role104'] = "<font color='#dcdcdc'>防御数值影响您在受到怪物或其他玩家攻击时受到的伤害大小</font>",
	['role105'] = "<font color='#dcdcdc'>命中值的大小影响您在打怪或PK时，击中目标的几率</font>",
	['role106'] = "<font color='#dcdcdc'>闪避值的大小影响您躲避攻击的几率</font>",
	['role107'] = "<font color='#dcdcdc'>暴击值的大小影响您在打怪或PK时造成多倍伤害的几率</font>",
	['role108'] = "<font color='#dcdcdc'>韧性值的大小影响您受到暴击的几率</font>",
	['role109'] = "<font color='#dcdcdc'>爆伤值的大小影响您在暴击时，造成伤害的倍率</font>",
	['role110'] = "<font color='#dcdcdc'>免爆值的大小影响您在受到暴击时，减免对面的暴击伤害的倍率</font>",
	['role111'] = "<font color='#dcdcdc'>穿刺值的大小影响您在攻击时造成无视防御伤害值的大小</font>",
	['role112'] = "<font color='#dcdcdc'>格挡率的大小影响您在受到伤害时格挡掉部分伤害的几率</font>",
	['role113'] = "<font color='#dcdcdc'>格挡值的大小影响您在受到伤害时减免掉伤害的大小</font>",
	['role114'] = "<font color='#dcdcdc'>伤害增强值的大小影响您在造成伤害时额外提高的百分比</font>",
	['role115'] = "<font color='#dcdcdc'>伤害减免值的大小影响您在受到伤害时减免掉伤害的百分比</font>",
	['role116'] = "<font color='#dcdcdc'>魂力值可以提高您的攻击力</font>",
	['role117'] = "<font color='#dcdcdc'>体魄值可以提高您的生命和防御</font>",
	['role118'] = "<font color='#dcdcdc'>身法值可以提高您的命中和闪避</font>",
	['role119'] = "<font color='#dcdcdc'>精神值可以提高您的暴击和韧性</font>",
	['role120'] = "<font color='#dcdcdc'>攻击速度影响您两次攻击的间隔</font>",
	['role121'] = "<font color='#dcdcdc'>移动速度影响您在地图上的移动速度</font>",
	['role122'] = "<font color='#dcdcdc'>角色前%s级自动升级 <br/>%s级后需手动升级</font>",
	['role123'] = "<font color='#dcdcdc'>影响卓越一击每次判定时，能否造成卓越一击的几率，判定次数等于当前身上卓越装备的数目</font>",
	['role124'] = "<font color='#dcdcdc'>影响造成卓越一击时伤害的大小</font>",
	['role125'] = "<font color='#dcdcdc'>影响攻击时忽视目标防御的大小</font>",
	['role126'] = "<font color='#dcdcdc'>您有潜能点可分配<br/>分配潜能可使您更强大</font>",
	['role127'] = "<font color='#dcdcdc'>恶意杀人将增加PK值<br/>PK值每30分钟自动消除1点。</font>",
	['role128'] = "<font color='#dcdcdc'>竞技场荣誉，可在竞技场商店内兑换道具。</font>",
	['role129'] = "<font color='#dcdcdc'>影响神武技能触发几率及自身抵抗其他玩家神武技能的几率。</font>",

	['role200'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'>规则提示:</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/>通过杀怪和杀BOSS获取
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/>在背包内使用道具增加对应属性，不同品级道具增加的属性值不同
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/>不同等阶丹药每天可服用上限不同
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/>累计使用次数达到上限后将无法再使用该类道具<img height='10'/></textformat>]],

	['role251'] = "物品数量不足",
	-- 详细信息
	['role301'] = "无",
	['role302'] = "基础属性",
	['role303'] = "战斗属性",
	
	-- 丹药
	['role401'] = "进度: %s%%",
	['role402'] = "攻击 <font color='#E7D6B5'>+%s</font>",
	['role403'] = "防御 <font color='#E7D6B5'>+%s</font>",
	['role404'] = "生命上限<font color='#E7D6B5'>+%s</font>",
	['role406'] = "体质 <font color='#E7D6B5'>+%s</font>",    --changer：houxudong   range：role406 ---role409
	['role407'] = "身法 <font color='#E7D6B5'>+%s</font>",
	['role408'] = "力量 <font color='#E7D6B5'>+%s</font>",
	['role409'] = "精神 <font color='#E7D6B5'>+%s</font>",
	['role405'] = "(%s/%s)",
	
	['role419'] = '<font color= "#00ff00">使用成功</font>',
	['role420'] = '没有可使用的丹药！',
	['role421'] = '只有VIP才可使用',
	['role422'] = '自动使用背包内可用普通丹药',
	['role423'] = '自动使用背包内可用至尊丹药',
	['role424'] = "<font color='#ffcc33' size='16'>丹药</font><br/><font color='#dcdcdc'>使用丹药增加人物属性</font><br/><font color='#e59607' size='16'>丹药附加属性</font><br/><font color='#00ff00'><font color ='#d5b772'>攻击</font>  +%s  <font color ='#d5b772'>防御</font>  +%s  <font color ='#d5b772'>生命</font>  +%s</font><p><img height='3'/><p><img width='210' height='1' align='baseline' vspace='3' src='img://resfile/icon/tipsLine.png'/></p><font color='#00ff00'>点击此按钮打开【丹药】界面</font>",
	['role425'] = "翅膀",
	['role426'] = "暂未开启",
	['role427'] = "暂无卓越套装属性",
	['role428'] = "<textformat leading='-84'><p>%s件效果：</p></textformat>",
	['role429'] = "无配偶",
	-- 融合相关   changer :houxudong 
	['role430'] = "装备类型不匹配，请重新选择！",
	['role431'] = "XXX道具不足，无法融合！",
	['role432'] = "银两不足，无法融合！",
	['role433'] = "恭喜您，融合成功！",
	['role434'] = "融合失败！",  
	['role435'] = "阶数不同！",
	['role436'] = "装备位不同！",
	['role437'] = "至少有一件不是二卓越装备！",
	['role438'] = "材料不够!",
	['role439'] = "该装备不能融合!",
	['role440'] = "请联系GM!",
	['role441'] = "请选择装备!",
	['role442'] = "<font color='#2aaefa'>%s</font>",
	['role443'] = "<font color='#cc00ff'>%s</font>",
	['role444'] = "<font color='#fff000'>%s</font>",
	['role445'] = '佛珠',
	['role446'] = '护符',
	['role447'] = '玄兵',
} 	
);