module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,},func_name=[[Name]],start_time=0,},
		[2]={
			args={sound_path=[[Magic/sound_magic_51102_1.wav]],sound_rate=1,},
			func_name=[[PlaySound]],
			start_time=0,
		},
		[3]={
			args={action_name=[[attack2]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.1,
		},
		[4]={
			args={
				alive_time=4,
				bind_idx=102,
				bind_type=[[node]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_att_prop.prefab]],
					preload=true,
				},
				excutor=[[atkobj]],
				height=0,
			},
			func_name=[[BodyEffect]],
			start_time=0.1,
		},
		[5]={
			args={
				alive_time=4,
				bind_idx=101,
				bind_type=[[node]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_att_prop.prefab]],
					preload=true,
				},
				excutor=[[atkobj]],
				height=0,
			},
			func_name=[[BodyEffect]],
			start_time=0.1,
		},
		[6]={args={},func_name=[[MagcAnimStart]],start_time=0.38,},
		[7]={args={},func_name=[[MagcAnimEnd]],start_time=1.05,},
		[8]={
			args={
				alive_time=4,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_att2.prefab]],
					preload=true,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.35,
		},
		[9]={
			args={
				alive_time=3,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_hit.prefab]],
					preload=true,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=3,
		},
		[10]={
			args={action_name=[[hit1]],excutor=[[vicobjs]],},
			func_name=[[PlayAction]],
			start_time=3.5,
		},
		[11]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=false,
			},
			func_name=[[VicHitInfo]],
			start_time=3.7,
		},
		[12]={
			args={action_name=[[hit1]],excutor=[[vicobjs]],},
			func_name=[[PlayAction]],
			start_time=3.8,
		},
		[13]={
			args={action_name=[[hit1]],excutor=[[vicobjs]],},
			func_name=[[PlayAction]],
			start_time=4.1,
		},
		[14]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
			},
			func_name=[[VicHitInfo]],
			start_time=4.5,
		},
		[15]={args={},func_name=[[End]],start_time=5,},
	},
	group_cmds={},
	magic_anim_end_time=1.05,
	magic_anim_start_time=0.38,
	pre_load_res={
		[1]=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_att_prop.prefab]],
		[2]=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_att_prop.prefab]],
		[3]=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_att2.prefab]],
		[4]=[[Effect/Magic/magic_eff_511/Prefabs/magic_eff_51102_hit.prefab]],
	},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
