module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={
			args={
				alive_time=2.5,
				effect={
					is_cached=false,
					magic_layer=[[top]],
					path=[[Effect/Magic/magic_eff_505/Prefabs/magic_eff_50502_hit01.prefab]],
					preload=true,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=-0.2,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=0,
		},
		[2]={
			args={action_name=[[attack2]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0,
		},
		[3]={args={alive_time=0.5,},func_name=[[Name]],start_time=0,},
		[4]={
			args={sound_path=[[Magic/sound_magic_50502_1.wav]],sound_rate=1,},
			func_name=[[PlaySound]],
			start_time=0,
		},
		[5]={args={},func_name=[[End]],start_time=0.1,},
		[6]={
			args={
				alive_time=2,
				bind_type=[[pos]],
				body_pos=[[foot]],
				effect={
					is_cached=true,
					magic_layer=[[top]],
					path=[[Effect/Magic/magic_eff_505/Prefabs/magic_eff_50501_hit02.prefab]],
					preload=true,
				},
				excutor=[[vicobjs]],
				height=0,
			},
			func_name=[[BodyEffect]],
			start_time=1.3,
		},
		[7]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=false,
				hurt_delta=0,
				play_anim=true,
			},
			func_name=[[VicHitInfo]],
			start_time=1.3,
		},
		[8]={
			args={shake_dis=0.035,shake_rate=20,shake_time=0.2,},
			func_name=[[ShakeScreen]],
			start_time=1.35,
		},
	},
	group_cmds={},
	pre_load_res={
		[1]=[[Effect/Magic/magic_eff_505/Prefabs/magic_eff_50502_hit01.prefab]],
		[2]=[[Effect/Magic/magic_eff_505/Prefabs/magic_eff_50501_hit02.prefab]],
	},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
