local t = 
{
	version = 1,
	components = 
	{
		
		{
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_Content",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "430",
							ignoreSize = "False",
							name = "img_di",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/bg_h.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
							},
							width = "600",
							ZOrder = "1",
							components = 
							{
								
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "68",
									ignoreSize = "False",
									name = "img_tiao",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/common/bg_biaoti2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 185,
									},
									width = "607",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "74",
									HitType = 
									{
										nHitType = 2,
										nRadius = 100,
									},
									ignoreSize = "True",
									name = "btn_close",
									normal = "ui_new/common/common_close2_icon.png",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 268,
										PositionY = 184,
										LeftPositon = 240,
										TopPosition = 382,
										relativeToName = "Panel",
									},
									UItype = "Button",
									width = "72",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "61",
									ignoreSize = "True",
									name = "img_wenben",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/bloodybattle/xz_guizeshuoming.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 187,
										LeftPositon = -97,
										TopPosition = 388,
										relativeToName = "Panel",
									},
									width = "194",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "进行对战，使用进攻布阵挑战对方的防守布阵",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -238,
										PositionY = 56,
										LeftPositon = -233,
										TopPosition = 480,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "每次进攻胜利和防守胜利都能获得积分，连胜越高积分越高",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -238,
										PositionY = 24,
										LeftPositon = -233,
										TopPosition = 523,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "开赛前15分钟，你可以设置进攻阵容和防守阵容",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -238,
										PositionY = 122,
										LeftPositon = -233,
										TopPosition = 581,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = 47,
										LeftPositon = -253,
										TopPosition = 482,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = 15,
										LeftPositon = -253,
										TopPosition = 524,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = 113,
										LeftPositon = -253,
										TopPosition = 583,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "积分赛奖励在当天22:00以邮件形式进行发放",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -239,
										PositionY = -84,
										LeftPositon = -233,
										TopPosition = 640,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = -94,
										LeftPositon = -253,
										TopPosition = 641,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "积分赛前八名选手可进入次日的争霸赛(争霸赛暂未开启)",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -239,
										PositionY = -119,
										LeftPositon = -233,
										TopPosition = 694,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = -128,
										LeftPositon = -253,
										TopPosition = 696,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben6",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "如果未设置则系统会默认选用你当前阵容",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -238,
										PositionY = 89,
										LeftPositon = -233,
										TopPosition = 694,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian6",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = 80,
										LeftPositon = -253,
										TopPosition = 696,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "METextArea",
									ColorMixing = "#FF000000",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									hAlignment = "0",
									height = "60",
									ignoreSize = "False",
									name = "txt_wenben7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "积分赛结束后将会根据积分排名给予奖励，积分越高奖励越高",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -238,
										PositionY = -33,
										LeftPositon = -233,
										TopPosition = 640,
										relativeToName = "Panel",
									},
									vAlignment = "0",
									width = "500",
									ZOrder = "1",
								},
								{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "15",
									ignoreSize = "True",
									name = "img_dian7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_dian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -250,
										PositionY = -44,
										LeftPositon = -253,
										TopPosition = 641,
										relativeToName = "Panel",
									},
									width = "15",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/common/bg_h.png",
			"ui_new/common/bg_biaoti2.png",
			"ui_new/common/common_close2_icon.png",
			"ui_new/bloodybattle/xz_guizeshuoming.png",
			"ui_new/pay/VIP_dian.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

