-- --------------------------------------------------------------------
-- 这里填写简要说明(必填),
-- @author: lwc@syg.com(必填, 创建模块的人员)
-- @editor: xxx@syg.com(必填, 后续维护以及修改的人员)
-- @description:
--      组队竞技场 后端 锋林 策划 康杰
-- <br/>Create: 2019-09-28
-- --------------------------------------------------------------------
ArenateamEvent = ArenateamEvent or {}

--组队竞技场主界面
ArenateamEvent.ARENATEAM_MAIN_EVENT = "ARENATEAM_MAIN_EVENT"
--主界面排行榜
ArenateamEvent.ARENATEAM_MAIN_RANK_EVENT = "ARENATEAM_MAIN_RANK_EVENT"
--组队大厅 组队信息
ArenateamEvent.ARENATEAM_HALL_MAIN_EVENT = "ARENATEAM_HALL_MAIN_EVENT"

--组队邀请列表
ArenateamEvent.ARENATEAM_INVITATION_LIST_EVENT = "ARENATEAM_INVITATION_LIST_EVENT"

--我的队伍信息
ArenateamEvent.ARENATEAM_MY_TEAM_INFO_EVENT = "ARENATEAM_MY_TEAM_INFO_EVENT"

--申请列表
ArenateamEvent.ARENATEAM_APPLY_LIST_EVENT = "ARENATEAM_APPLY_LIST_EVENT"
--申请入队
ArenateamEvent.ARENATEAM_APPLY_TEAM_EVENT = "ARENATEAM_APPLY_TEAM_EVENT"

--邀请玩家
ArenateamEvent.ARENATEAM_INVITATION_PLAYER_EVENT = "ARENATEAM_INVITATION_PLAYER_EVENT"
--回应玩家申请
ArenateamEvent.ARENATEAM_ANSWER_APPLY_EVENT = "ARENATEAM_ANSWER_APPLY_EVENT"
--回应玩家邀请
ArenateamEvent.ARENATEAM_ANSWER_INVITATION_EVENT = "ARENATEAM_ANSWER_INVITATION_EVENT"
--一键清除邀请信息
ArenateamEvent.ARENATEAM_KEY_CLEAR_EVENT = "ARENATEAM_KEY_CLEAR_EVENT"

--搜索队伍名字
ArenateamEvent.ARENATEAM_SEARCH_TEAM_EVENT  = "ARENATEAM_SEARCH_TEAM_EVENT"

--获取推荐玩家
ArenateamEvent.ARENATEAM_GET_RECOMMEND_INFO_EVENT  = "ARENATEAM_GET_RECOMMEND_INFO_EVENT"
--搜索玩家
ArenateamEvent.ARENATEAM_SEARCH_PLAYER_EVENT  = "ARENATEAM_SEARCH_PLAYER_EVENT"

--改名
ArenateamEvent.ARENATEAM_CHANGE_NAME_EVENT = "ARENATEAM_CHANGE_NAME_EVENT"
--修改队伍设置
ArenateamEvent.ARENATEAM_TEAM_SET_EVENT = "ARENATEAM_TEAM_SET_EVENT"

--名字修改返回
ArenateamEvent.ARENATEAM_CHANGE_NAME_CALLBACK = "ARENATEAM_CHANGE_NAME_CALLBACK"
--队伍设置修改返回
ArenateamEvent.ARENATEAM_TEAM_SET_CALLBACK = "ARENATEAM_TEAM_SET_CALLBACK"

--报名参赛
ArenateamEvent.ARENATEAM_JOIN_GAME_EVENT = "ARENATEAM_JOIN_GAME_EVENT"
--取消报名
ArenateamEvent.ARENATEAM_LEAVE_GAME_EVENT = "ARENATEAM_LEAVE_GAME_EVENT"

--匹配对手
ArenateamEvent.ARENATEAM_MATCH_OTHER_EVENT = "ARENATEAM_MATCH_OTHER_EVENT"

--阵营保存返回
ArenateamEvent.ARENATEAM_SAVE_FROM_EVENT = "ARENATEAM_SAVE_FROM_EVENT"
--获取阵容信息
ArenateamEvent.ARENATEAM_THREE_TEAM_INFO_EVENT = "ARENATEAM_THREE_TEAM_INFO_EVENT"

--是否刷新队伍信息
ArenateamEvent.ARENATEAM_REFRESH_TEAM_INFO_EVENT = "ARENATEAM_REFRESH_TEAM_INFO_EVENT"

--领取宝箱
ArenateamEvent.ARENATEAM_RECEIVE_BOX_EVENT = "ARENATEAM_RECEIVE_BOX_EVENT"

--红点
ArenateamEvent.ARENATEAM_ALL_RED_POINT_EVENT = "ARENATEAM_ALL_RED_POINT_EVENT"
--申请红点事件
ArenateamEvent.ARENATEAM_APPLY_RED_POINT_EVENT = "ARENATEAM_APPLY_RED_POINT_EVENT"
--邀请的红点
ArenateamEvent.ARENATEAM_INVITATION_RED_POINT_EVENT = "ARENATEAM_INVITATION_RED_POINT_EVENT"

--战报
ArenateamEvent.ARENATEAM_MIAIN_REPORT_EVENT = "ARENATEAM_MIAIN_REPORT_EVENT"
--个人战报
ArenateamEvent.ARENATEAM_SINGLE_REPORT_EVENT = "ARENATEAM_SINGLE_REPORT_EVENT"


ArenateamEvent.ARENATEAM_TIMER_EVENT = "ARENATEAM_TIMER_EVENT"

--是否在线
ArenateamEvent.ARENATEAM_ONLINE_EVENT = "ARENATEAM_ONLINE_EVENT"

--一键申请队伍
ArenateamEvent.ARENATEAM_KEY_APPLY_TEAM_EVENT = "ARENATEAM_KEY_APPLY_TEAM_EVENT"

