--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2019/12/18 20:02

ChildActBoxPanel = ChildActBoxPanel or class("ChildActBoxPanel", SevenDayPetBoxPanel)
local ChildActBoxPanel = ChildActBoxPanel

function ChildActBoxPanel:ctor(parent_node, actID)

end


function ChildActBoxPanel:AddEvent()

    ChildActBoxPanel.super.AddEvent(self)
end


