--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2019/12/28 11:07
ChildActExchangePanel = ChildActExchangePanel or class("ChildActExchangePanel", GodCeleExchangeView)
local ChildActExchangePanel = ChildActExchangePanel


function ChildActExchangePanel:ctor(parent_node, parent_panel, actID, asset)

end

function ChildActExchangePanel:AddEvent()
    local function callback()
        OpenLink(160, 1, 1, 2, 1, "true")
        GlobalEvent:Brocast(GodCeleEvent.CloseGodCelePanel)
    end
    AddButtonEvent(self.btn_plus.gameObject, callback)

    local function callback(data)
        if data.act_id ~= self.actID then
            return
        end
        self:UpdateNum()
    end
    self.success_exchange_event_id = GlobalEvent:AddListener(OperateEvent.SUCCESS_GET_REWARD, callback)

    local function callback()
        ShowHelpTip(HelpConfig.GodCelebration.ChildActDesc, true)
    end
    AddButtonEvent(self.ques.gameObject, callback)
end