_G.t_packetcost={
	[1]={
		['id'] = 1,
		['autoTime'] = 30,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[2]={
		['id'] = 2,
		['autoTime'] = 20,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[3]={
		['id'] = 3,
		['autoTime'] = 25,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[4]={
		['id'] = 4,
		['autoTime'] = 30,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[5]={
		['id'] = 5,
		['autoTime'] = 35,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[6]={
		['id'] = 6,
		['autoTime'] = 40,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[7]={
		['id'] = 7,
		['autoTime'] = 45,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[8]={
		['id'] = 8,
		['autoTime'] = 50,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[9]={
		['id'] = 9,
		['autoTime'] = 55,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[10]={
		['id'] = 10,
		['autoTime'] = 60,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[11]={
		['id'] = 11,
		['autoTime'] = 65,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[12]={
		['id'] = 12,
		['autoTime'] = 70,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[13]={
		['id'] = 13,
		['autoTime'] = 75,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[14]={
		['id'] = 14,
		['autoTime'] = 80,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[15]={
		['id'] = 15,
		['autoTime'] = 85,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[16]={
		['id'] = 16,
		['autoTime'] = 90,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[17]={
		['id'] = 17,
		['autoTime'] = 100,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[18]={
		['id'] = 18,
		['autoTime'] = 110,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[19]={
		['id'] = 19,
		['autoTime'] = 120,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[20]={
		['id'] = 20,
		['autoTime'] = 130,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[21]={
		['id'] = 21,
		['autoTime'] = 140,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[22]={
		['id'] = 22,
		['autoTime'] = 150,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[23]={
		['id'] = 23,
		['autoTime'] = 160,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[24]={
		['id'] = 24,
		['autoTime'] = 170,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[25]={
		['id'] = 25,
		['autoTime'] = 180,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[26]={
		['id'] = 26,
		['autoTime'] = 190,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[27]={
		['id'] = 27,
		['autoTime'] = 200,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[28]={
		['id'] = 28,
		['autoTime'] = 210,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[29]={
		['id'] = 29,
		['autoTime'] = 220,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[30]={
		['id'] = 30,
		['autoTime'] = 230,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[31]={
		['id'] = 31,
		['autoTime'] = 240,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[32]={
		['id'] = 32,
		['autoTime'] = 250,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[33]={
		['id'] = 33,
		['autoTime'] = 260,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[34]={
		['id'] = 34,
		['autoTime'] = 270,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[35]={
		['id'] = 35,
		['autoTime'] = 280,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[36]={
		['id'] = 36,
		['autoTime'] = 290,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[37]={
		['id'] = 37,
		['autoTime'] = 300,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[38]={
		['id'] = 38,
		['autoTime'] = 310,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[39]={
		['id'] = 39,
		['autoTime'] = 320,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[40]={
		['id'] = 40,
		['autoTime'] = 330,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[41]={
		['id'] = 41,
		['autoTime'] = 340,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[42]={
		['id'] = 42,
		['autoTime'] = 350,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[43]={
		['id'] = 43,
		['autoTime'] = 360,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[44]={
		['id'] = 44,
		['autoTime'] = 370,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[45]={
		['id'] = 45,
		['autoTime'] = 380,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[46]={
		['id'] = 46,
		['autoTime'] = 390,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[47]={
		['id'] = 47,
		['autoTime'] = 400,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[48]={
		['id'] = 48,
		['autoTime'] = 410,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[49]={
		['id'] = 49,
		['autoTime'] = 420,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[50]={
		['id'] = 50,
		['autoTime'] = 430,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[51]={
		['id'] = 51,
		['autoTime'] = 440,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[52]={
		['id'] = 52,
		['autoTime'] = 450,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[53]={
		['id'] = 53,
		['autoTime'] = 460,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[54]={
		['id'] = 54,
		['autoTime'] = 470,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[55]={
		['id'] = 55,
		['autoTime'] = 480,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[56]={
		['id'] = 56,
		['autoTime'] = 490,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[57]={
		['id'] = 57,
		['autoTime'] = 500,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[58]={
		['id'] = 58,
		['autoTime'] = 510,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[59]={
		['id'] = 59,
		['autoTime'] = 520,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[60]={
		['id'] = 60,
		['autoTime'] = 530,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[61]={
		['id'] = 61,
		['autoTime'] = 540,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[62]={
		['id'] = 62,
		['autoTime'] = 550,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[63]={
		['id'] = 63,
		['autoTime'] = 560,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[64]={
		['id'] = 64,
		['autoTime'] = 570,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[65]={
		['id'] = 65,
		['autoTime'] = 580,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[66]={
		['id'] = 66,
		['autoTime'] = 590,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[67]={
		['id'] = 67,
		['autoTime'] = 600,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[68]={
		['id'] = 68,
		['autoTime'] = 610,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[69]={
		['id'] = 69,
		['autoTime'] = 620,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[70]={
		['id'] = 70,
		['autoTime'] = 630,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[71]={
		['id'] = 71,
		['autoTime'] = 640,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[72]={
		['id'] = 72,
		['autoTime'] = 650,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[73]={
		['id'] = 73,
		['autoTime'] = 660,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[74]={
		['id'] = 74,
		['autoTime'] = 670,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[75]={
		['id'] = 75,
		['autoTime'] = 680,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[76]={
		['id'] = 76,
		['autoTime'] = 690,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[77]={
		['id'] = 77,
		['autoTime'] = 700,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[78]={
		['id'] = 78,
		['autoTime'] = 710,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[79]={
		['id'] = 79,
		['autoTime'] = 720,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[80]={
		['id'] = 80,
		['autoTime'] = 730,
		['itemNum'] = 1,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[81]={
		['id'] = 81,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[82]={
		['id'] = 82,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[83]={
		['id'] = 83,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[84]={
		['id'] = 84,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[85]={
		['id'] = 85,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[86]={
		['id'] = 86,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[87]={
		['id'] = 87,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[88]={
		['id'] = 88,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[89]={
		['id'] = 89,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[90]={
		['id'] = 90,
		['autoTime'] = -2,
		['itemNum'] = 5,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[91]={
		['id'] = 91,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[92]={
		['id'] = 92,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[93]={
		['id'] = 93,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[94]={
		['id'] = 94,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[95]={
		['id'] = 95,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[96]={
		['id'] = 96,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[97]={
		['id'] = 97,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[98]={
		['id'] = 98,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[99]={
		['id'] = 99,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[100]={
		['id'] = 100,
		['autoTime'] = -2,
		['itemNum'] = 10,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[101]={
		['id'] = 101,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[102]={
		['id'] = 102,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[103]={
		['id'] = 103,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[104]={
		['id'] = 104,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[105]={
		['id'] = 105,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[106]={
		['id'] = 106,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[107]={
		['id'] = 107,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[108]={
		['id'] = 108,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[109]={
		['id'] = 109,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[110]={
		['id'] = 110,
		['autoTime'] = -2,
		['itemNum'] = 20,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[111]={
		['id'] = 111,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[112]={
		['id'] = 112,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[113]={
		['id'] = 113,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[114]={
		['id'] = 114,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[115]={
		['id'] = 115,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[116]={
		['id'] = 116,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[117]={
		['id'] = 117,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[118]={
		['id'] = 118,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[119]={
		['id'] = 119,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
	[120]={
		['id'] = 120,
		['autoTime'] = -2,
		['itemNum'] = 40,
		['addMaxHp'] = 30,
		['addExp'] = 0,
	},
};