_G.t_questChapter={
	[1]={
		['id'] = 1,
		['index'] = 1,
		['name'] = "云海往事",
		['des'] = "云破天开越虚空。<br/>海涛拍岸斗恶灵。<br/>往生英魄今何在？<br/>事了拂衣藏功名。",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,20",
	},
	[2]={
		['id'] = 2,
		['index'] = 2,
		['name'] = "迷城风云",
		['des'] = "迷雾朦胧掩行踪。<br/>城残壁断藏冷锋。<br/>风雨满楼混不畏！<br/>云没烟消万事空。",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,21",
	},
	[3]={
		['id'] = 3,
		['index'] = 3,
		['name'] = "血染秘境",
		['des'] = "血海深仇终得报。<br/>染鬓微霜恨难消！<br/>秘术怎得通天地。<br/>境寂心宁自逍遥。",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,22",
	},
	[4]={
		['id'] = 4,
		['index'] = 4,
		['name'] = "纵横荒海",
		['des'] = "我是一只鱼u",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,23",
	},
	[5]={
		['id'] = 5,
		['index'] = 5,
		['name'] = "山穷水尽",
		['des'] = "我是一只鱼u",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,24",
	},
	[6]={
		['id'] = 6,
		['index'] = 6,
		['name'] = "柳暗花明",
		['des'] = "我是一只鱼u",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,25",
	},
	[7]={
		['id'] = 7,
		['index'] = 7,
		['name'] = "妖夜悲歌",
		['des'] = "我是一只鱼u",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,26",
	},
	[8]={
		['id'] = 8,
		['index'] = 8,
		['name'] = "魔沼巨妖",
		['des'] = "我是一只鱼u",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,27",
	},
	[9]={
		['id'] = 9,
		['index'] = 9,
		['name'] = "神木之辉",
		['des'] = "我是一只鱼u",
		['icon'] = "chapter_i1",
		['titleImg'] = "chapter_t1",
		['reward'] = "att,100#def,28",
	},
};