_G.t_trap={
	[1101]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1102]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1103]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1104]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1105]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1106]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1107]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1108]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1109]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1110]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1111]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1112]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1113]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1114]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1115]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1116]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1117]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1118]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1119]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1120]={
		['caster'] = "v_juexue_liehuoliaoyuan.pfx",
		['model'] = "v_juexue_liehuoliaoyuan.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1701]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1702]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1703]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1704]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1705]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1706]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1707]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1708]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1709]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1710]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1711]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1712]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1713]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1714]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1715]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1716]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1717]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1718]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1719]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1720]={
		['caster'] = "v_juexue_hanbingzhijie.pfx",
		['model'] = "v_juexue_hanbingzhijie.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1901]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1902]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1903]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1904]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1905]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1906]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1907]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1908]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1909]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1910]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1911]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1912]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1913]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1914]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1915]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1916]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1917]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1918]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1919]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[1920]={
		['caster'] = "v_juexue_xuanguanglanhuo.pfx",
		['model'] = "v_juexue_xuanguanglanhuo.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7001]={
		['caster'] = "lz_mihunzhen_sf.pfx",
		['model'] = "lz_mihunzhen_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7002]={
		['caster'] = "lz_flptz_sf.pfx",
		['model'] = "lz_flptz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7003]={
		['caster'] = "lz_xqjz_sf.pfx",
		['model'] = "lz_xqjz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7004]={
		['caster'] = "lz_jtl_sf.pfx",
		['model'] = "lz_jtl_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7005]={
		['caster'] = "lz_xbz_sf.pfx",
		['model'] = "lz_xbz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7006]={
		['caster'] = "lz_ylz_sf.pfx",
		['model'] = "lz_ylz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7007]={
		['caster'] = "lz_lyz_sf.pfx",
		['model'] = "lz_lyz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7008]={
		['caster'] = "lz_jgfmz_sf.pfx",
		['model'] = "lz_jgfmz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7009]={
		['caster'] = "lz_bmjzz_sf.pfx",
		['model'] = "lz_bmjzz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7010]={
		['caster'] = "lz_dymz_sf.pfx",
		['model'] = "lz_dymz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7011]={
		['caster'] = "lz_jxz_sf.pfx",
		['model'] = "lz_jxz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7012]={
		['caster'] = "lz_qixingbaguazhen_sf.pfx",
		['model'] = "lz_qixingbaguazhen_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7013]={
		['caster'] = "lz_dzxyz_sf.pfx",
		['model'] = "lz_dzxyz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[7014]={
		['caster'] = "lz_qbllz_sf.pfx",
		['model'] = "lz_qbllz_bz.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[9001]={
		['caster'] = "yunshi.pfx",
		['model'] = "yunshi.pfx",
		['finish'] = "",
		['yujing'] = "yunshi_2.pfx",
		['xiaoshi'] = 1,
	},
	[9002]={
		['caster'] = "jiguan_1.pfx",
		['model'] = "jiguan_1.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[9003]={
		['caster'] = "jiguan_2.pfx",
		['model'] = "jiguan_2.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[9004]={
		['caster'] = "jiguan_3.pfx",
		['model'] = "jiguan_3.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[9005]={
		['caster'] = "yunshi.pfx",
		['model'] = "yunshi.pfx",
		['finish'] = "",
		['yujing'] = "yunshi_2.pfx",
		['xiaoshi'] = 1,
	},
	[9006]={
		['caster'] = "yunshi.pfx",
		['model'] = "yunshi.pfx",
		['finish'] = "",
		['yujing'] = "yunshi_2.pfx",
		['xiaoshi'] = 1,
	},
	[9007]={
		['caster'] = "yunshi.pfx",
		['model'] = "yunshi.pfx",
		['finish'] = "",
		['yujing'] = "yunshi_2.pfx",
		['xiaoshi'] = 1,
	},
	[9008]={
		['caster'] = "jiguan_1.pfx",
		['model'] = "jiguan_1.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[9009]={
		['caster'] = "jiguan_4.pfx",
		['model'] = "jiguan_4.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
	[9010]={
		['caster'] = "jiguan_5.pfx",
		['model'] = "jiguan_5.pfx",
		['finish'] = "",
		['yujing'] = "",
		['xiaoshi'] = 0,
	},
};