return {
{
	id = 109,
	name = Lang.Item.n109,
	desc = Lang.Item.i109,
	type = 9,
	icon = 109,
	shape = 1,
	color = 0x15fff1,
	bgquality = 2,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	strongLimit = 6,
	staitcAttrs = {
{ type = 9, value = 26, },
{ type = 11, value = 32, },
{ type = 17, value = 34, },
{ type = 19, value = 42, },
{ type = 21, value = 37, },
{ type = 23, value = 62, },
{ type = 25, value = 8, },
{ type = 27, value = 14, },
	},
	initSmithAttrs = {
	},
	flags = {
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 5, },
		{ cond = 3, value = 3, },
	},
},
}