return {
{
	id = 1307,
	name = Lang.Item.n1307,
	desc = Lang.Item.i1307,
	type = 7,
	icon = 1277,
	shape = 1,
	color = 0xf0af00,
	bgquality = 6,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	sellMaxPrice = 50000000,
	suitLevel = 9,
	strongLimit = 15,
	injectLimit = 15,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 701, },
{ type = 11, value = 875, },
{ type = 17, value = 934, },
{ type = 19, value = 1167, },
{ type = 25, value = 2094, },
{ type = 27, value = 3490, },
	},
	initSmithAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		godEquip = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 80, },
		{ cond = 3, value = 3, },
	},
},
}