return {
{
	id = 1685,
	name = Lang.Item.n1685,
	desc = Lang.Item.i1685,
	type = 4,
	icon = 1625,
	shape = 1,
	color = 0xff0000,
	bgquality = 4,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 1,
	strongLimit = 15,
	injectLimit = 15,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 1320, },
{ type = 11, value = 1650, },
{ type = 13, value = 2640, },
{ type = 15, value = 3300, },
	},
	flags = {
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 1, },
		{ cond = 13, value = 25, },
		{ cond = 3, value = 2, },
	},
},
}