return {
{
	id = 1715,
	name = Lang.Item.n1715,
	desc = Lang.Item.i1715,
	type = 4,
	icon = 1655,
	shape = 1,
	color = 0xf0af00,
	bgquality = 6,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 1,
	strongLimit = 15,
	injectLimit = 15,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 1479, },
{ type = 11, value = 1848, },
{ type = 13, value = 2957, },
{ type = 15, value = 3696, },
	},
	flags = {
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		godEquip = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 1, },
		{ cond = 13, value = 25, },
		{ cond = 3, value = 2, },
	},
},
}