return {
{
	id = 27,
	name = Lang.Item.n27,
	desc = Lang.Item.i27,
	type = 7,
	icon = 27,
	shape = 1,
	color = 0x00ff00,
	bgquality = 1,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
{ type = 9, value = 14, },
{ type = 11, value = 18, },
{ type = 25, value = 12, },
{ type = 27, value = 21, },
	},
	initSmithAttrs = {
	},
	flags = {
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
	},
	conds = {
		{ cond = 1, value = 3, },
		{ cond = 3, value = 1, },
	},
},
}