return {
{
	id = 3114,
	name = Lang.Item.n3114,
	desc = Lang.Item.i3114,
	type = 14,
	icon = 3057,
	shape = 1,
	color = 0xf0af00,
	bgquality = 6,
	dura = 0,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	useType = 2,
	skillID = 0,
	sellBuyType = 0,
	strongLimit = 13,
	injectLimit = 13,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		showLootTips = true,
	},
	conds = {
		{ cond = 1, value = 36, },
	},
},
}