return {
{
	id = 3332,
	name = Lang.Item.n3332,
	desc = Lang.Item.i3332,
	type = 17,
	icon = 3086,
	shape = 1,
	color = 0xf0af00,
	bgquality = 6,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	strongLimit = 15,
	injectLimit = 15,
	staitcAttrs = {
{ type = 17, value = 1080, },
{ type = 19, value = 1540, },
{ type = 21, value = 552, },
{ type = 23, value = 1848, },
{ type = 25, value = 2240, },
{ type = 27, value = 3680, },
{ type = 118, value = 4000, },
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		notdura = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyReclaim = true,
		denyRepair = true,
		denyTipsAutoLine = true,
		NotUse = true,
		showLootTips = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 32, },
		{ cond = 3, value = 3, },
	},
},
}