return {
{
	id = 3384,
	name = Lang.Item.n3384,
	desc = Lang.Item.i3384,
	type = 20,
	icon = 3112,
	shape = 1,
	color = 0xff6600,
	bgquality = 5,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	strongLimit = 15,
	injectLimit = 15,
	staitcAttrs = {
{ type = 17, value = 190, },
{ type = 19, value = 270, },
{ type = 21, value = 600, },
{ type = 23, value = 960, },
{ type = 25, value = 64, },
{ type = 27, value = 216, },
{ type = 120, value = 900, },
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		notdura = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyReclaim = true,
		denyRepair = true,
		denyTipsAutoLine = true,
		NotUse = true,
		showLootTips = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 16, },
		{ cond = 3, value = 3, },
	},
},
}