return {
{
	id = 3429,
	name = Lang.Item.n3429,
	desc = Lang.Item.i3429,
	type = 105,
	icon = 3429,
	shape = 1,
	color = 0xff0000,
	bgquality = 4,
	dura = 4,
	useDurDrop = 0,
	dup = 1000,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 9,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
{ type = 9, value = 419, },
{ type = 11, value = 524, },
{ type = 13, value = 419, },
{ type = 15, value = 524, },
{ type = 17, value = 419, },
{ type = 19, value = 524, },
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		autoBindOnTake = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		NotUse = true,
		bagSell = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}