return {
{
	id = 3470,
	name = Lang.Item.n3470,
	desc = Lang.Item.i3470,
	type = 105,
	icon = 3470,
	shape = 1,
	color = 0xff0000,
	bgquality = 4,
	dura = 3,
	useDurDrop = 0,
	dup = 1000,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 10,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
{ type = 25, value = 390, },
{ type = 27, value = 660, },
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		autoBindOnTake = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		NotUse = true,
		bagSell = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}