return {
{
	id = 3499,
	name = Lang.Item.n3499,
	desc = Lang.Item.i3499,
	type = 105,
	icon = 3499,
	shape = 1,
	color = 0xf0af00,
	bgquality = 6,
	dura = 5,
	useDurDrop = 0,
	dup = 1000,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 19,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		autoBindOnTake = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		NotUse = true,
		bagSell = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}