return {
{
	id = 361,
	name = Lang.Item.n361,
	desc = Lang.Item.i361,
	type = 1,
	icon = 361,
	shape = 210,
	color = 0xff2e1e,
	bgquality = 4,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 3,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	sellMaxPrice = 47500,
	contri = 100,
	recycleGuildCoin = 1,
	strongLimit = 10,
	injectLimit = 10,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 499, },
{ type = 11, value = 624, },
{ type = 13, value = 998, },
{ type = 15, value = 1248, },
	},
	initSmithAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		hideDura = true,
		denyDropDua = true,
		denyTipsAutoLine = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 14, },
		{ cond = 3, value = 2, },
	},
},
}