return {
{
	id = 375,
	name = Lang.Item.n375,
	desc = Lang.Item.i375,
	type = 4,
	icon = 375,
	shape = 1,
	color = 0xff2e1e,
	bgquality = 4,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 3,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	sellMaxPrice = 15300,
	contri = 20,
	recycleGuildCoin = 1,
	strongLimit = 10,
	injectLimit = 10,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 243, },
{ type = 11, value = 305, },
{ type = 17, value = 324, },
{ type = 19, value = 406, },
	},
	initSmithAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		hideDura = true,
		denyDropDua = true,
		denyTipsAutoLine = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 14, },
		{ cond = 3, value = 3, },
	},
},
}