return {
{
	id = 4008,
	name = Lang.Item.n4008,
	desc = Lang.Item.i4008,
	type = 102,
	icon = 4008,
	shape = 1,
	color = 0x00ccff,
	bgquality = 2,
	dura = 0,
	useDurDrop = 0,
	dup = 100,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	batchType = 12,
	batchValue = 1000,
	skillID = 0,
	sellBuyType = 2,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		showLootTips = true,
	},
	conds = {
		{ cond = 1, value = 64, },
	},
},
}