return {
{
	id = 4044,
	name = Lang.Item.n4044,
	desc = Lang.Item.i4044,
	type = 102,
	icon = 4044,
	shape = 1,
	color = 0xcc00ff,
	bgquality = 3,
	dura = 0,
	useDurDrop = 0,
	dup = 100,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	batchType = 28,
	batchValue = 1000,
	skillID = 0,
	sellBuyType = 2,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		showLootTips = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}