return {
{
	id = 4358,
	name = Lang.Item.n4358,
	desc = Lang.Item.i4358,
	type = 102,
	icon = 4327,
	shape = 1,
	color = 0xffffff,
	bgquality = 0,
	dura = 0,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		showLootTips = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}