return {
{
	id = 4438,
	name = Lang.Item.n4438,
	desc = Lang.Item.i4438,
	type = 102,
	icon = 4428,
	shape = 1,
	color = 0xff0000,
	bgquality = 4,
	dura = 0,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 864000,
	secondConfirmMsg = Lang.Item.sc004,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		autoStartTime = true,
		denyStorage = true,
		denyGuildDepot = true,
		denyDeal = true,
		denySell = true,
		denyDestroy = true,
		denyReclaim = true,
		denyRepair = true,
		denySplite = true,
		denyTipsAutoLine = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}