return {
{
	id = 4536,
	name = Lang.Item.n4536,
	desc = Lang.Item.i4536,
	type = 102,
	icon = 4424,
	shape = 1,
	color = 0xcc00ff,
	bgquality = 3,
	dura = 0,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		denyStorage = true,
		denyGuildDepot = true,
		denyDeal = true,
		denySell = true,
		denyDestroy = true,
		denyReclaim = true,
		denyRepair = true,
		denySplite = true,
		denyTipsAutoLine = true,
	},
	conds = {
		{ cond = 1, value = 1, },
		--{ cond = 13, value = 1, },
	},
},
}