return {
{
	id = 4560,
	name = Lang.Item.n4560,
	desc = Lang.Item.i4560,
	type = 102,
	icon = 4560,
	shape = 1,
	color = 0xff6600,
	bgquality = 5,
	dura = 0,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 1,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	batchType = 1,
	batchValue = 100000000,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		hideDura = true,
		denyDropDua = true,
		denyStorage = true,
		denyGuildDepot = true,
		offlineDropdown = true,
		dieDropdown = true,
		denyTipsAutoLine = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}