return {
{
	id = 4604,
	name = Lang.Item.n4604,
	desc = Lang.Item.i4604,
	type = 104,
	icon = 4604,
	shape = 1,
	color = 0x00ccff,
	bgquality = 2,
	dura = 0,
	useDurDrop = 0,
	dup = 10,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 4,
	cdTime = 150,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
{ type = 2, value = 0.3, },
	},
	flags = {
		canCrossUse = true,
		notdura = true,
		denyGuildDepot = true,
		denyDestroy = true,
		offlineDropdown = true,
		dieDropdown = true,
		denyTipsAutoLine = true,
		medicalRecoverEffect = true,
		skillRemoveItem = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}