return {
{
	id = 461,
	name = Lang.Item.n461,
	desc = Lang.Item.i461,
	type = 1,
	icon = 431,
	shape = 590,
	color = 0xf0af00,
	bgquality = 6,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	sellMaxPrice = 50000000,
	suitLevel = 2,
	strongLimit = 11,
	injectLimit = 11,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 1279, },
{ type = 11, value = 1598, },
{ type = 17, value = 1705, },
{ type = 19, value = 2131, },
	},
	initSmithAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		godEquip = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 80, },
		{ cond = 3, value = 3, },
	},
},
}