return {
{
	id = 4625,
	name = Lang.Item.n4625,
	desc = Lang.Item.i4625,
	type = 102,
	icon = 4327,
	shape = 1,
	color = 0xff0000,
	bgquality = 4,
	dura = 0,
	useDurDrop = 0,
	dup = 999,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		hideDura = true,
		denyGuildDepot = true,
		denyDeal = true,
		denySell = true,
		denyDestroy = true,
		denyTipsAutoLine = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}