return {
{
	id = 4671,
	name = Lang.Item.n4671,
	desc = Lang.Item.i4671,
	type = 113,
	icon = 4303,
	shape = 1,
	color = 0xcc00ff,
	bgquality = 3,
	dura = 1000000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		showLootTips = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}