return {
{
	id = 4726,
	name = Lang.Item.n4726,
	desc = Lang.Item.i4726,
	type = 102,
	icon = 4726,
	shape = 1,
	color = 0xcc00ff,
	bgquality = 3,
	dura = 0,
	useDurDrop = 0,
	dup = 9999,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	openUi = {"Fashion", 6},
	skillID = 0,
	sellBuyType = 0,
	staitcAttrs = {
	},
	flags = {
		recordLog = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
	},
	conds = {
		{ cond = 1, value = 1, },
	},
},
}