return {
{
	id = 585,
	name = Lang.Item.n585,
	desc = Lang.Item.i585,
	type = 4,
	icon = 555,
	shape = 1,
	color = 0xf0af00,
	bgquality = 6,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	sellMaxPrice = 50000000,
	suitLevel = 3,
	strongLimit = 12,
	injectLimit = 12,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 573, },
{ type = 11, value = 716, },
{ type = 17, value = 764, },
{ type = 19, value = 955, },
	},
	initSmithAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		godEquip = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 80, },
		{ cond = 3, value = 3, },
	},
},
}