return {
{
	id = 91,
	name = Lang.Item.n91,
	desc = Lang.Item.i91,
	type = 1,
	icon = 91,
	shape = 120,
	color = 0x15fff1,
	bgquality = 2,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 0,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = 0,
	skillID = 0,
	sellBuyType = 0,
	strongLimit = 6,
	staitcAttrs = {
{ type = 9, value = 134, },
{ type = 11, value = 168, },
{ type = 13, value = 268, },
{ type = 15, value = 335, },
	},
	initSmithAttrs = {
	},
	flags = {
		hideDura = true,
		denyDropDua = true,
		denyGuildDepot = true,
		denyTipsAutoLine = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 5, },
		{ cond = 3, value = 2, },
	},
},
}