return {
{
	id = 957,
	name = Lang.Item.n957,
	desc = Lang.Item.i957,
	type = 7,
	icon = 957,
	shape = 1,
	color = 0xff2e1e,
	bgquality = 4,
	dura = 50000,
	useDurDrop = 0,
	dup = 0,
	weight = 1,
	dealType = 0,
	dealPrice = 1,
	time = 0,
	suitId = 17,
	colGroup = 0,
	cdTime = 0,
	dropBroadcast = -1,
	skillID = 0,
	sellBuyType = 1,
	sellMaxPrice = 65300,
	contri = 103680,
	recycleGuildCoin = 860,
	strongLimit = 15,
	injectLimit = 15,
	smithAttrMax = 3,
	staitcAttrs = {
{ type = 9, value = 570, },
{ type = 11, value = 712, },
{ type = 25, value = 1505, },
{ type = 27, value = 2508, },
	},
	initSmithAttrs = {
	},
	flags = {
		recordLog = true,
		trackDrop = true,
		hideDura = true,
		denyDropDua = true,
		denyTipsAutoLine = true,
		bagSell = true,
		star = true,
	},
	conds = {
		{ cond = 1, value = 34, },
		{ cond = 3, value = 1, },
	},
},
}