XMBossNotes = {}

XMBossNotes.OPEN_XMBOSSPANEL="OPEN_XMBOSSPANEL";
XMBossNotes.CLOSE_XMBOSSPANEL="CLOSE_XMBOSSPANEL";

XMBossNotes.OPEN_XMHUODONGJINDURANKPANEL="OPEN_XMHUODONGJINDURANKPANEL";
XMBossNotes.CLOSE_XMHUODONGJINDURANKPANEL="CLOSE_XMHUODONGJINDURANKPANEL";

XMBossNotes.OPEN_XMBOSSSHOULINGJIESHAOPANEL="OPEN_XMBOSSSHOULINGJIESHAOPANEL";
XMBossNotes.CLOSE_XMBOSSSHOULINGJIESHAOPANEL="CLOSE_XMBOSSSHOULINGJIESHAOPANEL";

XMBossNotes.OPEN_XMBOSSGAMERESULTPANEL="OPEN_XMBOSSGAMERESULTPANEL";
XMBossNotes.CLOSE_XMBOSSGAMERESULTPANEL="CLOSE_XMBOSSGAMERESULTPANEL";

XMBossNotes.OPEN_XMBOSSAWARDPANEL="OPEN_XMBOSSAWARDPANEL";
XMBossNotes.CLOSE_XMBOSSAWARDPANEL="CLOSE_XMBOSSAWARDPANEL";

XMBossNotes.OPEN_XMBOSSJOININFOSPANEL="OPEN_XMBOSSJOININFOSPANEL";
XMBossNotes.CLOSE_XMBOSSJOININFOSPANEL="CLOSE_XMBOSSJOININFOSPANEL";


XMBossNotes.OPEN_XMBOSSFULIPANEL="OPEN_XMBOSSFULIPANEL";
XMBossNotes.CLOSE_XMBOSSFULIPANEL="CLOSE_XMBOSSFULIPANEL";