-- this file is generated by program!
-- don't change it manaully.
-- source file: adventure_data.xls

Config = Config or {} 
Config.AdventureData = Config.AdventureData or {}
Config.AdventureData.data_explain_key_depth = 1
Config.AdventureData.data_explain_length = 5
Config.AdventureData.data_explain_lan = "zh"
Config.AdventureData.data_explain = {
	[1] = {id=1,desc="神界冒险每2天开启一轮，可选择5个宝可梦进行冒险，途中无法更换宝可梦。\n根据上一轮冒险的通关层数提供不同的增益buff。",title=""},
	[2] = {id=2,desc="每个守卫负责守护部分区域，击败守卫后可点击附近格子进行探索。\n消灭所有守卫后boss出现，击败boss后可通过传送门进入下一层。\n每次神界冒险开启时，按照历史最高层回退7层。",title="普通层玩法"},
	[3] = {id=3,desc="所有战斗均为1v1的单挑战斗，一方生命为0或回合数达到上限时战斗结束，战斗结束后双方维持生命值，生命值为0后无法继续战斗。",title="普通层战斗"},
	[4] = {id=4,desc="神界冒险中有多种事件，完成不同事件可获得不同奖励：\n守卫：击败神界中强大的怪物即可探索周围区域。\n采集：不要白不要，点一下就可以获得奖励。\nNPC事件：神界中有各种奇奇怪怪的npc，与他们交流说不定会有意外收获呢。\n冒险buff：拾取后仅可获得增益buff，本轮内对所有宝可梦生效。\n神之祝福：获得神的眷顾的人才能获得的物品。\n猜拳：下注猜拳，买定离手，你觉得你的手气如何呢~",title="普通层事件"},
	[5] = {id=5,desc="1.冒险中会遇到神秘商人，与神秘商人对话后，商品将会出现在冒险商店中。\n2.使用召唤商人后，商品也会出现在冒险商店中。\n3.冒险商店的商品在本次冒险重置后消失。",title="冒险商店"},
}
