-- this file is generated by program!
-- don't change it manaully.
-- source file: adventure_data.xls

Config = Config or {} 
Config.AdventureData = Config.AdventureData or {}
Config.AdventureData.data_round_reward_list_key_depth = 1
Config.AdventureData.data_round_reward_list_length = 5
Config.AdventureData.data_round_reward_list_lan = "zh"
Config.AdventureData.data_round_reward_list = {
	[1] = {count=5,id=1,items={{72001,30},{1,500000}}},
	[2] = {count=10,id=2,items={{72001,60},{1,800000}}},
	[3] = {count=15,id=3,items={{72001,90},{1,1200000}}},
	[4] = {count=20,id=4,items={{72001,120},{1,1600000}}},
	[5] = {count=30,id=5,items={{72001,150},{1,2000000}}},
}
