-- this file is generated by program!
-- don't change it manaully.
-- source file: arena_data.xls

Config = Config or {} 
Config.ArenaData = Config.ArenaData or {}
Config.ArenaData.data_activity_key_depth = 1
Config.ArenaData.data_activity_length = 12
Config.ArenaData.data_activity_lan = "zh"
Config.ArenaData.data_activity = {
	[1] = {items={{3,200},{8,500}},max=1,min=1},
	[2] = {items={{3,150},{8,400}},max=2,min=2},
	[3] = {items={{3,120},{8,300}},max=3,min=3},
	[4] = {items={{3,100},{8,250}},max=5,min=4},
	[5] = {items={{3,80},{8,220}},max=10,min=6},
	[6] = {items={{3,60},{8,200}},max=20,min=11},
	[7] = {items={{3,50},{8,180}},max=50,min=21},
	[8] = {items={{3,40},{8,160}},max=100,min=51},
	[9] = {items={{3,30},{8,140}},max=200,min=101},
	[10] = {items={{3,20},{8,120}},max=500,min=201},
	[11] = {items={{3,10},{8,100}},max=1000,min=501},
	[12] = {items={{3,5},{8,80}},max=99999,min=1001},
}
