-- this file is generated by program!
-- don't change it manaully.
-- source file: arena_data.xls

Config = Config or {} 
Config.ArenaData = Config.ArenaData or {}
Config.ArenaData.data_cup_key_depth = 1
Config.ArenaData.data_cup_length = 5
Config.ArenaData.data_cup_lan = "zh"
Config.ArenaData.data_cup = {
	[1] = {index=1,max_score=1099,min_score=800,name="青铜"},
	[2] = {index=2,max_score=1299,min_score=1100,name="白银"},
	[3] = {index=3,max_score=1499,min_score=1300,name="黄金"},
	[4] = {index=4,max_score=1799,min_score=1500,name="铂金"},
	[5] = {index=5,max_score=9999,min_score=1800,name="钻石"},
}
