-- this file is generated by program!
-- don't change it manaully.
-- source file: attr_data.xls

Config = Config or {} 
Config.AttrData = Config.AttrData or {}
Config.AttrData.data_key_to_name_key_depth = 1
Config.AttrData.data_key_to_name_length = 29
Config.AttrData.data_key_to_name_lan = "zh"
Config.AttrData.data_key_to_name = {
	["atk"] = "攻击",
	["atk_per"] = "攻击",
	["be_cure"] = "受疗",
	["crit_rate"] = "暴击率",
	["crit_ratio"] = "暴伤",
	["cure"] = "治疗",
	["dam"] = "伤害加成",
	["dam_p"] = "物伤",
	["dam_s"] = "特伤",
	["def"] = "防御",
	["def_p"] = "物防",
	["def_p_per"] = "物防",
	["def_per"] = "防御",
	["def_s"] = "特防",
	["def_s_per"] = "特防",
	["dodge_magic"] = "抗控",
	["dodge_rate"] = "闪躲",
	["hit_magic"] = "控制",
	["hit_rate"] = "命中",
	["hp"] = "生命",
	["hp_max"] = "生命",
	["hp_max_per"] = "生命",
	["res"] = "免伤",
	["res_p"] = "物免",
	["res_s"] = "特免",
	["speed"] = "速度",
	["speed_per"] = "速度",
	["tenacity"] = "抗暴",
	["toughness"] = "韧性",
}
