-- this file is generated by program!
-- don't change it manaully.
-- source file: attr_data.xls

Config = Config or {} 
Config.AttrData = Config.AttrData or {}
Config.AttrData.data_id_to_name_key_depth = 1
Config.AttrData.data_id_to_name_length = 29
Config.AttrData.data_id_to_name_lan = "zh"
Config.AttrData.data_id_to_name = {
	[101] = "攻击",
	[102] = "物防",
	[103] = "特防",
	[104] = "生命",
	[105] = "生命",
	[106] = "速度",
	[107] = "防御",
	[111] = "命中",
	[112] = "闪躲",
	[113] = "暴击率",
	[114] = "暴伤",
	[115] = "控制",
	[116] = "抗控",
	[117] = "抗暴",
	[118] = "攻击",
	[119] = "防御",
	[120] = "生命",
	[121] = "伤害加成",
	[122] = "免伤",
	[123] = "治疗",
	[124] = "受疗",
	[125] = "物伤",
	[126] = "特伤",
	[127] = "物免",
	[128] = "特免",
	[129] = "速度",
	[130] = "物防",
	[131] = "特防",
	[132] = "韧性",
}
