-- this file is generated by program!
-- don't change it manaully.
-- source file: buff_data.xls

Config = Config or {} 
Config.BuffData = Config.BuffData or {}
Config.BuffData.data_get_buff_data_key_depth = 1
Config.BuffData.data_get_buff_data_length = 38
Config.BuffData.data_get_buff_data_lan = "zh"
Config.BuffData.data_get_buff_data = {
	[1000] = {bid=1000,effect={{"exp",2}},group=1000,icon=10000,seconds=86400,type="add",des="经验获取增加100%",name="经验增幅"},
	[1010] = {bid=1010,effect={{"coin",2}},group=1010,icon=10010,seconds=86400,type="add",des="金币获取增加100%",name="金币增幅"},
	[1020] = {bid=1020,effect={{"exp",2}},group=1000,icon=10000,seconds=259200,type="add",des="经验获取增加100%",name="经验增幅"},
	[1030] = {bid=1030,effect={{"atk_per",50}},group=1030,icon=10000,seconds=0,type="add",des="攻击增加",name="攻击加成"},
	[1040] = {bid=1040,effect={{"hp_max_per",100}},group=1040,icon=10001,seconds=0,type="add",des="气血增加",name="气血加成"},
	[1050] = {bid=1050,effect={{"dam",50}},group=1050,icon=10002,seconds=0,type="add",des="伤害增加",name="伤害加成"},
	[1060] = {bid=1060,effect={{"res",50}},group=1060,icon=10003,seconds=0,type="add",des="免伤增加",name="免伤加成"},
	[1070] = {bid=1070,effect={{"speed_per",50}},group=1070,icon=10004,seconds=0,type="add",des="速度增加",name="速度加成"},
	[2000] = {bid=2000,effect={{"atk_per",50}},group=2000,icon=10000,seconds=0,type="add",des="攻击+5%",name="攻击+10%"},
	[2010] = {bid=2010,effect={{"atk_per",100}},group=2010,icon=10000,seconds=0,type="add",des="攻击+10%",name="攻击+15%"},
	[2020] = {bid=2020,effect={{"atk_per",150}},group=2010,icon=10000,seconds=0,type="add",des="攻击+15%",name="攻击+20%"},
	[3000] = {bid=3000,effect={{"atk_per",100}},group=3000,icon=3020,seconds=3,type="add",des="攻击+10%",name="攻击+10%"},
	[3020] = {bid=3020,effect={{"hp_max_per",100}},group=3020,icon=3030,seconds=3,type="add",des="气血+10%",name="气血+10%"},
	[3040] = {bid=3040,effect={{"dam",100}},group=3040,icon=3040,seconds=3,type="add",des="伤害+10%",name="伤害+10%"},
	[3060] = {bid=3060,effect={{"res",100}},group=3060,icon=3060,seconds=3,type="add",des="免伤+10%",name="免伤+10%"},
	[3080] = {bid=3080,effect={{"speed_per",100}},group=3080,icon=3070,seconds=3,type="add",des="速度+10%",name="速度+10%"},
	[3100] = {bid=3100,effect={{"adv_coin",100}},group=3100,icon=3012,seconds=7200,type="add",des="金币+10% ",name="金币加成+10% "},
	[3120] = {bid=3120,effect={{"adv_item_10102",200}},group=3120,icon=3013,seconds=7200,type="add",des="精炼石+20%",name="精炼石加成+20%"},
	[3140] = {bid=3140,effect={{"adv_mon",100}},group=3140,icon=3011,seconds=7200,type="add",des="怪物收益+10%",name="怪物收益+10%"},
	[3160] = {bid=3160,effect={{"adv_effect",100}},group=3160,icon=3010,seconds=7200,type="add",des="采集翻倍概率10%",name="采集翻倍+10%"},
	[3200] = {bid=3200,effect={{"dam",100}},group=3200,icon=3040,seconds=600,type="add",des="伤害+10%",name="伤害+10%"},
	[900101] = {bid=900101,effect={{"crit_rate",5}},group=900101,icon=3020,seconds=0,type="add",des="暴击提升0.5%",name="暴击+0.5%"},
	[900102] = {bid=900102,effect={{"def_per",5}},group=900102,icon=3060,seconds=0,type="add",des="防御提升0.5%",name="防御+0.5%"},
	[900103] = {bid=900103,effect={{"atk_per",5}},group=900103,icon=3020,seconds=0,type="add",des="攻击提升0.5%",name="攻击+0.5%"},
	[900104] = {bid=900104,effect={{"hp_max_per",5}},group=900104,icon=3030,seconds=0,type="add",des="生命提升0.5%",name="生命+0.5%"},
	[900105] = {bid=900105,effect={{"dam",5}},group=900105,icon=3040,seconds=0,type="add",des="伤害提升0.5%",name="伤害+0.5%"},
	[900106] = {bid=900106,effect={{"res",5}},group=900106,icon=3060,seconds=0,type="add",des="免伤提升0.5%",name="免伤+0.5%"},
	[900502] = {bid=900502,effect={{"def_per",20}},group=900502,icon=3060,seconds=0,type="add",des="防御提升2%",name="防御+2%"},
	[900503] = {bid=900503,effect={{"atk_per",20}},group=900503,icon=3020,seconds=0,type="add",des="攻击提升2%",name="攻击+2%"},
	[900512] = {bid=900512,effect={{"def_per",20}},group=900512,icon=3060,seconds=0,type="add",des="防御提升2%",name="防御+2%"},
	[900513] = {bid=900513,effect={{"atk_per",20}},group=900513,icon=3020,seconds=0,type="add",des="攻击提升2%",name="攻击+2%"},
	[900522] = {bid=900522,effect={{"def_per",30}},group=900522,icon=3060,seconds=0,type="add",des="防御提升3%",name="防御+3%"},
	[900523] = {bid=900523,effect={{"atk_per",30}},group=900523,icon=3020,seconds=0,type="add",des="攻击提升3%",name="攻击+3%"},
	[900532] = {bid=900532,effect={{"def_per",40}},group=900532,icon=3060,seconds=0,type="add",des="防御提升4%",name="防御+4%"},
	[900533] = {bid=900533,effect={{"atk_per",40}},group=900533,icon=3020,seconds=0,type="add",des="攻击提升4%",name="攻击+4%"},
	[900542] = {bid=900542,effect={{"def_per",50}},group=900542,icon=3060,seconds=0,type="add",des="防御提升5%",name="防御+5%"},
	[900543] = {bid=900543,effect={{"atk_per",50}},group=900543,icon=3020,seconds=0,type="add",des="攻击提升5%",name="攻击+5%"},
	[900903] = {bid=900903,effect={{"atk_per",100}},group=900103,icon=3020,seconds=0,type="add",des="攻击提升10%",name="攻击+10%"},
}
