-- this file is generated by program!
-- don't change it manaully.
-- source file: dailyplay_data.xls

Config = Config or {} 
Config.DailyplayData = Config.DailyplayData or {}
Config.DailyplayData.data_exerciseactivity_key_depth = 1
Config.DailyplayData.data_exerciseactivity_length = 4
Config.DailyplayData.data_exerciseactivity_lan = "zh"
Config.DailyplayData.data_exerciseactivity = {
	[1] = {id=1,activate={{"lev",15}},goto_id=2,is_open=1,pic_name="txt_cn_activity_item_12",val={{1,22,29904,72001}},desc="参与可获得大量实用道具",lock_desc="冒险家15级开启",name="伊布的宝藏"},
	[2] = {id=2,activate={{"lev",25}},goto_id=1,is_open=1,pic_name="txt_cn_activity_item_11",val={{22,1,10403,10450}},desc="参与可获得大量宝可梦经验",lock_desc="冒险家25级开启",name="无尽试炼"},
	[3] = {id=3,activate={{"lev",30}},goto_id=3,is_open=1,pic_name="txt_cn_activity_item_14",val={{29905,29904,1,25}},desc="参与可获得征战积分和金币",lock_desc="冒险家30级开启",name="位面征战"},
	[4] = {id=4,activate={{"lev",35}},goto_id=4,is_open=1,pic_name="txt_cn_activity_item_13",val={{50701,50702,50703}},desc="参与争夺神位，赢强力称号",lock_desc="冒险家35级开启",name="星河神殿"},
}
