-- this file is generated by program!
-- don't change it manaully.
-- source file: day_goals_data.xls

Config = Config or {} 
Config.DayGoalsData = Config.DayGoalsData or {}
Config.DayGoalsData.data_drama_explain_key_depth = 1
Config.DayGoalsData.data_drama_explain_length = 3
Config.DayGoalsData.data_drama_explain_lan = "zh"
Config.DayGoalsData.data_drama_explain = {
	[1] = {id=1,desc="七日目标根据天数开放，玩家完成任务后，可根据完成进度领取对应大奖。活动8天后关闭，奖励只可领取一次，领取后继续完成任务不可补充领取奖励",title="目标挑战"},
	[2] = {id=2,desc="每天有特别福利放送，快快领取奖励继续提升自己，完成目标挑战",title="每日福利"},
	[3] = {id=3,desc="精选各种酷炫礼包，每日半价超值出售。走过路过不要错过！",title="五折特惠"},
}
