-- this file is generated by program!
-- don't change it manaully.
-- source file: day_goals_data.xls

Config = Config or {} 
Config.DayGoalsData = Config.DayGoalsData or {}
Config.DayGoalsData.data_welfarecollection_key_depth = 3
Config.DayGoalsData.data_welfarecollection_length = 3
Config.DayGoalsData.data_welfarecollection_lan = "zh"
Config.DayGoalsData.data_welfarecollection = {
	[1] = {
		[1] = {
			[1] = {award1={{3,100},{10001,600}},condition={{"login",1}},day=1,extend={},goal_id=20000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,500},{10001,750}},condition={{"charge_rmb",100}},day=1,extend={},goal_id=20001,id=2,period=1,show_icon=131,desc="开服累充100元"},
		},
		[2] = {
			[1] = {award1={{3,150},{10403,2}},condition={{"login",2}},day=2,extend={},goal_id=30000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,1000},{10450,1500}},condition={{"charge_rmb",200}},day=2,extend={},goal_id=30001,id=2,period=1,show_icon=131,desc="开服累充200元"},
		},
		[3] = {
			[1] = {award1={{3,200},{10103,8}},condition={{"login",3}},day=3,extend={},goal_id=40000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,1500},{37002,2}},condition={{"charge_rmb",500}},day=3,extend={},goal_id=40001,id=2,period=1,show_icon=131,desc="开服累充500元"},
			[3] = {award1={{3,1500},{26907,50}},condition={{"charge_rmb",500}},day=3,extend={},goal_id=40011,id=2,period=1,show_icon=131,desc="开服累充500元"},
			[4] = {award1={{3,1500},{37002,2}},condition={{"charge_rmb",500}},day=3,extend={},goal_id=40021,id=2,period=1,show_icon=131,desc="开服累充500元"},
		},
		[4] = {
			[1] = {award1={{3,250},{10002,2}},condition={{"login",4}},day=4,extend={},goal_id=50000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,2000},{14001,2}},condition={{"charge_rmb",1000}},day=4,extend={},goal_id=50001,id=2,period=1,show_icon=131,desc="开服累充1000元"},
		},
		[5] = {
			[1] = {award1={{3,300},{40108,1}},condition={{"login",5}},day=5,extend={},goal_id=60000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,5000},{10450,7500}},condition={{"charge_rmb",2000}},day=5,extend={},goal_id=60001,id=2,period=1,show_icon=131,desc="开服累充2000元"},
		},
		[6] = {
			[1] = {award1={{3,350},{37001,8}},condition={{"login",6}},day=6,extend={},goal_id=70000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,7000},{14002,750}},condition={{"charge_rmb",3000}},day=6,extend={},goal_id=70001,id=2,period=1,show_icon=131,desc="开服累充3000元"},
		},
		[7] = {
			[1] = {award1={{3,400},{27306,1}},condition={{"login",7}},day=7,extend={},goal_id=80000,id=1,period=1,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,15000},{27906,50}},condition={{"charge_rmb",5000}},day=7,extend={},goal_id=80001,id=2,period=1,show_icon=131,desc="开服累充5000元"},
		},
	},
	[4] = {
		[1] = {
			[1] = {award1={{3,100},{10001,600}},condition={{"login",1}},day=1,extend={},goal_id=23000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,500},{10001,750}},condition={{"charge_rmb",100}},day=1,extend={},goal_id=23001,id=2,period=4,show_icon=131,desc="累充100元"},
		},
		[2] = {
			[1] = {award1={{3,150},{10403,2}},condition={{"login",2}},day=2,extend={},goal_id=33000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,1000},{10403,5}},condition={{"charge_rmb",200}},day=2,extend={},goal_id=33001,id=2,period=4,show_icon=131,desc="累充200元"},
		},
		[3] = {
			[1] = {award1={{3,200},{10103,8}},condition={{"login",3}},day=3,extend={},goal_id=43000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,1500},{37002,2}},condition={{"charge_rmb",500}},day=3,extend={},goal_id=43001,id=2,period=4,show_icon=131,desc="累充500元"},
		},
		[4] = {
			[1] = {award1={{3,250},{10002,8}},condition={{"login",4}},day=4,extend={},goal_id=53000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,2000},{14001,2}},condition={{"charge_rmb",1000}},day=4,extend={},goal_id=53001,id=2,period=4,show_icon=131,desc="累充1000元"},
		},
		[5] = {
			[1] = {award1={{3,300},{40108,1}},condition={{"login",5}},day=5,extend={},goal_id=63000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,5000},{10450,7500}},condition={{"charge_rmb",2000}},day=5,extend={},goal_id=63001,id=2,period=4,show_icon=131,desc="累充2000元"},
		},
		[6] = {
			[1] = {award1={{3,350},{37001,8}},condition={{"login",6}},day=6,extend={},goal_id=73000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,7000},{38051,2}},condition={{"charge_rmb",3000}},day=6,extend={},goal_id=73001,id=2,period=4,show_icon=131,desc="累充3000元"},
		},
		[7] = {
			[1] = {award1={{3,400},{14001,1}},condition={{"login",7}},day=7,extend={},goal_id=83000,id=1,period=4,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,15000},{28903,50}},condition={{"charge_rmb",5000}},day=7,extend={},goal_id=83001,id=2,period=4,show_icon=131,desc="累充5000元"},
		},
	},
	[7] = {
		[1] = {
			[1] = {award1={{3,100},{10450,600}},condition={{"login",1}},day=1,extend={},goal_id=27000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,200},{10450,750}},condition={{"charge_rmb",100}},day=1,extend={},goal_id=27001,id=2,period=7,show_icon=131,desc="累充100元"},
		},
		[2] = {
			[1] = {award1={{3,100},{10002,8}},condition={{"login",2}},day=2,extend={},goal_id=37000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,400},{10403,5}},condition={{"charge_rmb",200}},day=2,extend={},goal_id=37001,id=2,period=7,show_icon=131,desc="累充200元"},
		},
		[3] = {
			[1] = {award1={{3,100},{37001,8}},condition={{"login",3}},day=3,extend={},goal_id=47000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,1000},{37002,2}},condition={{"charge_rmb",500}},day=3,extend={},goal_id=47001,id=2,period=7,show_icon=131,desc="累充500元"},
		},
		[4] = {
			[1] = {award1={{3,100},{10403,2}},condition={{"login",4}},day=4,extend={},goal_id=57000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,2000},{14001,2}},condition={{"charge_rmb",1000}},day=4,extend={},goal_id=57001,id=2,period=7,show_icon=131,desc="累充1000元"},
		},
		[5] = {
			[1] = {award1={{3,100},{38080,1}},condition={{"login",5}},day=5,extend={},goal_id=67000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,3000},{10450,7500}},condition={{"charge_rmb",2000}},day=5,extend={},goal_id=67001,id=2,period=7,show_icon=131,desc="累充2000元"},
		},
		[6] = {
			[1] = {award1={{3,100},{38081,1}},condition={{"login",6}},day=6,extend={},goal_id=77000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,5000},{38061,1}},condition={{"charge_rmb",3000}},day=6,extend={},goal_id=77001,id=2,period=7,show_icon=131,desc="累充3000元"},
		},
		[7] = {
			[1] = {award1={{3,100},{37002,1}},condition={{"login",7}},day=7,extend={},goal_id=87000,id=1,period=7,show_icon=401,desc="登陆1次"},
			[2] = {award1={{3,8000},{27905,50}},condition={{"charge_rmb",5000}},day=7,extend={},goal_id=87001,id=2,period=7,show_icon=131,desc="累充5000元"},
		},
	},
}
