-- this file is generated by program!
-- don't change it manaully.
-- source file: dungeon_heaven_data.xls

Config = Config or {} 
Config.DungeonHeavenData = Config.DungeonHeavenData or {}
Config.DungeonHeavenData.data_chapter_key_depth = 1
Config.DungeonHeavenData.data_chapter_length = 48
Config.DungeonHeavenData.data_chapter_lan = "zh"
Config.DungeonHeavenData.data_chapter = {
	[1] = {bust_id=12,check_open={},cond_info={},ico=1,id=1,limit_id=0,map_id=84,pos_id=1,type="第一章"},
	[2] = {bust_id=1,check_open={},cond_info={},ico=2,id=2,limit_id=0,map_id=84,pos_id=2,type="第二章"},
	[3] = {bust_id=2,check_open={},cond_info={},ico=3,id=3,limit_id=0,map_id=84,pos_id=3,type="第三章"},
	[4] = {bust_id=3,check_open={6},cond_info={},ico=4,id=4,limit_id=0,map_id=84,pos_id=4,type="第四章"},
	[5] = {bust_id=4,check_open={7},cond_info={},ico=5,id=5,limit_id=0,map_id=84,pos_id=1,type="第五章"},
	[6] = {bust_id=5,check_open={8},cond_info={{4,20}},ico=6,id=6,limit_id=0,map_id=84,pos_id=2,type="第六章"},
	[7] = {bust_id=6,check_open={9},cond_info={{5,20}},ico=7,id=7,limit_id=6,map_id=84,pos_id=3,type="第七章"},
	[8] = {bust_id=7,check_open={10},cond_info={{6,20}},ico=8,id=8,limit_id=7,map_id=84,pos_id=4,type="第八章"},
	[9] = {bust_id=8,check_open={11},cond_info={{7,20}},ico=9,id=9,limit_id=8,map_id=84,pos_id=1,type="第九章"},
	[10] = {bust_id=9,check_open={12},cond_info={{8,20}},ico=10,id=10,limit_id=9,map_id=84,pos_id=2,type="第十章"},
	[11] = {bust_id=10,check_open={13},cond_info={{9,20}},ico=11,id=11,limit_id=10,map_id=84,pos_id=3,type="第十一章"},
	[12] = {bust_id=11,check_open={14},cond_info={{10,20}},ico=12,id=12,limit_id=11,map_id=84,pos_id=4,type="第十二章"},
	[13] = {bust_id=12,check_open={15},cond_info={{11,20}},ico=13,id=13,limit_id=12,map_id=84,pos_id=1,type="第十三章"},
	[14] = {bust_id=13,check_open={16},cond_info={{12,20}},ico=14,id=14,limit_id=13,map_id=84,pos_id=2,type="第十四章"},
	[15] = {bust_id=14,check_open={17},cond_info={{13,20}},ico=15,id=15,limit_id=14,map_id=84,pos_id=3,type="第十五章"},
	[16] = {bust_id=15,check_open={18},cond_info={{14,20}},ico=16,id=16,limit_id=15,map_id=84,pos_id=4,type="第十六章"},
	[17] = {bust_id=16,check_open={19},cond_info={{15,20}},ico=17,id=17,limit_id=16,map_id=84,pos_id=1,type="第十七章"},
	[18] = {bust_id=17,check_open={20},cond_info={{16,20}},ico=18,id=18,limit_id=17,map_id=84,pos_id=2,type="第十八章"},
	[19] = {bust_id=18,check_open={21},cond_info={{17,20}},ico=19,id=19,limit_id=18,map_id=84,pos_id=3,type="第十九章"},
	[20] = {bust_id=19,check_open={22},cond_info={{18,20}},ico=20,id=20,limit_id=19,map_id=84,pos_id=4,type="第二十章"},
	[21] = {bust_id=20,check_open={23},cond_info={{19,20}},ico=21,id=21,limit_id=20,map_id=84,pos_id=1,type="第二十一章"},
	[22] = {bust_id=21,check_open={24},cond_info={{20,20}},ico=22,id=22,limit_id=21,map_id=84,pos_id=2,type="第二十二章"},
	[23] = {bust_id=22,check_open={25},cond_info={{21,20}},ico=23,id=23,limit_id=22,map_id=84,pos_id=3,type="第二十三章"},
	[24] = {bust_id=23,check_open={26},cond_info={{22,20}},ico=24,id=24,limit_id=23,map_id=84,pos_id=4,type="第二十四章"},
	[25] = {bust_id=12,check_open={27},cond_info={{23,20}},ico=25,id=25,limit_id=24,map_id=84,pos_id=1,type="第二十五章"},
	[26] = {bust_id=1,check_open={28},cond_info={{24,20}},ico=26,id=26,limit_id=25,map_id=84,pos_id=2,type="第二十六章"},
	[27] = {bust_id=2,check_open={29},cond_info={{25,20}},ico=27,id=27,limit_id=26,map_id=84,pos_id=3,type="第二十七章"},
	[28] = {bust_id=3,check_open={30},cond_info={{26,20}},ico=28,id=28,limit_id=27,map_id=84,pos_id=4,type="第二十八章"},
	[29] = {bust_id=4,check_open={31},cond_info={{27,20}},ico=29,id=29,limit_id=28,map_id=84,pos_id=1,type="第二十九章"},
	[30] = {bust_id=5,check_open={32},cond_info={{28,20}},ico=30,id=30,limit_id=29,map_id=84,pos_id=2,type="第三十章"},
	[31] = {bust_id=6,check_open={33},cond_info={{29,20}},ico=31,id=31,limit_id=30,map_id=84,pos_id=3,type="第三十一章"},
	[32] = {bust_id=7,check_open={34},cond_info={{30,20}},ico=32,id=32,limit_id=31,map_id=84,pos_id=4,type="第三十二章"},
	[33] = {bust_id=8,check_open={35},cond_info={{31,20}},ico=33,id=33,limit_id=32,map_id=84,pos_id=1,type="第三十三章"},
	[34] = {bust_id=9,check_open={36},cond_info={{32,20}},ico=34,id=34,limit_id=33,map_id=84,pos_id=2,type="第三十四章"},
	[35] = {bust_id=10,check_open={37},cond_info={{33,20}},ico=35,id=35,limit_id=34,map_id=84,pos_id=3,type="第三十五章"},
	[36] = {bust_id=11,check_open={38},cond_info={{34,20}},ico=36,id=36,limit_id=35,map_id=84,pos_id=4,type="第三十六章"},
	[37] = {bust_id=12,check_open={39},cond_info={{35,20}},ico=37,id=37,limit_id=36,map_id=84,pos_id=1,type="第三十七章"},
	[38] = {bust_id=13,check_open={40},cond_info={{36,20}},ico=38,id=38,limit_id=37,map_id=84,pos_id=2,type="第三十八章"},
	[39] = {bust_id=14,check_open={41},cond_info={{37,20}},ico=39,id=39,limit_id=38,map_id=84,pos_id=3,type="第三十九章"},
	[40] = {bust_id=15,check_open={42},cond_info={{38,20}},ico=40,id=40,limit_id=39,map_id=84,pos_id=4,type="第四十章"},
	[41] = {bust_id=16,check_open={43},cond_info={{39,20}},ico=41,id=41,limit_id=40,map_id=84,pos_id=1,type="第四十一章"},
	[42] = {bust_id=17,check_open={44},cond_info={{40,20}},ico=42,id=42,limit_id=41,map_id=84,pos_id=2,type="第四十二章"},
	[43] = {bust_id=18,check_open={45},cond_info={{41,20}},ico=43,id=43,limit_id=42,map_id=84,pos_id=3,type="第四十三章"},
	[44] = {bust_id=19,check_open={46},cond_info={{42,20}},ico=44,id=44,limit_id=43,map_id=84,pos_id=4,type="第四十四章"},
	[45] = {bust_id=20,check_open={47},cond_info={{43,20}},ico=45,id=45,limit_id=44,map_id=84,pos_id=1,type="第四十五章"},
	[46] = {bust_id=21,check_open={48},cond_info={{44,20}},ico=46,id=46,limit_id=45,map_id=84,pos_id=2,type="第四十六章"},
	[47] = {bust_id=22,check_open={},cond_info={{45,20}},ico=47,id=47,limit_id=46,map_id=84,pos_id=3,type="第四十七章"},
	[48] = {bust_id=23,check_open={},cond_info={{46,20}},ico=48,id=48,limit_id=47,map_id=84,pos_id=4,type="第四十八章"},
}
