-- this file is generated by program!
-- don't change it manaully.
-- source file: dungeon_data.xls

Config = Config or {} 
Config.DungeonData = Config.DungeonData or {}
Config.DungeonData.data_drama_talk_key_depth = 1
Config.DungeonData.data_drama_talk_length = 13
Config.DungeonData.data_drama_talk_lan = "zh"
Config.DungeonData.data_drama_talk = {
	[1] = "捕捉是快速获得宝可梦的重要途径",
	[2] = "宝可梦升级能快速提升战斗力",
	[3] = "有空可以去竞技场学习下大神的阵容搭配",
	[4] = "通关更高的剧情副本，平时收益才会更大",
	[5] = "拥有更多的宝可梦，搭配起来才会更有趣",
	[6] = "每天可以免费快速作战，是快速升级的好办法",
	[7] = "你只是一个经验包，别挡了我的路",
	[8] = "越过前面那条河，我们离胜利就更近一步了",
	[9] = "没有什么是一招解决不了的，如果有，那打多一招",
	[10] = "翻过这座山，那里肯定有一片海",
	[11] = "不同的宝可梦搭配适合不同的站位",
	[12] = "上阵宝可梦满足系别搭配要求，就可以获得属性光环",
	[13] = "四五星宝可梦放生需谨慎，可能是重要的进化材料哦",
}
