-- this file is generated by program!
-- don't change it manaully.
-- source file: exchange_data.xls

Config = Config or {} 
Config.ExchangeData = Config.ExchangeData or {}
Config.ExchangeData.data_shop_exchage_expediton_key_depth = 1
Config.ExchangeData.data_shop_exchage_expediton_length = 14
Config.ExchangeData.data_shop_exchage_expediton_lan = "zh"
Config.ExchangeData.data_shop_exchage_expediton = {
	[1] = {bind=1,discount=0,icon=0,id=8012,is_partner=0,item_bid=10040,item_name="奥术之尘",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=1,open_srv_timestamp=0,order=1,pay_type="expedition_medal",price=3750,type=8},
	[2] = {bind=1,discount=0,icon=0,id=8001,is_partner=0,item_bid=72002,item_name="训练师天赋石",item_num=5,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=2,pay_type="expedition_medal",price=1250,type=8},
	[3] = {bind=1,discount=0,icon=0,id=8002,is_partner=0,item_bid=72001,item_name="金苹果",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=3,pay_type="expedition_medal",price=1875,type=8},
	[4] = {bind=1,discount=0,icon=0,id=8013,is_partner=0,item_bid=32,item_name="烈阳晶石",item_num=10000,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=5,open_srv_timestamp=0,order=4,pay_type="expedition_medal",price=1000,type=8},
	[5] = {bind=1,discount=0,icon=0,id=8003,is_partner=0,item_bid=29905,item_name="5星随机碎片",item_num=10,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=5,pay_type="expedition_medal",price=5000,type=8},
	[6] = {bind=1,discount=0,icon=0,id=8004,is_partner=0,item_bid=29104,item_name="4星水系碎片",item_num=10,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=6,pay_type="expedition_medal",price=1000,type=8},
	[7] = {bind=1,discount=0,icon=0,id=8005,is_partner=0,item_bid=29204,item_name="4星火系碎片",item_num=10,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=7,pay_type="expedition_medal",price=1000,type=8},
	[8] = {bind=1,discount=0,icon=0,id=8006,is_partner=0,item_bid=29304,item_name="4星草系碎片",item_num=10,label=0,lev={0,0},limit_day=0,limit_month=0,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=8,pay_type="expedition_medal",price=1000,type=8},
	[9] = {bind=1,discount=0,icon=0,id=8007,is_partner=0,item_bid=26907,item_name="裂空座碎片",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=1,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=9,pay_type="expedition_medal",price=45000,type=8},
	[10] = {bind=1,discount=0,icon=0,id=8008,is_partner=0,item_bid=25907,item_name="炎帝碎片",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=1,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=10,pay_type="expedition_medal",price=45000,type=8},
	[11] = {bind=1,discount=0,icon=0,id=8014,is_partner=0,item_bid=25909,item_name="莱希拉姆碎片",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=1,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=11,pay_type="expedition_medal",price=55000,type=8},
	[12] = {bind=1,discount=0,icon=0,id=8011,is_partner=0,item_bid=24909,item_name="盖欧卡碎片",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=1,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=12,pay_type="expedition_medal",price=45000,type=8},
	[13] = {bind=1,discount=0,icon=0,id=8009,is_partner=0,item_bid=27903,item_name="电击怪碎片",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=1,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=13,pay_type="expedition_medal",price=55000,type=8},
	[14] = {bind=1,discount=0,icon=0,id=8010,is_partner=0,item_bid=28905,item_name="宝贝龙碎片",item_num=50,label=0,lev={0,0},limit_day=0,limit_month=1,limit_vip=0,limit_week=0,open_srv_timestamp=0,order=14,pay_type="expedition_medal",price=50000,type=8},
}
