-- this file is generated by program!
-- don't change it manaully.
-- source file: formation_data.xls

Config = Config or {} 
Config.FormationData = Config.FormationData or {}
Config.FormationData.data_form_data_key_depth = 1
Config.FormationData.data_form_data_length = 6
Config.FormationData.data_form_data_lan = "zh"
Config.FormationData.data_form_data = {
	[1] = {desc="锋矢阵",name="锋矢阵",need_lev=1,order=1,pos={{1,2},{2,4},{3,6},{4,7},{5,9}},pos_list={{1,266,139},{2,50,126},{3,210,170},{4,226,215},{5,312,283}},type=1},
	[2] = {desc="疾风阵",name="疾风阵",need_lev=20,order=2,pos={{1,1},{2,3},{3,4},{4,6},{5,8}},pos_list={{1,196,98},{2,278,147},{3,356,198},{4,82,113},{5,358,299}},type=2},
	[3] = {desc="灵法阵",name="灵法阵",need_lev=30,order=3,pos={{1,1},{2,2},{3,3},{4,5},{5,8}},pos_list={{1,281,142},{2,113,147},{3,202,199},{4,289,254},{5,127,254}},type=3},
	[4] = {desc="天攻阵",name="天攻阵",need_lev=60,order=6,pos={{1,2},{2,4},{3,5},{4,6},{5,8}},pos_list={{1,308,111},{2,142,138},{3,286,231},{4,55,200},{5,214,292}},type=4},
	[5] = {desc="地绝阵",name="地绝阵",need_lev=40,order=4,pos={{1,2},{2,5},{3,7},{4,8},{5,9}},pos_list={{1,313,131},{2,233,185},{3,50,185},{4,152,239},{5,237,294}},type=5},
	[6] = {desc="圣灵阵",name="圣灵阵",need_lev=50,order=5,pos={{1,1},{2,3},{3,5},{4,7},{5,9}},pos_list={{1,284,141},{2,365,205},{3,204,198},{4,39,200},{5,132,253}},type=6},
}
