-- this file is generated by program!
-- don't change it manaully.
-- source file: function_data.xls

Config = Config or {} 
Config.FunctionData = Config.FunctionData or {}
Config.FunctionData.data_convert_icon_key_depth = 2
Config.FunctionData.data_convert_icon_length = 43
Config.FunctionData.data_convert_icon_lan = "zh"
Config.FunctionData.data_convert_icon = {
	["ameng"] = {
		[0] = {icon_res="icon_121",type_id=0,icon_name="欧皇盛宴"},
	},
	["aqili"] = {
		[0] = {icon_res="icon_143",type_id=0,icon_name="火灵庇护"},
	},
	["baiseqingren"] = {
		[0] = {icon_res="icon_58",type_id=0,icon_name="甜蜜豪礼"},
	},
	["chaomengsongguo"] = {
		[0] = {icon_res="icon_83",type_id=0,icon_name="松果"},
	},
	["chunjie"] = {
		[0] = {icon_res="icon_128",type_id=0,icon_name="贺岁好礼"},
	},
	["chunri"] = {
		[0] = {icon_res="icon_136",type_id=0,icon_name="暖春狂欢"},
	},
	["dongji"] = {
		[0] = {icon_res="icon_116",type_id=0,icon_name="冬日时光"},
	},
	["dongri"] = {
		[0] = {icon_res="icon_109",type_id=0,icon_name="纯白雪舞"},
	},
	["dongtian"] = {
		[0] = {icon_res="icon_117",type_id=0,icon_name="暮冬初雪"},
	},
	["ganen"] = {
		[0] = {icon_res="icon_114",type_id=0,icon_name="感恩好礼"},
	},
	["hailajianglin"] = {
		[0] = {icon_res="icon_78",type_id=0,icon_name="降临"},
	},
	["heilong"] = {
		[0] = {icon_res="icon_119",type_id=0,icon_name="光之降临"},
	},
	["hela"] = {
		[0] = {icon_res="icon_103",type_id=0,icon_name="誓约绽放"},
	},
	["huahuoshengdian"] = {
		[0] = {icon_res="icon_98",type_id=0,icon_name="花火大会"},
	},
	["huanleyixia"] = {
		[0] = {icon_res="icon_85",type_id=0,icon_name="欢乐一夏"},
	},
	["jiabailie"] = {
		[0] = {icon_res="icon_127",type_id=0,icon_name="光辉庇护"},
	},
	["jieri"] = {
		[0] = {icon_res="icon_75",type_id=0,icon_name="秋日时光"},
	},
	["jingling"] = {
		[0] = {icon_res="icon_107",type_id=0,icon_name="精灵祈愿"},
	},
	["kaixueji"] = {
		[0] = {icon_res="icon_70",type_id=0,icon_name="夏日狂欢"},
	},
	["kaixuelibao"] = {
		[0] = {icon_res="icon_94",type_id=0,icon_name="开学典礼"},
	},
	["laladui"] = {
		[0] = {icon_res="icon_142",type_id=0,icon_name="大作战"},
	},
	["liming"] = {
		[0] = {icon_res="icon_111",type_id=0,icon_name="黎明曙光"},
	},
	["liweitan"] = {
		[0] = {icon_res="icon_134",type_id=0,icon_name="水灵庇护"},
	},
	["nezha"] = {
		[0] = {icon_res="icon_92",type_id=0,icon_name="降临"},
	},
	["nuanchun"] = {
		[0] = {icon_res="icon_65",type_id=0,icon_name="冒险之旅"},
	},
	["qingrenjie"] = {
		[0] = {icon_res="icon_132",type_id=0,icon_name="情缘之礼"},
	},
	["qingyuanqixi"] = {
		[0] = {icon_res="icon_90",type_id=0,icon_name="圣诞好礼"},
	},
	["qiutian"] = {
		[0] = {icon_res="icon_100",type_id=0,icon_name="深秋狂欢"},
	},
	["saishate"] = {
		[0] = {icon_res="icon_139",type_id=0,icon_name="草灵之约"},
	},
	["shengdan"] = {
		[0] = {icon_res="icon_120",type_id=0,icon_name="圣光之约"},
	},
	["shengxiashiguang"] = {
		[0] = {icon_res="icon_73",type_id=0,icon_name="绝黯"},
	},
	["siyue"] = {
		[0] = {icon_res="icon_141",type_id=0,icon_name="灵舞四月"},
	},
	["wansheng"] = {
		[0] = {icon_res="icon_105",type_id=0,icon_name="奇遇万圣"},
	},
	["weinasi"] = {
		[0] = {icon_res="icon_87",type_id=0,icon_name="律动音符"},
	},
	["xiariji"] = {
		[0] = {icon_res="icon_85",type_id=0,icon_name="夏日盛典"},
		[1] = {icon_res="icon_86",type_id=1,icon_name="月圆之夜"},
	},
	["xiarikuanghuan"] = {
		[0] = {icon_res="icon_70",type_id=0,icon_name="夏日狂欢"},
	},
	["xinnian"] = {
		[0] = {icon_res="icon_57",type_id=0,icon_name="新春绮梦"},
		[1] = {icon_res="icon_125",type_id=0,icon_name="暖冬白雪"},
	},
	["xinxiya"] = {
		[0] = {icon_res="icon_101",type_id=0,icon_name="月神降临"},
	},
	["yuandan"] = {
		[0] = {icon_res="icon_124",type_id=0,icon_name="黑暗之神"},
	},
	["yuanxiao"] = {
		[0] = {icon_res="icon_130",type_id=0,icon_name="元宵盛典"},
	},
	["yulongjinjia"] = {
		[0] = {icon_res="icon_84",type_id=0,icon_name="神圣之光"},
	},
	["zhongqiu"] = {
		[0] = {icon_res="icon_95",type_id=0,icon_name="花好月圆"},
	},
	["zongxiaduanwu"] = {
		[0] = {icon_res="icon_79",type_id=0,icon_name="龙临"},
	},
}
