-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_dun_data.xls

Config = Config or {} 
Config.GuildDunData = Config.GuildDunData or {}
Config.GuildDunData.data_const_key_depth = 1
Config.GuildDunData.data_const_length = 28
Config.GuildDunData.data_const_lan = "zh"
Config.GuildDunData.data_const = {
	["action_time"] = {key="action_time",val=15,desc="每次挑战己方行动次数"},
	["bosstype_1"] = {key="bosstype_1",val={},desc="该Boss特防较低，推荐特攻输出"},
	["bosstype_2"] = {key="bosstype_2",val={},desc="该Boss物防较低，推荐物攻输出"},
	["box_max_num"] = {key="box_max_num",val=40,desc="宝箱总数量"},
	["buff_cost"] = {key="buff_cost",val=20,desc="激活&加强Buff消费红蓝钻"},
	["buff_item"] = {key="buff_item",val=10020,desc="激活&加强Buff消耗道具ID"},
	["coin_box"] = {key="coin_box",val=21,desc="宝箱4数量（金币）"},
	["concentrate_cd"] = {key="concentrate_cd",val=3600,desc="集结冷却时间（单位：秒）"},
	["des_nobuff"] = {key="des_nobuff",val={},desc="全联盟成员攻击力+0%"},
	["double_time"] = {key="double_time",val={},desc="双倍奖励时间段"},
	["free_time"] = {key="free_time",val=2,desc="每日初始免费次数"},
	["game_rule"] = {key="game_rule",val=1,desc="1.每次挑战副本中的Boss都会获得<div fontcolor=289b14>联盟贡献</div>、<div fontcolor=289b14>金币</div>\n2.击杀Boss后根据联盟成员对本Boss造成的伤害排名发放结算奖励，击杀者可额外获得<div fontcolor=289b14>击杀奖励</div>，同时联盟可获得一定<div fontcolor=289b14>联盟经验</div>\n3.玩家每日拥有2次免费挑战次数,次数在每日0点重置,此外玩家可消耗钻石购买额外挑战次数 \n4.扫荡会继承上一次挑战的伤害量进行结算，扫荡同样消耗1点挑战次数\n5.消耗<div fontcolor=289b14>联盟增幅令</div>或<div fontcolor=289b14>钻石</div>可激活或提升<div fontcolor=289b14>联盟全员增加攻击Buff</div>效果，最大可增加到20%的攻击力加成.每个Boss击杀奖励每个角色只可获得1次，更换联盟重复击杀只获得保底奖励"},
	["gold_box"] = {key="gold_box",val=1,desc="宝箱1数量(召唤书）"},
	["guild_box"] = {key="guild_box",val=10,desc="宝箱3数量（贡献）"},
	["guild_lev"] = {key="guild_lev",val=1,desc="联盟达到1级开启"},
	["hero_soul_box"] = {key="hero_soul_box",val=8,desc="宝箱2数量（神格）"},
	["join_lev"] = {key="join_lev",val=10,desc="成员最低参与等级"},
	["praise_reward"] = {key="praise_reward",val={{2,3000}},desc="点赞奖励"},
	["praise_time"] = {key="praise_time",val=3,desc="点赞次数限制"},
	["rank_dam"] = {key="rank_dam",val=2000,desc="上榜所需最低伤害"},
	["recover_time"] = {key="recover_time",val={},desc="每X分钟恢复1次挑战次数"},
	["reset_desc_0"] = {key="reset_desc_0",val="正常重置",desc="明日联盟副本重置至历史最高章节"},
	["reset_desc_1"] = {key="reset_desc_1",val="章节回退",desc="明日联盟副本重置至历史最高章节的前一章节"},
	["resetting_time"] = {key="resetting_time",val={0,0,0},desc="每天几点重置副本"},
	["reward_desc01"] = {key="reward_desc01",val={},desc="通关数越高奖励越丰厚！"},
	["reward_desc02"] = {key="reward_desc02",val={},desc="每周一<div fontcolor=289b14>00:00</div>根据最高通关数结算奖励，通过邮件向全联盟成员发放"},
	["rumour_items"] = {key="rumour_items",val={10201},desc="传闻道具"},
	["time_quantum"] = {key="time_quantum",val={},desc="每天恢复次数时间段"},
}
