-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_data.xls

Config = Config or {} 
Config.GuildData = Config.GuildData or {}
Config.GuildData.data_guild_scene_icon_key_depth = 1
Config.GuildData.data_guild_scene_icon_length = 8
Config.GuildData.data_guild_scene_icon_lan = "zh"
Config.GuildData.data_guild_scene_icon = {
	[1] = {icon="1",pos={{568,920}},res_type=1,type=1,name="联盟秘境"},
	[2] = {icon="1",pos={{516,750}},res_type=1,type=2,name="联盟技能"},
	[3] = {icon="1",pos={{308,554}},res_type=1,type=3,name="联盟宝库"},
	[4] = {icon="1",pos={{78,715}},res_type=1,type=4,name="联盟副本"},
	[5] = {icon="1",pos={{600,590}},res_type=1,type=5,name="联盟商店"},
	[6] = {icon="1",pos={{792,420}},res_type=1,type=6,name="联盟战"},
	[7] = {icon="1",pos={{348,408}},res_type=1,type=7,name="联盟活跃"},
	[8] = {icon="1",pos={{48,358}},res_type=1,type=8,name="联盟捐献"},
}
