-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_data.xls

Config = Config or {} 
Config.GuildData = Config.GuildData or {}
Config.GuildData.data_sign_key_depth = 1
Config.GuildData.data_sign_length = 3
Config.GuildData.data_sign_lan = "zh"
Config.GuildData.data_sign = {
	[1] = "欢迎各位勇敢的冒险者加入！一起打造大陆第一联盟！",
	[2] = "欢迎菜鸟们加入一起玩耍！o(￣v￣)o~努力成长！携手搬砖！",
	[3] = "我们是冠军！欢迎加入！",
}
