-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_war_data.xls

Config = Config or {} 
Config.GuildWarData = Config.GuildWarData or {}
Config.GuildWarData.data_marketplace_reward_key_depth = 1
Config.GuildWarData.data_marketplace_reward_length = 5
Config.GuildWarData.data_marketplace_reward_lan = "zh"
Config.GuildWarData.data_marketplace_reward = {
	[1] = {power_high=10000000,power_low=0,rand_reward={{29905,20,350},{29905,30,395},{29905,50,85},{14001,1,170}},reward={{10403,15},{10001,500},{37001,20}}},
	[2] = {power_high=20000000,power_low=10000000,rand_reward={{29905,20,350},{29905,30,395},{29905,50,85},{14001,1,170}},reward={{10403,15},{10001,500},{37001,20}}},
	[3] = {power_high=30000000,power_low=20000000,rand_reward={{29905,20,350},{29905,30,395},{29905,50,85},{14001,1,170}},reward={{10403,15},{10001,500},{37001,20}}},
	[4] = {power_high=40000000,power_low=30000000,rand_reward={{29905,20,350},{29905,30,395},{29905,50,85},{14001,1,170}},reward={{10403,15},{10001,500},{37001,20}}},
	[5] = {power_high=999999999,power_low=40000000,rand_reward={{29905,20,350},{29905,30,395},{29905,50,85},{14001,1,170}},reward={{10403,15},{10001,500},{37001,20}}},
}
