-- this file is generated by program!
-- don't change it manaully.
-- source file: guild_dun_data.xls

Config = Config or {} 
Config.GuildDunData = Config.GuildDunData or {}
Config.GuildDunData.data_buy_count_key_depth = 1
Config.GuildDunData.data_buy_count_length = 4
Config.GuildDunData.data_buy_count_lan = "zh"
Config.GuildDunData.data_buy_count = {
	[1] = {count=1,expend={15,20},vip_lev=0},
	[2] = {count=2,expend={15,30},vip_lev=0},
	[3] = {count=3,expend={15,40},vip_lev=0},
	[4] = {count=4,expend={15,60},vip_lev=0},
}
