-- this file is generated by program!
-- don't change it manaully.
-- source file: hallows_data.xls

Config = Config or {} 
Config.HallowsData = Config.HallowsData or {}
Config.HallowsData.data_skill_max_lev_key_depth = 1
Config.HallowsData.data_skill_max_lev_length = 5
Config.HallowsData.data_skill_max_lev_lan = "zh"
Config.HallowsData.data_skill_max_lev = {
	[1] = 12,
	[2] = 12,
	[3] = 12,
	[4] = 12,
	[5] = 12,
}
