-- this file is generated by program!
-- don't change it manaully.
-- source file: holiday_valentine_boss_data.xls

Config = Config or {} 
Config.HolidayValentineBossData = Config.HolidayValentineBossData or {}
Config.HolidayValentineBossData.data_boss_list_key_depth = 2
Config.HolidayValentineBossData.data_boss_list_length = 4
Config.HolidayValentineBossData.data_boss_list_lan = "zh"
Config.HolidayValentineBossData.data_boss_list = {
	[49971] = {
		[1] = {boss_id=97101,boss_skill_id={918101,918201,918301,918401},buy_time=0,camp_id=49971,draw_id=1,end_time={{2020,3,18},{23,59,59}},head_icon=2017,id=1,reward={{37011,1},{29905,1},{10603,1},{10403,1}},start_time={{2020,3,12},{0,0,0}},time=2,act_time="3月12日-3月18日",rules="1、活动期间，参与海拉玫瑰之恋boss挑战，单场战斗内造成越多伤害，可获得更多奖励，奖励必得<div fontcolor=#c23f35>【玫瑰之钥】</div>，更有机会掉落金羽蛋、高级召唤卷、5星随机碎片、符文精华等珍稀材料！\n2、每日挑战机会<div fontcolor=#c23f35>2次</div>，挑战机会0点重置哦",title_name="玫瑰之恋"},
	},
	[49995] = {
		[2] = {boss_id=97201,boss_skill_id={917101,917201,917301,917401},buy_time=2,camp_id=49995,draw_id=2,end_time={{2020,3,25},{23,59,59}},head_icon=30512,id=2,reward={{80266,1},{29905,1},{10408,1},{10450,1}},start_time={{2020,3,19},{0,0,0}},time=2,act_time="3月19日-3月25日",rules="1、活动期间，参与风灵之力塞莎特boss挑战，单场战斗内造成越多伤害，可获得更多奖励，奖励必得积分<div fontcolor=#c23f35>【魔法之书】</div>！\n2、<div fontcolor=#c23f35>【魔法之书】</div>可以在兑换杂货店中兑换冒险者大人喜欢的各种珍稀道具，活动限时，请抓紧时间兑换哦！\n3、每日免费挑战机会<div fontcolor=#c23f35>2次</div>，可以额外钻石购买2次挑战机会（200钻/次），挑战机会0点重置哦",title_name="风灵之力"},
	},
	[50038] = {
		[3] = {boss_id=97202,boss_skill_id={916101,916201,916301,916401},buy_time=0,camp_id=50038,draw_id=3,end_time={{2020,4,15},{23,59,59}},head_icon=2019,id=3,reward={{37012,1},{29905,1},{10408,1},{10450,1}},start_time={{2020,4,9},{0,0,0}},time=2,act_time="4月9日-4月15日",rules="1、活动期间，参与拉斐尔拉拉队boss挑战，单场战斗内造成越多伤害，可获得更多奖励，奖励必得道具<div fontcolor=#c23f35>【哨子】</div>！更有机会掉落精英召唤卷、5星随机碎片、符文精华等珍稀材料！\n2、<div fontcolor=#c23f35>【哨子】</div>可以在抽奖活动中挖取各种珍稀道具，活动限时，请抓紧时间参与哦！\n3、每日免费挑战机会<div fontcolor=#c23f35>2次</div>，挑战机会0点重置哦",title_name="活力大作战"},
	},
	[50050] = {
		[4] = {boss_id=97203,boss_skill_id={915101,915201,915301},buy_time=2,camp_id=50050,draw_id=4,end_time={{2020,4,22},{23,59,59}},head_icon=20512,id=4,reward={{80268,1},{29905,1},{10408,1},{10450,1}},start_time={{2020,4,13},{0,0,0}},time=2,act_time="12月24日-12月30日",rules="1、活动期间，参与火灵庇佑拉帝亚斯boss挑战，单场战斗内造成越多伤害，可获得更多奖励，奖励必得道具<div fontcolor=#c23f35>【火灵环】</div>！\n2、<div fontcolor=#c23f35>【火灵环】</div>可以在兑换杂货店中兑换冒险者大人喜欢的各种珍稀道具，活动限时，请抓紧时间兑换哦！\n3、每日免费挑战机会<div fontcolor=#c23f35>2次</div>，可以额外钻石购买2次挑战机会（200钻/次），挑战机会0点重置哦",title_name="火灵庇佑"},
	},
}
