-- this file is generated by program!
-- don't change it manaully.
-- source file: holiday_nian_data.xls

Config = Config or {} 
Config.HolidayNianData = Config.HolidayNianData or {}
Config.HolidayNianData.data_evt_info_key_depth = 1
Config.HolidayNianData.data_evt_info_length = 34
Config.HolidayNianData.data_evt_info_lan = "zh"
Config.HolidayNianData.data_evt_info = {
	[0] = {boss_skill_id={},ext={},id=0,is_walk=1,offset={},res_1={},res_2={},reversal=0,reward={},type=0},
	[10001] = {boss_skill_id={},ext={},id=10001,is_walk=1,offset={},res_1={},res_2={},reversal=0,reward={},type=2},
	[10101] = {boss_skill_id={},ext={10101},id=10101,is_walk=0,offset={0,38},res_1={1,9011},res_2={},reversal=0,reward={},type=3},
	[10201] = {boss_skill_id={},ext={{10201,500}},id=10201,is_walk=0,offset={0,40},res_1={1,9181},res_2={},reversal=0,reward={},type=5},
	[10202] = {boss_skill_id={},ext={{10202,500}},id=10202,is_walk=0,offset={0,40},res_1={1,9182},res_2={},reversal=0,reward={},type=5},
	[10301] = {boss_skill_id={},ext={},id=10301,is_walk=0,offset={0,35},res_1={1,9141},res_2={},reversal=0,reward={},type=8},
	[10302] = {boss_skill_id={},ext={},id=10302,is_walk=0,offset={0,35},res_1={1,9142},res_2={},reversal=0,reward={},type=8},
	[10303] = {boss_skill_id={},ext={},id=10303,is_walk=0,offset={0,35},res_1={1,9143},res_2={},reversal=0,reward={},type=8},
	[10304] = {boss_skill_id={},ext={},id=10304,is_walk=0,offset={0,35},res_1={1,9144},res_2={},reversal=0,reward={},type=8},
	[10401] = {boss_skill_id={},ext={},id=10401,is_walk=0,offset={3,35},res_1={1,1151},res_2={},reversal=0,reward={},type=4},
	[10501] = {boss_skill_id={},ext={},id=10501,is_walk=0,offset={-4,30},res_1={1,9151},res_2={},reversal=0,reward={},type=9},
	[10601] = {boss_skill_id={},ext={},id=10601,is_walk=0,offset={0,30},res_1={1,9152},res_2={},reversal=0,reward={},type=10},
	[10701] = {boss_skill_id={},ext={},id=10701,is_walk=0,offset={0,35},res_1={1,9153},res_2={},reversal=0,reward={},type=11},
	[10801] = {boss_skill_id={},ext={97004},id=10801,is_walk=0,offset={0,40},res_1={1,9183},res_2={},reversal=0,reward={{80351,5},{1,25000},{22,10000}},type=1},
	[19001] = {boss_skill_id={},ext={19003},id=19001,is_walk=0,offset={26,-21},res_1={2,"E28002"},res_2={},reversal=1,reward={},type=14},
	[19002] = {boss_skill_id={},ext={19004},id=19002,is_walk=0,offset={},res_1={},res_2={},reversal=0,reward={},type=14},
	[19003] = {boss_skill_id={919001,919101,919201,919401},ext={19001},id=19003,is_walk=0,offset={26,-21},res_1={2,"E28002"},res_2={},reversal=1,reward={{3,1},{29905,1},{80304,1},{80303,1},{10450,1},{72001,1}},type=12},
	[19004] = {boss_skill_id={},ext={19002},id=19004,is_walk=0,offset={},res_1={},res_2={},reversal=0,reward={},type=12},
	[19051] = {boss_skill_id={},ext={19053},id=19051,is_walk=0,offset={26,-21},res_1={2,"E28003"},res_2={},reversal=1,reward={},type=15},
	[19052] = {boss_skill_id={},ext={19054},id=19052,is_walk=0,offset={},res_1={},res_2={},reversal=0,reward={},type=15},
	[19053] = {boss_skill_id={919001,919101,919201,919401},ext={19051},id=19053,is_walk=0,offset={26,-21},res_1={2,"E28003"},res_2={},reversal=1,reward={{3,1},{37010,1},{80304,1},{80303,1},{29905,1},{10403,1}},type=13},
	[19054] = {boss_skill_id={},ext={19052},id=19054,is_walk=0,offset={},res_1={},res_2={},reversal=0,reward={},type=13},
	[90111] = {boss_skill_id={},ext={},id=90111,is_walk=0,offset={0,35},res_1={1,20001},res_2={},reversal=0,reward={},type=7},
	[90112] = {boss_skill_id={},ext={},id=90112,is_walk=0,offset={0,35},res_1={1,20001},res_2={},reversal=0,reward={},type=7},
	[90121] = {boss_skill_id={},ext={},id=90121,is_walk=0,offset={0,95},res_1={1,20002},res_2={},reversal=0,reward={},type=7},
	[90122] = {boss_skill_id={},ext={},id=90122,is_walk=0,offset={0,95},res_1={1,20002},res_2={},reversal=0,reward={},type=7},
	[90131] = {boss_skill_id={},ext={},id=90131,is_walk=0,offset={0,45},res_1={1,20003},res_2={},reversal=0,reward={},type=7},
	[90132] = {boss_skill_id={},ext={},id=90132,is_walk=0,offset={0,45},res_1={1,20003},res_2={},reversal=0,reward={},type=7},
	[90211] = {boss_skill_id={},ext={},id=90211,is_walk=0,offset={0,40},res_1={1,20004},res_2={},reversal=0,reward={},type=7},
	[90212] = {boss_skill_id={},ext={},id=90212,is_walk=0,offset={0,40},res_1={1,20004},res_2={},reversal=0,reward={},type=7},
	[90221] = {boss_skill_id={},ext={},id=90221,is_walk=0,offset={33,91},res_1={1,20005},res_2={},reversal=0,reward={},type=7},
	[90222] = {boss_skill_id={},ext={},id=90222,is_walk=0,offset={33,91},res_1={1,20005},res_2={},reversal=0,reward={},type=7},
	[90231] = {boss_skill_id={},ext={},id=90231,is_walk=0,offset={0,-50},res_1={1,20006},res_2={},reversal=0,reward={},type=7},
	[90232] = {boss_skill_id={},ext={},id=90232,is_walk=0,offset={0,-50},res_1={1,20006},res_2={},reversal=0,reward={},type=7},
}
