-- this file is generated by program!
-- don't change it manaully.
-- source file: holy_eqm_lottery_data.xls

Config = Config or {} 
Config.HolyEqmLotteryData = Config.HolyEqmLotteryData or {}
Config.HolyEqmLotteryData.data_const_key_depth = 1
Config.HolyEqmLotteryData.data_const_length = 7
Config.HolyEqmLotteryData.data_const_lan = "zh"
Config.HolyEqmLotteryData.data_const = {
	["activity_tips_show_condiction"] = {val=17365,desc="tips显示对应的活动"},
	["continuous_raffle_times"] = {val=10,desc="公共连抽次数"},
	["heaven_dun_condition"] = {val=0,desc="已开启"},
	["player_lev_condition"] = {val=50,desc="个人等级达到50级后开启"},
	["player_lev_second_condition"] = {val=50,desc="个人等级达到50级后开启"},
	["pray_rule"] = {val=1,desc="1.对神像祈祷可获得<div fontcolor=65df74>饰品碎片</div>、<div fontcolor=65df74>天界神石</div>、<div fontcolor=65df74>各类饰品</div>\n2.每日首次祈祷免费，每20次祈祷必定获得一件<div fontcolor=65df74>良品</div>或以上的饰品\n3.往<div fontcolor=65df74>心愿水晶</div>中放入心仪的饰品，可大大提高该饰品的祈祷获取概率；不同石像的心愿水晶互相独立\n4.每个石像累计一定祈祷次数后，玩家可领取对应<div fontcolor=65df74>进度奖励</div>；累计200次可获得<div fontcolor=65df74>【极品自选主题礼盒】</div>，能开启出指定主题的随机部位饰品1个\n5.玩家战力前5名英雄的饰品总评分达10000后开启<div fontcolor=65df74>【圣洁神像】</div>，抽取更高星级的饰品！同时更高的评分可在饰品商店中开启更多饰品商品以供购买。"},
	["world_lev_condition"] = {val=50,desc="世界等级达到50级后开启"},
}
