-- this file is generated by program!
-- don't change it manaully.
-- source file: item_data.xls

Config = Config or {} 
Config.ItemData = Config.ItemData or {}
Config.ItemData.data_item_effect_type_key_depth = 1
Config.ItemData.data_item_effect_type_length = 43
Config.ItemData.data_item_effect_type_lan = "zh"
Config.ItemData.data_item_effect_type = {
	[1] = "钻石",
	[2] = "金币",
	[3] = "经验",
	[4] = "宝可梦经验",
	[5] = "宝可梦碎片",
	[6] = "加buff",
	[7] = "获取宝可梦",
	[8] = "商城特惠礼包时效",
	[9] = "体力",
	[10] = "神格",
	[11] = "充值",
	[12] = "激活头像框",
	[13] = "激活聊天气泡",
	[14] = "VIP经验",
	[15] = "进入捕捉",
	[16] = "直接升星",
	[17] = "营地保护",
	[18] = "迁城令",
	[19] = "城防值",
	[20] = "竞技券",
	[21] = "获取时装",
	[22] = "获得训练师",
	[23] = "红包",
	[24] = "训练师碎片",
	[25] = "激活称号",
	[26] = "联盟副本Buff",
	[27] = "特定等级宝可梦",
	[28] = "激活圣器",
	[29] = "伙伴升星",
	[30] = "宝石星级",
	[31] = "激活特权",
	[32] = "激活头像",
	[33] = "激活周卡",
	[34] = "激活伙伴皮肤",
	[35] = "激活徽章",
	[36] = "增加事件概率",
	[37] = "增加城市权重",
	[38] = "出行城市列表",
	[39] = "激活明信片",
	[40] = "激活日记",
	[41] = "发送回归红包",
	[42] = "乐园形象",
	[43] = "位面宝可梦恢复",
}
