-- this file is generated by program!
-- don't change it manaully.
-- source file: loading_desc_data.xls

Config = Config or {} 
Config.LoadingDescData = Config.LoadingDescData or {}
Config.LoadingDescData.data_desc_key_depth = 1
Config.LoadingDescData.data_desc_length = 7
Config.LoadingDescData.data_desc_lan = "zh"
Config.LoadingDescData.data_desc = {
	[1] = "副本推图关卡越高，获取角色经验、金币、宝可梦经验效率越高",
	[2] = "宝可梦进化、进阶可大幅提高宝可梦属性成长，升级属性加成提高",
	[3] = "加入联盟，一起打Boss可以赚取大量联盟贡献",
	[4] = "战斗不停！即使离线也会不断获得经验、金币、宝可梦碎片等挂机奖励",
	[5] = "快速作战可以立即获得大量角色经验和资源",
	[6] = "挑战竞技场拿竞技奖杯，珍贵宝可梦、狩猎球超值兑换",
	[7] = "游戏怎么玩？推图、爬塔、冒险、养宝可梦玩竞技，感受成长和竞技的乐趣",
}
