-- this file is generated by program!
-- don't change it manaully.
-- source file: planes_war_order_data.xls

Config = Config or {} 
Config.PlanesWarOrderData = Config.PlanesWarOrderData or {}
Config.PlanesWarOrderData.data_period_day_key_depth = 1
Config.PlanesWarOrderData.data_period_day_length = 2
Config.PlanesWarOrderData.data_period_day_lan = "zh"
Config.PlanesWarOrderData.data_period_day = {
	[1] = {name="征战之证",period=1,period_day=44},
	[2] = {name="征战之证",period=2,period_day=44},
}
