-- this file is generated by program!
-- don't change it manaully.
-- source file: primus_data.xls

Config = Config or {} 
Config.PrimusData = Config.PrimusData or {}
Config.PrimusData.data_const_key_depth = 1
Config.PrimusData.data_const_length = 7
Config.PrimusData.data_const_lan = "zh"
Config.PrimusData.data_const = {
	["daily_challenge_limit"] = {desc="每日挑战次数限制",val=1599},
	["evolution_limit"] = {desc="进化次数上限",val=1599},
	["game_rule"] = {desc="1.竞技场排名达到指定名次内可挑战神位，3类神位分别对应排名条件为<div fontcolor=289b14>前10名</div>、<div fontcolor=289b14>前20名</div>、<div fontcolor=289b14>前50名</div>\n2.挑战成功后，玩家会取代神位上的Boss，并且获得对应的<div fontcolor=289b14>神位称号</div>，装配称号可享受强大<div fontcolor=289b14>属性加成</div>\n3.若在位玩家被其他挑战者挑战成功，则挑战者则替换该玩家成为新的神位主人，同时丧失神位的玩家称号将失效\n4.每位挑战者只可占有一个神位，在位期间若挑战其他神位成功，将丧失原有的神位\n5.挑战失败将进入<div fontcolor=289b14>20分钟</div>的冷却时间，期间无法挑战任何神位",val=1},
	["lose_challange_cd"] = {desc="挑战失败后的冷却cd",val=1200},
	["open_dun_id"] = {desc="副本开启",val=0},
	["open_lev"] = {desc="达到35级后开启",val=35},
	["redpoint_close_condition"] = {desc="红点关闭的等级",val=60},
}
