-- this file is generated by program!
-- don't change it manaully.
-- source file: privilege_data.xls

Config = Config or {} 
Config.PrivilegeData = Config.PrivilegeData or {}
Config.PrivilegeData.data_privilege_data_ypsdk_key_depth = 1
Config.PrivilegeData.data_privilege_data_ypsdk_length = 6
Config.PrivilegeData.data_privilege_data_ypsdk_lan = "zh"
Config.PrivilegeData.data_privilege_data_ypsdk = {
	[101] = {charge_id=304,desc="捕捉强力宝可梦必购礼包！超值优惠，每周限购一次！",icon_id="10",id=101,limit_day=7,limit_lev=0,limit_type=1,loss=30,name="狩猎球礼包",pay_type=1,sort_id=1,title_type=1},
	[102] = {charge_id=305,desc="搜集资源特权！每天三次免费快速作战，再送捕捉福利！",icon_id="10",id=102,limit_day=30,limit_lev=0,limit_type=1,loss=68,name="快速作战特权",pay_type=1,sort_id=3,title_type=1},
	[103] = {charge_id=0,desc="赏金冒险高级特权，每天首次赏金刷新必出紫色任务！",icon_id="11",id=103,limit_day=0,limit_lev=0,limit_type=0,loss=980,name="赏金高级特权",pay_type=2,sort_id=5,title_type=2},
	[104] = {charge_id=0,desc="赏金冒险豪华特权，每天第3次赏金刷新必出橙色任务！",icon_id="11",id=104,limit_day=0,limit_lev=0,limit_type=0,loss=1980,name="赏金豪华特权",pay_type=2,sort_id=6,title_type=2},
	[105] = {charge_id=307,desc="元素圣殿特权！每天两次额外免费次数，六次购买次数！",icon_id="12",id=105,limit_day=30,limit_lev=90,limit_type=1,loss=30,name="元素圣殿特权",pay_type=1,sort_id=4,title_type=3},
	[106] = {charge_id=310,desc="学习器制造特权！专属制造机，再送极品光盘和制造道具！",icon_id="12",id=106,limit_day=7,limit_lev=80,limit_type=1,loss=30,name="学习器制造特权",pay_type=1,sort_id=2,title_type=0},
}
