-- this file is generated by program!
-- don't change it manaully.
-- source file: privilege_data.xls

Config = Config or {} 
Config.PrivilegeData = Config.PrivilegeData or {}
Config.PrivilegeData.data_fast_combat_cost_key_depth = 1
Config.PrivilegeData.data_fast_combat_cost_length = 8
Config.PrivilegeData.data_fast_combat_cost_lan = "zh"
Config.PrivilegeData.data_fast_combat_cost = {
	[1] = {cost=200},
	[2] = {cost=200},
	[3] = {cost=200},
	[4] = {cost=200},
	[5] = {cost=200},
	[6] = {cost=200},
	[7] = {cost=200},
	[8] = {cost=200},
}
