-- this file is generated by program!
-- don't change it manaully.
-- source file: room_grow_data.xls

Config = Config or {} 
Config.RoomGrowData = Config.RoomGrowData or {}
Config.RoomGrowData.data_const_key_depth = 1
Config.RoomGrowData.data_const_length = 5
Config.RoomGrowData.data_const_lan = "zh"
Config.RoomGrowData.data_const = {
	["bbs_number_limit"] = {desc="每个留言板的最大留言数",key="bbs_number_limit",val=300},
	["bbs_open_limit"] = {desc="35级开启留言板功能",key="bbs_open_limit",val=35},
	["bbs_time_limit"] = {desc="留言冷却时间（秒）",key="bbs_time_limit",val=30},
	["bbs_writing_number"] = {desc="留言字数限制",key="bbs_writing_number",val=36},
	["open_lev_limit"] = {desc="55级开启个成长之路",key="open_lev_limit",val=55},
}
