-- this file is generated by program!
-- don't change it manaully.
-- source file: sky_ladder_data.xls

Config = Config or {} 
Config.SkyLadderData = Config.SkyLadderData or {}
Config.SkyLadderData.data_award_key_depth = 1
Config.SkyLadderData.data_award_length = 12
Config.SkyLadderData.data_award_lan = "zh"
Config.SkyLadderData.data_award = {
	[1] = {max=1,min=1,reward={{21,10000},{38101,12},{50801,1}}},
	[2] = {max=2,min=2,reward={{21,8500},{38101,10},{50802,1}}},
	[3] = {max=3,min=3,reward={{21,7000},{38101,9},{50803,1}}},
	[5] = {max=5,min=4,reward={{21,6000},{38101,8}}},
	[10] = {max=10,min=6,reward={{21,5000},{38101,7}}},
	[20] = {max=20,min=11,reward={{21,4500},{38101,6}}},
	[50] = {max=50,min=21,reward={{21,4000},{38101,5}}},
	[100] = {max=100,min=51,reward={{21,3500},{38101,4}}},
	[200] = {max=200,min=101,reward={{21,3000},{38101,3}}},
	[300] = {max=300,min=201,reward={{21,2500},{38101,2}}},
	[600] = {max=600,min=301,reward={{21,2000},{38101,1}}},
	[1000] = {max=1000,min=601,reward={{21,1500}}},
}
