-- this file is generated by program!
-- don't change it manaully.
-- source file: sprite_data.xls

Config = Config or {} 
Config.SpriteData = Config.SpriteData or {}
Config.SpriteData.data_tree_limit_key_depth = 1
Config.SpriteData.data_tree_limit_length = 4
Config.SpriteData.data_tree_limit_lan = "zh"
Config.SpriteData.data_tree_limit = {
	[1] = 0,
	[2] = 1,
	[3] = 2,
	[4] = 3,
}
