-- this file is generated by program!
-- don't change it manaully.
-- source file: sprite_data.xls

Config = Config or {} 
Config.SpriteData = Config.SpriteData or {}
Config.SpriteData.data_hatch_egg_key_depth = 1
Config.SpriteData.data_hatch_egg_length = 3
Config.SpriteData.data_hatch_egg_lan = "zh"
Config.SpriteData.data_hatch_egg = {
	[10601] = {award={},can_buy=1,desc="普通学习器95% 优良学习器4% 稀有学习期1%",drop_id1={81001},drop_id2={},item_bid=10601,limit_num=30,need_piont=2880,price={{1,1200000}},res_id=2,reset_award={{10601,1}}},
	[10602] = {award={{10040,3}},can_buy=1,desc="普通学习器75% 优良学习器22% 稀有学习器3%",drop_id1={81002},drop_id2={},item_bid=10602,limit_num=5,need_piont=5760,price={{3,300}},res_id=3,reset_award={{10601,2}}},
	[10603] = {award={{10040,6}},can_buy=0,desc="优良学习器92.8% 稀有学习器7.2%<div fontcolor=#e25a00>（15次必出稀有）</div>",drop_id1={81003},drop_id2={},item_bid=10603,limit_num=0,need_piont=8640,price={},res_id=1,reset_award={{10602,2}}},
}
