-- this file is generated by program!
-- don't change it manaully.
-- source file: sprite_data.xls

Config = Config or {} 
Config.SpriteData = Config.SpriteData or {}
Config.SpriteData.data_const_key_depth = 1
Config.SpriteData.data_const_length = 18
Config.SpriteData.data_const_lan = "zh"
Config.SpriteData.data_const = {
	["ancient_desc"] = {desc="1.每个学习器都携带一种<div fontcolor=#32CD32>专属技能</div>，学习器融合可提升技能等级。\n2.玩家可以将学习器依附在洛托姆上，借助洛托姆的属性。\n3.依附在洛托姆上的学习器，将作为特殊作战单位，在战斗中协同作战。\n4.洛托姆升级后可解锁更多供学习器依附的位置。\n5.同名学习器只能依附<div fontcolor=#32CD32>一个</div>在洛托姆身上。\n6.学习器的位置，决定了其技能在战斗中的<div fontcolor=#32CD32>施法顺序</div>。\n7.学习器通过<div fontcolor=#32CD32>学习器制造</div>获取，将空白光盘置于制造机中，等待一段时间随机制造出一张学习器。\n8.通过<div fontcolor=#32CD32>挂机奖励、冠军商店、活动、补充</div>等途径可获得相应数量的光盘。\n9.除了正常制造以外，多余学习器的<div fontcolor=#32CD32>分解</div>也可以转化为洛托姆升级所需的钢铁零件。",val=1},
	["ancient_story"] = {desc="手机洛托姆是一种拥有宝可梦图鉴等强大功能的手机，里面住着可以进入各种电器的宝可梦洛托姆。\n它还有许多非常实用的功能。比如把手机洛托姆装在自行车上后，自行车将不仅能在陆地上快速奔驰，还能够移动于水面之上。\n手机洛托姆除了可以查询宝可梦的属性和生态等信息外，还可以查看自己已经收服的宝可梦。\n因为其强大的记录及模拟功能，在嵌入招式学习器后，洛托姆可以获得该学习器所刻录的技能并在战斗中使用。\n招势学习器镶嵌在手机洛托姆身上，使得洛托姆可以使用该招式与宝可梦协同作战。",val=1},
	["awake_gain"] = {desc="",val=10042},
	["daily_free_gift"] = {desc="特权每日赠送道具",val={{10601,2}}},
	["egg_buy_limit"] = {desc="蛋蛋购买次数/每日",val=1},
	["egg_buy_price"] = {desc="蛋蛋购买价格 （itemid_钻石价格）",val={10603,{{3,2000000}}}},
	["end_time"] = {desc="制造结束时，光效开始播放n毫秒后，请求弹窗。",val=1300},
	["free_programmes"] = {desc="学习器管理方案免费数量",val=2},
	["hatch_desc"] = {desc="Lv.<div fontcolor=#32CD32>0</div>；<div fontcolor=#32CD32>11</div>秒减一点制造点；<div fontcolor=#32CD32>0</div>钻石；需要vip<div fontcolor=#32CD32>0</div>\nLv.<div fontcolor=#32CD32>1</div>；<div fontcolor=#32CD32>10</div>秒减一点制造点；<div fontcolor=#32CD32>100</div>钻石；需要vip<div fontcolor=#32CD32>0</div>\nLv.<div fontcolor=#32CD32>2</div>；<div fontcolor=#32CD32>9</div>秒减一点制造点；<div fontcolor=#32CD32>200</div>钻石；需要vip<div fontcolor=#32CD32>1</div>\nLv.<div fontcolor=#32CD32>3</div>；<div fontcolor=#32CD32>8</div>秒减一点制造点；<div fontcolor=#32CD32>500</div>钻石；需要vip<div fontcolor=#32CD32>3</div>\nLv.<div fontcolor=#32CD32>4</div>；<div fontcolor=#32CD32>7</div>秒减一点制造点；<div fontcolor=#32CD32>800</div>钻石；需要vip<div fontcolor=#32CD32>4</div>\nLv.<div fontcolor=#32CD32>5</div>；<div fontcolor=#32CD32>6</div>秒减一点制造点；<div fontcolor=#32CD32>1200</div>钻石；需要vip<div fontcolor=#32CD32>5</div>\nLv.<div fontcolor=#32CD32>6</div>；<div fontcolor=#32CD32>5</div>秒减一点制造点；<div fontcolor=#32CD32>1600</div>钻石；需要vip<div fontcolor=#32CD32>6</div>",val=1},
	["hatch_rate"] = {desc="制造效率",val=5},
	["programme_add_cost"] = {desc="学习器管理开启方案价格",val={3,300}},
	["prop_buy_limit"] = {desc="加速道具购买次数/每日",val=2},
	["prop_buy_price"] = {desc="加速道具购买价格 (itemid_钻石价格）",val={10701,{{3,100}}}},
	["reborn_exhibition"] = {desc="学习器重生获得预览",val={{39067,1},{10040,1}}},
	["reborn_tips"] = {desc="1.本期限时重生只能选择<div fontcolor=#32CD32>TM-04</div>与<div fontcolor=#32CD32>TM-07</div>,但无法重生一级TM-04与一级TM-07\n2.重生会保留<div fontcolor=#32CD32>1个</div>一级学习器本体\n3.重生返还等同于学习器培养消耗所需本体数量的学习器之魂与全部奥术之尘\n4.学习器之魂能自选兑换除本期重生学习器外的任意现有的橙色学习器\n5.本期活动结束时间：<div fontcolor=#32CD32>2020年1月16号 0点</div>",val=1},
	["sprite_max_star_show"] = {desc="图鉴显示最大星级",val=5},
	["sprite_unlocked_lv"] = {desc="学习器系统将在45级开放",val=45},
	["total_programmes"] = {desc="学习器管理总方案数量",val=10},
}
