-- this file is generated by program!
-- don't change it manaully.
-- source file: stronger_data.xls

Config = Config or {} 
Config.StrongerData = Config.StrongerData or {}
Config.StrongerData.data_problem_key_depth = 1
Config.StrongerData.data_problem_length = 8
Config.StrongerData.data_problem_lan = "zh"
Config.StrongerData.data_problem = {
	[1] = {desc="<div fontcolor=#249003>  →注意职业搭配：</div>\n一个完整的阵容一般可由<div fontcolor=#249003>防御宝可梦</div>（负责保护控制）；<div fontcolor=#249003>物攻、特攻宝可梦</div>（负责制造伤害）；<div fontcolor=#249003>辅助宝可梦</div>（负责治疗增益）这三部分组成\n<div fontcolor=#249003>  →注意种族克制：</div>\n阵营克制效果会在战斗中带来可观的伤害加成，根据敌方种族合理选择其克制种族也是胜利的关键\n<div fontcolor=#249003>  →注意阵型搭配：</div>\n上阵指定种族的宝可梦也可在战斗中获得属性加成，根据自己已有的宝可梦合理搭配阵型也能大幅提高胜率呢；具体搭配可在[宝可梦出战]面板中点击阵营图标查看\n<div fontcolor=#249003>  →注意技能组合：</div>\n大部分宝可梦的技能是可以相互配合的。还有更多厉害的组合等你去发掘~",id=1,name="怎样选择上阵宝可梦？",sort=1},
	[2] = {desc="<div fontcolor=#249003>  →根据我方宝可梦职业：</div>\n可根据实际上阵的宝可梦职业决定。例如上阵了<div fontcolor=#249003>2个防御型宝可梦</div>，推荐使用<div fontcolor=#249003>圣灵阵</div>，从而加强对我方其他宝可梦的保护\n<div fontcolor=#249003>  →根据对手的阵容：</div>\n还可根据对手上阵的宝可梦来决定。对于某些特定的AOE伤害（如妙蛙种子的飞叶快刀：攻击敌方前两排所有宝可梦），通过<div fontcolor=#249003>调整站位</div>来规避此类控制技能\n<div fontcolor=#249003>  →更换阵法：</div>\n若遇到打不过的战斗，调整阵法再战可能会有奇效哦",id=2,name="如何选择阵法？",sort=6},
	[3] = {desc="<div fontcolor=#249003>→进化的好处：</div>\n  进化能大幅提升宝可梦的属性；同时进化也是提升宝可梦技能等级的唯一途径\n<div fontcolor=#249003>→如何进化：</div>\n  前往城镇界面中的[宝可研究所]，选择你想进化的宝可梦，根据提示放入其他指定宝可梦就可以进化啦；6星宝可梦可在宝可梦培养界面中直接进行进化操作哦~\n<div fontcolor=#249003>→友情提示：</div>\n  因为一股神秘的力量，导致不是所有宝可梦都能升到最高星级呢，培养宝可梦的时候可要注意啦",id=3,name="如何给宝可梦进化？",sort=2},
	[4] = {desc="<div fontcolor=#249003>  →</div>每日免费的<div fontcolor=#249003>捕捉、点金和快速作战</div>千万别错过啦\n<div fontcolor=#249003>  →</div>每日可在<div fontcolor=#249003>冒险</div>中挑战伊布的宝藏副本、参与各种玩法可获得各种收益\n<div fontcolor=#249003>  →</div>每日在竞技场给排行榜中的玩家点赞也可获得金币哦\n<div fontcolor=#249003>  →</div>加入联盟，消耗贡献学习联盟技能也能让宝可梦获得极大的提升\n<div fontcolor=#249003>  →</div>最重要的[挂机收益]可别忘记每天上线领取哦~",id=4,name="如何让我的小伙伴快速成长？",sort=3},
	[5] = {desc="1.灼烧、流血、诅咒、中毒\n   每回合受到固定伤害，叠加的层数越多，伤害越高\n2.眩晕、石化、冰冻、睡眠、麻痹\n   宝可梦无法行动\n3.封印\n   携带该状态的单位无法产生暴击，被动技能无法触发\n4.虚弱\n   携带该状态的单位停止行动1回合，该状态不可叠加\n5.沉默\n   携带该状态的单位无法使用技能\n6.嘲讽\n   携带该状态的单位将强制只用普攻攻击嘲讽者\n7.技能效果的命中率\n   技能效果的实际命中率=效果命中属性-效果抵抗属性\n8.Buff的叠加规则\n   同类Buff默认不叠加，可叠加的Buff将在Buff描述中特殊说明；\n   某些Buff在与其他同类Buff共存时只生效最强的1个（例如破甲），且预览中只显示其中1层（因此当宝可梦身上其中1层该类Buff被“驱散”或“嫁祸转移”后，依然会显示1层）",id=5,name="宝可梦的各种技能效果有什么作用？",sort=7},
	[6] = {desc="<div fontcolor=#249003>→出手顺序</div>\n每回合开始时，根据场中单位<div fontcolor=#249003>速度高低</div>，决定本回合的出手顺序，过程中改变速度，会在下一回合开始时影响出手顺序\n（注：急冻鸟战斗开始时的减速，第一回合就会生效）",id=6,name="战斗中宝可梦的出手顺序是怎样的？",sort=8},
	[7] = {desc="<div fontcolor=#249003>→角色经验的获取：</div>\n  剧情战斗、剧情挂机和快速作战是获取角色经验的唯一途径，达到的关卡数越高，挂机获得的角色经验越多\n<div fontcolor=#249003>→快速作战相关：</div>\n  快速作战可<div fontcolor=#249003>直接获得120分钟的挂机收益</div>，是获得角色经验的捷径哦\n<div fontcolor=#249003>→特别提示：</div>\n  Vip等级越高，每次挂机获得的各项收益也就越高哦；购买<div fontcolor=#249003>快速作战特权</div>后每日可获得3次免费快速作战次数，还能额外购买11次作速作战，想要快速升级的冒险者大人千万不能错过啦",id=7,name="如何快速提升角色升级？",sort=4},
	[8] = {desc="<div fontcolor=#249003>→快速作战：</div>\n  每次快速作战都能直接获得120分钟的挂机收益，小助手建议每日都买满哦~\n<div fontcolor=#249003>→日常副本：</div>\n  使用钻石购买日常副本次数也是很划算的哦\n<div fontcolor=#249003>→赏金订单：</div>\n  若遇到不想要赏金订单，那就放心用钻石去刷新吧，更好的奖励等着你呢\n<div fontcolor=#249003>→联盟副本：</div>\n  购买次数加速副本的推进，从而更快的获得联盟贡献哦，另外自己的伤害排名越高，获得的联盟贡献也越多呢\n<div fontcolor=#249003>→特别提示：</div>\n  特权商城的赏金礼包一定要记得购买哦；达到VIP2后每日还能购买超值高级捕捉球1个~",id=8,name="钻石如何使用性价比最高？",sort=5},
}
