-- this file is generated by program!
-- don't change it manaully.
-- source file: stronger_data.xls

Config = Config or {} 
Config.StrongerData = Config.StrongerData or {}
Config.StrongerData.data_stronger_two_key_depth = 1
Config.StrongerData.data_stronger_two_length = 7
Config.StrongerData.data_stronger_two_lan = "zh"
Config.StrongerData.data_stronger_two = {
	[1] = {desc="简单的培养，适合前期发展",evt_type=203,icon=1001,id=1,limit={{"lev",1}},name="宝可梦等级",sort=1},
	[2] = {desc="穿戴装备可迅速提升实力",evt_type=203,icon=1006,id=2,limit={{"lev",1}},name="装备穿戴",sort=2},
	[3] = {desc="大幅提升战力的关键",evt_type=203,icon=1007,id=3,limit={{"lev",1}},name="宝可梦星级",sort=3},
	[4] = {desc="前期提升战力的关键",evt_type=203,icon=1005,id=4,limit={{"lev",1}},name="宝可梦进阶",sort=4},
	[5] = {desc="提升训练师伤害和属性加成",evt_type=201,icon=1004,id=5,limit={{"lev",1}},name="训练师培养",sort=5},
	[6] = {desc="后期最强属性增幅",evt_type=202,icon=1003,id=6,limit={{"lev",1}},name="联盟技能",sort=6},
	[7] = {desc="宝可梦可获额外被动技能",evt_type=203,icon=1002,id=7,limit={{"lev",1}},name="宝石培养",sort=7},
}
