-- this file is generated by program!
-- don't change it manaully.
-- source file: subtitle_data.xls

Config = Config or {} 
Config.SubtitleData = Config.SubtitleData or {}
Config.SubtitleData.data_const_key_depth = 1
Config.SubtitleData.data_const_length = 6
Config.SubtitleData.data_const_lan = "zh"
Config.SubtitleData.data_const = {
	["sub_color"] = {desc="弹幕颜色编号(color表)",key="sub_color",val={91,97}},
	["sub_cost"] = {desc="弹幕发送消耗(银币)",key="sub_cost",val=500},
	["sub_font"] = {desc="弹幕字体大小",key="sub_font",val={25,30}},
	["sub_space"] = {desc="弹幕间隔(秒)",key="sub_space",val=2},
	["sub_speed"] = {desc="弹幕速度",key="sub_speed",val={8,14}},
	["subcircle_space"] = {desc="弹幕循环间隔(秒)",key="subcircle_space",val=3},
}
