-- this file is generated by program!
-- don't change it manaully.
-- source file: subtitle_data.xls

Config = Config or {} 
Config.SubtitleData = Config.SubtitleData or {}
Config.SubtitleData.data_system_key_depth = 2
Config.SubtitleData.data_system_length = 3
Config.SubtitleData.data_system_lan = "zh"
Config.SubtitleData.data_system = {
	[101] = {
		[1] = {msg="666666666"},
		[2] = {msg="23333"},
		[3] = {msg="一边拉满幸福美满"},
		[4] = {msg="冲冲冲"},
		[5] = {msg="参与竞猜，赢取大量冠军积分可以去商城兑换奖励哦"},
	},
	[102] = {
		[1] = {msg="666666666"},
		[2] = {msg="23333"},
		[3] = {msg="一边拉满幸福美满"},
		[4] = {msg="冲冲冲"},
		[5] = {msg="参与竞猜，赢取大量冠军币可以去商城兑换奖励哦"},
	},
	[103] = {
		[1] = {msg="晚上八点半正式开打，再问吃屁"},
		[2] = {msg="世纪大战么，感觉这里能见到好多大佬"},
		[3] = {msg="三局两胜是指第一队打第一队，第二队打第二队！"},
		[4] = {msg="商店奖励好像很不错的样子~"},
		[5] = {msg="请各位懂事，让我们多拿竞猜币~"},
		[6] = {msg="一天一局，不慌哈哈"},
	},
}
