-- this file is generated by program!
-- don't change it manaully.
-- source file: training_camp_data.xls

Config = Config or {} 
Config.TrainingCampData = Config.TrainingCampData or {}
Config.TrainingCampData.data_city_tips_key_depth = 1
Config.TrainingCampData.data_city_tips_length = 12
Config.TrainingCampData.data_city_tips_lan = "zh"
Config.TrainingCampData.data_city_tips = {
	[1] = {desc="这儿有变强攻略哦~",id=1},
	[2] = {desc="今天天气真好~",id=2},
	[3] = {desc="ヾ(*´∀`)ﾉ 啦啦啦~♪",id=3},
	[4] = {desc="良好的策略搭配是\n制胜的关键！",id=4},
	[5] = {desc="哼哼~想我了吧？",id=5},
	[6] = {desc="你是宝可梦大陆的希望！",id=6},
	[7] = {desc="高输出类宝可梦往往\n很脆弱，需要防御\n或辅助宝可梦保护！",id=7},
	[8] = {desc="哼哼，超市中可\n以刷到超便宜的道\n具呢~",id=8},
	[9] = {desc="超市和道具商\n城位于城镇中，\n多去逛逛哦！",id=9},
	[10] = {desc="别忘了每周的竞技\n场挑战奖励哦~",id=10},
	[11] = {desc="锻造屋可以助你打\n造更强力的装备和\n宝石！",id=11},
	[12] = {desc="精彩活动奖励多多，\n等着你来参与！~",id=12},
}
