-- this file is generated by program!
-- don't change it manaully.
-- source file: vip_data.xls

Config = Config or {} 
Config.VipData = Config.VipData or {}
Config.VipData.data_get_vip_icon_key_depth = 1
Config.VipData.data_get_vip_icon_length = 5
Config.VipData.data_get_vip_icon_lan = "zh"
Config.VipData.data_get_vip_icon = {
	[5] = {fun_id=900,vip_lev=5},
	[8] = {fun_id=901,vip_lev=8},
	[12] = {fun_id=902,vip_lev=12},
	[13] = {fun_id=903,vip_lev=13},
	[14] = {fun_id=904,vip_lev=14},
}
