-- this file is generated by program!
-- don't change it manaully.
-- source file: week_act_data.xls

Config = Config or {} 
Config.WeekActData = Config.WeekActData or {}
Config.WeekActData.data_info_key_depth = 1
Config.WeekActData.data_info_length = 13
Config.WeekActData.data_info_lan = "zh"
Config.WeekActData.data_info = {
	[11001] = {bid=11001,ico="11001",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=1,action_type=2,sort_val=1,type="",type_ico=11001,title="灵泉培育"},
	[11002] = {bid=11002,ico="3",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=2,action_type=2,sort_val=2,type="",type_ico=3,title="灵泉任务"},
	[11003] = {bid=11003,ico="11003",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=3,action_type=2,sort_val=3,type="",type_ico=11003,title="灵泉商城"},
	[11004] = {bid=11004,ico="11004",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=4,action_type=2,sort_val=4,type="",type_ico=11004,title="灵泉兑换"},
	[11005] = {bid=11005,ico="11005",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=6,action_type=1,sort_val=1,type="",type_ico=11005,title="地宫探险"},
	[11006] = {bid=11006,ico="3",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=2,action_type=1,sort_val=2,type="",type_ico=3,title="地宫任务"},
	[11007] = {bid=11007,ico="11007",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=3,action_type=1,sort_val=3,type="",type_ico=11007,title="地宫商城"},
	[11008] = {bid=11008,ico="11008",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=4,action_type=1,sort_val=4,type="",type_ico=11008,title="地宫兑换"},
	[11009] = {bid=11009,ico="11009",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=7,action_type=3,sort_val=1,type="",type_ico=11009,title="石室之旅"},
	[11010] = {bid=11010,ico="3",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=2,action_type=3,sort_val=2,type="",type_ico=3,title="石室任务"},
	[11011] = {bid=11011,ico="11011",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=3,action_type=3,sort_val=3,type="",type_ico=11011,title="石室商城"},
	[11012] = {bid=11012,ico="11012",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=4,action_type=3,sort_val=4,type="",type_ico=11012,title="石室兑换"},
	[11013] = {bid=11013,ico="11013",is_verifyios=0,items={},open_lev={{"lev",10}},panel_type=5,action_type=0,sort_val=5,type="",type_ico=11013,title="活动预告"},
}
