---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/2/28 17:50
---

FreeCaptureModel = FreeCaptureModel or BaseClass()

function FreeCaptureModel:__init(ctrl)
    self.ctrl = ctrl
    self:config()
end

function FreeCaptureModel:config()
end


function FreeCaptureModel:__delete()
end