-- Automatically generated, do not edit
Config.db_filter_words [7501]  = {words= [[顔清標]] }
Config.db_filter_words [7502]  = {words= [[顔慶章]] }
Config.db_filter_words [7503]  = {words= [[顔射]] }
Config.db_filter_words [7504]  = {words= [[讞]] }
Config.db_filter_words [7505]  = {words= [[央視內部晚會]] }
Config.db_filter_words [7506]  = {words= [[陽痿]] }
Config.db_filter_words [7507]  = {words= [[楊懷安]] }
Config.db_filter_words [7508]  = {words= [[楊建利]] }
Config.db_filter_words [7509]  = {words= [[楊巍]] }
Config.db_filter_words [7510]  = {words= [[楊月清]] }
Config.db_filter_words [7511]  = {words= [[楊周]] }
Config.db_filter_words [7512]  = {words= [[姚羅]] }
Config.db_filter_words [7513]  = {words= [[姚月謙]] }
Config.db_filter_words [7514]  = {words= [[軺]] }
Config.db_filter_words [7515]  = {words= [[藥材商人蘇耐得]] }
Config.db_filter_words [7516]  = {words= [[藥水]] }
Config.db_filter_words [7517]  = {words= [[野鶏]] }
Config.db_filter_words [7518]  = {words= [[葉菊蘭]] }
Config.db_filter_words [7519]  = {words= [[夜話紫禁城]] }
Config.db_filter_words [7520]  = {words= [[一陀糞]] }
Config.db_filter_words [7521]  = {words= [[㈠]] }
Config.db_filter_words [7522]  = {words= [[伊莎貝爾]] }
Config.db_filter_words [7523]  = {words= [[伊斯蘭亞格林尼斯]] }
Config.db_filter_words [7524]  = {words= [[遺精]] }
Config.db_filter_words [7525]  = {words= [[議長阿茵斯塔]] }
Config.db_filter_words [7526]  = {words= [[議員斯格文德]] }
Config.db_filter_words [7527]  = {words= [[异見人士]] }
Config.db_filter_words [7528]  = {words= [[异型叛軍]] }
Config.db_filter_words [7529]  = {words= [[异議人士]] }
Config.db_filter_words [7530]  = {words= [[易丹軒]] }
Config.db_filter_words [7531]  = {words= [[意志不堅的圖騰]] }
Config.db_filter_words [7532]  = {words= [[瘞]] }
Config.db_filter_words [7533]  = {words= [[陰門]] }
Config.db_filter_words [7534]  = {words= [[陰囊]] }
Config.db_filter_words [7535]  = {words= [[淫貨]] }
Config.db_filter_words [7536]  = {words= [[尹慶民]] }
Config.db_filter_words [7537]  = {words= [[引導]] }
Config.db_filter_words [7538]  = {words= [[隱者之路]] }
Config.db_filter_words [7539]  = {words= [[鷹眼派氏族]] }
Config.db_filter_words [7540]  = {words= [[硬直圖騰]] }
Config.db_filter_words [7541]  = {words= [[憂鬱的艾拉]] }
Config.db_filter_words [7542]  = {words= [[尤比亞]] }
Config.db_filter_words [7543]  = {words= [[由喜貴]] }
Config.db_filter_words [7544]  = {words= [[游蕩的僵尸]] }
Config.db_filter_words [7545]  = {words= [[游蕩的士兵]] }
Config.db_filter_words [7546]  = {words= [[游蕩爪牙]] }
Config.db_filter_words [7547]  = {words= [[游錫坤]] }
Config.db_filter_words [7548]  = {words= [[游戲管理員]] }
Config.db_filter_words [7549]  = {words= [[友好的魯德]] }
Config.db_filter_words [7550]  = {words= [[幼龍]] }
Config.db_filter_words [7551]  = {words= [[于幼軍]] }
Config.db_filter_words [7552]  = {words= [[余英時]] }
Config.db_filter_words [7553]  = {words= [[漁夫菲斯曼]] }
Config.db_filter_words [7554]  = {words= [[輿論]] }
Config.db_filter_words [7555]  = {words= [[輿論反制]] }
Config.db_filter_words [7556]  = {words= [[傴]] }
Config.db_filter_words [7557]  = {words= [[宇明網]] }
Config.db_filter_words [7558]  = {words= [[齬]] }
Config.db_filter_words [7559]  = {words= [[飫]] }
Config.db_filter_words [7560]  = {words= [[鵒]] }
Config.db_filter_words [7561]  = {words= [[元老蘭提(沃德）]] }
Config.db_filter_words [7562]  = {words= [[緣圈圈]] }
Config.db_filter_words [7563]  = {words= [[遠志明]] }
Config.db_filter_words [7564]  = {words= [[月經]] }
Config.db_filter_words [7565]  = {words= [[韞]] }
Config.db_filter_words [7566]  = {words= [[鏨]] }
Config.db_filter_words [7567]  = {words= [[造愛]] }
Config.db_filter_words [7568]  = {words= [[則民]] }
Config.db_filter_words [7569]  = {words= [[擇民]] }
Config.db_filter_words [7570]  = {words= [[澤夫]] }
Config.db_filter_words [7571]  = {words= [[澤民]] }
Config.db_filter_words [7572]  = {words= [[賾]] }
Config.db_filter_words [7573]  = {words= [[賊民]] }
Config.db_filter_words [7574]  = {words= [[譖]] }
Config.db_filter_words [7575]  = {words= [[扎卡維是英雄]] }
Config.db_filter_words [7576]  = {words= [[驏]] }
Config.db_filter_words [7577]  = {words= [[張伯笠]] }
Config.db_filter_words [7578]  = {words= [[張博雅]] }
Config.db_filter_words [7579]  = {words= [[張鋼]] }
Config.db_filter_words [7580]  = {words= [[張健]] }
Config.db_filter_words [7581]  = {words= [[張林]] }
Config.db_filter_words [7582]  = {words= [[張清芳]] }
Config.db_filter_words [7583]  = {words= [[張溫鷹]] }
Config.db_filter_words [7584]  = {words= [[張昭富]] }
Config.db_filter_words [7585]  = {words= [[張志清]] }
Config.db_filter_words [7586]  = {words= [[章孝嚴]] }
Config.db_filter_words [7587]  = {words= [[帳號]] }
Config.db_filter_words [7588]  = {words= [[賬號]] }
Config.db_filter_words [7589]  = {words= [[招鶏]] }
Config.db_filter_words [7590]  = {words= [[趙海青]] }
Config.db_filter_words [7591]  = {words= [[趙建銘]] }
Config.db_filter_words [7592]  = {words= [[趙南]] }
Config.db_filter_words [7593]  = {words= [[趙品潞]] }
Config.db_filter_words [7594]  = {words= [[趙曉微]] }
Config.db_filter_words [7595]  = {words= [[貞操]] }
Config.db_filter_words [7596]  = {words= [[爭鳴論壇]] }
Config.db_filter_words [7597]  = {words= [[正見網]] }
Config.db_filter_words [7598]  = {words= [[正義黨論壇]] }
Config.db_filter_words [7599]  = {words= [[㊣]] }
Config.db_filter_words [7600]  = {words= [[鄭寶清]] }
Config.db_filter_words [7601]  = {words= [[鄭麗文]] }
Config.db_filter_words [7602]  = {words= [[鄭義]] }
Config.db_filter_words [7603]  = {words= [[鄭餘鎮]] }
Config.db_filter_words [7604]  = {words= [[鄭源]] }
Config.db_filter_words [7605]  = {words= [[鄭運鵬]] }
Config.db_filter_words [7606]  = {words= [[政權]] }
Config.db_filter_words [7607]  = {words= [[縶]] }
Config.db_filter_words [7608]  = {words= [[躑]] }
Config.db_filter_words [7609]  = {words= [[指點江山論壇]] }
Config.db_filter_words [7610]  = {words= [[騭]] }
Config.db_filter_words [7611]  = {words= [[觶]] }
Config.db_filter_words [7612]  = {words= [[躓]] }
Config.db_filter_words [7613]  = {words= [[中毒的圖騰]] }
Config.db_filter_words [7614]  = {words= [[中毒圖騰]] }
Config.db_filter_words [7615]  = {words= [[中俄邊界]] }
Config.db_filter_words [7616]  = {words= [[中國復興論壇]] }
Config.db_filter_words [7617]  = {words= [[中國共産黨]] }
Config.db_filter_words [7618]  = {words= [[中國孤兒院]] }
Config.db_filter_words [7619]  = {words= [[中國和平]] }
Config.db_filter_words [7620]  = {words= [[中國論壇]] }
Config.db_filter_words [7621]  = {words= [[中國社會進步黨]] }
Config.db_filter_words [7622]  = {words= [[中國社會論壇]] }
Config.db_filter_words [7623]  = {words= [[中國威脅論]] }
Config.db_filter_words [7624]  = {words= [[中國問題論壇]] }
Config.db_filter_words [7625]  = {words= [[中國移動通信]] }
Config.db_filter_words [7626]  = {words= [[中國真實內容]] }
Config.db_filter_words [7627]  = {words= [[中國猪]] }
Config.db_filter_words [7628]  = {words= [[中華大地]] }
Config.db_filter_words [7629]  = {words= [[中華大衆]] }
Config.db_filter_words [7630]  = {words= [[中華講清]] }
Config.db_filter_words [7631]  = {words= [[中華民國]] }
Config.db_filter_words [7632]  = {words= [[中華人民實話實說]] }
Config.db_filter_words [7633]  = {words= [[中華人民正邪]] }
Config.db_filter_words [7634]  = {words= [[中華時事]] }
Config.db_filter_words [7635]  = {words= [[中華養生益智功]] }
Config.db_filter_words [7636]  = {words= [[中華真實報道]] }
Config.db_filter_words [7637]  = {words= [[鐘山風雨論壇]] }
Config.db_filter_words [7638]  = {words= [[周鋒鎖]] }
Config.db_filter_words [7639]  = {words= [[周守訓]] }
Config.db_filter_words [7640]  = {words= [[朱鳳芝]] }
Config.db_filter_words [7641]  = {words= [[朱立倫]] }
Config.db_filter_words [7642]  = {words= [[朱溶劑]] }
Config.db_filter_words [7643]  = {words= [[㈱]] }
Config.db_filter_words [7644]  = {words= [[猪聾畸]] }
Config.db_filter_words [7645]  = {words= [[主攻指揮官]] }
Config.db_filter_words [7646]  = {words= [[主義]] }
Config.db_filter_words [7647]  = {words= [[助手威爾特]] }
Config.db_filter_words [7648]  = {words= [[顓]] }
Config.db_filter_words [7649]  = {words= [[轉化]] }
Config.db_filter_words [7650]  = {words= [[諑]] }
Config.db_filter_words [7651]  = {words= [[資本主義]] }
Config.db_filter_words [7652]  = {words= [[鯔]] }
Config.db_filter_words [7653]  = {words= [[自民黨]] }
Config.db_filter_words [7654]  = {words= [[自由民主論壇]] }
Config.db_filter_words [7655]  = {words= [[總理]] }
Config.db_filter_words [7656]  = {words= [[諏]] }
Config.db_filter_words [7657]  = {words= [[鯫]] }
Config.db_filter_words [7658]  = {words= [[躦]] }
Config.db_filter_words [7659]  = {words= [[纘]] }
Config.db_filter_words [7660]  = {words= [[bcd.s.59764.com]] }
Config.db_filter_words [7661]  = {words= [[kkk.xaoh.cn]] }
Config.db_filter_words [7662]  = {words= [[www.xaoh.cn]] }
Config.db_filter_words [7663]  = {words= [[zzz.xaoh.cn]] }
Config.db_filter_words [7664]  = {words= [[aa.yazhousetu.hi.9705.net.cn]] }
Config.db_filter_words [7665]  = {words= [[eee.xaoh.cn]] }
Config.db_filter_words [7666]  = {words= [[lll.xaoh.cn]] }
Config.db_filter_words [7667]  = {words= [[jj.pangfangwuyuetian.hi.9705.net.cn]] }
Config.db_filter_words [7668]  = {words= [[rrr.xaoh.cn]] }
Config.db_filter_words [7669]  = {words= [[ooo.xaoh.cn]] }
Config.db_filter_words [7670]  = {words= [[www.zy528.com]] }
Config.db_filter_words [7671]  = {words= [[aaad.s.59764.com]] }
Config.db_filter_words [7672]  = {words= [[www.dy6789.cn]] }
Config.db_filter_words [7673]  = {words= [[aaac.s.51524.com]] }
Config.db_filter_words [7674]  = {words= [[208.43.198.56]] }
Config.db_filter_words [7675]  = {words= [[166578.cn]] }
Config.db_filter_words [7676]  = {words= [[www.wang567.com]] }
Config.db_filter_words [7677]  = {words= [[www.bin5.cn]] }
Config.db_filter_words [7678]  = {words= [[www.sanjidianying.com.cn]] }
Config.db_filter_words [7679]  = {words= [[www.anule.cn]] }
Config.db_filter_words [7680]  = {words= [[www.976543.com]] }
Config.db_filter_words [7681]  = {words= [[www.50spcombaidu1828adyou97sace.co.cc]] }
Config.db_filter_words [7682]  = {words= [[chengrenmanhua.1242.net.cn]] }
Config.db_filter_words [7683]  = {words= [[qingsewuyuetian.1174.net.cn]] }
Config.db_filter_words [7684]  = {words= [[lunlidianyingxiazai.1174.net.cn]] }
Config.db_filter_words [7685]  = {words= [[siwameitui.1274.net.cn]] }
Config.db_filter_words [7686]  = {words= [[niuniujidi.1174.net.cn]] }
Config.db_filter_words [7687]  = {words= [[xiao77.1243.net.cn]] }
Config.db_filter_words [7688]  = {words= [[woyinwose.1243.net.cn]] }
Config.db_filter_words [7689]  = {words= [[dingxiang.1249.net]] }
Config.db_filter_words [7690]  = {words= [[cnaicheng.1174.net.cn]] }
Config.db_filter_words [7691]  = {words= [[1234chengren.1249.net.cn]] }
Config.db_filter_words [7692]  = {words= [[sewuyuetian.1174.net.cn]] }
Config.db_filter_words [7693]  = {words= [[huangsexiaoshuo.1242.net.cn]] }
Config.db_filter_words [7694]  = {words= [[lunlidianying.1274.net.cn]] }
Config.db_filter_words [7695]  = {words= [[xingqingzhongren.1174.net.cn]] }
Config.db_filter_words [7696]  = {words= [[chengrenwangzhi.1242.net.cn]] }
Config.db_filter_words [7697]  = {words= [[xiao77luntan.1249.net.cn]] }
Config.db_filter_words [7698]  = {words= [[dingxiang.1243.net.cn]] }
Config.db_filter_words [7699]  = {words= [[11xp.1243.net.cn]] }
Config.db_filter_words [7700]  = {words= [[baijie.1249.net.cn]] }
Config.db_filter_words [7701]  = {words= [[sewuyuetian.1274.net.cn]] }
Config.db_filter_words [7702]  = {words= [[meiguiqingren.1274.net.cn]] }
Config.db_filter_words [7703]  = {words= [[tb.hi.4024.net.cn]] }
Config.db_filter_words [7704]  = {words= [[www.91wangyou.com]] }
Config.db_filter_words [7705]  = {words= [[www.wow366.cn]] }
Config.db_filter_words [7706]  = {words= [[www.yxnpc.com]] }
Config.db_filter_words [7707]  = {words= [[www.365jw.com]] }
Config.db_filter_words [7708]  = {words= [[58.253.67.74]] }
Config.db_filter_words [7709]  = {words= [[www.978808.com]] }
Config.db_filter_words [7710]  = {words= [[www.sexwyt.com]] }
Config.db_filter_words [7711]  = {words= [[7GG]] }
Config.db_filter_words [7712]  = {words= [[www.567yx.com]] }
Config.db_filter_words [7713]  = {words= [[131.com]] }
Config.db_filter_words [7714]  = {words= [[bbs.7gg.cn]] }
Config.db_filter_words [7715]  = {words= [[www.99game.net]] }
Config.db_filter_words [7716]  = {words= [[ppt.cc]] }
Config.db_filter_words [7717]  = {words= [[www.zsyxhd.cn]] }
Config.db_filter_words [7718]  = {words= [[www.foyeye.com]] }
Config.db_filter_words [7719]  = {words= [[www.23nice.com.cn]] }
Config.db_filter_words [7720]  = {words= [[www.maituan.com]] }
Config.db_filter_words [7721]  = {words= [[www.ylteam.cn]] }
Config.db_filter_words [7722]  = {words= [[www.yhzt.org]] }
Config.db_filter_words [7723]  = {words= [[vip886.com]] }
Config.db_filter_words [7724]  = {words= [[www.neicehao.cn]] }
Config.db_filter_words [7725]  = {words= [[bbs.butcn.com]] }
Config.db_filter_words [7726]  = {words= [[www.gamelifeclub.cn]] }
Config.db_filter_words [7727]  = {words= [[consignment5173]] }
Config.db_filter_words [7728]  = {words= [[www.70yx.com]] }
Config.db_filter_words [7729]  = {words= [[www.legu.com]] }
Config.db_filter_words [7730]  = {words= [[ko180]] }
Config.db_filter_words [7731]  = {words= [[bbs.pkmmo]] }
Config.db_filter_words [7732]  = {words= [[whoyo.com]] }
Config.db_filter_words [7733]  = {words= [[www.2q5q.com]] }
Config.db_filter_words [7734]  = {words= [[www.zxkaku.cn]] }
Config.db_filter_words [7735]  = {words= [[www.gw17173.cn]] }
Config.db_filter_words [7736]  = {words= [[www.315ts.net]] }
Config.db_filter_words [7737]  = {words= [[qgqm.org]] }
Config.db_filter_words [7738]  = {words= [[17173dl.net]] }
Config.db_filter_words [7739]  = {words= [[i9game.com]] }
Config.db_filter_words [7740]  = {words= [[365gn]] }
Config.db_filter_words [7741]  = {words= [[158le.com]] }
Config.db_filter_words [7742]  = {words= [[1100y.com]] }
Config.db_filter_words [7743]  = {words= [[bulaoge.com]] }
Config.db_filter_words [7744]  = {words= [[17youle.com]] }
Config.db_filter_words [7745]  = {words= [[reddidi.com.cn]] }
Config.db_filter_words [7746]  = {words= [[icpcn.com]] }
Config.db_filter_words [7747]  = {words= [[ul86.com]] }
Config.db_filter_words [7748]  = {words= [[showka8.com]] }
Config.db_filter_words [7749]  = {words= [[szlmgh.cn]] }
Config.db_filter_words [7750]  = {words= [[bbs.766.com]] }
Config.db_filter_words [7751]  = {words= [[www.766.com]] }
Config.db_filter_words [7752]  = {words= [[91bysd.cn]] }
Config.db_filter_words [7753]  = {words= [[jiayyou.cn]] }
Config.db_filter_words [7754]  = {words= [[gigabyte.cn]] }
Config.db_filter_words [7755]  = {words= [[duowan]] }
Config.db_filter_words [7756]  = {words= [[wgxiaowu.com]] }
Config.db_filter_words [7757]  = {words= [[youxiji888.cn]] }
Config.db_filter_words [7758]  = {words= [[yz55.cn]] }
Config.db_filter_words [7759]  = {words= [[Carrefour]] }
Config.db_filter_words [7760]  = {words= [[51jiafen.cn]] }
Config.db_filter_words [7761]  = {words= [[597ft.com]] }
Config.db_filter_words [7762]  = {words= [[itnongzhuang.com2y7v.cnhwxvote.cn]] }
Config.db_filter_words [7763]  = {words= [[92klgh.cn]] }
Config.db_filter_words [7764]  = {words= [[xiaoqinzaixian.cn]] }
Config.db_filter_words [7765]  = {words= [[661661.com]] }
Config.db_filter_words [7766]  = {words= [[haosilu.com]] }
Config.db_filter_words [7767]  = {words= [[dl.com]] }
Config.db_filter_words [7768]  = {words= [[xl517.com]] }
Config.db_filter_words [7769]  = {words= [[sjlike.com]] }
Config.db_filter_words [7770]  = {words= [[tont.cn]] }
Config.db_filter_words [7771]  = {words= [[xq-wl.cn]] }
Config.db_filter_words [7772]  = {words= [[feitengdl.com]] }
Config.db_filter_words [7773]  = {words= [[bz176.com]] }
Config.db_filter_words [7774]  = {words= [[dadati.com]] }
Config.db_filter_words [7775]  = {words= [[asgardcn.com]] }
Config.db_filter_words [7776]  = {words= [[dolbbs.com]] }
Config.db_filter_words [7777]  = {words= [[okaygood.cn]] }
Config.db_filter_words [7778]  = {words= [[1t1t.com]] }
Config.db_filter_words [7779]  = {words= [[jinpaopao.com]] }
Config.db_filter_words [7780]  = {words= [[blacksee.com.cn]] }
Config.db_filter_words [7781]  = {words= [[1qmsj.com]] }
Config.db_filter_words [7782]  = {words= [[202333.com]] }
Config.db_filter_words [7783]  = {words= [[luoxialu.cn]] }
Config.db_filter_words [7784]  = {words= [[37447.cn]] }
Config.db_filter_words [7785]  = {words= [[567567aa.cn]] }
Config.db_filter_words [7786]  = {words= [[09city.com]] }
Config.db_filter_words [7787]  = {words= [[71ka.com]] }
Config.db_filter_words [7788]  = {words= [[fy371.com]] }
Config.db_filter_words [7789]  = {words= [[365tttyx.com]] }
Config.db_filter_words [7790]  = {words= [[host800.com]] }
Config.db_filter_words [7791]  = {words= [[lybbs.info]] }
Config.db_filter_words [7792]  = {words= [[ys168.com]] }
Config.db_filter_words [7793]  = {words= [[88mysf.com]] }
Config.db_filter_words [7794]  = {words= [[5d6d.com]] }
Config.db_filter_words [7795]  = {words= [[id666.uqc.cn]] }
Config.db_filter_words [7796]  = {words= [[stlmbbs.cn]] }
Config.db_filter_words [7797]  = {words= [[pcikchina.com]] }
Config.db_filter_words [7798]  = {words= [[lxsm888.com]] }
Config.db_filter_words [7799]  = {words= [[wangyoudl.com]] }
Config.db_filter_words [7800]  = {words= [[chinavfx.net]] }
Config.db_filter_words [7801]  = {words= [[zxsj188.com]] }
Config.db_filter_words [7802]  = {words= [[wg7766.cn]] }
Config.db_filter_words [7803]  = {words= [[e7sw.cn]] }
Config.db_filter_words [7804]  = {words= [[jooplay.com]] }
Config.db_filter_words [7805]  = {words= [[gssmtt.com]] }
Config.db_filter_words [7806]  = {words= [[likeko.com]] }
Config.db_filter_words [7807]  = {words= [[lyx-game.cn]] }
Config.db_filter_words [7808]  = {words= [[wy33.com]] }
Config.db_filter_words [7809]  = {words= [[zy666.net]] }
Config.db_filter_words [7810]  = {words= [[newsmth.net]] }
Config.db_filter_words [7811]  = {words= [[l2jsom.cn]] }
Config.db_filter_words [7812]  = {words= [[13888wg.com]] }
Config.db_filter_words [7813]  = {words= [[qtoy.com]] }
Config.db_filter_words [7814]  = {words= [[1000scarf.com]] }
Config.db_filter_words [7815]  = {words= [[digitallongking.com]] }
Config.db_filter_words [7816]  = {words= [[zaixu.net]] }
Config.db_filter_words [7817]  = {words= [[ncyh.cn]] }
Config.db_filter_words [7818]  = {words= [[888895.com]] }
Config.db_filter_words [7819]  = {words= [[ising99.com]] }
Config.db_filter_words [7820]  = {words= [[cikcatv.2om]] }
Config.db_filter_words [7821]  = {words= [[parke888.com]] }
Config.db_filter_words [7822]  = {words= [[01gh.com]] }
Config.db_filter_words [7823]  = {words= [[gogo.net]] }
Config.db_filter_words [7824]  = {words= [[uu1001.com]] }
Config.db_filter_words [7825]  = {words= [[wy724.com]] }
Config.db_filter_words [7826]  = {words= [[prettyirene.net]] }
Config.db_filter_words [7827]  = {words= [[yaokong7.com]] }
Config.db_filter_words [7828]  = {words= [[zzmysf.com]] }
Config.db_filter_words [7829]  = {words= [[52sxhy.cn]] }
Config.db_filter_words [7830]  = {words= [[92wydl.com]] }
Config.db_filter_words [7831]  = {words= [[g365.net]] }
Config.db_filter_words [7832]  = {words= [[pkmmo.com]] }
Config.db_filter_words [7833]  = {words= [[52ppsa.cn]] }
Config.db_filter_words [7834]  = {words= [[bl62.com]] }
Config.db_filter_words [7835]  = {words= [[canyaa.com]] }
Config.db_filter_words [7836]  = {words= [[lordren.com]] }
Config.db_filter_words [7837]  = {words= [[xya3.cn]] }
Config.db_filter_words [7838]  = {words= [[5m5m5m.com]] }
Config.db_filter_words [7839]  = {words= [[www.gardcn.com]] }
Config.db_filter_words [7840]  = {words= [[www.sf766.com.cn]] }
Config.db_filter_words [7841]  = {words= [[ent365.com]] }
Config.db_filter_words [7842]  = {words= [[18900.com]] }
Config.db_filter_words [7843]  = {words= [[7mmo.com]] }
Config.db_filter_words [7844]  = {words= [[cdream.com]] }
Config.db_filter_words [7845]  = {words= [[wy3868.com]] }
Config.db_filter_words [7846]  = {words= [[nbfib.cn]] }
Config.db_filter_words [7847]  = {words= [[17173yxdl.cn]] }
Config.db_filter_words [7848]  = {words= [[osisa.cn]] }
Config.db_filter_words [7849]  = {words= [[haouse.cn]] }
Config.db_filter_words [7850]  = {words= [[54hero.com]] }
Config.db_filter_words [7851]  = {words= [[ieboy.cn]] }
Config.db_filter_words [7852]  = {words= [[geocities.com]] }
Config.db_filter_words [7853]  = {words= [[xiuau.cn]] }
Config.db_filter_words [7854]  = {words= [[cvceo.com]] }
Config.db_filter_words [7855]  = {words= [[fxjsqc.com]] }
Config.db_filter_words [7856]  = {words= [[thec.cn]] }
Config.db_filter_words [7857]  = {words= [[c5c8.cn]] }
Config.db_filter_words [7858]  = {words= [[a33.com]] }
Config.db_filter_words [7859]  = {words= [[qqsg.org]] }
Config.db_filter_words [7860]  = {words= [[my3q.com]] }
Config.db_filter_words [7861]  = {words= [[51juezhan.com]] }
Config.db_filter_words [7862]  = {words= [[kartt.cn]] }
Config.db_filter_words [7863]  = {words= [[hexun.com]] }
Config.db_filter_words [7864]  = {words= [[15wy.com]] }
Config.db_filter_words [7865]  = {words= [[13ml.net]] }
Config.db_filter_words [7866]  = {words= [[homexf.cn]] }
Config.db_filter_words [7867]  = {words= [[xyxgh.com]] }
Config.db_filter_words [7868]  = {words= [[jdyou.com]] }
Config.db_filter_words [7869]  = {words= [[langyou.info]] }
Config.db_filter_words [7870]  = {words= [[duowan.com]] }
Config.db_filter_words [7871]  = {words= [[8188mu.com]] }
Config.db_filter_words [7872]  = {words= [[tianlong4f.cn]] }
Config.db_filter_words [7873]  = {words= [[yeswm.com]] }
Config.db_filter_words [7874]  = {words= [[wgbobo.cn]] }
Config.db_filter_words [7875]  = {words= [[haog8.cn]] }
Config.db_filter_words [7876]  = {words= [[47513.cn]] }
Config.db_filter_words [7877]  = {words= [[92ey.com]] }
Config.db_filter_words [7878]  = {words= [[hao1788.co]] }
Config.db_filter_words [7879]  = {words= [[mgjzybj.com]] }
Config.db_filter_words [7880]  = {words= [[xdns.eu]] }
Config.db_filter_words [7881]  = {words= [[shenycs.co]] }
Config.db_filter_words [7882]  = {words= [[mpceggs.cn]] }
Config.db_filter_words [7883]  = {words= [[kod920.cn]] }
Config.db_filter_words [7884]  = {words= [[njgamecollege.org]] }
Config.db_filter_words [7885]  = {words= [[51hdw.com]] }
Config.db_filter_words [7886]  = {words= [[025game.cn]] }
Config.db_filter_words [7887]  = {words= [[bibidu.com]] }
Config.db_filter_words [7888]  = {words= [[bwowd.com]] }
Config.db_filter_words [7889]  = {words= [[3kwow.com]] }
Config.db_filter_words [7890]  = {words= [[zx002.com]] }
Config.db_filter_words [7891]  = {words= [[bazhuwg.cn]] }
Config.db_filter_words [7892]  = {words= [[991game.com]] }
Config.db_filter_words [7893]  = {words= [[zuanshi1000.cn]] }
Config.db_filter_words [7894]  = {words= [[10mb.cn]] }
Config.db_filter_words [7895]  = {words= [[Huihuangtx.com]] }
Config.db_filter_words [7896]  = {words= [[chongxianmu.cn]] }
Config.db_filter_words [7897]  = {words= [[any2000.com]] }
Config.db_filter_words [7898]  = {words= [[99sa.com]] }
Config.db_filter_words [7899]  = {words= [[zhidian8.com]] }
Config.db_filter_words [7900]  = {words= [[t9wg.cn]] }
Config.db_filter_words [7901]  = {words= [[bobaoping]] }
Config.db_filter_words [7902]  = {words= [[qixingnet.com]] }
Config.db_filter_words [7903]  = {words= [[88kx.com]] }
Config.db_filter_words [7904]  = {words= [[00sm.cn]] }
Config.db_filter_words [7905]  = {words= [[moyi520.cn]] }
Config.db_filter_words [7906]  = {words= [[d666.com]] }
Config.db_filter_words [7907]  = {words= [[fisonet.com]] }
Config.db_filter_words [7908]  = {words= [[0571qq.com]] }
Config.db_filter_words [7909]  = {words= [[173at.com]] }
Config.db_filter_words [7910]  = {words= [[pk200.com]] }
Config.db_filter_words [7911]  = {words= [[2feiche.cn]] }
Config.db_filter_words [7912]  = {words= [[jjdlw.com]] }
Config.db_filter_words [7913]  = {words= [[xyq2sf.com]] }
Config.db_filter_words [7914]  = {words= [[69nb.com]] }
Config.db_filter_words [7915]  = {words= [[txwsWind]] }
Config.db_filter_words [7916]  = {words= [[jiayyou.com]] }
Config.db_filter_words [7917]  = {words= [[胡总书记]] }
Config.db_filter_words [7918]  = {words= [[胡景涛]] }
Config.db_filter_words [7919]  = {words= [[大纪元]] }
Config.db_filter_words [7920]  = {words= [[大纪元新闻网]] }
Config.db_filter_words [7921]  = {words= [[燕玲论坛]] }
Config.db_filter_words [7922]  = {words= [[urban]] }
Config.db_filter_words [7923]  = {words= [[cao]] }
Config.db_filter_words [7924]  = {words= [[他妈的]] }
Config.db_filter_words [7925]  = {words= [[urban-rivals]] }
Config.db_filter_words [7926]  = {words= [[rivals]] }
Config.db_filter_words [7927]  = {words= [[UR]] }
Config.db_filter_words [7928]  = {words= [[ur]] }
Config.db_filter_words [7929]  = {words= [[她妈]] }
Config.db_filter_words [7930]  = {words= [[牛B]] }
Config.db_filter_words [7931]  = {words= [[日你妈]] }
Config.db_filter_words [7932]  = {words= [[不玩了]] }
Config.db_filter_words [7933]  = {words= [[删号]] }
Config.db_filter_words [7934]  = {words= [[卖号]] }
Config.db_filter_words [7935]  = {words= [[草你妈]] }
Config.db_filter_words [7936]  = {words= [[T.M.D]] }
Config.db_filter_words [7937]  = {words= [[jb]] }
Config.db_filter_words [7938]  = {words= [[出售账号]] }
Config.db_filter_words [7939]  = {words= [[出售此号]] }
Config.db_filter_words [7940]  = {words= [[U/R]] }
Config.db_filter_words [7941]  = {words= [[U-R]] }
Config.db_filter_words [7942]  = {words= [[j8]] }
Config.db_filter_words [7943]  = {words= [[吗的]] }
Config.db_filter_words [7944]  = {words= [[8仙]] }
Config.db_filter_words [7945]  = {words= [[出售神符]] }
Config.db_filter_words [7946]  = {words= [[黄色]] }
Config.db_filter_words [7947]  = {words= [[NPC]] }
Config.db_filter_words [7948]  = {words= [[*法*轮*功*]] }
Config.db_filter_words [7949]  = {words= [[*李*洪*志*阿扁]] }
Config.db_filter_words [7950]  = {words= [[阿拉]] }
Config.db_filter_words [7951]  = {words= [[挨球]] }
Config.db_filter_words [7952]  = {words= [[安全局]] }
Config.db_filter_words [7953]  = {words= [[澳洲光明网]] }
Config.db_filter_words [7954]  = {words= [[八九]] }
Config.db_filter_words [7955]  = {words= [[八九风波]] }
Config.db_filter_words [7956]  = {words= [[办理文凭]] }
Config.db_filter_words [7957]  = {words= [[办理证件]] }
Config.db_filter_words [7958]  = {words= [[包皮]] }
Config.db_filter_words [7959]  = {words= [[保钓]] }
Config.db_filter_words [7960]  = {words= [[保监会]] }
Config.db_filter_words [7961]  = {words= [[保密局]] }
Config.db_filter_words [7962]  = {words= [[鸨]] }
Config.db_filter_words [7963]  = {words= [[鲍岳桥]] }
Config.db_filter_words [7964]  = {words= [[暴动]] }
Config.db_filter_words [7965]  = {words= [[暴乱]] }
Config.db_filter_words [7966]  = {words= [[暴徒]] }
Config.db_filter_words [7967]  = {words= [[北京之春]] }
Config.db_filter_words [7968]  = {words= [[贝肉]] }
Config.db_filter_words [7969]  = {words= [[本?拉登]] }
Config.db_filter_words [7970]  = {words= [[苯比]] }
Config.db_filter_words [7971]  = {words= [[笨屄]] }
Config.db_filter_words [7972]  = {words= [[笨逼]] }
Config.db_filter_words [7973]  = {words= [[逼你老母]] }
Config.db_filter_words [7974]  = {words= [[比毛]] }
Config.db_filter_words [7975]  = {words= [[宾周]] }
Config.db_filter_words [7976]  = {words= [[波霸]] }
Config.db_filter_words [7977]  = {words= [[博讯]] }
Config.db_filter_words [7978]  = {words= [[薄一波]] }
Config.db_filter_words [7979]  = {words= [[布雷尔]] }
Config.db_filter_words [7980]  = {words= [[财政部]] }
Config.db_filter_words [7981]  = {words= [[参事室]] }
Config.db_filter_words [7982]  = {words= [[操GM]] }
Config.db_filter_words [7983]  = {words= [[操Gm]] }
Config.db_filter_words [7984]  = {words= [[操gM]] }
Config.db_filter_words [7985]  = {words= [[操gm]] }
Config.db_filter_words [7986]  = {words= [[操XX]] }
Config.db_filter_words [7987]  = {words= [[交媾]] }
Config.db_filter_words [7988]  = {words= [[CAO]] }
Config.db_filter_words [7989]  = {words= [[小姐兼职]] }
Config.db_filter_words [7990]  = {words= [[西藏314事件]] }
Config.db_filter_words [7991]  = {words= [[新疆7.5事件]] }
Config.db_filter_words [7992]  = {words= [[毛片]] }
Config.db_filter_words [7993]  = {words= [[黄片]] }
Config.db_filter_words [7994]  = {words= [[交配]] }
Config.db_filter_words [7995]  = {words= [[茉莉花革命]] }
Config.db_filter_words [7996]  = {words= [[操你八辈祖宗]] }
Config.db_filter_words [7997]  = {words= [[操你妈屄]] }
Config.db_filter_words [7998]  = {words= [[草的你妈]] }
Config.db_filter_words [7999]  = {words= [[草妈]] }
Config.db_filter_words [8000]  = {words= [[草拟妈]] }
