-- Automatically generated, do not edit
-- Generated by parse_enum.go

enum = {

	ACCOUNT = {

		ACCOUNT_NM = 1, -- Normal player

		ACCOUNT_GM = 2, -- GM

	},

	CAREER = {

		CAREER_SWORDMAN = 1, -- Swordsman

		CAREER_KNIGHT = 2, -- Knight

	},

	GENDER = {

		GENDER_MALE = 1, -- Male

		GENDER_FEMALE = 2, -- Female

	},

	COLOR = {

		COLOR_WHITE = 1, -- White

		COLOR_GREEN = 2, -- Green

		COLOR_BLUE = 3, -- Blue

		COLOR_PURPLE = 4, -- Violet

		COLOR_ORANGE = 5, -- Orange

		COLOR_RED = 6, -- Red

		COLOR_PINK = 7, -- Pink

	},

	MAIL_TYPE = {

		MAIL_TYPE_PERSON = 1, -- Personal Mail

		MAIL_TYPE_SYSTEM = 2, -- System Mail

		MAIL_TYPE_REFUND = 3, -- 封测返还

	},

	ITEM_TYPE = {

		ITEM_TYPE_EQUIP = 1, -- Gear

		ITEM_TYPE_STONE = 2, -- Gem

		ITEM_TYPE_EQUIP_BEAST = 3, -- Beast Gear

		ITEM_TYPE_EQUIP_BABY = 4, -- Baby Toy

		ITEM_TYPE_ILLUSTRATION = 5, -- Atlas

		ITEM_TYPE_EQUIP_GOD = 6, -- Hallow

		ITEM_TYPE_TASK = 8, -- Quest

		ITEM_TYPE_MONEY = 9, -- Currency

		ITEM_TYPE_MISC = 10, -- Misc

		ITEM_TYPE_STONE2 = 11, -- Crystal

		ITEM_TYPE_EQUIP_MECHA = 12, -- Mecha Gear

		ITEM_TYPE_PET_EQUIP = 13, -- Pet Gear

		ITEM_TYPE_ARTI_EQUIP = 14, -- Divine equipment

		ITEM_TYPE_TOTEMS_EQUIP = 15, -- Totem equipment

	},

	ITEM_STYPE = {

		ITEM_STYPE_WEAPON = 1001, -- Weapon

		ITEM_STYPE_DEPUTY = 1002, -- Off-hand

		ITEM_STYPE_NECK = 1003, -- Necklace

		ITEM_STYPE_RING1 = 1004, -- Ring

		ITEM_STYPE_RING2 = 1005, -- Amulet

		ITEM_STYPE_HELMET = 1006, -- Helmet

		ITEM_STYPE_CLOTH = 1007, -- Chestpiece

		ITEM_STYPE_PANTS = 1008, -- Legging

		ITEM_STYPE_GLOVE = 1009, -- Gauntlet

		ITEM_STYPE_SHOES = 1010, -- Shoes

		ITEM_STYPE_FAIRY = 1011, -- Phantom

		ITEM_STYPE_LOCK = 1012, -- Wedding Ring

		ITEM_STYPE_FAIRY2 = 1013, -- Nightmare

		ITEM_STYPE_HEAD = 4001, -- Bamboo Dragonfly

		ITEM_STYPE_LEFT_HAND = 4002, -- Toy Car

		ITEM_STYPE_RIGHT_HAND = 4003, -- Cotton Jacket

		ITEM_STYPE_BACK = 4004, -- Schoolbag

		ITEM_STYPE_LOIN = 4005, -- Amulet

		ITEM_STYPE_BOOTS = 4006, -- Duck Shoes

		ITEM_STYPE_GOD_EQUIP_HEAD = 5001, -- Godly Crown

		ITEM_STYPE_GOD_EQUIP_RING = 5002, -- Avatar Pendant

		ITEM_STYPE_GOD_EQUIP_FRONT = 5003, -- Godly Rope

		ITEM_STYPE_GOD_EQUIP_HUFU = 5004, -- Avatar Right Ring

		ITEM_STYPE_GOD_EQUIP_HAND = 5005, -- Avatar Bracelets

		ITEM_STYPE_GOD_EQUIP_WEAPON = 5006, -- Godly Amulet

		ITEM_STYPE_GOD_EQUIP_GLOVE = 5007, -- Avatar Gaunlets

		ITEM_STYPE_GOD_EQUIP_LEG = 5008, -- Deity Leggings

		ITEM_STYPE_GOD_EQUIP_WING = 5009, -- Godly Right Wing

		ITEM_STYPE_GOD_EQUIP_SHOE = 5010, -- Avatar Boots

		ITEM_STYPE_ILLUSTRATION = 6001, -- Atlas

		ITEM_STYPE_MECHA_EQUIP_SHIELD = 7001, -- Protective Cover

		ITEM_STYPE_MECHA_EQUIP_PROPELLER = 7002, -- Thruster

		ITEM_STYPE_MECHA_EQUIP_ENGINE = 7003, -- Engine

		ITEM_STYPE_MECHA_EQUIP_RADAR = 7004, -- Radar

		ITEM_STYPE_MECHA_EQUIP_CORE = 7005, -- Mecha Core

		ITEM_STYPE_HORNS = 3001, -- Beast Horn

		ITEM_STYPE_EYES = 3002, -- Eye

		ITEM_STYPE_TUSH = 3003, -- Fang

		ITEM_STYPE_PAW = 3004, -- Claw

		ITEM_STYPE_SCUTE = 3005, -- Scale

		ITEM_STYPE_PET_EQUIP_HUFU = 8001, -- Pet Helmat

		ITEM_STYPE_PET_EQUIP_HAND = 8002, -- Pet Spirit

		ITEM_STYPE_PET_EQUIP_RING = 8003, -- Pet Claw

		ITEM_STYPE_PET_EQUIP_WEAPON = 8004, -- Pet Necklace

		ITEM_STYPE_LEVEL = 10001, -- Upgrade Pill

		ITEM_STYPE_EXP = 10002, -- Fixed EXP Pill

		ITEM_STYPE_GOLD = 10003, -- Ingot Card

		ITEM_STYPE_BGOLD = 10004, -- Bound Ingot Card

		ITEM_STYPE_COIN = 10005, -- Gold Card

		ITEM_STYPE_BCOIN = 10006, -- Bound Gold Card

		ITEM_STYPE_FAME = 10007, -- Fame Card

		ITEM_STYPE_HONOR = 10008, -- Glory Card

		ITEM_STYPE_FEAT = 10009, -- Feat Card

		ITEM_STYPE_MANA = 10010, -- Prestige Card

		ITEM_STYPE_CTRB = 10011, -- Guild Contribution Card

		ITEM_STYPE_ILLUS_ESSENCE = 10012, -- Atlas Essence Card

		ITEM_STYPE_MC_EXP = 10012, -- Soul Card Dust

		ITEM_STYPE_MC_EXCH = 10013, -- Soul Card Shard

		ITEM_STYPE_MC_FUSE = 10014, -- Combined Soul Crystal

		ITEM_STYPE_MC_HUNT = 10015, -- Hunting Energy

		ITEM_STYPE_EXP2 = 10016, -- EXP Upgrade Pill

		ITEM_STYPE_EXP3 = 10017, -- Level EXP Pill

		ITEM_STYPE_PETJH = 10018, -- Pet Essence Card

		ITEM_STYPE_EXP4 = 10019, -- Level EXP Pill

		ITEM_STYPE_SOUL_EXP = 10022, -- Stigmata EXP

		ITEM_STYPE_SOUL_EXCH = 10023, -- Combine Stigmata

		ITEM_STYPE_SOUL_FUSE = 10024, -- Advance Stigmata

		ITEM_STYPE_CLOTHES = 10070, -- Costume

		ITEM_STYPE_TITLE = 10071, -- Title

		ITEM_STYPE_GIFT = 10080, -- Pack

		ITEM_STYPE_FLOWER = 10081, -- Flower

		ITEM_STYPE_FIREWORK = 10082, -- Firework

		ITEM_STYPE_LEVEL_GIFT = 10083, -- Level Pack

		ITEM_STYPE_MOUNT_EXP = 10101, -- Mount EXP Pill

		ITEM_STYPE_WING_EXP = 10102, -- Wings EXP Pill

		ITEM_STYPE_TALIS_EXP = 10103, -- Relic EXP Pill

		ITEM_STYPE_WEAPON_EXP = 10104, -- Artifact EXP Pill

		ITEM_STYPE_OFFHAND_EXP = 10105, -- Off hand EXP Pill

		ITEM_STYPE_GOD_EXP = 10106, -- Avatar EXP Pill

		ITEM_STYPE_MECHA_EXP = 10107, -- Mecha EXP Pill

		ITEM_STYPE_MOUNT_ATTR = 10121, -- Mount Attribute Pill

		ITEM_STYPE_OFFHAND_ATTR = 10122, -- Off hand Attribute Pill

		ITEM_STYPE_MOUNT_MORPH = 10141, -- Mount Morph

		ITEM_STYPE_WING_MORPH = 10142, -- Wings Morph

		ITEM_STYPE_TALIS_MORPH = 10143, -- Relic Morph

		ITEM_STYPE_WEAPON_MORPH = 10144, -- Artifact Morph

		ITEM_STYPE_OFFHAND_MORPH = 10145, -- Off hand Morph

		ITEM_STYPE_BABY_WING_MORPH = 10146, -- Baby Wings Morph

		ITEM_STYPE_MECHA_MORPH = 10147, -- Mecha Morph

		ITEM_STYPE_EXP_CARD = 10151, -- EXP Card

		ITEM_STYPE_VIP_CARD = 10152, -- VIP Card

		ITEM_STYPE_AFK = 10153, -- Auto Card

		ITEM_STYPE_MAGICCARD = 10154, -- Soul Card

		ITEM_STYPE_SUITSTONE = 10155, -- Set Stone

		ITEM_STYPE_BEASTSTONE = 10160, -- Mythical Beast Stone

		ITEM_STYPE_OTHERS = 10163, -- Sundries

		ITEM_STYPE_GUILDBOSS = 10165, -- Guild Summon Boss

		ITEM_STYPE_BOSS_TIRED = 10166, -- World Boss Fatigue

		ITEM_STYPE_DUNGE_BUY = 10167, -- Dungeon Ticket

		ITEM_STYPE_BAG_EXP = 10168, -- Smelting EXP Pill

		ITEM_STYPE_MC_GIFT = 10169, -- Soul Card Pack

		ITEM_STYPE_GUILD_CARD = 10170, -- Guild Rename Card

		ITEM_STYPE_PAY_CARD = 10171, -- Recharge Card

		ITEM_STYPE_BUFF = 10172, -- buff

		ITEM_STYPE_CHARACTER_CARD = 10173, -- Character Rename Card

		ITEM_STYPE_BEAST_TIRED = 10174, -- Beast Boss Fatigue

		ITEM_STYPE_BABY_BORN = 10175, -- Baby Activation Item

		ITEM_STYPE_GOD_MORPH = 10177, -- Deity Morph Shard

		ITEM_STYPE_SOUL = 10179, -- Stigmata

		ITEM_STYPE_MECHA_MORPH_SUIPIAN = 10180, -- Mecha Morph

		ITEM_STYPE_PET_EQUIP = 10182, -- Pet Gear Material

		ITEM_STYPE_VIP2_CARD = 10183, -- vip2激活卡

		ITEM_STYPE_PET = 10201, -- Pet

		ITEM_STYPE_PET_EGG = 10202, -- Pet Egg

	},

	ITEM = {

		ITEM_LEVEL = 90010001, -- Level

		ITEM_EXP = 90010002, -- EXP

		ITEM_GOLD = 90010003, -- Diamond

		ITEM_BGOLD = 90010004, -- Bound Diamond

		ITEM_COIN = 90010005, -- Gold

		ITEM_BCOIN = 90010006, -- Bound Gold

		ITEM_FAME = 90010007, -- Fame

		ITEM_HONOR = 90010008, -- Glory

		ITEM_FEAT = 90010009, -- Feat

		ITEM_MANA = 90010010, -- Prestige

		ITEM_CONTRIB = 90010011, -- Guild Contribution

		ITEM_MC_EXP = 90010012, -- Soul Card Dust

		ITEM_MC_EXCH = 90010013, -- Soul Card Shard

		ITEM_MC_FUSE = 90010014, -- Combined Soul Crystal

		ITEM_MC_HUNT = 90010015, -- Hunting Energy

		ITEM_GUILD_FUND = 90010016, -- Guild Fund

		ITEM_WEEKLY_ACT = 90010017, -- Weekly Activity

		ITEM_PLAYER_EXP = 90010018, -- Level EXP

		ITEM_WORLDLV_EXP = 90010019, -- World Level EXP

		ITEM_PET_CREAM = 90010020, -- Pet Essence

		ITEM_INTEGRAL = 90010021, -- Hunting Points

		ITEM_SOUL_EXP = 90010022, -- Stigmata EXP

		ITEM_SOUL_EXCH = 90010023, -- Combine Stigmata

		ITEM_SOUL_FUSE = 90010024, -- Advance Stigmata

		ITEM_TALENT = 90010025, -- Talent Points

		ITEM_BOSSFEN = 90010026, -- Boss Points

		ITEM_BABY = 90010027, -- Baby Essence

		ITEM_ILLUS_ESSENCE = 90010028, -- Atlas Essence

		ITEM_ARENA_MONEY = 90010029, -- Ring Coin

		ITEM_GOD_MONEY = 90010030, -- Deity Essence

		ITEM_MECHA_MONEY = 90010031, -- Titanium Alloy

		ITEM_MEDAL = 90010033, -- Medal

		ITEM_PETEQUIP_EXP = 90010034, -- Pet Gear EXP

		ITEM_GREEN_DRILL = 90010035, -- Market Currency Green Diamond

		ITEM_ELEMENT_1 = 90010037, -- 元素1

		ITEM_ELEMENT_2 = 90010038, -- 元素2

		ITEM_ELEMENT_3 = 90010039, -- 元素3

		ITEM_ELEMENT_4 = 90010040, -- 元素4

		ITEM_ELEMENT_5 = 90010041, -- 元素5

		ITEM_ARTIFACT_EXP = 90010042, -- Artifact Enhance EXP

		ITEM_EXPADD = 90019001, -- EXP Update

		ITEM_EXPCOEF = 90019002, -- EXP Factor

		ITEM_SHOES = 11001, -- Talaria

		ITEM_GRAIN = 30010001, -- Food

		ITEM_DICE_RANDOM = 13200, -- 大富豪普通骰子

		ITEM_DICE_FIXED = 13201, -- 大富豪固定骰子

	},

	ATTR_TYPE = {

		ATTR_TYPE_BASE = 1, -- Basic Sys Attr.

		ATTR_TYPE_WEAPON = 2, -- Weapon Sys Attr.

		ATTR_TYPE_ARMOR = 3, -- Armor Sys Attr.

		ATTR_TYPE_JEWEL = 4, -- Accessory Sys Attr.

		ATTR_TYPE_NORMAL = 5, -- Normal Sys Attr.

	},

	ATTR = {

		ATTR_HP = 1, -- Current HP

		ATTR_HPMAX = 2, -- HP

		ATTR_SPEED = 3, -- Speed (pixel/s), multiplier of 20

		ATTR_ATT = 4, -- ATK

		ATTR_DEF = 5, -- DEF

		ATTR_WRECK = 6, -- Penetration

		ATTR_HIT = 7, -- Accuracy

		ATTR_MISS = 8, -- Dodge

		ATTR_CRIT = 9, -- Crit

		ATTR_TOUGH = 10, -- TEN

		ATTR_HOLY_ATT = 11, -- M. ATK

		ATTR_HOLY_DEF = 12, -- M. DEF

		ATTR_DMG_AMP = 13, -- Attack Boost

		ATTR_DMG_RED = 14, -- Damage Reduction

		ATTR_HIT_PRO = 15, -- Hit Chance

		ATTR_MISS_PRO = 16, -- Dodge Rate

		ATTR_ARMOR_PRO = 17, -- Avatar Armor

		ATTR_ARMOR_STR = 18, -- Armor Penetration

		ATTR_BLOCK_PRO = 19, -- Block Rate

		ATTR_BLOCK_STR = 20, -- Pierce

		ATTR_CRIT_PRO = 21, -- Crit Rate

		ATTR_CRIT_RES = 22, -- Crit Resistance

		ATTR_HEART_PRO = 23, -- Concentrated Strike Rate

		ATTR_HEART_RES = 24, -- Concentrated Strike Resistance

		ATTR_CRIT_DMG = 25, -- Crit Damage

		ATTR_HEART_DMG = 26, -- Concentrated Strike Damage

		ATTR_SKILL_AMP = 27, -- Increased Skill Damage

		ATTR_SKILL_RED = 28, -- Skill Damage Reduction

		ATTR_THUMP_PRO = 29, -- Strike Rate

		ATTR_WEAK_PRO = 30, -- Chance of Weakening

		ATTR_CRIT_RED = 31, -- Crit DMG Reduction

		ATTR_HEW_AMP = 32, -- ATK DMG Increase

		ATTR_BLOCK_RED = 33, -- Block DMG Reduction

		ATTR_PVP_RED = 34, -- PVP Damage Resistance

		ATTR_PVP_ARMOR_PRO = 35, -- PVP Avatar Armor

		ATTR_PVP_ARMOR_STR = 36, -- PVP Armor Penetration

		ATTR_BOSS_AMP = 37, -- Boss DMG Increase

		ATTR_CREEP_AMP = 38, -- Mob DMG Increase

		ATTR_SKILL_ATT_POWER = 39, -- Skill CP of the Attack

		ATTR_SKILL_DEF_POWER = 40, -- Skill CP of the Defense

		ATTR_DMG_RED_S = 41, -- Damage Reduction

		ATTR_PVP_RED_S = 42, -- PVP Damage Resistance

		ATTR_HEART_RED = 43, -- Concentrated Strike Resistance

		ATTR_POWER = 44, -- CP

		ATTR_ABS_ATT = 45, -- Absolute Attack

		ATTR_ABS_MISS = 46, -- Absolute Doge

		ATTR_ALL_GP = 1100, -- Total Attribute Percentage (Overall)

		ATTR_HPMAX_GP = 1102, -- HP Bonus

		ATTR_SPEED_GP = 1103, -- Speed Bonus

		ATTR_ATT_GP = 1104, -- Attack Bonus

		ATTR_DEF_GP = 1105, -- DEF Bonus

		ATTR_WRECK_GP = 1106, -- Penetration Bonus

		ATTR_HIT_GP = 1107, -- Accuracy Bonus

		ATTR_MISS_GP = 1108, -- Dodge Bonus

		ATTR_CRIT_GP = 1109, -- Crit Bonus

		ATTR_TOUGH_GP = 1110, -- TEN Bonus

		ATTR_HOLY_ATT_GP = 1111, -- M. ATK Bonus

		ATTR_HOLY_DEF_GP = 1112, -- M. DEF Bonus

		ATTR_ALL_PP = 1200, -- Total Attribute Percentage (Partial)

		ATTR_HPMAX_PP = 1202, -- HP

		ATTR_ATT_PP = 1204, -- ATK

		ATTR_DEF_PP = 1205, -- DEF

		ATTR_WRECK_PP = 1206, -- Penetration

		ATTR_HIT_PP = 1207, -- Accuracy

		ATTR_MISS_PP = 1208, -- Dodge

		ATTR_CRIT_PP = 1209, -- Crit

		ATTR_TOUGH_PP = 1210, -- TEN

		ATTR_HOLY_ATT_PP = 1211, -- M. ATK

		ATTR_HOLY_DEF_PP = 1212, -- M. DEF

		ATTR_HPMAX_BP = 1302, -- Basic HP

		ATTR_ATT_BP = 1304, -- Basic Attack

		ATTR_DEF_BP = 1305, -- Basic Defense

		ATTR_WRECK_BP = 1306, -- Basic Penetration

		ATTR_ATT_WP = 1404, -- Weapon Attack

		ATTR_WRECK_WP = 1406, -- Weapon Penetration

		ATTR_HPMAX_AP = 1502, -- Armor HP

		ATTR_DEF_AP = 1505, -- Armor DEF

		ATTR_ATT_JP = 1604, -- Accessory ATK

		ATTR_EXP_PER = 2000, -- EXP Bonus

		ATTR_GOLD_DROP = 2001, -- Gold Drop Rate

		ATTR_ITEM_DROP = 2002, -- Drop rate

		ATTR_EQUIP_DEF = 2003, -- Increase defense every 3 levels

		ATTR_EQUIP_HPMAX = 2004, -- Increase HP every 3 levels

		ATTR_EQUIP_ATT = 2005, -- Increase attack every 3 levels

		ATTR_TARGET_ATT = 2006, -- Increase attack by 10 each level

		ATTR_TARGET_BOSS_AMP = 2007, -- Increase damage done to bosses by 2% every 50 levels

		ATTR_SKILLCD_RED = 2009, -- Decrease skill CD percentage

		ATTR_TARGET_ES = 2010, -- Enhancement Bonus

		ATTR_MECHA_SHIELD = 2011, -- Mecha Shield

		ATTR_ENCHANT = 2012, -- 神器附灵百分比属性

	},

	EVENT = {

		EVENT_LEVEL = 1, -- Upgrade

		EVENT_TALK = 2, -- Talk

		EVENT_CREEP = 3, -- Mob Fight

		EVENT_DUNGE = 4, -- Stage

		EVENT_ITEM = 5, -- Collect items

		EVENT_EQUIP = 6, -- Gear

		EVENT_TASK = 7, -- Complete Quest

		EVENT_FLOWER = 8, -- Send Flower

		EVENT_DUNGE_FLOOR = 9, -- Stage Levels

		EVENT_DUNGE_ENTER = 10, -- Enter Stage

		EVENT_ATTR = 11, -- Attribute changes

		EVENT_POWER = 12, -- CP increased

		EVENT_EQUIP_STRENGTH = 13, -- Enhance Gear

		EVENT_ESCORT = 14, -- Polar Cross

		EVENT_WAKE = 15, -- Awaken

		EVENT_PAY = 16, -- Recharge

		EVENT_TRAIN_ORDER = 17, -- Training System Advance

		EVENT_MORPH_STAR = 18, -- Morph System Advance

		EVENT_COLLECT = 19, -- Collect

		EVENT_ACHIEVE = 20, -- Achievement Points

		EVENT_DUNGE_STAR = 21, -- Difficulty

		EVENT_RANK = 22, -- Leaderboard Rank

		EVENT_MC_POWER = 23, -- Soul Card CP

		EVENT_COMPOSE = 24, -- Item Combine

		EVENT_LIVENESS = 25, -- Activity

		EVENT_FRIEND = 26, -- Add Friend

		EVENT_STONE = 27, -- Socket Gem

		EVENT_GUILD_JOIN = 28, -- Join a Guild

		EVENT_EQUIP_SMELT = 29, -- Devour Gear

		EVENT_MARKET_SALE = 30, -- Sell

		EVENT_GUILD_DONATE = 31, -- Guild Donation

		EVENT_ARENA = 32, -- Arena Rank

		EVENT_PET_COMPOSE = 33, -- Pet Fusion

		EVENT_VIPLV = 34, -- Improve VIP

		EVENT_STONE_UPGRADE = 35, -- Gem Upgrade

		EVENT_BEAST_LOAD = 36, -- Put on Beast Gear

		EVENT_PET_GET = 37, -- Pet gains

		EVENT_SEARCH_TREASURE = 38, -- Gear Hunting

		EVENT_MC_HUNT = 39, -- Soul Card Hunt

		EVENT_VIP_CARD = 40, -- Buy VIP Card

		EVENT_INVEST = 41, -- Buy Investment Plan

		EVENT_MARRY = 42, -- Get Married

		EVENT_CONSUME = 43, -- Consumption

		EVENT_VIP_MCARD = 44, -- Buy Monthly Card

		EVENT_YY_ACT = 45, -- Operation Event

		EVENT_WELFARE_GRAIL = 46, -- Daily Prayer

		EVENT_LOGIN = 47, -- Login

		EVENT_YY_SEARCH = 48, -- Treasure Hunt

		EVENT_GUILD_CREATE = 49, -- Create

		EVENT_GUILD_APPOINT = 50, -- Appoint

		EVENT_GUILD_NUM = 51, -- Member

		EVENT_MAKE_SUIT = 52, -- Forge Set

		EVENT_PET_FIGHT = 53, -- Deployed Pet

		EVENT_PET_EVOLUTION = 54, -- Pet Breakthrough x times

		EVENT_PET_STRONG = 55, -- Pet Training x times

		EVENT_ATTEND_ACTIVITY = 56, -- Join xx xx times

		EVENT_DUNGE_INSPIRE = 57, -- Inspire xx times in EXP Vault

		EVENT_ROLE_DEATH = 58, -- Die xx times

		EVENT_KILL_ROLE = 59, -- Defeat x players

		EVENT_WELFARE_SIGN = 60, -- Total sign-in xxx days

		EVENT_OPEN_BAG = 61, -- Unlock xx slots of xx backpack

		EVENT_GUILD_LEVEL = 62, -- Guild Level

		EVENT_QUESTION = 63, -- Quiz

		EVENT_SEND_REDENVELOPE = 64, -- Sent out Red Packet

		EVENT_GWAR_WIN = 65, -- 公会争霸获得胜利 

		EVENT_GWAR_BREAK = 66, -- End enemy guild's win streak in Guild Clash

		EVENT_ACTIVITY_JOIN = 67, -- Participate

		EVENT_PET_POWER = 68, -- Pet CP

		EVENT_PET_TOTAL_POWER = 69, -- Total Pet CP

		EVENT_GWAR_RANK = 70, -- Guild Clash Rank

		EVENT_YY_LOTTERY = 71, -- Egg Smash

		EVENT_GOD_TOTAL_POWER = 72, -- Total Avatar CP

		EVENT_EQUIP_REFINE = 73, -- gear Refinery

		EVENT_EQUIP_CAST = 74, -- Forge Gear

		EVENT_BEAST_SUMMON = 75, -- Assisting Beast

		EVENT_SEARCH_TOP = 76, -- Peak Hunting

		EVENT_EQUIP_STR_FINAL = 77, -- Enhance Gear (Only Trigger Once)

		EVENT_ADD_INTIMACY = 78, -- Increase Intimacy

		EVENT_EQUIP_REFINE_FINAL = 79, -- Gear Polishing (Only Trigger Once)

		EVENT_ILLUSTRATION_POWER = 80, -- Atlas CP

		EVENT_TALK_WITHIN_SCENE = 81, -- Talk with appointed NPC

		EVENT_CREEP_WITHIN_SCENE = 82, -- Attack appointed Mob

		EVENT_BABY_POWER = 83, -- Children CP

		EVENT_MECHA_EQUIP = 84, -- Equip Mecha Gear

		EVENT_SEARCH_MECHA = 85, -- Mecha Hunt

		EVENT_SOUL_POWER = 86, -- Stigmata CP

		EVENT_MECHA_POWER = 87, -- Mecha CP

		EVENT_BEAST_POWER = 88, -- Beast CP

		EVENT_INTEGRAL = 89, -- Points Pack for Time-L treasure hunt

		EVENT_TOTEMS = 90, -- Totem

		EVENT_TOTEMS_LOAD = 91, -- 图腾穿装备

		EVENT_TOTEMS_SUMMON = 92, -- 图腾助战

	},

	TASK_TYPE = {

		TASK_TYPE_MAIN = 1, -- Main

		TASK_TYPE_TIME = 2, -- Limited

		TASK_TYPE_DAILY = 3, -- Daily

		TASK_TYPE_GUILD = 4, -- GUild

		TASK_TYPE_SIDE = 5, -- Sub

		TASK_TYPE_REIN = 6, -- Awaken

		TASK_TYPE_ESCORT = 7, -- Cross

		TASK_TYPE_BEAST = 8, -- Beast

		TASK_TYPE_BABY = 9, -- Baby

		TASK_TYPE_ACTIVE = 10, -- Activity

		TASK_TYPE_LOOP1 = 90, -- Daily

		TASK_TYPE_LOOP2 = 91, -- GUild

		TASK_TYPE_PREV1 = 92, -- Daily

		TASK_TYPE_PREV2 = 93, -- GUild

		TASK_TYPE_LOOP3 = 94, -- Beast

		TASK_TYPE_PREV3 = 95, -- Beast

		TASK_TYPE_LOOP4 = 96, -- Beast

		TASK_TYPE_PREV4 = 97, -- Beast

	},

	TASK_STATE = {

		TASK_STATE_TRIGGER = 1, -- Pending

		TASK_STATE_ACCEPT = 2, -- Accepted

		TASK_STATE_FINISH = 3, -- Completed

		TASK_STATE_COMING = 4, -- Next Quest

	},

	ACTIVITY_TYPE = {

		ACTIVITY_TYPE_LOCAL = 1, -- Server Event

		ACTIVITY_TYPE_CROSS = 2, -- Cross-server Event

		ACTIVITY_TYPE_CENTER = 3, -- Center-server Event

	},

	ACTIVITY_GROUP = {

		ACTIVITY_GROUP_ESCORT = 101, -- Polar Cross

		ACTIVITY_GROUP_GUILDWAR = 102, -- Guild Brawl

		ACTIVITY_GROUP_MELEE = 103, -- Brawl Battleground

		ACTIVITY_GROUP_CANDYROOM = 104, -- Candy House

		ACTIVITY_GROUP_GUILDHOUSE = 105, -- Guild Ceremony

		ACTIVITY_GROUP_GUILDGUARD = 106, -- Guild Guard

		ACTIVITY_GROUP_WEDDINGPARTY = 107, -- Wedding Ceremony

		ACTIVITY_GROUP_COMBAT1V1 = 108, -- Ace Duel

		ACTIVITY_GROUP_WARRIOR = 109, -- Altar of Bravery

		ACTIVITY_GROUP_COMPETE = 110, -- Diamond Ring

		ACTIVITY_GROUP_TIMEBOSS = 111, -- Time-limited Boss

		ACTIVITY_GROUP_SIEGEWAR = 113, -- Siege War

		ACTIVITY_GROUP_THRONE = 114, -- Throne of Star

		ACTIVITY_GROUP_CGW = 115, -- Cross-Server Guild War

		ACTIVITY_GROUP_FISSURE = 116, -- Time Rift

		ACTIVITY_GROUP_CLUSTER = 200, -- Cross-server Group

	},

	SCENE_STATE = {

		SCENE_STATE_NORMAL = 0, -- Normal

		SCENE_STATE_TIMEOUT = 1, -- Time out

	},

	SCENE_KIND = {

		SCENE_KIND_LOCAL = 1, -- Server Map

		SCENE_KIND_CROSS = 2, -- Cross-Server Map

	},

	SCENE_TYPE = {

		SCENE_TYPE_CITY = 1, -- Main City Map

		SCENE_TYPE_FIELD = 2, -- Wild Map

		SCENE_TYPE_DUNGE = 3, -- Stage Map

		SCENE_TYPE_BOSS = 4, -- Boss Map

		SCENE_TYPE_ACT = 5, -- Event Map

	},

	SCENE_STYPE = {

		SCENE_STYPE_DUNGE_EXP = 301, -- Temple of Trial

		SCENE_STYPE_DUNGE_COIN = 302, -- Cave of Covet

		SCENE_STYPE_DUNGE_MAGICTOWER = 303, -- Tower of Judgment

		SCENE_STYPE_DUNGE_EQUIP = 304, -- Fighter's Path

		SCENE_STYPE_DUNGE_NEWBIE = 305, -- Novice Stage

		SCENE_STYPE_DUNGE_DAILY = 306, -- Daily Stage

		SCENE_STYPE_DUNGE_ROLE_BOSS = 307, -- Personal Boss

		SCENE_STYPE_DUNGE_MOUNT = 308, -- Mount (Advance) Stage

		SCENE_STYPE_DUNGE_ARENA = 309, -- Arena

		SCENE_STYPE_DUNGE_PET = 310, -- Demon Invasion

		SCENE_STYPE_GUILDGUARD = 311, -- Guild Guard

		SCENE_STYPE_DUNGE_WORLD_BOSS = 312, -- World Boss Stage

		SCENE_STYPE_DUNGE_COUPLE = 313, -- Wedding Dungeon

		SCENE_STYPE_DUNGE_YUNYING_TOWER = 314, -- Operation Tower Dungeon

		SCENE_STYPE_DUNGE_SOUL = 315, -- Stigmata Realm

		SCENE_STYPE_DUNGE_YUNYING_LIMITTOWER = 316, -- Mecha Trial

		SCENE_STYPE_DUNGE_GOD = 317, -- Avatar Dungeon

		SCENE_STYPE_DUNGE_NEWBIE_SUMMON = 318, -- Novice Mermaid Stage

		SCENE_STYPE_DUNGE_RACE = 319, -- Mecha Racing

		SCENE_STYPE_DUNGE_NEWBIE_ANGER = 320, -- Novice Evil Stage (Anger Stage)

		SCENE_STYPE_BOSS_WORLD = 401, -- World Boss

		SCENE_STYPE_BOSS_HOME = 402, -- Boss Home

		SCENE_STYPE_BOSS_WILD = 403, -- Ancient Ruins

		SCENE_STYPE_BOSS_PET = 404, -- Monster Castle

		SCENE_STYPE_BOSS_BEAST = 405, -- Fantasy Island

		SCENE_STYPE_BOSS_NOTIRED = 406, -- World Boss (Non Fatigue Floor)

		SCENE_STYPE_BOSS_FISSURE = 409, -- Time Rift

		SCENE_STYPE_GUILD_WAR = 501, -- Guild Clash

		SCENE_STYPE_MELEEWAR = 502, -- Brawl Battleground

		SCENE_STYPE_CANDYROOM = 503, -- Candy House

		SCENE_STYPE_GUILDHOUSE = 504, -- Guild Camp

		SCENE_STYPE_WEDDINGPARTY = 505, -- Wedding Venue

		SCENE_STYPE_COMBAT1V1 = 506, -- Ace Duel

		SCENE_STYPE_WARRIOR = 507, -- Altar of Bravery

		SCENE_STYPE_COMPETE_PREPARE = 508, -- Diamond Ring Prepare Scene

		SCENE_STYPE_COMPETE_BATTLE = 509, -- Diamond Ring Battle Scene

		SCENE_STYPE_TIMEBOSS = 510, -- Time-limited Boss

		SCENE_STYPE_SIEGEWAR = 511, -- Siege War

		SCENE_STYPE_THRONE = 512, -- Throne of Star

		SCENE_STYPE_CROSS_GUILDWAR = 513, -- Cross-Server Guild War

	},

	SCENE_COST = {

		SCENE_COST_FIXED = 0, -- Fixed Cost

		SCENE_COST_TIMES = 1, -- According to Attempts

	},

	BCTYPE = {

		BCTYPE_GRID = 0, -- Sudoku Broadcast

		BCTYPE_SCENE = 1, -- World Broadcast

	},

	SCENE_CHANGE = {

		SCENE_CHANGE_PROTAL = 0, -- Portal

		SCENE_CHANGE_SHOES = 1, -- Talaria

		SCENE_CHANGE_TELE = 2, -- Teleport

		SCENE_CHANGE_BOSS = 3, -- Boss Map

		SCENE_CHANGE_ACT = 4, -- Event Scene

		SCENE_CHANGE_DUNGE = 5, -- Stage

		SCENE_CHANGE_LEAVE = 6, -- Leave

		SCENE_CHANGE_SERVER = 7, -- Server-side Skip

	},

	TELEPORT = {

		TELEPORT_SHOES = 0, -- Talaria

	},

	JUMP = {

		JUMP_TYPE_NORMAL = 0, -- Normal Leap

		JUMP_TYPE_POINT = 3, -- Jump Point

	},

	DUNGE_TYPE = {

		DUNGE_TYPE_ROLE = 1, -- Personal Stage

		DUNGE_TYPE_TEAM = 2, -- Team Stage

		DUNGE_TYPE_GUILD = 3, -- Guild Stage

	},

	ACTOR_TYPE = {

		ACTOR_TYPE_ROLE = 1, -- Player

		ACTOR_TYPE_CREEP = 2, -- Monster

		ACTOR_TYPE_DROP = 3, -- Drop

		ACTOR_TYPE_NPC = 4, -- NPC

		ACTOR_TYPE_PROTAL = 5, -- Portal

		ACTOR_TYPE_JUMP = 6, -- Jump Point

		ACTOR_TYPE_EFFECT = 7, -- Scene effects

		ACTOR_TYPE_TALISMAN = 8, -- Talisman

		ACTOR_TYPE_PET = 9, -- Pet

		ACTOR_TYPE_FAIRY = 10, -- Fairy (Chirden)

		ACTOR_TYPE_MAGIC = 11, -- Artifact

		ACTOR_TYPE_ROBOT = 12, -- Robot

		ACTOR_TYPE_BORN = 13, -- Spawn

		ACTOR_TYPE_GOD = 14, -- Deity

		ACTOR_TYPE_WING = 15, -- Wings

		ACTOR_TYPE_Weapon = 16, -- Weapon

		ACTOR_TYPE_MACHINEARMOR = 17, -- Mecha

		ACTOR_TYPE_MOUNT = 18, -- Mount

		ACTOR_TYPE_HEAD = 19, -- Head

		ACTOR_TYPE_HAND = 20, -- Gauntlet

		ACTOR_TYPE_MAG = 21, -- Magic Array

	},

	ACTOR_STATE = {

		ACTOR_STATE_NORMAL = 0, -- Normal

		ACTOR_STATE_DEATH = 1, -- Death

		ACTOR_STATE_ZAZEN = 2, -- Meditate

		ACTOR_STATE_COLLECT = 4, -- Collect

		ACTOR_STATE_OCCUPY = 8, -- Occupy

		ACTOR_STATE_CONVEY = 16, -- Convey

		ACTOR_STATE_UNBEAT = 32, -- Invincible

		ACTOR_STATE_DIZZY = 64, -- Stun

		ACTOR_STATE_SILENT = 128, -- Silence

		ACTOR_STATE_CHAOS = 256, -- Confuse

		ACTOR_STATE_IMMOB = 512, -- Immobilize

		ACTOR_STATE_PALSY = 1024, -- Paralyze

		ACTOR_STATE_SHIELD = 2048, -- Shield

		ACTOR_STATE_PET_MORPH = 4096, -- Pet Morph

		ACTOR_STATE_LEECH = 8192, -- HP-steal

		ACTOR_STATE_DECAY = 16384, -- Drop Decay

		ACTOR_STATE_DANCE = 32768, -- Dance

		ACTOR_STATE_BLEED = 65536, -- Bleed

		ACTOR_STATE_UNYIELD = 131072, -- Invulnerable

		ACTOR_STATE_SLOW = 262144, -- Slow

		ACTOR_STATE_LEI_GC = 524288, -- Thunder*Attack Wave

		ACTOR_STATE_BING_KJ = 1048576, -- Frost*Armor

		ACTOR_STATE_YOU_GC = 2097152, -- Phantom*Attack Wave

		ACTOR_STATE_HUAN_LS = 4194304, -- Mirage*Flash

		ACTOR_STATE_IMMUNE = 8388608, -- Immune

		ACTOR_STATE_MECHA_MORPH = 16777216, -- Mecha Transform

	},

	PKMODE = {

		PKMODE_PEACE = 1, -- Peace

		PKMODE_JUST = 2, -- Good&Evil

		PKMODE_TEAM = 3, -- Team

		PKMODE_GUILD = 4, -- Guild

		PKMODE_ALLY = 5, -- Force

		PKMODE_WHOLE = 6, -- All

		PKMODE_GUARD = 7, -- Guard

		PKMODE_INVADE = 8, -- Invade

		PKMODE_CROSS = 9, -- Cross-server

		PKMODE_ENEMY = 10, -- Enemy

	},

	CREEP_KIND = {

		CREEP_KIND_MONSTER = 1, -- Monster

		CREEP_KIND_COLLECT = 2, -- Material

		CREEP_KIND_TOMB = 3, -- Tombstone

	},

	CREEP_TYPE = {

		CREEP_TYPE_ACTIVE = 1, -- Active Mob

		CREEP_TYPE_PASSIVE = 2, -- Passive Mob

	},

	CREEP_RARITY = {

		CREEP_RARITY_COMM = 1, -- Normal Mob

		CREEP_RARITY_ELITE = 2, -- Elite Mob

		CREEP_RARITY_BOSS = 3, -- Boss (World Boss)

		CREEP_RARITY_GUARD = 4, -- Treasure Guard

		CREEP_RARITY_BOMB = 5, -- Bomb Monster

		CREEP_RARITY_BOSS2 = 6, -- Boss (Normal)

		CREEP_RARITY_HUNT = 7, -- Treasure Hunt Mob

		CREEP_RARITY_COLL = 8, -- Material (Single)

		CREEP_RARITY_COLL2 = 9, -- Material (Multiplayer)

		CREEP_GUILD_BOSS = 10, -- Summon Boss in Guild

		CREEP_RARITY_ARENA = 11, -- PK Guard

		CREEP_RARITY_AFK = 12, -- Offline Robot

		CREEP_RARITY_FAKER = 13, -- Team Robot

		CREEP_RARITY_BOSS3 = 14, -- Elite Mob (Stage)

		CREEP_RARITY_BEAST = 15, -- Beast Island Guard

		CREEP_RARITY_TIMEBOSS = 16, -- Time-limited Boss

		CREEP_RARITY_SIEGEBOSS = 17, -- Siege War Boss

		CREEP_RARITY_THRONE = 18, -- Throne of Star  Boss

		CREEP_RARITY_CGW_CRYSTAL = 19, -- 跨服公会战水晶

		CREEP_RARITY_CGW_STATUE = 20, -- 跨服公会战雕像

	},

	BOSS_KIND = {

		BOSS_KIND_LOCAL = 1, -- Server Boss

		BOSS_KIND_CROSS = 2, -- Cross-Server Boss

	},

	BOSS_TYPE = {

		BOSS_TYPE_WORLD = 1, -- World Boss

		BOSS_TYPE_HOME = 2, -- Home Boss

		BOSS_TYPE_WILD = 3, -- 远古Boss

		BOSS_TYPE_PET = 4, -- 宠物Boss

		BOSS_TYPE_BEAST = 5, -- Beast Boss

		BOSS_TYPE_BEAST_CROSS = 6, -- Cross-Server Beast Boss

		BOSS_TYPE_CONSTELLATION = 7, -- 星之王座BOSS

		BOSS_TYPE_SPATIOTEMPORAL = 8, -- Time Rift Default Boss

		BOSS_TYPE_SPATIOTEMPORAL2 = 9, -- Time Rift Hiden Boss

	},

	SKILL_GROUP = {

		SKILL_GROUP_NORMAL = 1, -- Normal Skill

		SKILL_GROUP_GUILD = 2, -- Guild Skill

		SKILL_GROUP_WAKE = 3, -- Awaken Skill

		SKILL_GROUP_OTHER = 4, -- Other Skill

		SKILL_GROUP_PET = 5, -- Pet Skill

		SKILL_GROUP_BEAST_SELF = 6, -- Beast Island Single Target Skill

		SKILL_GROUP_BEAST_ALL = 7, -- Beast Island AoE Skill

		SKILL_GROUP_TALENT_MOUNT = 8, -- Talent Skill (Mount)

		SKILL_GROUP_TALENT_OFFHAND = 9, -- Talent Skill (Off-hand)

		SKILL_GROUP_TALENT_WING = 10, -- Talent Skill (Wing Morph)

		SKILL_GROUP_TALENT_TALIS = 11, -- Talent Skill (Off-hand Morph)

		SKILL_GROUP_ANGER = 12, -- Rage Skill

		SKILL_GROUP_MECHA = 13, -- Mecha Skill

		SKILL_GROUP_TOTEM_SELF = 20, -- 图腾单体技能

		SKILL_GROUP_TOTEM_ALL = 21, -- 图腾全体技能

	},

	SKILL_TYPE = {

		SKILL_TYPE_ACTIVE = 1, -- Active Skill

		SKILL_TYPE_PASSIVE = 2, -- Passive Skill

		SKILL_TYPE_ATTR = 3, -- Attrbute Skill

	},

	SKILL_AIM = {

		SKILL_AIM_ENEMY = 1, -- Enemy

		SKILL_AIM_SELF = 2, -- Self

		SKILL_AIM_ALLY = 3, -- Ally

	},

	SKILL_AREA = {

		SKILL_AREA_SINGLE = 1, -- Single Target

		SKILL_AREA_RECT = 2, -- Rectangle

		SKILL_AREA_SECTOR = 3, -- Sector

		SKILL_AREA_CIRCLE = 4, -- Circle

	},

	SKILL_POS = {

		SKILL_POS_TRANSFORM = 7, -- Avatar Morph Skill

		SKILL_POS_PET_TRANSFORM = 8, -- Pet Morph Skill

		SKILL_POS_PET_NORMAL = 9, -- Pet Normal Attack Skill

		SKILL_POS_PET_TRANS_NOR = 10, -- Pet Normal Morph Skill

		SKILL_POS_PET_TRANS_PRO = 11, -- Pet Ogi Morph Skill

		SKILL_POS_PET_TRANS_RRO = 12, -- Pet Ogi Skill (Normal)

		SKILL_POS_ANGER = 13, -- Rage Skill

		SKILL_POS_MACHINEARMOR_NOR = 14, -- Mecha normal attack

		SKILL_POS_MACHINEARMOR_1 = 15, -- Mecha Skill 1

		SKILL_POS_MACHINEARMOR_2 = 16, -- Mecha Skill 2

		SKILL_POS_MACHINEARMOR_3 = 17, -- Mecha Skill 3

		SKILL_POS_MACHINEARMOR_4 = 18, -- Mecha Skill 4

		SKILL_POS_MACHINEARMOR_5 = 19, -- Mecha Skill 5

		SKILL_POS_MACHINEARMOR_6 = 20, -- Mecha Skill 6

	},

	ATTACK_UNIT = {

		ATTACK_UNIT_ROLE = 0, -- Character

		ATTACK_UNIT_PET = 1, -- Pet

		ATTACK_UNIT_CREEP = 9, -- Monster

	},

	DAMAGE = {

		DAMAGE_MISS = 1, -- Dodge

		DAMAGE_BLOOD = 2, -- HP Deduction

		DAMAGE_CRIT = 3, -- Crit

		DAMAGE_HEART = 4, -- Concentrated Strike

		DAMAGE_HEAL = 5, -- Heal

		DAMAGE_PURIFY = 6, -- Purify

		DAMAGE_ABSORB = 7, -- Absorb

		DAMAGE_BLOCK = 8, -- Block

		DAMAGE_REFLECT = 9, -- Reflect

		DAMAGE_KILL = 10, -- Kill

		DAMAGE_FIRE = 11, -- Fire DMG

		DAMAGE_BLEED = 12, -- Bleed

		DAMAGE_UNYIELD = 13, -- Invulnerable

		DAMAGE_LEECH = 14, -- HP-steal

		DAMAGE_IMMUNE = 15, -- Immune

		DAMAGE_PET_BLOOD = 1002, -- HP Deduction (Pet)

		DAMAGE_PET_CRIT = 1003, -- Crit (Pet)

		DAMAGE_PET_HEART = 1004, -- Concentrated Strike (Pet)

		DAMAGE_PET_HEAL = 1005, -- --HP Restore (Pet)

		DAMAGE_CRIT_HEART = 101, -- Crit+Concentrated Strike

		DAMAGE_CRIT_BLOCK = 102, -- Crit+Block

	},

	DROP_RULE = {

		DROP_RULE_FIXED = 1, -- Fixed drops

		DROP_RULE_WEIGHT = 2, -- Randomly Drop

		DROP_RULE_RANDOM = 3, -- Independent probability drop

	},

	DROP_MODE = {

		DROP_MODE_BAG = 1, -- Put in Backpack immediately

		DROP_MODE_SCENE = 2, -- Drop in scene

		DROP_MODE_DUMMY = 3, -- Half-virtual drop, it need to pick up

		DROP_MODE_DUMMY2 = 4, -- Half-virtual drop, auto pick up

	},

	DROP_BELONG = {

		DROP_BELONG_EVERY = 0, -- All players

		DROP_BELONG_KILLER = 1, -- Final Hit

		DROP_BELONG_TEAM_LEADER = 2, -- Leader obtains

		DROP_BELONG_TEAM_SHARE = 3, -- Team Sharing

		DROP_BELONG_TEAM_RANDOM = 4, -- Team Random

		DROP_BELONG_GUILD = 5, -- Guild Sharing

		DROP_BELONG_BOSS = 6, -- Boss Drop

		DROP_BELONG_TEAM_COPY = 7, -- Each team member can a reward. It has limit.

	},

	REVIVE_TYPE = {

		REVIVE_TYPE_SITU = 1, -- Revive on Site

		REVIVE_TYPE_SAFE = 2, -- Safe Zone Revive

	},

	BUFF_TYPE = {

		BUFF_TYPE_POSITIVE = 1, -- Buff

		BUFF_TYPE_NEGATIVE = 2, -- DeBuff

	},

	BUFF_LAP = {

		BUFF_LAP_ADDTIME = 1, -- Extend old Buff Time

		BUFF_LAP_REPLACE = 2, -- Replace old buff immediately

		BUFF_LAP_KEEPOLD = 3, -- Remain old Buff same

		BUFF_LAP_LVFIRST = 4, -- Replace low level buff

		BUFF_LAP_MAXTIME = 5, -- Use Long-time Buff

		BUFF_LAP_ADDATTR = 6, -- Stack up the attribute of old buff

		BUFF_LAP_ADDVAL = 7, -- Stack up the value of old buff

	},

	BUFF_EFFECT = {

		BUFF_EFFECT_HEAL = 1101, -- Heal

		BUFF_EFFECT_HEAL2 = 1102, -- Mount Skill: HP Restore

		BUFF_EFFECT_UNBEAT = 1201, -- Invincible

		BUFF_EFFECT_SHIELD = 1202, -- Shield

		BUFF_EFFECT_PURIFY = 1203, -- Purify

		BUFF_EFFECT_LEECH = 1204, -- HP-steal

		BUFF_EFFECT_OCCUPY = 1205, -- Occupy

		BUFF_EFFECT_UNYIELD = 1206, -- Invulnerable

		BUFF_EFFECT_LEI_GC = 1207, -- Thunder*Attack Wave

		BUFF_EFFECT_BING_KJ = 1208, -- Frost*Armor

		BUFF_EFFECT_YOU_GC = 1209, -- Phantom*Attack Wave

		BUFF_EFFECT_HUAN_LS = 1210, -- Mirage*Flash

		BUFF_EFFECT_DIZZY = 2201, -- Stun

		BUFF_EFFECT_SILENT = 2202, -- Silence

		BUFF_EFFECT_CHAOS = 2203, -- Confuse

		BUFF_EFFECT_IMMOB = 2204, -- Immobilize

		BUFF_EFFECT_PALSY = 2205, -- Paralyze

		BUFF_EFFECT_DECAY = 2206, -- Drop Decay

		BUFF_EFFECT_BLEED = 2207, -- Bleed

		BUFF_EFFECT_SLOW = 2208, -- Slow

		BUFF_EFFECT_SKILL = 3001, -- Cast skills regularly

		BUFF_EFFECT_ALARM = 3002, -- Ultimate alert!

		BUFF_EFFECT_ATTR = 3003, -- Attrbute

		BUFF_EFFECT_BELONG = 3004, -- World Boss Belongs to

		BUFF_EFFECT_ADDBUFF = 3005, -- Timing Buff

		BUFF_EFFECT_PET_MORPH = 3006, -- Morphy

		BUFF_EFFECT_TEAMMATE = 3007, -- Search teammate and give Hola Buff to them

		BUFF_EFFECT_REFLECT = 3008, -- Damage Reflection Aura

		BUFF_EFFECT_HEART = 3009, -- Concentrated Strike Aura

		BUFF_EFFECT_DAMAGE = 3010, -- Kill Aura

		BUFF_EFFECT_BLOCK = 3011, -- Block Aura

		BUFF_EFFECT_VIP = 3012, -- VIP Buff

		BUFF_EFFECT_POWER = 3013, -- CP Bonus

		BUFF_EFFECT_PURIFY2 = 3014, -- Purify Randomly

		BUFF_EFFECT_IMMUNE = 3015, -- Immune

		BUFF_EFFECT_DECAYTRIG = 3016, -- Trigger Drop Decay

		BUFF_EFFECT_CANDYJUMP = 3017, -- Candy House Dance

		BUFF_EFFECT_SUMMON = 3018, -- Summon mob

		BUFF_EFFECT_ADD_ANGER = 3019, -- Rage Increase

		BUFF_EFFECT_DEL_ANGER = 3020, -- Rage Decrease

		BUFF_EFFECT_MECHA_MORPH = 3021, -- Mecha Transform

		BUFF_EFFECT_MECHA_SHIELD = 3022, -- Mecha Shield

	},

	BUFF_VTYPE = {

		BUFF_VTYPE_ABS = 1, -- Absolute Value

		BUFF_VTYPE_PER = 2, -- Permyriad

	},

	BUFF_ID = {

		BUFF_ID_WORLD_BOSS_KILL_TIRED = 300410011, -- Fatigue Buff for Killing World Boss

		BUFF_ID_BEAST_BOSS_KILL_TIRED = 300410012, -- Fatigue Buff for Killing Beast Boss

		BUFF_ID_WORLD_BOSS_DEAD_TIRED = 220610001, -- Fatigue Buff for World Boss Revival

		BUFF_ID_BEAST_BOSS_DEAD_TIRED = 220610002, -- Fatigue Buff for Beast Boss Revival

		BUFF_ID_BEAST_BOSS_COLL_TIRED = 220610003, -- Fatigue Buff for Dragonscale Crystal (Beast  Boss)

		BUFF_ID_BEAST_BOSS_COLL2_TIRED = 220610004, -- Fatigue Buff for Phoenixscale Crystal (Beast  Boss)

		BUFF_ID_HOME_BOSS_VIGOR = 300410013, -- Home Boss - Energy

		BUFF_ID_COMPETE_BATTLE_LIFE = 304100004, -- Diamond Ring Lives

		BUFF_ID_TIMEBOSS_RANK_TIRED = 300410014, -- Time-limited Boss Ranking Reward Attempts

		BUFF_ID_TIMEBOSS_JOIN_TIRED = 300410015, -- Time-limited Boss Participation Reward Attempts

		BUFF_ID_CROSS_BOSS_SHIELD = 304010007, -- Cross-server Boss Shield

		BUFF_ID_SIEGEBOSS_KILL_TIRED = 300410018, -- Fatigue for Siege Boss Killing

		BUFF_ID_ANGER_SKILL_ADD = 300410016, -- Rage Increase Buff

		BUFF_ID_ANGER_SKILL_REDUCE = 300410017, -- Rage Decrease Buff

		BUFF_ID_SIEGEWAR_BOSS_SHIELD = 304010013, -- Siege War Boss Shield

		BUFF_ID_FISSURE_BOSS_TIRED = 300410020, -- Time Rift Fatigue buff

	},

	GUILD_POST = {

		GUILD_POST_MEMB = 1, -- Member

		GUILD_POST_BABY = 2, -- Baby

		GUILD_POST_ELDER = 3, -- Elder

		GUILD_POST_VICE = 4, -- Guild Deputy

		GUILD_POST_CHIEF = 5, -- Guild Leader

	},

	GUILD_PERM = {

		GUILD_PERM_NORMAL = 0, -- Normal Permissions

		GUILD_PERM_DISBAND = 1, -- Disband Guild

		GUILD_PERM_APPROVE = 2, -- Approval

		GUILD_PERM_KICKOUT = 3, -- Remove

		GUILD_PERM_APPOINT = 4, -- Appoint

		GUILD_PERM_NOTICE = 5, -- Edit Notice

		GUILD_PERM_DISMISS = 6, -- Position Remove

		GUILD_PERM_RENAME = 7, -- Guild Rename

		GUILD_PERM_SETUP = 8, -- Settings

		GUILD_PERM_UPGRADE = 9, -- Guild Upgrade

		GUILD_PERM_DESTROY = 10, -- Dispose

	},

	GUILD_LOG = {

		GUILD_LOG_JOIN = 1, -- Join a Guild

		GUILD_LOG_QUIT = 2, -- Leave

		GUILD_LOG_APPROVE = 3, -- Appoint

		GUILD_LOG_UPGRADE = 4, -- Guild Upgrade

	},

	GUILD_WELFARE = {

		GUILD_WELFARE_DAILY = 1, -- Daily Welfare

		GUILD_WELFARE_BABY = 2, -- Baby Welfare

		GUILD_WELFARE_POST = 3, -- Position Welfare

	},

	RANK_ID = {

		RANK_ID_LEVEL = 1001, -- Level Ranking

		RANK_ID_POWER = 1002, -- CP Ranking

		RANK_ID_AFK = 1008, -- Offline Farming

		RANK_ID_ARENA = 1011, -- Arena

		RANK_ID_COMBAT1V1 = 1012, -- Ace Duel

		RANK_ID_GUILD_GUARD = 1015, -- Guild Guard

		RANK_ID_BABY = 1019, -- Children Ranking

		RANK_ID_BABY_CROSS = 1020, -- Cross-server Children Ranking

		RANK_ID_MOUNT = 2001, -- Mount Ranking

		RANK_ID_WING = 2002, -- Wing Ranking

		RANK_ID_TALIS = 2003, -- Artifact Ranking

		RANK_ID_COMBAT1V1_CROSS = 2012, -- Ace Duel

	},

	RELATION = {

		RELATION_STRANGER = 1, -- Stranger

		RELATION_FRIEND = 2, -- Friends

		RELATION_BLACK = 3, -- Blacklist

	},

	TRAIN = {

		TRAIN_MOUNT = 1, -- Mount

		TRAIN_WING = 2, -- Wings

		TRAIN_TALIS = 3, -- Talisman

		TRAIN_WEAPON = 4, -- Artifact

		TRAIN_OFFHAND = 5, -- Off hand

		TRAIN_GOD = 6, -- Deity

		TRAIN_MECHA = 7, -- Mecha

	},

	TIPS_SHOW = {

		TIPS_SHOW_FASHION = 1, -- Costume

		TIPS_SHOW_TITLE = 2, -- Title

		TIPS_SHOW_MOUNT = 3, -- Mount

		TIPS_SHOW_OFFHAND = 4, -- Off hand

		TIPS_SHOW_WING = 5, -- Wings

		TIPS_SHOW_TAIL = 6, -- Talisman

		TIPS_SHOW_WEAPON = 7, -- Artifact

		TIPS_SHOW_PET = 8, -- Pet

		TIPS_SHOW_GOD = 9, -- Deity

		TIPS_SHOW_FRAME_ICON = 11, -- Portrait Frame

		TIPS_SHOW_FRAME_CHAT = 11, -- Bubble Frame

		TIPS_SHOW_MECHA = 12, -- Mecha

	},

	DEAD_TYPE = {

		DEAD_TYPE_NORM = 1, -- Natural Death (Manual Revive)

		DEAD_TYPE_TIRED = 2, -- Fatigue Death (World Boss)

		DEAD_TYPE_AUTO = 3, -- Natural Death (Auto-Revive)

	},

	WAKE_TASK_TYPE = {

		WAKE_TYPE_ACTIVE = 1, -- Daily Quests

		WAKE_TYPE_DUNGE = 2, -- Stages

		WAKE_TYPE_TASK = 3, -- Quests

	},

	FIGHT_STATE_TYPE = {

		FIGHT_STATE_TYPE_NULL = 1, -- Out of combat

		FIGHT_STATE_TYPE_NORMAL = 2, -- Normal combat

		FIGHT_STATE_TYPE_PK = 3, -- PK

	},

	VIP_RIGHTS = {

		VIP_RIGHTS_EXP_BUFF = 1, -- Monster Killing EXP buff

		VIP_RIGHTS_MARKET_TAX = 2, -- Trade Tax

		VIP_RIGHTS_FREE_FLY = 3, -- Unlimited Teleport

		VIP_RIGHTS_DUNGE_EXP_BUY = 4, -- Dungeon purchase attempts

		VIP_RIGHTS_5 = 5, -- Out of combat

		VIP_RIGHTS_6 = 6, -- Out of combat

		VIP_RIGHTS_MARKET_DEAL = 7, -- Unlock Specified Trade on the market

		VIP_RIGHTS_8 = 8, -- Out of combat

		VIP_RIGHTS_DUNGE_COIN_BUY = 9, -- Greedy Cave purchase chance

		VIP_RIGHTS_10 = 10, -- Out of combat

		VIP_RIGHTS_WILD_BOSS = 11, -- Ancient Boss Attempts

		VIP_RIGHTS_12 = 12, -- Out of combat

		VIP_RIGHTS_13 = 13, -- Out of combat

		VIP_RIGHTS_ROLE_BOSS = 14, -- Personal Boss

		VIP_RIGHTS_15 = 15, -- Out of combat

		VIP_RIGHTS_16 = 16, -- Out of combat

		VIP_RIGHTS_17 = 17, -- Daily Sign-in Attempts

		VIP_RIGHTS_SEARCH_TREASURE = 18, -- Out of combat

		VIP_RIGHTS_19 = 19, -- Out of combat

		VIP_RIGHTS_20 = 20, -- Out of combat

		VIP_RIGHTS_21 = 21, -- Out of combat

		VIP_RIGHTS_22 = 22, -- Out of combat

		VIP_RIGHTS_23 = 23, -- Out of combat

		VIP_RIGHTS_24 = 24, -- Out of combat

		VIP_RIGHTS_25 = 25, -- Out of combat

		VIP_RIGHTS_MARKET_TIMES = 26, -- Max Grant additional market trade attempts +x

		VIP_RIGHTS_27 = 27, -- Out of combat

		VIP_RIGHTS_MARKET_NUM = 28, -- Max Grant additional market shelf slots +x

		VIP_RIGHTS_DUNGE_EQUIP_BUY = 29, -- Gear Dungeon purchase attempts

		VIP_RIGHTS_DUNGE_ARENA = 30, -- Arena

		VIP_RIGHTS_DUNGE_PET_BUY = 31, -- Demon Invasion purchase attempts

		VIP_RIGHTS_PET_BOSS = 32, -- Pet Boss Attempts

		VIP_RIGHTS_CAST_RESET = 33, -- Forge Hut Reset Attempts

		VIP_RIGHTS_DUNGE_SOUL = 34, -- Stigmata Realm purchase attempts

		VIP_RIGHTS_SPATIOTEMPORAL_BOSS = 35, -- 时空裂缝Boss次数

		VIP_RIGHTS_FISSURE_TIRED = 36, -- Time Rift Boss Fatigue

	},

	FASHION_STATE_TYPE = {

		FASHION_STATE_TYPE_CLOTHES = 1, -- Costume

		FASHION_STATE_TYPE_HEAD = 2, -- Headwear

		FASHION_STATE_TYPE_WEAPON = 3, -- Weapon

		FASHION_STATE_TYPE_SHIELD = 4, -- Off hand

		FASHION_STATE_TYPE_FOOTPRINT = 5, -- footprint

		FASHION_STATE_TYPE_MAGICARRAY = 6, -- Magic Array

		FASHION_STATE_TYPE_FRAME = 11, -- Portrait Frame

		FASHION_STATE_TYPE_BUBBLE = 12, -- Bubble Frame

	},

	GIFT_TYPE = {

		GIFT_TYPE_RANDOM = 1, -- Random Pack

		GIFT_TYPE_SELECT = 2, -- Optional Pack

		GIFT_TYPE_FIXED = 3, -- Fixed Pack

		GIFT_TYPE_GOLD_Multiple = 4, -- Ingot Selection Pack

		GIFT_TYPE_DROP = 5, -- Drop Pack

		GIFT_TYPE_LEVEL = 6, -- Level Pack

	},

	VIP_TYPE = {

		VIP_TYPE_NONE = 0, -- Non-vip

		VIP_TYPE_TASTE = 1, -- Experience VIP

		VIP_TYPE_NORM = 2, -- Normal VIP

	},

	ROLE_STATE = {

		ROLE_STATE_NORMAL = 0, -- Normal

		ROLE_STATE_MCHUNT = 1, -- Soul Card Hunting

		ROLE_STATE_ESCORT = 2, -- Polar Crossing

	},

	TARGET_TYPE = {

		TARGET_TYPE_FIRST_RECHARGE = 1, -- New Server Carnival

		TARGET_TYPE_MONTH_CARD = 2, -- Activating monthly card

		TARGET_TYPE_BUY_FAIRY = 3, -- Purchase Fairy

		TARGET_TYPE_VIP = 4, -- Activate VIP

		TARGET_TYPE_INVEST = 5, -- Buy Investment Plan

		TARGET_TYPE_ATTRIB = 6, -- Attribute achieved

		TARGET_TYPE_EQUIP = 7, -- Equip Gear

		TARGET_TYPE_CREEP = 8, -- Slay Mobs

		TARGET_TYPE_EQUIP_SUITE = 9, -- Gear Set

		TARGET_TYPE_EVENT = 10, -- Type

	},

	CHAT_CHANNEL = {

		CHAT_CHANNEL_WORLD = 1, -- World

		CHAT_CHANNEL_SCENE = 2, -- Zone

		CHAT_CHANNEL_CROSS = 3, -- Cross-server

		CHAT_CHANNEL_TEAM = 4, -- Team

		CHAT_CHANNEL_TEAM2 = 5, -- Team

		CHAT_CHANNEL_GUILD = 6, -- Immortal Alliance

		CHAT_CHANNEL_QUESTION = 7, -- Quiz

		CHAT_CHANNEL_P2P = 99, -- PM

		CHAT_CHANNEL_SYS = 100, -- System

	},

	MAIL = {

		MAIL_MONEY_EXCEED_NOTIFY = 1000002, -- Notice for currency overage

		MAIL_MONEY_EXCEED_GIVE = 1000003, -- Reissue for currency overage

		MAIL_BAG_FULL = 1000004, -- Insufficient capacity, send mail failed.

		MAIL_GAME_TOO_FAST = 1000005, -- Package launching too frequent

		MAIL_GUILD_GUARD_SUCC = 1000006, -- Guild Guard Statistics

		MAIL_GUILD_GUARD_FAIL = 1000007, -- Guild Guard Statistics

		MAIL_GUILD_MERGE_ROLE_RENAME = 1000013, -- 合服玩家重名

		MAIL_GUILD_MERGE_GUILD_RENAME = 1000014, -- 合服公会重名

		MAIL_ROLE_RENAME = 1100001, -- Rename

		MAIL_MARKET_BUY = 1113001, -- Market purchase

		MAIL_MARKET_SALE = 1113002, -- Sale

		MAIL_MARKET_REFUSE = 1113003, -- Reject

		MAIL_MARKET_EXPIRE = 1113004, -- Out of date

		MAIL_ARENA_PK = 1132001, -- Defeated in the Arena

		MAIL_MARRIAGE_REFUSE = 1134001, -- Proposal Failed

		MAIL_MARRIAGE_DIVORCE = 1134002, -- Divorce

		MAIL_WEDDING_APPOINTMNET = 1135001, -- Wedding Reserve

		MAIL_WEDDING_ACCEPT = 1135002, -- Wedding Notice

		MAIL_WEDDING_PARTY = 1135003, -- Wedding Popularity Rewards

		MAIL_WEDDING_COMPENSATE = 1135004, -- Cancel

		MAIL_DUNGE_RACE = 1203001, -- Mecha Racing Reward

		MAIL_BOSS_ATTEND = 1204001, -- World Boss Participation Reward

		MAIL_GUILD_NOTICE = 1400001, -- Guild Notice

		MAIL_GUILD_APPLY_FAIL = 1400002, -- Fail to apply

		MAIL_GUILD_APPLY_SUCC = 1400003, -- Apply successfully

		MAIL_GUILD_KICKOUT = 1400004, -- Removed from Guild

		MAIL_GUILD_APPOINT = 1400005, -- Position Change

		MAIL_GUILD_AUTO_DEMISE1 = 1400006, -- Auto-transfer Chairman (Old Chairman)

		MAIL_GUILD_AUTO_DEMISE2 = 1400007, -- Auto-transfer Chairman (Member)

		MAIL_MELEE_REWARD = 1603001, -- Brawl Rewards

		MAIL_MELEE_FINAL_REWARD = 1603002, -- Brawl Placement Rewards

		MAIL_CANDYROOM_REWARD = 1604001, -- Candy House Rewards

		MAIL_GUILDWAR_WIN_REWARD = 1602001, -- Guild Clash Winner Reward

		MAIL_GUILDWAR_LOSE_REWARD = 1602002, -- Guild Clash Participate Reward

		MAIL_GUILDWAR_ROLE_REWARD = 1602003, -- Guild Clash Personal Reward

		MAIL_GUILDWAR_VICTORY_REWARD = 1602004, -- Win-streak Reward

		MAIL_GUILDWAR_BREAKUP_REWARD = 1602005, -- Defeat Reward

		MAIL_GUILDWAR_ROUND1_PREDICT = 1602006, -- Prediction of Round I

		MAIL_GUILDWAR_ROUND2_PREDICT = 1602007, -- Prediction of Round II

		MAIL_GUILDWAR_UPGRADE = 1602008, -- Division Upgrade

		MAIL_GUILDWAR_DEGRADE = 1602009, -- Division Degrade

		MAIL_GUILDWAR_FIRST_RANK = 1602010, -- No.1 Guild

		MAIL_GUILDWAR_FIRST_REWARD = 1602011, -- No.1 Guild Leader Reward

		MAIL_GUILDWAR_NO_RIVAL = 1602012, -- Guild Clash Winner Reward (bye)

		MAIL_GUILDHOUSE_QUESTION = 1605001, -- Guild Quiz Rewards

		MAIL_COMBAT1V1_RANK = 1605002, -- Ace Duel Placement Reward

		MAIL_COMBAT1V1_GRADE = 1605003, -- Ace Duel Placement Reward

		MAIL_WARRIOR_RANK = 1606001, -- Altar of Courage Placement Rewards

		MAIL_WARRIOR_FLOOR = 1606002, -- Altar of Courage Progress Rewards

		MAIL_BABY_LIKE_RANK = 1606003, -- Children Thumb Up Reward

		MAIL_COMPETE_ENROLL_SUCC = 1607001, -- Successfully signed up

		MAIL_COMPETE_ENROLL_OUST = 1607002, -- Reimbursement for Qualifier Failure

		MAIL_COMPETE_ENROLL_PASS = 1607003, -- Qualification Notice

		MAIL_COMPETE_SELECT_PASS = 1607004, -- Reminder of Heaven List

		MAIL_COMPETE_RANK_REWARD = 1607005, -- Heaven/Earth List Statistics

		MAIL_COMPETE_BATTLE_REWARD = 1607006, -- Diamond Arena Reward

		MAIL_COMPETE_GUESS_RIGHT = 1607007, -- Quiz Successful

		MAIL_COMPETE_GUESS_WRONG = 1607008, -- Quiz Failed

		MAIL_COMPETE_SELECT_REWARD1 = 1607009, -- Heaven List Participate Reward

		MAIL_COMPETE_SELECT_REWARD2 = 1607010, -- Earth List Participate Reward

		MAIL_TIMEBOSS_SHIELD_REWARD = 1608001, -- Time-limited Boss Shield Breaking Reward

		MAIL_TIMEBOSS_JOIN_REWARD = 1608002, -- Time-limited Boss Participation Reward

		MAIL_TIMEBOSS_RANK_REWARD = 1608003, -- Time-limited Boss Ranking Reward

		MAIL_TIMEBOSS_BOX_REWARD = 1608004, -- Time-limited Boss Chest Reward

		MAIL_SIEGEWAR_OCCUPY_REWARD = 1609001, -- Siege War Capture Rewards

		MAIL_YUNYING_SHOP_REWARD = 1700001, -- X-server Shopping

	},

	ROLE_COUNT = {

		ROLE_COUNT_SEND_FLOWER = 1001, -- Daily first flower gifting

		ROLE_COUNT_MARKET_DEAL = 1002, -- Market Trade Attempts

		ROLE_COUNT_WELFARE_GRAIL = 1003, -- Trophy Bless Attempts

		ROLE_COUNT_WELFARE_SIGN = 1004, -- Daily Sign-in Attempts

		ROLE_COUNT_ESCORT_COUNT = 1005, -- Daily Polar Cross Attempts

		ROLE_COUNT_ESCORT_ROB = 1006, -- Daily Plunder

		ROLE_COUNT_ESCORT_FRESH = 1007, -- Daily refresh attempts

		ROLE_COUNT_ESCORT_SUPP = 1008, -- Daily Assist

		ROLE_COUNT_BOSS_TIRED = 1009, -- boss fatigue

		ROLE_COUNT_GW_REWARD = 1010, -- Guild Brawl Daily Bonus

		ROLE_COUNT_GUILD_JOIN = 1011, -- Guild Join Attempts

		ROLE_COUNT_DAILY_PAY = 1012, -- Daily Top-up Ingots

		ROLE_COUNT_ARENA_STIMULATE = 1013, -- Arena encourage attempts

		ROLE_COUNT_ARENA_TOP_CHALLENGE = 1014, -- Arena Ace challenge attempts

		ROLE_COUNT_ARENA_RANK = 1015, -- Daily Reward

		ROLE_COUNT_TOP_RANK = 1016, -- Arena Ace Welfare

		ROLE_COUNT_FRIEND_REQUEST = 1017, -- Friend Request

		ROLE_COUNT_ASSIST_HONOR = 1018, -- Daily Assist Glory Cap

		ROLE_COUNT_ASSIST_INTIMACY = 1019, -- Daily Assist Intimacy Cap

		ROLE_COUNT_LOGIN = 1020, -- Daily Login

		ROLE_COUNT_BEAST_TIRED = 1021, -- Beast Island Fatigue

		ROLE_COUNT_BEAST_COLL = 1022, -- Beast Island Crystal Gathering

		ROLE_COUNT_BEAST_COLL2 = 1023, -- Beast Island Crystal Gathering

		ROLE_COUNT_EQUIP_REFINE = 1024, -- Free Gear Refinery

		ROLE_COUNT_CASTHOUSE = 1025, -- Forge Hut daily attempts

		ROLE_COUNT_CASTHOUSE_RESET = 1026, -- Forge Hut daily reset attempts

		ROLE_COUNT_CASTHOUSE_FREE = 1027, -- Forge Hut daily free dice attempts

		ROLE_COUNT_DUNGE_GOD_RESET = 1028, -- Reset Deity's Path

		ROLE_COUNT_HOME_BOSS_VIGOR = 1029, -- Home Boss - Energy

		ROLE_COUNT_MARKET_GAIN_GOLD = 1030, -- 市场获得钻石

		ROLE_COUNT_MARKET_COST_GOLD = 1031, -- 市场消耗钻石

		ROLE_COUNT_GUILD_WELFARE = 2001, -- Guild Bonus

		ROLE_COUNT_SCENE_ENTER = 2002, -- Enter Attempts

		ROLE_COUNT_SCENE_BUY = 2003, -- Buy Attempts

		ROLE_COUNT_SCENE_SWEEP = 2004, -- Dungeon Raid attempts

		ROLE_COUNT_VIP_WELFARE = 2005, -- VIP Welfare

		ROLE_COUNT_ITEM_GAIN = 2006, -- Item Obtaining

		ROLE_COUNT_DUNGE_ASSIST = 2007, -- Dungeon Assist attempts

		ROLE_COUNT_REDENVELOPE = 2008, -- Daily Send Red Packs Attempts

		ROLE_COUNT_AFK_ITEM_GAIN = 2009, -- Offline items obtained

		ROLE_COUNT_COMBAT1V1 = 2010, -- Ace Duel

		ROLE_COUNT_SCENE_ITEMADD = 2011, -- Item Increase attempt

		ROLE_COUNT_BEAST_SUMMON_BC = 2013, -- Beast Assist Broadcast

		ROLE_COUNT_SCENE_ASK_BUY = 2014, -- Purchase Increase Apply from Stage

		ROLE_COUNT_DAILY_RECHARGE = 2015, -- 充值购买次数

		ROLE_COUNT_TOTEMS_SUMMON_BC = 2016, -- 图腾助阵广播

	},

	YY_TASK_STATE = {

		YY_TASK_STATE_FINISH = 1, -- Done

		YY_TASK_STATE_UNDONE = 2, -- Pending

		YY_TASK_STATE_REWARD = 3, -- Claimed

		YY_TASK_STATE_REFUND = 4, -- Rebated

	},

	MODEL_TYPE = {

		MODEL_TYPE_FABAO = 1, -- Talisman

		MODEL_TYPE_MONSTER = 2, -- Monster

		MODEL_TYPE_MOUNT = 3, -- Mount

		MODEL_TYPE_NPC = 4, -- NPC

		MODEL_TYPE_PET = 5, -- Pet

		MODEL_TYPE_ROLE = 6, -- Character

		MODEL_TYPE_WING = 7, -- Wings

		MODEL_TYPE_WEAPON = 8, -- Artifact

		MODEL_TYPE_FAIRY = 9, -- Wisp

		MODEL_TYPE_FUSHOW = 10, -- Off hand

		MODEL_TYPE_EQUIP = 11, -- Gear

		MODEL_TYPE_BABY = 12, -- Baby

		MODEL_TYPE_GOD = 13, -- Deity

		MODEL_TYPE_MECHA = 14, -- Mecha

		MODEL_TYPE_ARTIFACT = 15, -- Artifact

	},

	WANTED_TASK_STATE = {

		WANTED_TASK_STATE_UNDONE = 1, -- Pending

		WANTED_TASK_STATE_FINISH = 2, -- Done

		WANTED_TASK_STATE_REWARD = 3, -- Claimed

	},

	RED_ENVELOPE_STATE = {

		RED_ENVELOPE_STATE_NEW = 1, -- Not send yet

		RED_ENVELOPE_STATE_SEND = 2, -- Already sent

		RED_ENVELOPE_STATE_DONE = 3, -- Claimed out

	},

	PROGRESS_STATE = {

		PROGRESS_STATE_UNDONE = 1, -- Pending

		PROGRESS_STATE_FINISH = 2, -- Done

		PROGRESS_STATE_REWARD = 3, -- Claimed

	},

	HEAL_TYPE = {

		HEAL_TYPE_SKILL = 1, -- HP Restore

		HEAL_TYPE_BLEED = 2, -- Bleed

	},

	TRADE_TYPE = {

		TRADE_TYPE_SALE = 1, -- Sell

		TRADE_TYPE_DEAL = 2, -- Market Trade

	},

	TALENT_GROUP = {

		TALENT_GROUP_FIGHT = 1, -- Fight

		TALENT_GROUP_GUARD = 2, -- Guard

		TALENT_GROUP_BASE = 3, -- Basic

	},

	CROSS_RULE = {

		CROSS_RULE_24_8 = 1024008, -- 

	},

	DUNGE_OP = {

		DUNGE_OP_ENTER = 1, -- Enter Stage

		DUNGE_OP_BUY_TIMES = 2, -- Buy Attempts

		DUNGE_OP_SWEEP = 3, -- Raid attempts

		DUNGE_OP_STAR = 4, -- Stars

	},

	PLAY_STAT = {

		PLAY_STAT_ESCORT = 3, -- Polar Cross

		PLAY_STAT_ARENA = 4, -- Arena

		PLAY_STAT_ARENA_TOP = 5, -- Super Challenge

		PLAY_STAT_COMBAT1V1 = 6, -- Ace Duel

	},

	PLAY_OP = {

		PLAY_OP_PART = 1, -- Join

	},

	COMPETE_PERIOD = {

		COMPETE_PERIOD_TRUCE = 0, -- Armistice

		COMPETE_PERIOD_ENROLL = 1, -- Sign up

		COMPETE_PERIOD_SELECT = 2, -- Mass-election

		COMPETE_PERIOD_RANK = 3, -- Clash

		COMPETE_PERIOD_OUST = 4, -- Eliminate

	},

	COMPETE_PHASE = {

		COMPETE_PHASE_PREPARE = 0, -- Preparation

		COMPETE_PHASE_BATTLE = 1, -- Battle

	},

	COMPETE_BATTLE = {

		COMPETE_BATTLE_SELECT = 1, -- Mass-election

		COMPETE_BATTLE_RANK1 = 2, -- Heaven Ranking

		COMPETE_BATTLE_RANK2 = 3, -- Earth Ranking

	},

	CGW_PERIOD = {

		CGW_PERIOD_DIVIDE = 1, -- 分配

		CGW_PERIOD_BOOK = 2, -- 约战

		CGW_PERIOD_BATTLE = 3, -- 开启

		CGW_PERIOD_TRUCE = 4, -- 休战(周结)

		CGW_PERIOD_SETTLE = 5, -- 月结

	},

	ROLELOG = {

		ROLELOG_CLIENT_ERROR = 1000001, -- Client error

		ROLELOG_MOUNT_UPGRADE = 1107101, -- Mount Tier-up

		ROLELOG_OFFHAND_UPGRADE = 1107501, -- Off-hand Advancing

		ROLELOG_MOUNT_TRAIN = 1107102, -- Mount Soul Pearl

		ROLELOG_OFFHAND_TRAIN = 1107502, -- Off-hand Soul Pearl

		ROLELOG_WING_UPGRADE = 1109201, -- Wing Upgrade

		ROLELOG_TALIS_UPGRADE = 1109301, -- Talisman Upgrade

		ROLELOG_WEAPON_UPGRADE = 1109401, -- Artifact Upgrade

		ROLELOG_GOD_UPGRADE = 1109601, -- Avatar Upgrade

		ROLELOG_MECHA_UPGRADE = 1109601, -- Mecha upgrades

		ROLELOG_WING_TRAIN = 1109202, -- Wing Soul Pearl

		ROLELOG_TALIS_TRAIN = 1109302, -- Talisman Soul Pearl

		ROLELOG_WEAPON_TRAIN = 1109402, -- Artifact Soul Pearl

		ROLELOG_GOD_TRAIN = 1109602, -- Deity Soul Pearl

		ROLELOG_MOUNT_ACTIVE = 1108101, -- Active Mount Morph

		ROLELOG_WING_ACTIVE = 1108201, -- Active Wing Morph

		ROLELOG_TALIS_ACTIVE = 1108301, -- Active Relic Morph

		ROLELOG_WEAPON_ACTIVE = 1108401, -- Active Artifact Morph

		ROLELOG_OFFHAND_ACTIVE = 1108501, -- Active Off hand Morph

		ROLELOG_GOD_ACTIVE = 1108601, -- Active Deity Morph

		ROLELOG_MECHA_ACTIVE = 1108701, -- Mecha Morph Activation

		ROLELOG_MOUNT_UPSTAR = 1108102, -- Star-up Mount Morph

		ROLELOG_WING_UPSTAR = 1108202, -- Star-up Wings Morph

		ROLELOG_TALIS_UPSTAR = 1108302, -- Star-up Relic Morph

		ROLELOG_WEAPON_UPSTAR = 1108402, -- Star-up Artifact Morph

		ROLELOG_OFFHAND_UPSTAR = 1108502, -- Star-up Off-hand Morph

		ROLELOG_GOD_UPSTAR = 1108602, -- Star-up Avatar Morph

		ROLELOG_MECHA_UPSTAR = 1108702, -- Mecha Morph

		ROLELOG_DUNGE_ENTER = 120001, -- Enter Stage

		ROLELOG_DUNGE_LEAVE = 120002, -- Exit

		ROLELOG_EQUIP_REINF = 110601, -- Enhance gear

		ROLELOG_EQUIP_REINF_AUTO = 110602, -- 1-Key Enhance

		ROLELOG_EQUIP_COMBINE = 110603, -- Combine gear

		ROLELOG_KILL_BOSS = 120101, -- Kill Boss

	},

	NFTTYPE = {

		NFTTYPE_MALL = 101, -- Boss Drop

		NFTTYPE_MARKET = 102, -- Market

		NFTTYPE_PET = 201, -- Pet

		NFTTYPE_MOUNT = 202, -- Mount

		NFTTYPE_WING = 203, -- Wings

		NFTTYPE_F_HAIR = 301, -- 时装-头发

		NFTTYPE_F_CLOTH = 302, -- 时装-衣服

		NFTTYPE_F_WEAPON = 303, -- 时装-武器

	},

}

enumName = {

	ACCOUNT = {

		[1] = "Normal player",

		[2] = "GM",

	},

	CAREER = {

		[1] = "Swordsman",

		[2] = "Knight",

	},

	GENDER = {

		[1] = "Male",

		[2] = "Female",

	},

	COLOR = {

		[1] = "White",

		[2] = "Green",

		[3] = "Blue",

		[4] = "Violet",

		[5] = "Orange",

		[6] = "Red",

		[7] = "Pink",

	},

	MAIL_TYPE = {

		[1] = "Personal Mail",

		[2] = "System Mail",

		[3] = "封测返还",

	},

	ITEM_TYPE = {

		[1] = "Gear",

		[2] = "Gem",

		[3] = "Beast Gear",

		[4] = "Baby Toy",

		[5] = "Atlas",

		[6] = "Hallow",

		[8] = "Quest",

		[9] = "Currency",

		[10] = "Misc",

		[11] = "Crystal",

		[12] = "Mecha Gear",

		[13] = "Pet Gear",

		[14] = "Divine equipment",

		[15] = "Totem equipment",

	},

	ITEM_STYPE = {

		[1001] = "Weapon",

		[1002] = "Off-hand",

		[1003] = "Necklace",

		[1004] = "Ring",

		[1005] = "Amulet",

		[1006] = "Helmet",

		[1007] = "Chestpiece",

		[1008] = "Legging",

		[1009] = "Gauntlet",

		[1010] = "Shoes",

		[1011] = "Phantom",

		[1012] = "Wedding Ring",

		[1013] = "Nightmare",

		[4001] = "Bamboo Dragonfly",

		[4002] = "Toy Car",

		[4003] = "Cotton Jacket",

		[4004] = "Schoolbag",

		[4005] = "Amulet",

		[4006] = "Duck Shoes",

		[5001] = "Godly Crown",

		[5002] = "Avatar Pendant",

		[5003] = "Godly Rope",

		[5004] = "Avatar Right Ring",

		[5005] = "Avatar Bracelets",

		[5006] = "Godly Amulet",

		[5007] = "Avatar Gaunlets",

		[5008] = "Deity Leggings",

		[5009] = "Godly Right Wing",

		[5010] = "Avatar Boots",

		[6001] = "Atlas",

		[7001] = "Protective Cover",

		[7002] = "Thruster",

		[7003] = "Engine",

		[7004] = "Radar",

		[7005] = "Mecha Core",

		[3001] = "Beast Horn",

		[3002] = "Eye",

		[3003] = "Fang",

		[3004] = "Claw",

		[3005] = "Scale",

		[8001] = "Pet Helmat",

		[8002] = "Pet Spirit",

		[8003] = "Pet Claw",

		[8004] = "Pet Necklace",

		[10001] = "Upgrade Pill",

		[10002] = "Fixed EXP Pill",

		[10003] = "Ingot Card",

		[10004] = "Bound Ingot Card",

		[10005] = "Gold Card",

		[10006] = "Bound Gold Card",

		[10007] = "Fame Card",

		[10008] = "Glory Card",

		[10009] = "Feat Card",

		[10010] = "Prestige Card",

		[10011] = "Guild Contribution Card",

		[10012] = "Atlas Essence Card",

		[10012] = "Soul Card Dust",

		[10013] = "Soul Card Shard",

		[10014] = "Combined Soul Crystal",

		[10015] = "Hunting Energy",

		[10016] = "EXP Upgrade Pill",

		[10017] = "Level EXP Pill",

		[10018] = "Pet Essence Card",

		[10019] = "Level EXP Pill",

		[10022] = "Stigmata EXP",

		[10023] = "Combine Stigmata",

		[10024] = "Advance Stigmata",

		[10070] = "Costume",

		[10071] = "Title",

		[10080] = "Pack",

		[10081] = "Flower",

		[10082] = "Firework",

		[10083] = "Level Pack",

		[10101] = "Mount EXP Pill",

		[10102] = "Wings EXP Pill",

		[10103] = "Relic EXP Pill",

		[10104] = "Artifact EXP Pill",

		[10105] = "Off hand EXP Pill",

		[10106] = "Avatar EXP Pill",

		[10107] = "Mecha EXP Pill",

		[10121] = "Mount Attribute Pill",

		[10122] = "Off hand Attribute Pill",

		[10141] = "Mount Morph",

		[10142] = "Wings Morph",

		[10143] = "Relic Morph",

		[10144] = "Artifact Morph",

		[10145] = "Off hand Morph",

		[10146] = "Baby Wings Morph",

		[10147] = "Mecha Morph",

		[10151] = "EXP Card",

		[10152] = "VIP Card",

		[10153] = "Auto Card",

		[10154] = "Soul Card",

		[10155] = "Set Stone",

		[10160] = "Mythical Beast Stone",

		[10163] = "Sundries",

		[10165] = "Guild Summon Boss",

		[10166] = "World Boss Fatigue",

		[10167] = "Dungeon Ticket",

		[10168] = "Smelting EXP Pill",

		[10169] = "Soul Card Pack",

		[10170] = "Guild Rename Card",

		[10171] = "Recharge Card",

		[10172] = "buff",

		[10173] = "Character Rename Card",

		[10174] = "Beast Boss Fatigue",

		[10175] = "Baby Activation Item",

		[10177] = "Deity Morph Shard",

		[10179] = "Stigmata",

		[10180] = "Mecha Morph",

		[10182] = "Pet Gear Material",

		[10183] = "vip2激活卡",

		[10201] = "Pet",

		[10202] = "Pet Egg",

	},

	ITEM = {

		[90010001] = "Level",

		[90010002] = "EXP",

		[90010003] = "Diamond",

		[90010004] = "Bound Diamond",

		[90010005] = "Gold",

		[90010006] = "Bound Gold",

		[90010007] = "Fame",

		[90010008] = "Glory",

		[90010009] = "Feat",

		[90010010] = "Prestige",

		[90010011] = "Guild Contribution",

		[90010012] = "Soul Card Dust",

		[90010013] = "Soul Card Shard",

		[90010014] = "Combined Soul Crystal",

		[90010015] = "Hunting Energy",

		[90010016] = "Guild Fund",

		[90010017] = "Weekly Activity",

		[90010018] = "Level EXP",

		[90010019] = "World Level EXP",

		[90010020] = "Pet Essence",

		[90010021] = "Hunting Points",

		[90010022] = "Stigmata EXP",

		[90010023] = "Combine Stigmata",

		[90010024] = "Advance Stigmata",

		[90010025] = "Talent Points",

		[90010026] = "Boss Points",

		[90010027] = "Baby Essence",

		[90010028] = "Atlas Essence",

		[90010029] = "Ring Coin",

		[90010030] = "Deity Essence",

		[90010031] = "Titanium Alloy",

		[90010033] = "Medal",

		[90010034] = "Pet Gear EXP",

		[90010035] = "Market Currency Green Diamond",

		[90010037] = "元素1",

		[90010038] = "元素2",

		[90010039] = "元素3",

		[90010040] = "元素4",

		[90010041] = "元素5",

		[90010042] = "Artifact Enhance EXP",

		[90019001] = "EXP Update",

		[90019002] = "EXP Factor",

		[11001] = "Talaria",

		[30010001] = "Food",

		[13200] = "大富豪普通骰子",

		[13201] = "大富豪固定骰子",

	},

	ATTR_TYPE = {

		[1] = "Basic Sys Attr.",

		[2] = "Weapon Sys Attr.",

		[3] = "Armor Sys Attr.",

		[4] = "Accessory Sys Attr.",

		[5] = "Normal Sys Attr.",

	},

	ATTR = {

		[1] = "Current HP",

		[2] = "HP",

		[3] = "Speed (pixel/s), multiplier of 20",

		[4] = "ATK",

		[5] = "DEF",

		[6] = "Penetration",

		[7] = "Accuracy",

		[8] = "Dodge",

		[9] = "Crit",

		[10] = "TEN",

		[11] = "M. ATK",

		[12] = "M. DEF",

		[13] = "Attack Boost",

		[14] = "Damage Reduction",

		[15] = "Hit Chance",

		[16] = "Dodge Rate",

		[17] = "Avatar Armor",

		[18] = "Armor Penetration",

		[19] = "Block Rate",

		[20] = "Pierce",

		[21] = "Crit Rate",

		[22] = "Crit Resistance",

		[23] = "Concentrated Strike Rate",

		[24] = "Concentrated Strike Resistance",

		[25] = "Crit Damage",

		[26] = "Concentrated Strike Damage",

		[27] = "Increased Skill Damage",

		[28] = "Skill Damage Reduction",

		[29] = "Strike Rate",

		[30] = "Chance of Weakening",

		[31] = "Crit DMG Reduction",

		[32] = "ATK DMG Increase",

		[33] = "Block DMG Reduction",

		[34] = "PVP Damage Resistance",

		[35] = "PVP Avatar Armor",

		[36] = "PVP Armor Penetration",

		[37] = "Boss DMG Increase",

		[38] = "Mob DMG Increase",

		[39] = "Skill CP of the Attack",

		[40] = "Skill CP of the Defense",

		[41] = "Damage Reduction",

		[42] = "PVP Damage Resistance",

		[43] = "Concentrated Strike Resistance",

		[44] = "CP",

		[45] = "Absolute Attack",

		[46] = "Absolute Doge",

		[1100] = "Total Attribute Percentage (Overall)",

		[1102] = "HP Bonus",

		[1103] = "Speed Bonus",

		[1104] = "Attack Bonus",

		[1105] = "DEF Bonus",

		[1106] = "Penetration Bonus",

		[1107] = "Accuracy Bonus",

		[1108] = "Dodge Bonus",

		[1109] = "Crit Bonus",

		[1110] = "TEN Bonus",

		[1111] = "M. ATK Bonus",

		[1112] = "M. DEF Bonus",

		[1200] = "Total Attribute Percentage (Partial)",

		[1202] = "HP",

		[1204] = "ATK",

		[1205] = "DEF",

		[1206] = "Penetration",

		[1207] = "Accuracy",

		[1208] = "Dodge",

		[1209] = "Crit",

		[1210] = "TEN",

		[1211] = "M. ATK",

		[1212] = "M. DEF",

		[1302] = "Basic HP",

		[1304] = "Basic Attack",

		[1305] = "Basic Defense",

		[1306] = "Basic Penetration",

		[1404] = "Weapon Attack",

		[1406] = "Weapon Penetration",

		[1502] = "Armor HP",

		[1505] = "Armor DEF",

		[1604] = "Accessory ATK",

		[2000] = "EXP Bonus",

		[2001] = "Gold Drop Rate",

		[2002] = "Drop rate",

		[2003] = "Increase defense every 3 levels",

		[2004] = "Increase HP every 3 levels",

		[2005] = "Increase attack every 3 levels",

		[2006] = "Increase attack by 10 each level",

		[2007] = "Increase damage done to bosses by 2% every 50 levels",

		[2009] = "Decrease skill CD percentage",

		[2010] = "Enhancement Bonus",

		[2011] = "Mecha Shield",

		[2012] = "神器附灵百分比属性",

	},

	EVENT = {

		[1] = "Upgrade",

		[2] = "Talk",

		[3] = "Mob Fight",

		[4] = "Stage",

		[5] = "Collect items",

		[6] = "Gear",

		[7] = "Complete Quest",

		[8] = "Send Flower",

		[9] = "Stage Levels",

		[10] = "Enter Stage",

		[11] = "Attribute changes",

		[12] = "CP increased",

		[13] = "Enhance Gear",

		[14] = "Polar Cross",

		[15] = "Awaken",

		[16] = "Recharge",

		[17] = "Training System Advance",

		[18] = "Morph System Advance",

		[19] = "Collect",

		[20] = "Achievement Points",

		[21] = "Difficulty",

		[22] = "Leaderboard Rank",

		[23] = "Soul Card CP",

		[24] = "Item Combine",

		[25] = "Activity",

		[26] = "Add Friend",

		[27] = "Socket Gem",

		[28] = "Join a Guild",

		[29] = "Devour Gear",

		[30] = "Sell",

		[31] = "Guild Donation",

		[32] = "Arena Rank",

		[33] = "Pet Fusion",

		[34] = "Improve VIP",

		[35] = "Gem Upgrade",

		[36] = "Put on Beast Gear",

		[37] = "Pet gains",

		[38] = "Gear Hunting",

		[39] = "Soul Card Hunt",

		[40] = "Buy VIP Card",

		[41] = "Buy Investment Plan",

		[42] = "Get Married",

		[43] = "Consumption",

		[44] = "Buy Monthly Card",

		[45] = "Operation Event",

		[46] = "Daily Prayer",

		[47] = "Login",

		[48] = "Treasure Hunt",

		[49] = "Create",

		[50] = "Appoint",

		[51] = "Member",

		[52] = "Forge Set",

		[53] = "Deployed Pet",

		[54] = "Pet Breakthrough x times",

		[55] = "Pet Training x times",

		[56] = "Join xx xx times",

		[57] = "Inspire xx times in EXP Vault",

		[58] = "Die xx times",

		[59] = "Defeat x players",

		[60] = "Total sign-in xxx days",

		[61] = "Unlock xx slots of xx backpack",

		[62] = "Guild Level",

		[63] = "Quiz",

		[64] = "Sent out Red Packet",

		[65] = "公会争霸获得胜利 ",

		[66] = "End enemy guild's win streak in Guild Clash",

		[67] = "Participate",

		[68] = "Pet CP",

		[69] = "Total Pet CP",

		[70] = "Guild Clash Rank",

		[71] = "Egg Smash",

		[72] = "Total Avatar CP",

		[73] = "gear Refinery",

		[74] = "Forge Gear",

		[75] = "Assisting Beast",

		[76] = "Peak Hunting",

		[77] = "Enhance Gear (Only Trigger Once)",

		[78] = "Increase Intimacy",

		[79] = "Gear Polishing (Only Trigger Once)",

		[80] = "Atlas CP",

		[81] = "Talk with appointed NPC",

		[82] = "Attack appointed Mob",

		[83] = "Children CP",

		[84] = "Equip Mecha Gear",

		[85] = "Mecha Hunt",

		[86] = "Stigmata CP",

		[87] = "Mecha CP",

		[88] = "Beast CP",

		[89] = "Points Pack for Time-L treasure hunt",

		[90] = "Totem",

		[91] = "图腾穿装备",

		[92] = "图腾助战",

	},

	TASK_TYPE = {

		[1] = "Main",

		[2] = "Limited",

		[3] = "Daily",

		[4] = "GUild",

		[5] = "Sub",

		[6] = "Awaken",

		[7] = "Cross",

		[8] = "Beast",

		[9] = "Baby",

		[10] = "Activity",

		[90] = "Daily",

		[91] = "GUild",

		[92] = "Daily",

		[93] = "GUild",

		[94] = "Beast",

		[95] = "Beast",

		[96] = "Beast",

		[97] = "Beast",

	},

	TASK_STATE = {

		[1] = "Pending",

		[2] = "Accepted",

		[3] = "Completed",

		[4] = "Next Quest",

	},

	ACTIVITY_TYPE = {

		[1] = "Server Event",

		[2] = "Cross-server Event",

		[3] = "Center-server Event",

	},

	ACTIVITY_GROUP = {

		[101] = "Polar Cross",

		[102] = "Guild Brawl",

		[103] = "Brawl Battleground",

		[104] = "Candy House",

		[105] = "Guild Ceremony",

		[106] = "Guild Guard",

		[107] = "Wedding Ceremony",

		[108] = "Ace Duel",

		[109] = "Altar of Bravery",

		[110] = "Diamond Ring",

		[111] = "Time-limited Boss",

		[113] = "Siege War",

		[114] = "Throne of Star",

		[115] = "Cross-Server Guild War",

		[116] = "Time Rift",

		[200] = "Cross-server Group",

	},

	SCENE_STATE = {

		[0] = "Normal",

		[1] = "Time out",

	},

	SCENE_KIND = {

		[1] = "Server Map",

		[2] = "Cross-Server Map",

	},

	SCENE_TYPE = {

		[1] = "Main City Map",

		[2] = "Wild Map",

		[3] = "Stage Map",

		[4] = "Boss Map",

		[5] = "Event Map",

	},

	SCENE_STYPE = {

		[301] = "Temple of Trial",

		[302] = "Cave of Covet",

		[303] = "Tower of Judgment",

		[304] = "Fighter's Path",

		[305] = "Novice Stage",

		[306] = "Daily Stage",

		[307] = "Personal Boss",

		[308] = "Mount (Advance) Stage",

		[309] = "Arena",

		[310] = "Demon Invasion",

		[311] = "Guild Guard",

		[312] = "World Boss Stage",

		[313] = "Wedding Dungeon",

		[314] = "Operation Tower Dungeon",

		[315] = "Stigmata Realm",

		[316] = "Mecha Trial",

		[317] = "Avatar Dungeon",

		[318] = "Novice Mermaid Stage",

		[319] = "Mecha Racing",

		[320] = "Novice Evil Stage (Anger Stage)",

		[401] = "World Boss",

		[402] = "Boss Home",

		[403] = "Ancient Ruins",

		[404] = "Monster Castle",

		[405] = "Fantasy Island",

		[406] = "World Boss (Non Fatigue Floor)",

		[409] = "Time Rift",

		[501] = "Guild Clash",

		[502] = "Brawl Battleground",

		[503] = "Candy House",

		[504] = "Guild Camp",

		[505] = "Wedding Venue",

		[506] = "Ace Duel",

		[507] = "Altar of Bravery",

		[508] = "Diamond Ring Prepare Scene",

		[509] = "Diamond Ring Battle Scene",

		[510] = "Time-limited Boss",

		[511] = "Siege War",

		[512] = "Throne of Star",

		[513] = "Cross-Server Guild War",

	},

	SCENE_COST = {

		[0] = "Fixed Cost",

		[1] = "According to Attempts",

	},

	BCTYPE = {

		[0] = "Sudoku Broadcast",

		[1] = "World Broadcast",

	},

	SCENE_CHANGE = {

		[0] = "Portal",

		[1] = "Talaria",

		[2] = "Teleport",

		[3] = "Boss Map",

		[4] = "Event Scene",

		[5] = "Stage",

		[6] = "Leave",

		[7] = "Server-side Skip",

	},

	TELEPORT = {

		[0] = "Talaria",

	},

	JUMP = {

		[0] = "Normal Leap",

		[3] = "Jump Point",

	},

	DUNGE_TYPE = {

		[1] = "Personal Stage",

		[2] = "Team Stage",

		[3] = "Guild Stage",

	},

	ACTOR_TYPE = {

		[1] = "Player",

		[2] = "Monster",

		[3] = "Drop",

		[4] = "NPC",

		[5] = "Portal",

		[6] = "Jump Point",

		[7] = "Scene effects",

		[8] = "Talisman",

		[9] = "Pet",

		[10] = "Fairy (Chirden)",

		[11] = "Artifact",

		[12] = "Robot",

		[13] = "Spawn",

		[14] = "Deity",

		[15] = "Wings",

		[16] = "Weapon",

		[17] = "Mecha",

		[18] = "Mount",

		[19] = "Head",

		[20] = "Gauntlet",

		[21] = "Magic Array",

	},

	ACTOR_STATE = {

		[0] = "Normal",

		[1] = "Death",

		[2] = "Meditate",

		[4] = "Collect",

		[8] = "Occupy",

		[16] = "Convey",

		[32] = "Invincible",

		[64] = "Stun",

		[128] = "Silence",

		[256] = "Confuse",

		[512] = "Immobilize",

		[1024] = "Paralyze",

		[2048] = "Shield",

		[4096] = "Pet Morph",

		[8192] = "HP-steal",

		[16384] = "Drop Decay",

		[32768] = "Dance",

		[65536] = "Bleed",

		[131072] = "Invulnerable",

		[262144] = "Slow",

		[524288] = "Thunder*Attack Wave",

		[1048576] = "Frost*Armor",

		[2097152] = "Phantom*Attack Wave",

		[4194304] = "Mirage*Flash",

		[8388608] = "Immune",

		[16777216] = "Mecha Transform",

	},

	PKMODE = {

		[1] = "Peace",

		[2] = "Good&Evil",

		[3] = "Team",

		[4] = "Guild",

		[5] = "Force",

		[6] = "All",

		[7] = "Guard",

		[8] = "Invade",

		[9] = "Cross-server",

		[10] = "Enemy",

	},

	CREEP_KIND = {

		[1] = "Monster",

		[2] = "Material",

		[3] = "Tombstone",

	},

	CREEP_TYPE = {

		[1] = "Active Mob",

		[2] = "Passive Mob",

	},

	CREEP_RARITY = {

		[1] = "Normal Mob",

		[2] = "Elite Mob",

		[3] = "Boss (World Boss)",

		[4] = "Treasure Guard",

		[5] = "Bomb Monster",

		[6] = "Boss (Normal)",

		[7] = "Treasure Hunt Mob",

		[8] = "Material (Single)",

		[9] = "Material (Multiplayer)",

		[10] = "Summon Boss in Guild",

		[11] = "PK Guard",

		[12] = "Offline Robot",

		[13] = "Team Robot",

		[14] = "Elite Mob (Stage)",

		[15] = "Beast Island Guard",

		[16] = "Time-limited Boss",

		[17] = "Siege War Boss",

		[18] = "Throne of Star  Boss",

		[19] = "跨服公会战水晶",

		[20] = "跨服公会战雕像",

	},

	BOSS_KIND = {

		[1] = "Server Boss",

		[2] = "Cross-Server Boss",

	},

	BOSS_TYPE = {

		[1] = "World Boss",

		[2] = "Home Boss",

		[3] = "远古Boss",

		[4] = "宠物Boss",

		[5] = "Beast Boss",

		[6] = "Cross-Server Beast Boss",

		[7] = "星之王座BOSS",

		[8] = "Time Rift Default Boss",

		[9] = "Time Rift Hiden Boss",

	},

	SKILL_GROUP = {

		[1] = "Normal Skill",

		[2] = "Guild Skill",

		[3] = "Awaken Skill",

		[4] = "Other Skill",

		[5] = "Pet Skill",

		[6] = "Beast Island Single Target Skill",

		[7] = "Beast Island AoE Skill",

		[8] = "Talent Skill (Mount)",

		[9] = "Talent Skill (Off-hand)",

		[10] = "Talent Skill (Wing Morph)",

		[11] = "Talent Skill (Off-hand Morph)",

		[12] = "Rage Skill",

		[13] = "Mecha Skill",

		[20] = "图腾单体技能",

		[21] = "图腾全体技能",

	},

	SKILL_TYPE = {

		[1] = "Active Skill",

		[2] = "Passive Skill",

		[3] = "Attrbute Skill",

	},

	SKILL_AIM = {

		[1] = "Enemy",

		[2] = "Self",

		[3] = "Ally",

	},

	SKILL_AREA = {

		[1] = "Single Target",

		[2] = "Rectangle",

		[3] = "Sector",

		[4] = "Circle",

	},

	SKILL_POS = {

		[7] = "Avatar Morph Skill",

		[8] = "Pet Morph Skill",

		[9] = "Pet Normal Attack Skill",

		[10] = "Pet Normal Morph Skill",

		[11] = "Pet Ogi Morph Skill",

		[12] = "Pet Ogi Skill (Normal)",

		[13] = "Rage Skill",

		[14] = "Mecha normal attack",

		[15] = "Mecha Skill 1",

		[16] = "Mecha Skill 2",

		[17] = "Mecha Skill 3",

		[18] = "Mecha Skill 4",

		[19] = "Mecha Skill 5",

		[20] = "Mecha Skill 6",

	},

	ATTACK_UNIT = {

		[0] = "Character",

		[1] = "Pet",

		[9] = "Monster",

	},

	DAMAGE = {

		[1] = "Dodge",

		[2] = "HP Deduction",

		[3] = "Crit",

		[4] = "Concentrated Strike",

		[5] = "Heal",

		[6] = "Purify",

		[7] = "Absorb",

		[8] = "Block",

		[9] = "Reflect",

		[10] = "Kill",

		[11] = "Fire DMG",

		[12] = "Bleed",

		[13] = "Invulnerable",

		[14] = "HP-steal",

		[15] = "Immune",

		[1002] = "HP Deduction (Pet)",

		[1003] = "Crit (Pet)",

		[1004] = "Concentrated Strike (Pet)",

		[1005] = "--HP Restore (Pet)",

		[101] = "Crit+Concentrated Strike",

		[102] = "Crit+Block",

	},

	DROP_RULE = {

		[1] = "Fixed drops",

		[2] = "Randomly Drop",

		[3] = "Independent probability drop",

	},

	DROP_MODE = {

		[1] = "Put in Backpack immediately",

		[2] = "Drop in scene",

		[3] = "Half-virtual drop, it need to pick up",

		[4] = "Half-virtual drop, auto pick up",

	},

	DROP_BELONG = {

		[0] = "All players",

		[1] = "Final Hit",

		[2] = "Leader obtains",

		[3] = "Team Sharing",

		[4] = "Team Random",

		[5] = "Guild Sharing",

		[6] = "Boss Drop",

		[7] = "Each team member can a reward. It has limit.",

	},

	REVIVE_TYPE = {

		[1] = "Revive on Site",

		[2] = "Safe Zone Revive",

	},

	BUFF_TYPE = {

		[1] = "Buff",

		[2] = "DeBuff",

	},

	BUFF_LAP = {

		[1] = "Extend old Buff Time",

		[2] = "Replace old buff immediately",

		[3] = "Remain old Buff same",

		[4] = "Replace low level buff",

		[5] = "Use Long-time Buff",

		[6] = "Stack up the attribute of old buff",

		[7] = "Stack up the value of old buff",

	},

	BUFF_EFFECT = {

		[1101] = "Heal",

		[1102] = "Mount Skill: HP Restore",

		[1201] = "Invincible",

		[1202] = "Shield",

		[1203] = "Purify",

		[1204] = "HP-steal",

		[1205] = "Occupy",

		[1206] = "Invulnerable",

		[1207] = "Thunder*Attack Wave",

		[1208] = "Frost*Armor",

		[1209] = "Phantom*Attack Wave",

		[1210] = "Mirage*Flash",

		[2201] = "Stun",

		[2202] = "Silence",

		[2203] = "Confuse",

		[2204] = "Immobilize",

		[2205] = "Paralyze",

		[2206] = "Drop Decay",

		[2207] = "Bleed",

		[2208] = "Slow",

		[3001] = "Cast skills regularly",

		[3002] = "Ultimate alert!",

		[3003] = "Attrbute",

		[3004] = "World Boss Belongs to",

		[3005] = "Timing Buff",

		[3006] = "Morphy",

		[3007] = "Search teammate and give Hola Buff to them",

		[3008] = "Damage Reflection Aura",

		[3009] = "Concentrated Strike Aura",

		[3010] = "Kill Aura",

		[3011] = "Block Aura",

		[3012] = "VIP Buff",

		[3013] = "CP Bonus",

		[3014] = "Purify Randomly",

		[3015] = "Immune",

		[3016] = "Trigger Drop Decay",

		[3017] = "Candy House Dance",

		[3018] = "Summon mob",

		[3019] = "Rage Increase",

		[3020] = "Rage Decrease",

		[3021] = "Mecha Transform",

		[3022] = "Mecha Shield",

	},

	BUFF_VTYPE = {

		[1] = "Absolute Value",

		[2] = "Permyriad",

	},

	BUFF_ID = {

		[300410011] = "Fatigue Buff for Killing World Boss",

		[300410012] = "Fatigue Buff for Killing Beast Boss",

		[220610001] = "Fatigue Buff for World Boss Revival",

		[220610002] = "Fatigue Buff for Beast Boss Revival",

		[220610003] = "Fatigue Buff for Dragonscale Crystal (Beast  Boss)",

		[220610004] = "Fatigue Buff for Phoenixscale Crystal (Beast  Boss)",

		[300410013] = "Home Boss - Energy",

		[304100004] = "Diamond Ring Lives",

		[300410014] = "Time-limited Boss Ranking Reward Attempts",

		[300410015] = "Time-limited Boss Participation Reward Attempts",

		[304010007] = "Cross-server Boss Shield",

		[300410018] = "Fatigue for Siege Boss Killing",

		[300410016] = "Rage Increase Buff",

		[300410017] = "Rage Decrease Buff",

		[304010013] = "Siege War Boss Shield",

		[300410020] = "Time Rift Fatigue buff",

	},

	GUILD_POST = {

		[1] = "Member",

		[2] = "Baby",

		[3] = "Elder",

		[4] = "Guild Deputy",

		[5] = "Guild Leader",

	},

	GUILD_PERM = {

		[0] = "Normal Permissions",

		[1] = "Disband Guild",

		[2] = "Approval",

		[3] = "Remove",

		[4] = "Appoint",

		[5] = "Edit Notice",

		[6] = "Position Remove",

		[7] = "Guild Rename",

		[8] = "Settings",

		[9] = "Guild Upgrade",

		[10] = "Dispose",

	},

	GUILD_LOG = {

		[1] = "Join a Guild",

		[2] = "Leave",

		[3] = "Appoint",

		[4] = "Guild Upgrade",

	},

	GUILD_WELFARE = {

		[1] = "Daily Welfare",

		[2] = "Baby Welfare",

		[3] = "Position Welfare",

	},

	RANK_ID = {

		[1001] = "Level Ranking",

		[1002] = "CP Ranking",

		[1008] = "Offline Farming",

		[1011] = "Arena",

		[1012] = "Ace Duel",

		[1015] = "Guild Guard",

		[1019] = "Children Ranking",

		[1020] = "Cross-server Children Ranking",

		[2001] = "Mount Ranking",

		[2002] = "Wing Ranking",

		[2003] = "Artifact Ranking",

		[2012] = "Ace Duel",

	},

	RELATION = {

		[1] = "Stranger",

		[2] = "Friends",

		[3] = "Blacklist",

	},

	TRAIN = {

		[1] = "Mount",

		[2] = "Wings",

		[3] = "Talisman",

		[4] = "Artifact",

		[5] = "Off hand",

		[6] = "Deity",

		[7] = "Mecha",

	},

	TIPS_SHOW = {

		[1] = "Costume",

		[2] = "Title",

		[3] = "Mount",

		[4] = "Off hand",

		[5] = "Wings",

		[6] = "Talisman",

		[7] = "Artifact",

		[8] = "Pet",

		[9] = "Deity",

		[11] = "Portrait Frame",

		[11] = "Bubble Frame",

		[12] = "Mecha",

	},

	DEAD_TYPE = {

		[1] = "Natural Death (Manual Revive)",

		[2] = "Fatigue Death (World Boss)",

		[3] = "Natural Death (Auto-Revive)",

	},

	WAKE_TASK_TYPE = {

		[1] = "Daily Quests",

		[2] = "Stages",

		[3] = "Quests",

	},

	FIGHT_STATE_TYPE = {

		[1] = "Out of combat",

		[2] = "Normal combat",

		[3] = "PK",

	},

	VIP_RIGHTS = {

		[1] = "Monster Killing EXP buff",

		[2] = "Trade Tax",

		[3] = "Unlimited Teleport",

		[4] = "Dungeon purchase attempts",

		[5] = "Out of combat",

		[6] = "Out of combat",

		[7] = "Unlock Specified Trade on the market",

		[8] = "Out of combat",

		[9] = "Greedy Cave purchase chance",

		[10] = "Out of combat",

		[11] = "Ancient Boss Attempts",

		[12] = "Out of combat",

		[13] = "Out of combat",

		[14] = "Personal Boss",

		[15] = "Out of combat",

		[16] = "Out of combat",

		[17] = "Daily Sign-in Attempts",

		[18] = "Out of combat",

		[19] = "Out of combat",

		[20] = "Out of combat",

		[21] = "Out of combat",

		[22] = "Out of combat",

		[23] = "Out of combat",

		[24] = "Out of combat",

		[25] = "Out of combat",

		[26] = "Max Grant additional market trade attempts +x",

		[27] = "Out of combat",

		[28] = "Max Grant additional market shelf slots +x",

		[29] = "Gear Dungeon purchase attempts",

		[30] = "Arena",

		[31] = "Demon Invasion purchase attempts",

		[32] = "Pet Boss Attempts",

		[33] = "Forge Hut Reset Attempts",

		[34] = "Stigmata Realm purchase attempts",

		[35] = "时空裂缝Boss次数",

		[36] = "Time Rift Boss Fatigue",

	},

	FASHION_STATE_TYPE = {

		[1] = "Costume",

		[2] = "Headwear",

		[3] = "Weapon",

		[4] = "Off hand",

		[5] = "footprint",

		[6] = "Magic Array",

		[11] = "Portrait Frame",

		[12] = "Bubble Frame",

	},

	GIFT_TYPE = {

		[1] = "Random Pack",

		[2] = "Optional Pack",

		[3] = "Fixed Pack",

		[4] = "Ingot Selection Pack",

		[5] = "Drop Pack",

		[6] = "Level Pack",

	},

	VIP_TYPE = {

		[0] = "Non-vip",

		[1] = "Experience VIP",

		[2] = "Normal VIP",

	},

	ROLE_STATE = {

		[0] = "Normal",

		[1] = "Soul Card Hunting",

		[2] = "Polar Crossing",

	},

	TARGET_TYPE = {

		[1] = "New Server Carnival",

		[2] = "Activating monthly card",

		[3] = "Purchase Fairy",

		[4] = "Activate VIP",

		[5] = "Buy Investment Plan",

		[6] = "Attribute achieved",

		[7] = "Equip Gear",

		[8] = "Slay Mobs",

		[9] = "Gear Set",

		[10] = "Type",

	},

	CHAT_CHANNEL = {

		[1] = "World",

		[2] = "Zone",

		[3] = "Cross-server",

		[4] = "Team",

		[5] = "Team",

		[6] = "Immortal Alliance",

		[7] = "Quiz",

		[99] = "PM",

		[100] = "System",

	},

	MAIL = {

		[1000002] = "Notice for currency overage",

		[1000003] = "Reissue for currency overage",

		[1000004] = "Insufficient capacity, send mail failed.",

		[1000005] = "Package launching too frequent",

		[1000006] = "Guild Guard Statistics",

		[1000007] = "Guild Guard Statistics",

		[1000013] = "合服玩家重名",

		[1000014] = "合服公会重名",

		[1100001] = "Rename",

		[1113001] = "Market purchase",

		[1113002] = "Sale",

		[1113003] = "Reject",

		[1113004] = "Out of date",

		[1132001] = "Defeated in the Arena",

		[1134001] = "Proposal Failed",

		[1134002] = "Divorce",

		[1135001] = "Wedding Reserve",

		[1135002] = "Wedding Notice",

		[1135003] = "Wedding Popularity Rewards",

		[1135004] = "Cancel",

		[1203001] = "Mecha Racing Reward",

		[1204001] = "World Boss Participation Reward",

		[1400001] = "Guild Notice",

		[1400002] = "Fail to apply",

		[1400003] = "Apply successfully",

		[1400004] = "Removed from Guild",

		[1400005] = "Position Change",

		[1400006] = "Auto-transfer Chairman (Old Chairman)",

		[1400007] = "Auto-transfer Chairman (Member)",

		[1603001] = "Brawl Rewards",

		[1603002] = "Brawl Placement Rewards",

		[1604001] = "Candy House Rewards",

		[1602001] = "Guild Clash Winner Reward",

		[1602002] = "Guild Clash Participate Reward",

		[1602003] = "Guild Clash Personal Reward",

		[1602004] = "Win-streak Reward",

		[1602005] = "Defeat Reward",

		[1602006] = "Prediction of Round I",

		[1602007] = "Prediction of Round II",

		[1602008] = "Division Upgrade",

		[1602009] = "Division Degrade",

		[1602010] = "No.1 Guild",

		[1602011] = "No.1 Guild Leader Reward",

		[1602012] = "Guild Clash Winner Reward (bye)",

		[1605001] = "Guild Quiz Rewards",

		[1605002] = "Ace Duel Placement Reward",

		[1605003] = "Ace Duel Placement Reward",

		[1606001] = "Altar of Courage Placement Rewards",

		[1606002] = "Altar of Courage Progress Rewards",

		[1606003] = "Children Thumb Up Reward",

		[1607001] = "Successfully signed up",

		[1607002] = "Reimbursement for Qualifier Failure",

		[1607003] = "Qualification Notice",

		[1607004] = "Reminder of Heaven List",

		[1607005] = "Heaven/Earth List Statistics",

		[1607006] = "Diamond Arena Reward",

		[1607007] = "Quiz Successful",

		[1607008] = "Quiz Failed",

		[1607009] = "Heaven List Participate Reward",

		[1607010] = "Earth List Participate Reward",

		[1608001] = "Time-limited Boss Shield Breaking Reward",

		[1608002] = "Time-limited Boss Participation Reward",

		[1608003] = "Time-limited Boss Ranking Reward",

		[1608004] = "Time-limited Boss Chest Reward",

		[1609001] = "Siege War Capture Rewards",

		[1700001] = "X-server Shopping",

	},

	ROLE_COUNT = {

		[1001] = "Daily first flower gifting",

		[1002] = "Market Trade Attempts",

		[1003] = "Trophy Bless Attempts",

		[1004] = "Daily Sign-in Attempts",

		[1005] = "Daily Polar Cross Attempts",

		[1006] = "Daily Plunder",

		[1007] = "Daily refresh attempts",

		[1008] = "Daily Assist",

		[1009] = "boss fatigue",

		[1010] = "Guild Brawl Daily Bonus",

		[1011] = "Guild Join Attempts",

		[1012] = "Daily Top-up Ingots",

		[1013] = "Arena encourage attempts",

		[1014] = "Arena Ace challenge attempts",

		[1015] = "Daily Reward",

		[1016] = "Arena Ace Welfare",

		[1017] = "Friend Request",

		[1018] = "Daily Assist Glory Cap",

		[1019] = "Daily Assist Intimacy Cap",

		[1020] = "Daily Login",

		[1021] = "Beast Island Fatigue",

		[1022] = "Beast Island Crystal Gathering",

		[1023] = "Beast Island Crystal Gathering",

		[1024] = "Free Gear Refinery",

		[1025] = "Forge Hut daily attempts",

		[1026] = "Forge Hut daily reset attempts",

		[1027] = "Forge Hut daily free dice attempts",

		[1028] = "Reset Deity's Path",

		[1029] = "Home Boss - Energy",

		[1030] = "市场获得钻石",

		[1031] = "市场消耗钻石",

		[2001] = "Guild Bonus",

		[2002] = "Enter Attempts",

		[2003] = "Buy Attempts",

		[2004] = "Dungeon Raid attempts",

		[2005] = "VIP Welfare",

		[2006] = "Item Obtaining",

		[2007] = "Dungeon Assist attempts",

		[2008] = "Daily Send Red Packs Attempts",

		[2009] = "Offline items obtained",

		[2010] = "Ace Duel",

		[2011] = "Item Increase attempt",

		[2013] = "Beast Assist Broadcast",

		[2014] = "Purchase Increase Apply from Stage",

		[2015] = "充值购买次数",

		[2016] = "图腾助阵广播",

	},

	YY_TASK_STATE = {

		[1] = "Done",

		[2] = "Pending",

		[3] = "Claimed",

		[4] = "Rebated",

	},

	MODEL_TYPE = {

		[1] = "Talisman",

		[2] = "Monster",

		[3] = "Mount",

		[4] = "NPC",

		[5] = "Pet",

		[6] = "Character",

		[7] = "Wings",

		[8] = "Artifact",

		[9] = "Wisp",

		[10] = "Off hand",

		[11] = "Gear",

		[12] = "Baby",

		[13] = "Deity",

		[14] = "Mecha",

		[15] = "Artifact",

	},

	WANTED_TASK_STATE = {

		[1] = "Pending",

		[2] = "Done",

		[3] = "Claimed",

	},

	RED_ENVELOPE_STATE = {

		[1] = "Not send yet",

		[2] = "Already sent",

		[3] = "Claimed out",

	},

	PROGRESS_STATE = {

		[1] = "Pending",

		[2] = "Done",

		[3] = "Claimed",

	},

	HEAL_TYPE = {

		[1] = "HP Restore",

		[2] = "Bleed",

	},

	TRADE_TYPE = {

		[1] = "Sell",

		[2] = "Market Trade",

	},

	TALENT_GROUP = {

		[1] = "Fight",

		[2] = "Guard",

		[3] = "Basic",

	},

	CROSS_RULE = {

		[1024008] = "",

	},

	DUNGE_OP = {

		[1] = "Enter Stage",

		[2] = "Buy Attempts",

		[3] = "Raid attempts",

		[4] = "Stars",

	},

	PLAY_STAT = {

		[3] = "Polar Cross",

		[4] = "Arena",

		[5] = "Super Challenge",

		[6] = "Ace Duel",

	},

	PLAY_OP = {

		[1] = "Join",

	},

	COMPETE_PERIOD = {

		[0] = "Armistice",

		[1] = "Sign up",

		[2] = "Mass-election",

		[3] = "Clash",

		[4] = "Eliminate",

	},

	COMPETE_PHASE = {

		[0] = "Preparation",

		[1] = "Battle",

	},

	COMPETE_BATTLE = {

		[1] = "Mass-election",

		[2] = "Heaven Ranking",

		[3] = "Earth Ranking",

	},

	CGW_PERIOD = {

		[1] = "分配",

		[2] = "约战",

		[3] = "开启",

		[4] = "休战(周结)",

		[5] = "月结",

	},

	ROLELOG = {

		[1000001] = "Client error",

		[1107101] = "Mount Tier-up",

		[1107501] = "Off-hand Advancing",

		[1107102] = "Mount Soul Pearl",

		[1107502] = "Off-hand Soul Pearl",

		[1109201] = "Wing Upgrade",

		[1109301] = "Talisman Upgrade",

		[1109401] = "Artifact Upgrade",

		[1109601] = "Avatar Upgrade",

		[1109601] = "Mecha upgrades",

		[1109202] = "Wing Soul Pearl",

		[1109302] = "Talisman Soul Pearl",

		[1109402] = "Artifact Soul Pearl",

		[1109602] = "Deity Soul Pearl",

		[1108101] = "Active Mount Morph",

		[1108201] = "Active Wing Morph",

		[1108301] = "Active Relic Morph",

		[1108401] = "Active Artifact Morph",

		[1108501] = "Active Off hand Morph",

		[1108601] = "Active Deity Morph",

		[1108701] = "Mecha Morph Activation",

		[1108102] = "Star-up Mount Morph",

		[1108202] = "Star-up Wings Morph",

		[1108302] = "Star-up Relic Morph",

		[1108402] = "Star-up Artifact Morph",

		[1108502] = "Star-up Off-hand Morph",

		[1108602] = "Star-up Avatar Morph",

		[1108702] = "Mecha Morph",

		[120001] = "Enter Stage",

		[120002] = "Exit",

		[110601] = "Enhance gear",

		[110602] = "1-Key Enhance",

		[110603] = "Combine gear",

		[120101] = "Kill Boss",

	},

	NFTTYPE = {

		[101] = "Boss Drop",

		[102] = "Market",

		[201] = "Pet",

		[202] = "Mount",

		[203] = "Wings",

		[301] = "时装-头发",

		[302] = "时装-衣服",

		[303] = "时装-武器",

	},

}
