-- Automatically generated, do not edit
-- Generated by parse_errno.go

errno = {

	[1] = [[ System error ]],

	[2] = [[ Wrong signature ]],

	[3] = [[ Wrong parameter ]],

	[4] = [[ Failed to connect to game server ]],

	[5] = [[ Request expired ]],

	[6] = [[ Related info not found ]],

	[1000001] = [[ System error ]],

	[1000002] = [[ Server under maintenance ]],

	[1000003] = [[ Client version too low ]],

	[1000004] = [[ Package launching too frequent ]],

	[1000005] = [[ Offline for a long time ]],

	[1000006] = [[ Heartbeat Package not found ]],

	[1000007] = [[ Parameter error ]],

	[1000008] = [[ Illegal data package ]],

	[1000009] = [[ Illegal enumerated values ]],

	[1000010] = [[ Account logged in on another device ]],

	[1000011] = [[ Do not call your progress ]],

	[1000012] = [[ Kicked offline by the administrator ]],

	[1000013] = [[ Cross-server closed ]],

	[1000014] = [[ The Room Number must be an integer ]],

	[1000015] = [[ Order ID doesn't exist ]],

	[1000016] = [[ Time out of sync ]],

	[1000017] = [[ Sever access closed ]],

	[1000018] = [[ The system is closed ]],

	[1000019] = [[ Unable to call other servers directly ]],

	[1000020] = [[ The same node does not need call Center Server ]],

	[1000021] = [[ Kicked offline by the anti-addict system. Time Limit: 22:00 - 8:00 ]],

	[1000022] = [[ Kicked offline by the anti-addict system. Online time too long ]],

	[1000023] = [[ Your account has been banned due to an malicious act of creating too many characters. Please contact GM for any questions. ]],

	[1000024] = [[ Top-up is not available. ]],

	[1000025] = [[ 系统未开放 ]],

	[1001001] = [[ Verification failed ]],

	[1001002] = [[ Max character quantity reached ]],

	[1001003] = [[ Character name too long ]],

	[1001004] = [[ Character name contains illegal characters ]],

	[1001005] = [[ Character name already exists ]],

	[1001006] = [[ Character doesn't exist ]],

	[1001007] = [[ IP has been banned ]],

	[1001008] = [[ Your account is banned ]],

	[1001009] = [[ The character is banned ]],

	[1001010] = [[ TOKEN expired ]],

	[1001011] = [[ Invalid TOKEN ]],

	[1001012] = [[ Too many players are queuing for this server, please change to the newest servers ]],

	[1100001] = [[ Character doesn't exist ]],

	[1100002] = [[ Max level reached ]],

	[1100003] = [[ The player is offline ]],

	[1100004] = [[ The player is in an abnormal status ]],

	[1100005] = [[ Please awaken first before levelling up ]],

	[1100006] = [[ Unable to view yourself ]],

	[1101001] = [[ All slots have been unlocked ]],

	[1101002] = [[ Insufficient room of %s ]],

	[1101003] = [[ %s Bag is full, rewards will be sent via mail ]],

	[1102001] = [[ Item doesn't exist ]],

	[1102002] = [[ Insufficient items ]],

	[1102003] = [[ This item can't be used directly ]],

	[1102004] = [[ This item can't be discarded ]],

	[1102005] = [[ This item can't be sold ]],

	[1102006] = [[ This item can't be stored in the warehouse ]],

	[1102007] = [[ Your level is too low to use it ]],

	[1102008] = [[ Your VIP level is too low to use it ]],

	[1102009] = [[ Fatigue value maxed out, unable to use Fatigue Potion ]],

	[1102010] = [[ Magic Tower not cleared, unable to use it ]],

	[1102011] = [[ Select a reward first ]],

	[1103001] = [[ This quest is not triggered ]],

	[1103002] = [[ You haven't accepted this quest ]],

	[1103003] = [[ You already accepted this quest ]],

	[1103004] = [[ The quest is not done yet ]],

	[1103005] = [[ The quest has been submitted ]],

	[1103006] = [[ The chapter is not complete yet ]],

	[1103007] = [[ Quest timed out ]],

	[1103008] = [[ Insufficient quest materials ]],

	[1104001] = [[ The mail doesn't exist ]],

	[1104002] = [[ Max attachment capacity reached ]],

	[1104003] = [[ No unclaimed attachment left ]],

	[1104004] = [[ Claim the attachment first before deleting the mail ]],

	[1104005] = [[ Already claimed the attachment ]],

	[1105001] = [[ Skill not learned ]],

	[1105002] = [[ Max skill level reached ]],

	[1105003] = [[ Enable skill stack ]],

	[1106001] = [[ Non-gears can't be equipped ]],

	[1106002] = [[ Classes don't match ]],

	[1106003] = [[ Level too low ]],

	[1106004] = [[ The gear is not equipped ]],

	[1106005] = [[ Max enhancement level reached ]],

	[1106006] = [[ Enhancement info not found ]],

	[1106007] = [[ Enhancement limit info not found ]],

	[1106008] = [[ The slot is locked ]],

	[1106009] = [[ The gem can't be inlaid on this slot ]],

	[1106010] = [[ Already crafted ]],

	[1106011] = [[ Insufficient ingots ]],

	[1106012] = [[ Basic set hasn't been crafted yet ]],

	[1106013] = [[ Awakening level too low ]],

	[1106014] = [[ Max devouring level reached ]],

	[1106015] = [[ Only fairies can take off ]],

	[1106016] = [[ No gem inlaid on this slot ]],

	[1106017] = [[ Max gem level reached ]],

	[1106018] = [[ Set crafting requirement not met ]],

	[1106019] = [[ Wrong combining material ]],

	[1106020] = [[ Wrong devouring material ]],

	[1106021] = [[ Max forging level reached ]],

	[1106022] = [[ This gear doesn't meet the forging requirement ]],

	[1106023] = [[ This position is unlocked ]],

	[1106024] = [[ Unlocking level not met ]],

	[1106025] = [[ This position is locked ]],

	[1106025] = [[ This slot is unlocked ]],

	[1106026] = [[ There are too many locked slots ]],

	[1106027] = [[ Slot locking error ]],

	[1106028] = [[ No attributes available for resetting ]],

	[1106029] = [[ No gear equipped ]],

	[1106030] = [[ VIP level too low ]],

	[1106031] = [[ There are unpolished slots, unable to reset ]],

	[1106032] = [[ Error in using Flawless Polishing Stone ]],

	[1106033] = [[ Error in using Eternal Polishing Stone ]],

	[1106034] = [[ The gear has expired ]],

	[1106035] = [[ Max set enhancing level reached ]],

	[1106036] = [[ Leveling up requirement not met ]],

	[1106037] = [[ 不满足拆解条件 ]],

	[1107001] = [[ Max Tier reached ]],

	[1107002] = [[ Max training level reached ]],

	[1107003] = [[ Illegal training ]],

	[1107004] = [[ The skin is already in use ]],

	[1107005] = [[ Not Enabled this %s ]],

	[1107006] = [[ Mounted status on ]],

	[1107007] = [[ Mounted status off ]],

	[1108001] = [[ Enabled ]],

	[1108002] = [[ Not Enabled ]],

	[1108003] = [[ Max Stars ]],

	[1108004] = [[ The skin is already in use ]],

	[1108005] = [[ Awakening level too low ]],

	[1108006] = [[ Gender doesn't match ]],

	[1109001] = [[ Not Enabled ]],

	[1109002] = [[ Max Level ]],

	[1109003] = [[ Max training level ]],

	[1110001] = [[ Enabled ]],

	[1110002] = [[ Claimed ]],

	[1110003] = [[ VIP level too low ]],

	[1110004] = [[ VIP expired ]],

	[1110005] = [[ VIP Trial doesn't enjoy VIP Packs and VIP EXP ]],

	[1110006] = [[ No accumulated EXP in the EXP Pool ]],

	[1110007] = [[ Today's Ingot / Bound Ingot gaining limit has been reached, the surplus amount will be issued tomorrow! ]],

	[1110008] = [[ You've bought the Monthly Card ]],

	[1110009] = [[ Buy the Monthly Card first ]],

	[1110010] = [[ Reward claimed ]],

	[1110011] = [[ Claim the reward first ]],

	[1110012] = [[ This grade has been bought ]],

	[1110013] = [[ Reward claimed ]],

	[1110014] = [[ Your level is too low to claim it ]],

	[1110015] = [[ Already claimed ]],

	[1110016] = [[ Reward not available yet ]],

	[1111001] = [[ Hunting for treasures ]],

	[1111002] = [[ Max attempts reached ]],

	[1111003] = [[ Treasure Hunt hasn't started yet ]],

	[1111004] = [[ You are too faraway from the Specter ]],

	[1111005] = [[ Treasure Hunt is not available in the current scene ]],

	[1111006] = [[ Time out. The system picked a random Fairy for you. ]],

	[1111007] = [[ The scene generating fairies is full, the fairy has been tamed ]],

	[1112001] = [[ Max assisting limit reached ]],

	[1112002] = [[ Level too low, unable to improve ]],

	[1112003] = [[ Color doesn't match, unable to equip ]],

	[1112004] = [[ Assisting limit reached ]],

	[1112005] = [[ Already assisting ]],

	[1112006] = [[ Haven't equipped all, unable to assist ]],

	[1112007] = [[ No assists ]],

	[1112008] = [[ Max enhancement level reached ]],

	[1112009] = [[ Only assisting beasts can be enhanced ]],

	[1112101] = [[ Max assisting limit reached ]],

	[1112102] = [[ Level too low, unable to improve ]],

	[1112103] = [[ Color doesn't match, unable to equip ]],

	[1112104] = [[ Assisting limit reached ]],

	[1112105] = [[ Already assisting ]],

	[1112106] = [[ Haven't equipped all, unable to assist ]],

	[1112107] = [[ No assists ]],

	[1112108] = [[ Max enhancement level reached ]],

	[1112109] = [[ Only assisting beasts can be enhanced ]],

	[1113001] = [[ This item can't be traded ]],

	[1113002] = [[ Price error ]],

	[1113003] = [[ Server sale limit reached ]],

	[1113004] = [[ Personal sale limit reached ]],

	[1113005] = [[ Can only trade with friends ]],

	[1113006] = [[ Max trade quantity reached ]],

	[1113007] = [[ The player has reached the max trade quantity ]],

	[1113008] = [[ The item doesn't exist ]],

	[1113009] = [[ Item price changed ]],

	[1113010] = [[ Insufficient items ]],

	[1113011] = [[ The player hasn't sent this trade offer to you ]],

	[1113012] = [[ VIP level too low ]],

	[1113013] = [[ Bound items can't be traded ]],

	[1113014] = [[ Max trade attempts reached ]],

	[1113015] = [[ Unable to buy your own items ]],

	[1114001] = [[ Rewards already claimed ]],

	[1114002] = [[ Insufficient Activity, unable to claim ]],

	[1114003] = [[ Max Level reached ]],

	[1115001] = [[ Rewards already claimed ]],

	[1115002] = [[ Insufficient Activity, unable to claim ]],

	[1115003] = [[ Not done yet, unable to claim ]],

	[1117001] = [[ Max phase reached ]],

	[1117002] = [[ You haven't completed all quests in the current phase ]],

	[1117003] = [[ Max Awakening level reached ]],

	[1117004] = [[ Unable to light up at current awakening level ]],

	[1117005] = [[ Character level too low ]],

	[1117006] = [[ The slot has been lit up ]],

	[1117007] = [[ Awakening requirement not met ]],

	[1117008] = [[ 进阶条件未满足 ]],

	[1118001] = [[ The slot is locked ]],

	[1118002] = [[ Soul Card type incorrect ]],

	[1118003] = [[ Unable to inlay Soul Cards of the same attributes ]],

	[1118004] = [[ Max stars reached ]],

	[1118005] = [[ Max enhancement level reached ]],

	[1118006] = [[ Insufficient consumables ]],

	[1118007] = [[ Soul Card not equipped ]],

	[1118008] = [[ Equipped to the wrong position ]],

	[1119001] = [[ Max level reached ]],

	[1119002] = [[ Insufficient CP ]],

	[1138001] = [[ The child is not born yet ]],

	[1138002] = [[ Max training level reached ]],

	[1138003] = [[ The child is enabled ]],

	[1138004] = [[ Advancing item error ]],

	[1138005] = [[ Not Enabled this Child yet. ]],

	[1138006] = [[ Morphed ]],

	[1138007] = [[ Unable to activate this Wing. ]],

	[1138008] = [[ The child has reached its max tier ]],

	[1138009] = [[ No child has morphed ]],

	[1138010] = [[ No gear is equipped to this position ]],

	[1138011] = [[ Max enhancement level reached ]],

	[1138012] = [[ Max stars reached ]],

	[1138013] = [[ This pair of wings is being morphed ]],

	[1138014] = [[ Not Enabled this Wing yet. ]],

	[1139001] = [[ Today's attempts used out ]],

	[1139002] = [[ Reached the end ]],

	[1139003] = [[ Haven't reached the terminal, unable to reset ]],

	[1139004] = [[ Today's reset attempts used out ]],

	[1139005] = [[ Finish the previous one first ]],

	[1139006] = [[ Please make sure there is enough room in your bag ]],

	[1140001] = [[ No Stigmata is equipped on this slot ]],

	[1140002] = [[ Max level reached ]],

	[1140003] = [[ Wrong position ]],

	[1140004] = [[ The slot is locked ]],

	[1140005] = [[ Stigmata type incorrect ]],

	[1140006] = [[ Unable to inlay Stigmata of the same attributes ]],

	[1141001] = [[ Player level too low ]],

	[1141002] = [[ Insufficient %s ]],

	[1141003] = [[ %s level too low ]],

	[1141004] = [[ Insufficient Talent points ]],

	[1142001] = [[ Max level reached ]],

	[1142002] = [[ Wrong type, unable to dismantle ]],

	[1142003] = [[ Lack of items. ]],

	[1142004] = [[ The Atlas hasn't reached the max level, unable to dismantle it ]],

	[1143001] = [[ Total recharge is not completed yet ]],

	[1143002] = [[ Today's rewards have been claimed ]],

	[1143003] = [[ No rewards available ]],

	[1143004] = [[ Event hasn't started yet ]],

	[1145001] = [[ No investments ]],

	[1145002] = [[ Today's rewards have been claimed ]],

	[1145003] = [[ No rewards available ]],

	[1145004] = [[ Event has ended ]],

	[1145005] = [[ Already invested ]],

	[1147001] = [[ Max Stars ]],

	[1147002] = [[ Max Level ]],

	[1147003] = [[ Not Enabled ]],

	[1147004] = [[ Already deployed ]],

	[1147005] = [[ Unable to equip this gear ]],

	[1147006] = [[ Insufficient Mecha Stars ]],

	[1147007] = [[ Unable to switch Mecha after transformation ]],

	[1149001] = [[ 该元素已达到最高等级 ]],

	[1149002] = [[ 该神器尚未解锁 ]],

	[1149003] = [[ 该位置未穿戴装备 ]],

	[1149004] = [[ Max enhancement level reached ]],

	[1149005] = [[ 尚未激活该属性 ]],

	[1149006] = [[ 已达到附灵最大值 ]],

	[1149007] = [[ 穿戴三件橙色品质以上的装备才可以进行附灵 ]],

	[1120001] = [[ Not Enabled this Costume yet ]],

	[1120002] = [[ The Costume is not equipped ]],

	[1120003] = [[ Enabled this Costume ]],

	[1120004] = [[ The Costume is equipped ]],

	[1120005] = [[ Max star level reached ]],

	[1121001] = [[ The title is equipped ]],

	[1121002] = [[ The Title doesn't exist ]],

	[1121003] = [[ The title has expired ]],

	[1121004] = [[ The title is not equipped ]],

	[1122001] = [[ Target quest error ]],

	[1122002] = [[ Target quest not finished ]],

	[1122003] = [[ Goal not completed ]],

	[1200001] = [[ Failed to create scene ]],

	[1200002] = [[ The scene doesn't exist ]],

	[1200003] = [[ Already in the scene ]],

	[1200004] = [[ The character is not in the scene ]],

	[1200005] = [[ Haven't reached the map's required level ]],

	[1200006] = [[ VIP level too low ]],

	[1200007] = [[ Unable to move ]],

	[1200008] = [[ Step too big ]],

	[1200009] = [[ You are too faraway from the portal ]],

	[1200010] = [[ Unable to teleport in this scene ]],

	[1200011] = [[ Not in a stage ]],

	[1200012] = [[ Unable to switch scenes in a stage ]],

	[1200013] = [[ You need to team up to enter the stage ]],

	[1200014] = [[ Only the team leader can lead the team into the stage ]],

	[1200015] = [[ Unable to join this event without a guild ]],

	[1200016] = [[ Event locked ]],

	[1200017] = [[ Max access attempts reached ]],

	[1200018] = [[ Already in the subline ]],

	[1200019] = [[ The subline doesn't exist ]],

	[1200020] = [[ The subline is full ]],

	[1200021] = [[ Unable to revive manually in this scene ]],

	[1200022] = [[ The portal doesn't exist ]],

	[1200023] = [[ You are too faraway from the warp point ]],

	[1200024] = [[ The scene is full ]],

	[1200025] = [[ The NPC doesn't exist ]],

	[1200026] = [[ You are too faraway from the NPC ]],

	[1200027] = [[ Stage is under cooldown. ]],

	[1200028] = [[ Unable to enter the Stage through the current scene ]],

	[1200029] = [[ Unable to enter the Boss map through the current scene. ]],

	[1200030] = [[ You are in %s, unable to enter the stage ]],

	[1200031] = [[ Unable to enter the map through the current scene ]],

	[1200032] = [[ Unable to mount on the current scene ]],

	[1200033] = [[ You haven't accepted the related quest ]],

	[1200034] = [[ You are in %s, unable to use the talaria ]],

	[1200035] = [[ You are in a Soul Card Hunt, please finish it in line 1 first ]],

	[1200036] = [[ Failed to switch the scene ]],

	[1201001] = [[ Unable to use the Passive Skill ]],

	[1201002] = [[ There are obstacles ahead ]],

	[1201003] = [[ Too many attackers ]],

	[1201004] = [[ Attacking speed too fast ]],

	[1201005] = [[ The skill is cooling off ]],

	[1201006] = [[ The target is out of the attack range ]],

	[1201007] = [[ Unable to attack when you are killed ]],

	[1201008] = [[ Unable to attack when you are stunned ]],

	[1201009] = [[ Unable to attack when you are silenced ]],

	[1201010] = [[ Unable to attack when you are confused ]],

	[1201011] = [[ Unable to attack when you are immobilized ]],

	[1201012] = [[ Unable to revive when you are not dead ]],

	[1201013] = [[ The target has been killed ]],

	[1201014] = [[ The target has gained invincibility ]],

	[1201015] = [[ The item doesn't exist ]],

	[1201016] = [[ It's not collectable ]],

	[1201017] = [[ Already collected by other players ]],

	[1201018] = [[ The item is too far away ]],

	[1201019] = [[ The collection hasn't started yet ]],

	[1201020] = [[ The collection is not complete ]],

	[1201021] = [[ There are no dropped items ]],

	[1201022] = [[ It's not a dropped item ]],

	[1201023] = [[ The dropped item is too far away ]],

	[1201024] = [[ Pick-up interval is too short ]],

	[1201026] = [[ The item doesn't belong to you, unable to pick it up ]],

	[1201027] = [[ Your Fatigue is 0, unable to attack boss ]],

	[1201028] = [[ Unable to switch to PK mode on the current scene ]],

	[1201029] = [[ It's not your Treasure Monster ]],

	[1201030] = [[ Unable to attack your guild mates in Force Mode ]],

	[1201031] = [[ Unable to attack your teammates in Team Mode ]],

	[1201032] = [[ Unable to attack others in Newbie Phase ]],

	[1201033] = [[ The player is in Newbie Phase ]],

	[1201034] = [[ Unable to attack others in Peace Mode ]],

	[1201035] = [[ You can only attack players with grey or higher-grade names in Justice Mode ]],

	[1201036] = [[ Unable to attack others in the Safe Zone ]],

	[1201037] = [[ Unable to attack players in the Safe Zone ]],

	[1201038] = [[ This skill is not equipped ]],

	[1201039] = [[ Unable to use this skill without transformation ]],

	[1201040] = [[ Same team ]],

	[1201041] = [[ Unable to attack yourself ]],

	[1201042] = [[ Unable to pick up drops in fatigue status ]],

	[1201043] = [[ You've reached today's collection limit ]],

	[1201044] = [[ No EXP Phantom is equipped ]],

	[1201045] = [[ The character can't use pet skills ]],

	[1201046] = [[ The pet can't use character skills ]],

	[1201047] = [[ Unable to attack players of your server in Cross-server Mode ]],

	[1201048] = [[ Unable to attack non-rivals in Rival Mode ]],

	[1201049] = [[ 击破水晶后才能攻击雕像 ]],

	[1203001] = [[ You are not in a stage ]],

	[1203002] = [[ Max inspiration attempts reached ]],

	[1203003] = [[ Purchase chances used out ]],

	[1203004] = [[ No need to clear CD ]],

	[1203005] = [[ Get 3-star rating to unlock Raid ]],

	[1203006] = [[ Raid attempts used out ]],

	[1203007] = [[ Cleared ]],

	[1203008] = [[ Rewards have been claimed ]],

	[1203009] = [[ Your Lucky Attempt is 0, clear more Magic Tower floors to get Lucky Attempts ]],

	[1203010] = [[ Please clear the previous floor first ]],

	[1203011] = [[ Star requirement not met ]],

	[1203012] = [[ The reward doesn't exist ]],

	[1203013] = [[ 3-Star Cleared ]],

	[1203014] = [[ Raid requirement not met ]],

	[1203015] = [[ You've achieved 3-star ratings for all stages, no need to raid ]],

	[1203016] = [[ Assisting players can't collect chests ]],

	[1203017] = [[ Only married players can buy it ]],

	[1203018] = [[ The player is offline ]],

	[1203019] = [[ Level too low, unable to raid ]],

	[1203020] = [[ Max deployed units reached ]],

	[1203021] = [[ Already summoned ]],

	[1203022] = [[ Already started, unable to adjust ]],

	[1203023] = [[ Insufficient stage challenge attempts ]],

	[1203024] = [[ Unable to combine attempts in the current stage ]],

	[1203025] = [[ Hasn't started, unable to summon ]],

	[1203026] = [[ Setting successful ]],

	[1203027] = [[ No need to raid ]],

	[1203028] = [[ The stage is not cleared ]],

	[1203029] = [[ All waves have been cleared ]],

	[1203030] = [[ Event hasn't started yet ]],

	[1203031] = [[ Level too low, unable to enter ]],

	[1204001] = [[ The boss doesn't exist ]],

	[1204002] = [[ Not in Field Bosses ]],

	[1204003] = [[ Not in Boss scene. ]],

	[1204004] = [[ The Boss is not killed. ]],

	[1400001] = [[ Already have a guild ]],

	[1400002] = [[ Guild name can't be longer than 2-12 characters ]],

	[1400003] = [[ Guild name contains sensitive words ]],

	[1400004] = [[ The guild name has been taken ]],

	[1400005] = [[ Haven't joined a guild ]],

	[1400006] = [[ The guild doesn't exist ]],

	[1400007] = [[ The guild has other members, can't disband it ]],

	[1400008] = [[ Insufficient authority ]],

	[1400009] = [[ Guild application limit reached ]],

	[1400010] = [[ Already applied ]],

	[1400011] = [[ The player hasn't sent an application ]],

	[1400012] = [[ The guild receives no applications ]],

	[1400013] = [[ The guild is full ]],

	[1400014] = [[ You didn't apply for this guild ]],

	[1400015] = [[ Level too low ]],

	[1400016] = [[ VIP level too low ]],

	[1400017] = [[ The member doesn't exist ]],

	[1400018] = [[ Already on this position ]],

	[1400019] = [[ This position has no vacancies ]],

	[1400020] = [[ Already applied ]],

	[1400021] = [[ The player didn't apply for this position ]],

	[1400022] = [[ You are not the Guild Leader ]],

	[1400023] = [[ Report requirement not met ]],

	[1400024] = [[ Someone else has filed the report ]],

	[1400025] = [[ No one has filed a report ]],

	[1400026] = [[ You've accepted/rejected it ]],

	[1400027] = [[ You are the sponsor ]],

	[1400028] = [[ Only the guild sweetie can claim this benefit ]],

	[1400029] = [[ Already claimed this benefit ]],

	[1400030] = [[ Already at max level ]],

	[1400031] = [[ Insufficient guild funds ]],

	[1400032] = [[ Guild admission level requirement not met ]],

	[1400033] = [[ Guild admission CP requirement not met ]],

	[1400034] = [[ The item is not found in the Warehouse ]],

	[1400035] = [[ Unable to donate the item ]],

	[1400036] = [[ Insufficient room in the warehouse ]],

	[1400037] = [[ Insufficient points ]],

	[1400038] = [[ The notice has been changed by others ]],

	[1400039] = [[ Unable to manipulate yourself ]],

	[1400040] = [[ It's not a guild skill ]],

	[1400041] = [[ Leveling up requirement not met ]],

	[1400042] = [[ Max level reached ]],

	[1400043] = [[ Already a guild member ]],

	[1400044] = [[ Unable to quit a guild during the guild event ]],

	[1400045] = [[ The player has joined another guild ]],

	[1404001] = [[ The Red Packet doesn't exist ]],

	[1404002] = [[ Red Packet status error ]],

	[1404003] = [[ The Red Packet has been snapped up ]],

	[1404004] = [[ You've claimed this Red Packet ]],

	[1405001] = [[ Your time in the guild is not long enough ]],

	[1405002] = [[ The Guarding event has ended, please come earlier next time ]],

	[1500001] = [[ Already have a team ]],

	[1500002] = [[ Not in a team ]],

	[1500003] = [[ Already applied for this team, please wait for a response ]],

	[1500004] = [[ The team is full ]],

	[1500005] = [[ Only the team leader can make this move! ]],

	[1500006] = [[ The player is not in a team ]],

	[1500007] = [[ The player is offline ]],

	[1500008] = [[ The team doesn't exist ]],

	[1500009] = [[ You don't meet the team's level requirement ]],

	[1500010] = [[ Only the team leader can start a team match-up! ]],

	[1500011] = [[ The two teams have more than 3 players in total, please quit your team first ]],

	[1500012] = [[ One of the team members failed to meet the level requirement ]],

	[1500013] = [[ A member of the other team failed to meet the level requirement ]],

	[1500014] = [[ The two teams have more than 3 players in total, unable to combine them ]],

	[1500015] = [[ Already in this team ]],

	[1500016] = [[ Escorting, unable to enter the stage ]],

	[1500017] = [[ Wrong team target ]],

	[1500018] = [[ Not a stage type ]],

	[1500019] = [[ Not in the applicant list ]],

	[1500020] = [[ Not in the invitation list ]],

	[1500021] = [[ Some team members haven't got ready ]],

	[1500022] = [[ The Couple's Stage requires a team of two ]],

	[1500023] = [[ You have to team up with a player of the opposite sex ]],

	[1500024] = [[ Unable to find this teammate ]],

	[1500025] = [[ The player already has a team ]],

	[1500026] = [[ Unable to enter in a team ]],

	[1124001] = [[ Insufficient room in the warehouse, please clear some room! ]],

	[1124002] = [[ Treasure Hunting reward data error! ]],

	[1124003] = [[ Treasure Hunting batch data error ]],

	[1124004] = [[ Treasure Hunting attempts error ]],

	[1124005] = [[ Treasure Hunting type error ]],

	[1124006] = [[ Insufficient room in the bag, please clear some room first! ]],

	[1124007] = [[ No consumption data found! ]],

	[1125001] = [[ You've exceeded the purchase limit! ]],

	[1125002] = [[ Please clear the corresponding stages first! ]],

	[1125003] = [[ The item doesn't exist! ]],

	[1125004] = [[ Not the event time, unable to buy! ]],

	[1125005] = [[ Still valid! ]],

	[1125006] = [[ This gear can't be renewed! ]],

	[1125007] = [[ Insufficient items, unable to pack up ]],

	[1128001] = [[ Achievement data error! ]],

	[1128002] = [[ Achievement status error! ]],

	[1129001] = [[ The pet is not assisting! ]],

	[1129002] = [[ Max level reached! ]],

	[1129003] = [[ Excessive consumption error ]],

	[1129004] = [[ Please train all to the max level! ]],

	[1129005] = [[ Max breakthrough level reached! ]],

	[1129006] = [[ Level too low! ]],

	[1129007] = [[ Only the items in the Pet Bag can be dismantled ]],

	[1129008] = [[ The pet has expired ]],

	[1129009] = [[ 不存在该装备 ]],

	[1129010] = [[ 不满足强化条件 ]],

	[1129011] = [[ 进阶后才可以继续强化 ]],

	[1129011] = [[ 不满足进阶条件 ]],

	[1129012] = [[ 不能分解 ]],

	[1129013] = [[ 不能拆解 ]],

	[1129014] = [[ Max Tier reached ]],

	[1129015] = [[ 不满足继承条件 ]],

	[1129016] = [[ 不满足穿戴条件 ]],

	[1300001] = [[ The messages you left have reached the limit! ]],

	[1300002] = [[ You are muted ]],

	[1300003] = [[ The data doesn't exist ]],

	[1300004] = [[ Content too long ]],

	[1300005] = [[ You are speaking too frequently ]],

	[1126001] = [[ Friend request already sent ]],

	[1126002] = [[ You are in that player's blacklist, unable to befriend ]],

	[1126003] = [[ Unable to find this player ]],

	[1126004] = [[ Your friend list is full ]],

	[1126005] = [[ The player is offline ]],

	[1126006] = [[ Unable to befriend yourself ]],

	[1126007] = [[ The player is in your blacklist ]],

	[1126008] = [[ You are already friends with each other ]],

	[1126009] = [[ The player's friend list is full ]],

	[1126010] = [[ Unable to gift yourself ]],

	[1126011] = [[ Your friend list is full ]],

	[1126012] = [[ You've reached today's new friend limit ]],

	[1126013] = [[ You are married ]],

	[1126014] = [[ The player's level is too low to add friends ]],

	[1127001] = [[ Offline Farming time limit has been reached ]],

	[1130001] = [[ 1st recharge not completed yet ]],

	[1130002] = [[ Today's rewards have been claimed ]],

	[1130003] = [[ No rewards available ]],

	[1131001] = [[ No rewards available ]],

	[1131002] = [[ Reward claimed ]],

	[1131003] = [[ Quest not finished yet ]],

	[1132001] = [[ Currently in a challenge ]],

	[1132002] = [[ The defender is being challenged ]],

	[1132003] = [[ The ranking of the player you are challenging has changed ]],

	[1132004] = [[ Purchase limit has been reached ]],

	[1132005] = [[ Challenge attempts used out ]],

	[1132006] = [[ Only the top 50 can join the super challenge ]],

	[1132007] = [[ Your best ranking doesn't meet the requirement ]],

	[1132008] = [[ Reward claimed ]],

	[1132009] = [[ You didn't enter the leaderboard ]],

	[1132010] = [[ Unable to challenge yourself ]],

	[1132011] = [[ Level too low, unable to skip battle ]],

	[1132012] = [[ Level too low, unable to combine attempts ]],

	[1133001] = [[ Today's flirting limit is reached ]],

	[1134001] = [[ Not finished yet ]],

	[1134002] = [[ Rewards have been claimed ]],

	[1134003] = [[ Only players of opposite sexes can get married ]],

	[1134004] = [[ Both players should be online ]],

	[1134005] = [[ Insufficient Intimacy ]],

	[1134006] = [[ Your levels are too low ]],

	[1134007] = [[ You received a proposal ]],

	[1134008] = [[ You are proposing ]],

	[1134009] = [[ The player received a proposal ]],

	[1134010] = [[ The player is proposing ]],

	[1134011] = [[ You are married ]],

	[1134012] = [[ The player is married ]],

	[1134013] = [[ The player didn't propose ]],

	[1134014] = [[ You are not married ]],

	[1134015] = [[ Max level reached ]],

	[1134016] = [[ You have a wedding reservation, unable to divorce ]],

	[1135001] = [[ Single ]],

	[1135002] = [[ You have a wedding reservation, unable to reserve again ]],

	[1135003] = [[ Reservation attempts used out ]],

	[1135004] = [[ Already reserved ]],

	[1135005] = [[ Wrong reservation time ]],

	[1135006] = [[ Please make a reservation first ]],

	[1135007] = [[ Already invited ]],

	[1135008] = [[ Invitation limit reached ]],

	[1135009] = [[ You don't need an invitation card ]],

	[1135010] = [[ Already asked ]],

	[1135011] = [[ Please increase your invitation limit ]],

	[1135012] = [[ Can only be used on the wedding feast ]],

	[1135013] = [[ Wedding Ceremony hasn't started yet ]],

	[1135014] = [[ You are not invited ]],

	[1135015] = [[ You've eaten a lot, please leave some for others ]],

	[1135016] = [[ You've got a lot, please leave some for others ]],

	[1135017] = [[ Insufficient Popularity ]],

	[1135018] = [[ You missed the reservation time ]],

	[1135019] = [[ Already claimed ]],

	[1136001] = [[ The data doesn't exist ]],

	[1136002] = [[ Retrieval type error ]],

	[1136003] = [[ No data can be retrieved ]],

	[1136004] = [[ Wrong key retrieved ]],

	[1136005] = [[ Max retrieval attempts reached ]],

	[1136006] = [[ No Floor Clearance Reward ]],

	[1402001] = [[ It's not a Summoning Item ]],

	[1403001] = [[ Red Packet type error ]],

	[1403002] = [[ The quantity of the Red Packet can't surpass its total amount ]],

	[1403003] = [[ Red Packet data doesn't exist ]],

	[1403004] = [[ Red Packet status error ]],

	[1403005] = [[ The total amount of the Red Packet can't be 0. ]],

	[1601001] = [[ The escorting quest doesn't exist ]],

	[1601002] = [[ Max escorting attempts reached ]],

	[1601003] = [[ Max quality reached ]],

	[1601004] = [[ No escorting quest found ]],

	[1601005] = [[ Wrong escorting phase ]],

	[1602001] = [[ Your guild failed to meet the participation requirement ]],

	[1602002] = [[ Battle on this War Zone has ended ]],

	[1602003] = [[ The crystal is taken by our side ]],

	[1602004] = [[ Can only be used by the dominating guild ]],

	[1602005] = [[ Rewards have been distributed ]],

	[1602006] = [[ Rewards have been claimed ]],

	[1602007] = [[ Players joining the guild after 19:00 of the day can't participate in the Guild War ]],

	[1602008] = [[ Win Streak requirement not met ]],

	[1602009] = [[ Failed to stop any guild's win streak ]],

	[1604001] = [[ The player is not in the Candy House ]],

	[1604002] = [[ Insufficient attempts ]],

	[1604003] = [[ Purchase chances used out ]],

	[1605001] = [[ Reward claimed ]],

	[1605002] = [[ Requirements not met, unable to claim ]],

	[1605003] = [[ You have no grades, unable to claim rewards ]],

	[1605004] = [[ Purchase chances used out ]],

	[1605005] = [[ Max access attempts reached ]],

	[1605006] = [[ Level too low, unable to join ]],

	[1606001] = [[ You are not qualified to enter the next floor ]],

	[1607001] = [[ Sign-up requirement not met ]],

	[1607002] = [[ Already signed up ]],

	[1607003] = [[ You didn't sign up for this event ]],

	[1607004] = [[ The buff doesn't exist ]],

	[1607005] = [[ You already bought this buff ]],

	[1607006] = [[ It's not the Sign-up Phase ]],

	[1607007] = [[ It's not the Bet Phase ]],

	[1607008] = [[ Already bet ]],

	[1607009] = [[ You didn't pass the knockout ]],

	[1608001] = [[ Servers of the top 3 players can open the chest, you can't open it ]],

	[1608002] = [[ Reward attempts used out, unable to enter the cross-server Boss scene ]],

	[1608003] = [[ Treasure Chest opening chances are used out, unable to open more ]],

	[1609001] = [[ The city doesn't exist ]],

	[1609002] = [[ Please occupy the previous city first ]],

	[1609003] = [[ Haven't achieved this progress ]],

	[1609004] = [[ Rewards have been claimed ]],

	[1609005] = [[ Treasure Chest opening chances are used out, unable to open more ]],

	[1610001] = [[ 尚未解锁下一层地图 ]],

	[1611001] = [[ Your guild failed to meet the participation requirement ]],

	[1611002] = [[ 不在预约阶段 ]],

	[1611003] = [[ 对手不存在 ]],

	[1611004] = [[ 已达到最大预约次数 ]],

	[1611005] = [[ 对方已达到最大预约次数 ]],

	[1611006] = [[ 已有预约对手 ]],

	[1611007] = [[ Insufficient points ]],

	[1611008] = [[ 不能预约同一组的公会 ]],

	[1611009] = [[ Insufficient authority ]],

	[1611010] = [[ 不能采集 ]],

	[1611011] = [[ Event has ended ]],

	[1611012] = [[ 此轮轮空 ]],

	[1701001] = [[ Rewards have been claimed ]],

	[1701002] = [[ Insufficient login days, unable to claim ]],

	[1701003] = [[ All rewards have been claimed ]],

	[1702001] = [[ You are not qualified to claim it ]],

	[1702002] = [[ Claimed ]],

	[1702003] = [[ 已达到最大圈数 ]],

	[1702004] = [[ 不需要补签 ]],

	[1123001] = [[ Insufficient Activity, unable to recheck ]],

	[1123101] = [[ Please enter the correct Gift Code ]],

	[1123102] = [[ The Gift Code has been used ]],

	[1123103] = [[ You've claimed this gift ]],

	[1123104] = [[ You are not qualified to claim it ]],

	[1123105] = [[ The Gift Code has expired ]],

	[1123004] = [[ Praying chances used out ]],

	[1123005] = [[ You are not qualified to claim it ]],

	[1123006] = [[ You've claimed this reward ]],

	[1123007] = [[ Max check-in days reached ]],

	[1123008] = [[ Insufficient VIP check-in attempts ]],

	[1123009] = [[ Not the right time ]],

	[1123010] = [[ Reward data error ]],

	[1700001] = [[ Rewards have been claimed ]],

	[1700002] = [[ The event hasn't finished yet, unable to claim the reward ]],

	[1700003] = [[ Reward requirement not met ]],

	[1700004] = [[ The reward doesn't exist ]],

	[1700005] = [[ Max reward claiming limit reached ]],

	[1700006] = [[ Max reward claiming limit reached ]],

	[1700007] = [[ Only the guild leader can claim this Reward ]],

	[1700008] = [[ Rewards have been claimed ]],

	[1700009] = [[ All rewards have been claimed ]],

	[1700010] = [[ Insufficient Myth Points ]],

	[1700011] = [[ All rewards have been drawn out ]],

	[1700012] = [[ Event hasn't started yet ]],

	[1700013] = [[ The drawing result has been revealed, failed to buy ]],

	[1700014] = [[ Purchase limit exceeded, failed to buy ]],

	[1700015] = [[ Purchase limit exceeded, please come another time ]],

	[1700016] = [[ The item is not for sale any more ]],

	[1800001] = [[ You can only join the event through the Guild Territory ]],

	[1800002] = [[ The question has expired ]],

	[1800003] = [[ Not the event time ]],

	[1800004] = [[ You can only summon 1 Boss at a time ]],

	[1800005] = [[ Guild mates who joined the guild for less than 15min can't enter the Guild Camp ]],

}
