SignInNotes = { }

SignInNotes.OPEN_SIGNINPANEL = "OPEN_SIGNINPANEL"
SignInNotes.CLOSE_SIGNINPANEL = "CLOSE_SIGNINPANEL"
SignInNotes.UPDATE_SIGNINPANEL = "UPDATE_SIGNINPANEL"
SignInNotes.CHANGE_SIGNINPANEL = "CHANGE_SIGNINPANEL"
SignInNotes.UPDATE_SIGNINPANELTIP = "UPDATE_SIGNINPANELTIP"

SignInNotes.ENV_REVERTAWARD_RSP = "ENV_REVERTAWARD_RSP";
SignInNotes.ENV_VIP_DAILY_AWARD_RSP = "ENV_VIP_DAILY_AWARD_RSP";