LoginEvent = LoginEvent or {}

LoginEvent.CLOSE_CHANGE_PANEL = "LoginEvent.CLOSE_CHANGE_PANEL"
LoginEvent.LOGIN_NEW_USER_REQUEST = "LoginEvent.LOGIN_NEW_USER_REQUEST"
LoginEvent.DEFAULE_SERVER_SUCCESS = "LoginEvent.DEFAULE_SERVER_SUCCESS"
LoginEvent.REQUEST_SERVERLIST_SUCCESS = "LoginEvent.REQUEST_SERVERLIST_SUCCESS"

LoginEvent.SERVER_ROLELIST_CHANGE = "LoginEvent.SERVER_ROLELIST_CHANGE"

-- 登陆成功
LoginEvent.LOGIN_SUCCESS = "LoginEvent.LOGIN_SUCCESS"

-- 断线重连
LoginEvent.RE_LINK_GAME = "LoginEvent.RE_LINK_GAME"

LoginEvent.ENTER_SCENE_SUCCESS = "LoginEvent.ENTER_SCENE_SUCCESS"